"""P2 — identity: keys, layered identity (L0-L3), wash cost, federation."""

from vacant.identity.attestation import (
    ATTESTATION_REVOCATION_INTENT,
    PeerAttestation,
    is_revoked,
    issue_attestation,
    revoke_attestation,
    verify_attestation,
)
from vacant.identity.attestation import RevocationRecord as AttestationRevocationRecord
from vacant.identity.errors import (
    AttestationError,
    FederationError,
    IdentityError,
    KeyNotFoundError,
    KeyRevokedError,
    KeyVaultError,
    LayerPromotionError,
)
from vacant.identity.governance import (
    AttestorDiversity,
    ControllerTransferEvent,
    GovernanceChangeEvent,
    MigrationEvent,
    MigrationEventStore,
    MigrationRaceError,
    recently_transferred,
    score_attestor_set,
)
from vacant.identity.federation import (
    FederatedAttestation,
    RootSet,
    RootSetHistory,
    RootSignature,
    build_federated_attestation,
    default_mvp_rootset,
    issue_root_signature,
    rotate_root,
    sign_rotation,
    verify_federated,
)
from vacant.identity.keys import (
    KEY_REVOCATION_KIND,
    KEY_ROTATION_KIND,
    FileVault,
    InMemoryVault,
    KeyVault,
    RotationRecord,
    is_key_revoked,
    revoke_key,
    rotate_key,
)
from vacant.identity.keys import RevocationRecord as KeyRevocationRecord
from vacant.identity.layers import (
    L0Identity,
    L1Identity,
    L2Identity,
    L3Identity,
    promote_to_l1,
    promote_to_l2,
    promote_to_l3,
    vacant_id_did_key,
)
from vacant.identity.tee import (
    MOCK_TEE_VENDOR,
    L3TEEIdentity,
    TEEAttestation,
    TEEVendor,
    TEEVerifierRegistry,
    issue_tee_attestation_mock,
    promote_to_l3_tee,
    verify_tee_attestation,
)
from vacant.identity.wash_cost import (
    WASH_COST_FALSE_CLAIM_WEIGHT_DEFAULT,
    WashCost,
    WashCostWeights,
    compute_wash_cost,
)

__all__ = [
    "ATTESTATION_REVOCATION_INTENT",
    "KEY_REVOCATION_KIND",
    "KEY_ROTATION_KIND",
    "MOCK_TEE_VENDOR",
    "WASH_COST_FALSE_CLAIM_WEIGHT_DEFAULT",
    "AttestationError",
    "AttestationRevocationRecord",
    "AttestorDiversity",
    "ControllerTransferEvent",
    "FederatedAttestation",
    "FederationError",
    "FileVault",
    "GovernanceChangeEvent",
    "IdentityError",
    "InMemoryVault",
    "KeyNotFoundError",
    "KeyRevocationRecord",
    "KeyRevokedError",
    "KeyVault",
    "KeyVaultError",
    "L0Identity",
    "L1Identity",
    "L2Identity",
    "L3Identity",
    "L3TEEIdentity",
    "LayerPromotionError",
    "MigrationEvent",
    "MigrationEventStore",
    "MigrationRaceError",
    "PeerAttestation",
    "RootSet",
    "RootSetHistory",
    "RootSignature",
    "RotationRecord",
    "TEEAttestation",
    "TEEVendor",
    "TEEVerifierRegistry",
    "WashCost",
    "WashCostWeights",
    "build_federated_attestation",
    "compute_wash_cost",
    "default_mvp_rootset",
    "is_key_revoked",
    "is_revoked",
    "issue_attestation",
    "issue_root_signature",
    "issue_tee_attestation_mock",
    "promote_to_l1",
    "promote_to_l2",
    "promote_to_l3",
    "promote_to_l3_tee",
    "recently_transferred",
    "revoke_attestation",
    "revoke_key",
    "rotate_key",
    "rotate_root",
    "score_attestor_set",
    "sign_rotation",
    "vacant_id_did_key",
    "verify_attestation",
    "verify_federated",
    "verify_tee_attestation",
]
