"""Visible acceptance for s1_21_total — rendered data, do not hand-edit.

Generated by ops/gain/r535/build_bank.py from ops/gain/r535/tasks_s1.
Every check is zero-argument and passes by returning normally
(vacant/vrun/acceptance.py runs them in definition order).
"""


def check_01_total():
    from solution import total
    args = (1, 5)
    got = total(*args)
    want = 15
    assert got == want, "total args=%r got=%r want=%r" % (args, got, want)


def check_02_total():
    from solution import total
    args = (5, 1)
    got = total(*args)
    want = 0
    assert got == want, "total args=%r got=%r want=%r" % (args, got, want)
