"""Hidden acceptance for s1_12_hms — rendered data, do not hand-edit.

Generated by ops/gain/r535/build_bank.py from ops/gain/r535/tasks_s1.
Every check is zero-argument and passes by returning normally
(vacant_network/vrun/acceptance.py runs them in definition order).
"""


def check_01_hms():
    from solution import hms
    args = (3723,)
    got = hms(*args)
    want = '1:02:03'
    assert got == want, "hms args=%r got=%r want=%r" % (args, got, want)


def check_02_hms():
    from solution import hms
    args = (59,)
    got = hms(*args)
    want = '0:00:59'
    assert got == want, "hms args=%r got=%r want=%r" % (args, got, want)


def check_03_hms():
    from solution import hms
    args = (0,)
    got = hms(*args)
    want = '0:00:00'
    assert got == want, "hms args=%r got=%r want=%r" % (args, got, want)


def check_04_hms():
    from solution import hms
    args = (3600,)
    got = hms(*args)
    want = '1:00:00'
    assert got == want, "hms args=%r got=%r want=%r" % (args, got, want)


def check_05_hms():
    from solution import hms
    args = (86399,)
    got = hms(*args)
    want = '23:59:59'
    assert got == want, "hms args=%r got=%r want=%r" % (args, got, want)


def check_06_hms():
    from solution import hms
    args = (61,)
    got = hms(*args)
    want = '0:01:01'
    assert got == want, "hms args=%r got=%r want=%r" % (args, got, want)


def check_07_hms():
    from solution import hms
    args = (7322,)
    got = hms(*args)
    want = '2:02:02'
    assert got == want, "hms args=%r got=%r want=%r" % (args, got, want)
