"""Visible checks for bcb_37 -- these ship with the task and can be run.

Rendered from bigcode/bigcodebench-hard v0.1.4 (BigCodeBench/37) by
ops/vacantrun/bcb_hard_bank_20260924/build_bank.py. The code below is the
dataset's unittest TestCases, restricted to the test methods that ship with
this task; each check_* runs one of those methods.
"""

from solution import *
import sys as _vacant_sys
import solution as _vacant_solution
_vacant_sys.modules.setdefault(__name__, _vacant_solution)

import unittest
import pandas as pd
class TestCases(unittest.TestCase):
    """Test cases for the task_func function."""
    def test_case_1(self):
        df = pd.DataFrame(
            {
                "A": [4, 6, 2, 11],
                "B": [7, 5, 3, 12],
                "C": [1, 9, 8, 10],
                "D": [1, 0, 1, 0],
            }
        )
        target_column = "D"
        model, ax = task_func(df, target_column)
        self._validate_results(model, ax)
    def test_case_2(self):
        df = pd.DataFrame(
            {
                "E": [1, 2, 3, 4, 5],
                "F": [6, 7, 8, 9, 10],
                "G": [11, 12, 13, 14, 15],
                "H": [0, 0, 1, 0, 1],
            }
        )
        target_column = "H"
        model, ax = task_func(df, target_column)
        self._validate_results(model, ax)
    def _validate_results(self, model, ax):
        # Asserting that the trained model is an instance of RandomForestClassifier
        self.assertIsInstance(model, RandomForestClassifier)
        # Asserting that the axes object is returned for visualization
        self.assertIsInstance(ax, plt.Axes)
        # Asserting that the title of the plot is as expected
        self.assertEqual(ax.get_title(), "Visualizing Important Features")
        self.assertEqual(ax.get_xlabel(), "Feature Importance Score")
        self.assertEqual(ax.get_ylabel(), "Features")
        # Feature importances
        self.assertListEqual(
            sorted(list(model.feature_importances_))[::-1],
            [bar.get_width() for bar in ax.patches],
        )


# ── Vacant wrapper (generated by build_bank.py) ──────────────────────────
# Each check_* below runs exactly one TestCases method (with its setUp /
# tearDown) and raises AssertionError with a short message if it fails.
import unittest as _vacant_unittest

for _vacant_name in [_n for _n in list(globals()) if _n.startswith("check_")]:
    del globals()[_vacant_name]


def _vacant_short(tb_text, limit=700):
    lines = (tb_text or "").rstrip().splitlines()
    idx = [i for i, ln in enumerate(lines) if ln.startswith("  File ")]
    tail = lines[idx[-1] + 2:] if idx and idx[-1] + 2 < len(lines) else lines[-3:]
    tail = [ln for ln in tail if ln.strip() and set(ln.strip()) - set("^~")]
    msg = "\n".join(tail).strip()
    if len(msg) > limit:
        msg = msg[: limit // 2] + " ...[cut]... " + msg[-(limit // 2):]
    return msg


def _vacant_run(method_name):
    suite = _vacant_unittest.TestSuite([TestCases(method_name)])
    result = _vacant_unittest.TestResult()
    suite.run(result)
    if result.wasSuccessful() and result.testsRun == 1:
        return
    if result.failures:
        kind, tb = "FAIL", result.failures[0][1]
    elif result.errors:
        kind, tb = "ERROR", result.errors[0][1]
    elif result.unexpectedSuccesses:
        kind, tb = "UNEXPECTED SUCCESS", ""
    else:
        kind, tb = "NOT RUN", ""
    raise AssertionError("%s %s: %s" % (kind, method_name, _vacant_short(tb)))


def check_test_case_1():
    _vacant_run('test_case_1')

def check_test_case_2():
    _vacant_run('test_case_2')
