"""Visible checks for bcb_865 -- these ship with the task and can be run.

Rendered from bigcode/bigcodebench-hard v0.1.4 (BigCodeBench/865) by
ops/vacantrun/bcb_hard_bank_20260924/build_bank.py. The code below is the
dataset's unittest TestCases, restricted to the test methods that ship with
this task; each check_* runs one of those methods.
"""

from solution import *
import sys as _vacant_sys
import solution as _vacant_solution
_vacant_sys.modules.setdefault(__name__, _vacant_solution)

import unittest
import sys
sys.path.append('/mnt/data/testing')
import pandas as pd
import numpy as np
from faker import Faker
class TestCases(unittest.TestCase):
    def setUp(self):
        # This method will be used to set up any variables or conditions that are common across all test cases.
        self.tolerance = 1e-3  # Tolerance level for comparing floating point numbers
    def test_case_1(self):
        # Testing with basic input.
        data = [('A', 100, 0.5), ('B', 200, 0.6), ('C', 150, 0.7)]
        result = task_func(data)
        expected_items = ['A', 'B', 'C']
        # Check if all items are present and in the correct order
        self.assertEqual(list(result['Item']), expected_items)
        # Check if normalization is within the expected range (0-1 for min-max, mean=0 for z-score)
        self.assertTrue(result['Normalized Weight'].min() >= 0)
        self.assertTrue(result['Normalized Weight'].max() <= 1)
        self.assertTrue(abs(result['Normalized Count'].mean()) <= self.tolerance)
    def test_case_2(self):
        # Testing with negative counts and weights.
        data = [('A', -100, -0.5), ('B', -200, -0.1), ('C', -150, -0.2)]
        result = task_func(data)
        
        # Even with negative inputs, normalization should stay within the expected range
        self.assertTrue(result['Normalized Weight'].min() >= 0)
        self.assertTrue(result['Normalized Weight'].max() <= 1)
        self.assertTrue(abs(result['Normalized Count'].mean()) <= self.tolerance)
    def test_case_3(self):
        # Testing with identical counts and weights.
        data = [('A', 100, 0.5), ('B', 100, 0.5), ('C', 100, 0.5)]
        result = task_func(data)
        
        # If all counts and weights are identical, normalization should result in equality and nan for z score
        self.assertTrue(all(result['Normalized Weight'] == 0.0))
        self.assertTrue(all(result['Normalized Count'].isna()))


# ── Vacant wrapper (generated by build_bank.py) ──────────────────────────
# Each check_* below runs exactly one TestCases method (with its setUp /
# tearDown) and raises AssertionError with a short message if it fails.
import unittest as _vacant_unittest

for _vacant_name in [_n for _n in list(globals()) if _n.startswith("check_")]:
    del globals()[_vacant_name]


def _vacant_short(tb_text, limit=700):
    lines = (tb_text or "").rstrip().splitlines()
    idx = [i for i, ln in enumerate(lines) if ln.startswith("  File ")]
    tail = lines[idx[-1] + 2:] if idx and idx[-1] + 2 < len(lines) else lines[-3:]
    tail = [ln for ln in tail if ln.strip() and set(ln.strip()) - set("^~")]
    msg = "\n".join(tail).strip()
    if len(msg) > limit:
        msg = msg[: limit // 2] + " ...[cut]... " + msg[-(limit // 2):]
    return msg


def _vacant_run(method_name):
    suite = _vacant_unittest.TestSuite([TestCases(method_name)])
    result = _vacant_unittest.TestResult()
    suite.run(result)
    if result.wasSuccessful() and result.testsRun == 1:
        return
    if result.failures:
        kind, tb = "FAIL", result.failures[0][1]
    elif result.errors:
        kind, tb = "ERROR", result.errors[0][1]
    elif result.unexpectedSuccesses:
        kind, tb = "UNEXPECTED SUCCESS", ""
    else:
        kind, tb = "NOT RUN", ""
    raise AssertionError("%s %s: %s" % (kind, method_name, _vacant_short(tb)))


def check_test_case_1():
    _vacant_run('test_case_1')

def check_test_case_2():
    _vacant_run('test_case_2')

def check_test_case_3():
    _vacant_run('test_case_3')
