"""Hidden acceptance for s1_29_strip_zeros — rendered data, do not hand-edit.

Generated by ops/gain/r535/build_bank.py from ops/gain/r535/tasks_s1.
Every check is zero-argument and passes by returning normally
(vacant/vrun/acceptance.py runs them in definition order).
"""


def check_01_strip_zeros():
    from solution import strip_zeros
    args = ('1.500',)
    got = strip_zeros(*args)
    want = '1.5'
    assert got == want, "strip_zeros args=%r got=%r want=%r" % (args, got, want)


def check_02_strip_zeros():
    from solution import strip_zeros
    args = ('100',)
    got = strip_zeros(*args)
    want = '100'
    assert got == want, "strip_zeros args=%r got=%r want=%r" % (args, got, want)


def check_03_strip_zeros():
    from solution import strip_zeros
    args = ('2.000',)
    got = strip_zeros(*args)
    want = '2'
    assert got == want, "strip_zeros args=%r got=%r want=%r" % (args, got, want)


def check_04_strip_zeros():
    from solution import strip_zeros
    args = ('0.0',)
    got = strip_zeros(*args)
    want = '0'
    assert got == want, "strip_zeros args=%r got=%r want=%r" % (args, got, want)


def check_05_strip_zeros():
    from solution import strip_zeros
    args = ('3.14',)
    got = strip_zeros(*args)
    want = '3.14'
    assert got == want, "strip_zeros args=%r got=%r want=%r" % (args, got, want)


def check_06_strip_zeros():
    from solution import strip_zeros
    args = ('10.10',)
    got = strip_zeros(*args)
    want = '10.1'
    assert got == want, "strip_zeros args=%r got=%r want=%r" % (args, got, want)


def check_07_strip_zeros():
    from solution import strip_zeros
    args = ('0',)
    got = strip_zeros(*args)
    want = '0'
    assert got == want, "strip_zeros args=%r got=%r want=%r" % (args, got, want)
