"""Visible checks for bcb_15 -- these ship with the task and can be run.

Rendered from bigcode/bigcodebench-hard v0.1.4 (BigCodeBench/15) by
ops/vacantrun/bcb_hard_bank_20260924/build_bank.py. The code below is the
dataset's unittest TestCases, restricted to the test methods that ship with
this task; each check_* runs one of those methods.
"""

from solution import *
import sys as _vacant_sys
import solution as _vacant_solution
_vacant_sys.modules.setdefault(__name__, _vacant_solution)

import unittest
import tempfile
import shutil
import os
import csv
class TestCases(unittest.TestCase):
    def setUp(self):
        # Setup temporary directories for outputs and inputs
        self.temp_dir = tempfile.mkdtemp()
        self.output_dir_path = tempfile.mkdtemp()
    def tearDown(self):
        # Remove temporary directories after each test
        shutil.rmtree(self.temp_dir)
        shutil.rmtree(self.output_dir_path)
    def test_empty_csv_file(self):
        # Test with an empty CSV file
        empty_commands_path = os.path.join(self.temp_dir, "empty.csv")
        with open(empty_commands_path, "w", newline='') as file:
            pass
        result = task_func(empty_commands_path, self.output_dir_path)
        self.assertEqual(len(result), 0)
    
    def test_command_failure_with_specific_exit_code(self):
        # Prepare a CSV with a command guaranteed to fail and return a specific exit code
        commands_path = os.path.join(self.temp_dir, "failing_commands.csv")
        with open(commands_path, "w", newline='') as file:
            writer = csv.writer(file)
            writer.writerow(["exit 1"])
        
        result = task_func(commands_path, self.output_dir_path)
        self.assertEqual(len(result), 1)
        with open(os.path.join(self.output_dir_path, result[0]), "r") as f:
            content = f.read()
            self.assertIn("Error executing command", content)


# ── Vacant wrapper (generated by build_bank.py) ──────────────────────────
# Each check_* below runs exactly one TestCases method (with its setUp /
# tearDown) and raises AssertionError with a short message if it fails.
import unittest as _vacant_unittest

for _vacant_name in [_n for _n in list(globals()) if _n.startswith("check_")]:
    del globals()[_vacant_name]


def _vacant_short(tb_text, limit=700):
    lines = (tb_text or "").rstrip().splitlines()
    idx = [i for i, ln in enumerate(lines) if ln.startswith("  File ")]
    tail = lines[idx[-1] + 2:] if idx and idx[-1] + 2 < len(lines) else lines[-3:]
    tail = [ln for ln in tail if ln.strip() and set(ln.strip()) - set("^~")]
    msg = "\n".join(tail).strip()
    if len(msg) > limit:
        msg = msg[: limit // 2] + " ...[cut]... " + msg[-(limit // 2):]
    return msg


def _vacant_run(method_name):
    suite = _vacant_unittest.TestSuite([TestCases(method_name)])
    result = _vacant_unittest.TestResult()
    suite.run(result)
    if result.wasSuccessful() and result.testsRun == 1:
        return
    if result.failures:
        kind, tb = "FAIL", result.failures[0][1]
    elif result.errors:
        kind, tb = "ERROR", result.errors[0][1]
    elif result.unexpectedSuccesses:
        kind, tb = "UNEXPECTED SUCCESS", ""
    else:
        kind, tb = "NOT RUN", ""
    raise AssertionError("%s %s: %s" % (kind, method_name, _vacant_short(tb)))


def check_test_command_failure_with_specific_exit_code():
    _vacant_run('test_command_failure_with_specific_exit_code')

def check_test_empty_csv_file():
    _vacant_run('test_empty_csv_file')
