"""Scoring checks for bcb_1013 -- NOT part of any workspace.

This file lives in a separate tree and is never copied into an agent's
workspace. It runs every test method of the dataset's TestCases
(bigcode/bigcodebench-hard v0.1.4, BigCodeBench/1013): the visible ones plus the rest.
"""

from solution import *
import sys as _vacant_sys
import solution as _vacant_solution
_vacant_sys.modules.setdefault(__name__, _vacant_solution)

import unittest
from unittest.mock import patch, MagicMock
import requests
import os
class TestCases(unittest.TestCase):
    """Test cases for task_func."""
    @patch("requests.get")
    def test_empty_page(self, mock_get):
        """
        Test the function with an empty webpage (no links).
        """
        mock_get.return_value = MagicMock(text="<html></html>")
        result = task_func("/empty")
        self.assertEqual(result, 0)
    @patch("requests.get")
    def test_single_link(self, mock_get):
        """
        Test the function with a webpage containing a single link.
        """
        mock_get.return_value = MagicMock(
            text='<html><a href="link1.html">Link1</a></html>'
        )
        result = task_func("/single-link")
        self.assertEqual(result, 1)
    @patch("requests.get")
    def test_multiple_links(self, mock_get):
        """
        Test the function with a webpage containing multiple distinct links.
        """
        mock_get.return_value = MagicMock(
            text='<html><a href="link1.html">Link1</a><a href="link2.html">Link2</a></html>'
        )
        result = task_func("/multiple-links")
        self.assertEqual(result, 2)
    @patch("requests.get")
    def test_duplicate_links(self, mock_get):
        """
        Test the function with a webpage containing duplicate links.
        """
        mock_get.return_value = MagicMock(
            text='<html><a href="link.html">Link</a><a href="link.html">Link</a></html>'
        )
        result = task_func("/duplicate-links")
        self.assertEqual(result, 1)
    @patch("requests.get")
    def test_external_links(self, mock_get):
        """
        Test the function with a webpage containing external links.
        """
        mock_get.return_value = MagicMock(
            text='<html><a href="http://external.com/link">External Link</a></html>'
        )
        result = task_func("/external-link")
        self.assertEqual(result, 1)
    def tearDown(self):
        """Remove the database file with retries."""
        if os.path.exists("scraped_data.csv"):
            os.remove("scraped_data.csv")


# ── Vacant wrapper (generated by build_bank.py) ──────────────────────────
# Each check_* below runs exactly one TestCases method (with its setUp /
# tearDown) and raises AssertionError with a short message if it fails.
import unittest as _vacant_unittest

for _vacant_name in [_n for _n in list(globals()) if _n.startswith("check_")]:
    del globals()[_vacant_name]


def _vacant_short(tb_text, limit=700):
    lines = (tb_text or "").rstrip().splitlines()
    idx = [i for i, ln in enumerate(lines) if ln.startswith("  File ")]
    tail = lines[idx[-1] + 2:] if idx and idx[-1] + 2 < len(lines) else lines[-3:]
    tail = [ln for ln in tail if ln.strip() and set(ln.strip()) - set("^~")]
    msg = "\n".join(tail).strip()
    if len(msg) > limit:
        msg = msg[: limit // 2] + " ...[cut]... " + msg[-(limit // 2):]
    return msg


def _vacant_run(method_name):
    suite = _vacant_unittest.TestSuite([TestCases(method_name)])
    result = _vacant_unittest.TestResult()
    suite.run(result)
    if result.wasSuccessful() and result.testsRun == 1:
        return
    if result.failures:
        kind, tb = "FAIL", result.failures[0][1]
    elif result.errors:
        kind, tb = "ERROR", result.errors[0][1]
    elif result.unexpectedSuccesses:
        kind, tb = "UNEXPECTED SUCCESS", ""
    else:
        kind, tb = "NOT RUN", ""
    raise AssertionError("%s %s: %s" % (kind, method_name, _vacant_short(tb)))


def check_test_duplicate_links():
    _vacant_run('test_duplicate_links')

def check_test_empty_page():
    _vacant_run('test_empty_page')

def check_test_external_links():
    _vacant_run('test_external_links')

def check_test_multiple_links():
    _vacant_run('test_multiple_links')

def check_test_single_link():
    _vacant_run('test_single_link')
