"""Visible acceptance for s2_34_hms — rendered data, do not hand-edit.

Generated by ops/gain/r535/build_bank.py from ops/gain/r535/tasks_s2.
Every check is zero-argument and passes by returning normally
(vacant/vrun/acceptance.py runs them in definition order).
"""


def check_01_hms():
    from solution import hms
    args = (59,)
    got = hms(*args)
    want = '00:59'
    assert got == want, "hms args=%r got=%r want=%r" % (args, got, want)


def check_02_hms():
    from solution import hms
    args = (3723,)
    got = hms(*args)
    want = '1:02:03'
    assert got == want, "hms args=%r got=%r want=%r" % (args, got, want)


def check_03_hms():
    from solution import hms
    args = (-1,)
    try:
        got = hms(*args)
    except ValueError:
        return
    except Exception as exc:
        raise AssertionError("hms args=%r got=%s(%s) want=ValueError" %
                             (args, type(exc).__name__, exc))
    raise AssertionError("hms args=%r got=%r want=ValueError to be raised" %
                         (args, got))
