"""Visible checks for bcb_162 -- these ship with the task and can be run.

Rendered from bigcode/bigcodebench-hard v0.1.4 (BigCodeBench/162) by
ops/vacantrun/bcb_hard_bank_20260924/build_bank.py. The code below is the
dataset's unittest TestCases, restricted to the test methods that ship with
this task; each check_* runs one of those methods.
"""

from solution import *
import sys as _vacant_sys
import solution as _vacant_solution
_vacant_sys.modules.setdefault(__name__, _vacant_solution)

import unittest
import matplotlib.pyplot as plt
from unittest.mock import patch
class TestCases(unittest.TestCase):
    def setUp(self):
        self.fig, self.ax = plt.subplots()
    def tearDown(self):
        plt.close(self.fig)
    def test_empty_text(self):
        # Testing with empty text
        ax = task_func('')
        n, bins, patches = ax.hist([], bins=[])
        self.assertEqual(len(patches), 0, "No bars should be displayed for empty text")
    def test_histogram_bin_counts(self):
        # Testing with specific text to check histogram bins and counts
        ax = task_func('one two three four five six seven eight nine ten')
        n, bins, patches = ax.hist([3, 3, 5, 4, 4, 3, 5, 5, 4, 3], bins=[2.5, 3.5, 4.5, 5.5])
        self.assertEqual(len(patches), 3, "Three bins should be created")
        self.assertEqual(list(n), [4, 3, 3], "Counts per bin should match word lengths")


# ── Vacant wrapper (generated by build_bank.py) ──────────────────────────
# Each check_* below runs exactly one TestCases method (with its setUp /
# tearDown) and raises AssertionError with a short message if it fails.
import unittest as _vacant_unittest

for _vacant_name in [_n for _n in list(globals()) if _n.startswith("check_")]:
    del globals()[_vacant_name]


def _vacant_short(tb_text, limit=700):
    lines = (tb_text or "").rstrip().splitlines()
    idx = [i for i, ln in enumerate(lines) if ln.startswith("  File ")]
    tail = lines[idx[-1] + 2:] if idx and idx[-1] + 2 < len(lines) else lines[-3:]
    tail = [ln for ln in tail if ln.strip() and set(ln.strip()) - set("^~")]
    msg = "\n".join(tail).strip()
    if len(msg) > limit:
        msg = msg[: limit // 2] + " ...[cut]... " + msg[-(limit // 2):]
    return msg


def _vacant_run(method_name):
    suite = _vacant_unittest.TestSuite([TestCases(method_name)])
    result = _vacant_unittest.TestResult()
    suite.run(result)
    if result.wasSuccessful() and result.testsRun == 1:
        return
    if result.failures:
        kind, tb = "FAIL", result.failures[0][1]
    elif result.errors:
        kind, tb = "ERROR", result.errors[0][1]
    elif result.unexpectedSuccesses:
        kind, tb = "UNEXPECTED SUCCESS", ""
    else:
        kind, tb = "NOT RUN", ""
    raise AssertionError("%s %s: %s" % (kind, method_name, _vacant_short(tb)))


def check_test_empty_text():
    _vacant_run('test_empty_text')

def check_test_histogram_bin_counts():
    _vacant_run('test_histogram_bin_counts')
