"""Visible checks for bcb_945 -- these ship with the task and can be run.

Rendered from bigcode/bigcodebench-hard v0.1.4 (BigCodeBench/945) by
ops/vacantrun/bcb_hard_bank_20260924/build_bank.py. The code below is the
dataset's unittest TestCases, restricted to the test methods that ship with
this task; each check_* runs one of those methods.
"""

from solution import *
import sys as _vacant_sys
import solution as _vacant_solution
_vacant_sys.modules.setdefault(__name__, _vacant_solution)

import unittest
import numpy as np
class TestCases(unittest.TestCase):
    
    def test_with_custom_parameters(self):
        np.random.seed(0)  # For consistent test setup
        forecasted_sales = task_func('2020-01-01', 10, 'M', [200, 300, 400, 500, 600, 700, 800, 900, 1000, 1100])
        self.assertIsInstance(forecasted_sales, np.ndarray)
        self.assertEqual(forecasted_sales.shape[0], 10)
    
    def test_forecasted_values_increasing(self):
        np.random.seed(66)  # For consistent test setup
        sales_data = [100, 150, 200, 250, 300]
        forecasted_sales = task_func('2021-01-01', 5, 'M', sales_data)
        self.assertFalse(all(forecasted_sales[i] <= forecasted_sales[i + 1] for i in range(len(forecasted_sales) - 1)))


# ── Vacant wrapper (generated by build_bank.py) ──────────────────────────
# Each check_* below runs exactly one TestCases method (with its setUp /
# tearDown) and raises AssertionError with a short message if it fails.
import unittest as _vacant_unittest

for _vacant_name in [_n for _n in list(globals()) if _n.startswith("check_")]:
    del globals()[_vacant_name]


def _vacant_short(tb_text, limit=700):
    lines = (tb_text or "").rstrip().splitlines()
    idx = [i for i, ln in enumerate(lines) if ln.startswith("  File ")]
    tail = lines[idx[-1] + 2:] if idx and idx[-1] + 2 < len(lines) else lines[-3:]
    tail = [ln for ln in tail if ln.strip() and set(ln.strip()) - set("^~")]
    msg = "\n".join(tail).strip()
    if len(msg) > limit:
        msg = msg[: limit // 2] + " ...[cut]... " + msg[-(limit // 2):]
    return msg


def _vacant_run(method_name):
    suite = _vacant_unittest.TestSuite([TestCases(method_name)])
    result = _vacant_unittest.TestResult()
    suite.run(result)
    if result.wasSuccessful() and result.testsRun == 1:
        return
    if result.failures:
        kind, tb = "FAIL", result.failures[0][1]
    elif result.errors:
        kind, tb = "ERROR", result.errors[0][1]
    elif result.unexpectedSuccesses:
        kind, tb = "UNEXPECTED SUCCESS", ""
    else:
        kind, tb = "NOT RUN", ""
    raise AssertionError("%s %s: %s" % (kind, method_name, _vacant_short(tb)))


def check_test_forecasted_values_increasing():
    _vacant_run('test_forecasted_values_increasing')

def check_test_with_custom_parameters():
    _vacant_run('test_with_custom_parameters')
