"""Scoring checks for lcb_3502 -- NOT part of any workspace.

⚠ 計分用的 GT。住在 hidden/ 這棵**另外的樹**，永遠不複製進 agent 的工作區；
  任何把它的內容（含失敗訊息）回饋給模型的路徑都作廢那一批資料。

case 組成 ＝ 題庫的 `visible_tests` ＋ `hidden_tests`（超集），與
vacant_network/codebench.py::LiveCodeBenchLoader 的 `hidden_check` 同一組（ops/gain/data/lcb_bank_v2.jsonl）。
"""

import solution

def _aeq(a, b):
    """與 vacant_network/codebench.py::_lcb_check_code 的 __aeq 同一套判等（逐行對應）。"""
    try:
        if a == b:
            return True
    except (TypeError, ValueError):
        pass
    if isinstance(a, bool) != isinstance(b, bool):
        return False
    if isinstance(a, (int, float)) and isinstance(b, (int, float)):
        return abs(a - b) <= 1e-6
    if isinstance(a, (list, tuple)) and isinstance(b, (list, tuple)):
        return len(a) == len(b) and all(_aeq(x, y) for x, y in zip(a, b))
    return a == b


def check_case_01():
    args = ['abacb', 2]
    want = 4
    got = solution.numberOfSubstrings(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_02():
    args = ['abcde', 1]
    want = 15
    got = solution.numberOfSubstrings(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_03():
    args = ['e', 1]
    want = 1
    got = solution.numberOfSubstrings(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_04():
    args = ['sf', 2]
    want = 0
    got = solution.numberOfSubstrings(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_05():
    args = ['aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaazaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', 899]
    want = 2207252
    got = solution.numberOfSubstrings(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_06():
    args = ['lesuk', 3]
    want = 0
    got = solution.numberOfSubstrings(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_07():
    args = ['mmofpdohxshldgauhyncmagyriuhuqvjffzblhjcbxxmqqzhvlyctijfhzbntrzcywoypxahcsoasjzxddakdalbdgyuwqwxitauuvtohcpvlhbblvjmpyqvffovoiujynubvucooswelzoycolkupczgfdlmqavpovhuwrqkiznhhulxzskhhsbmgudffbivfkurakycotchsglzqhxrgqqwmteuragsxsgmqomdntcktgbibajbhxiducmkqdyswbzuicywlcbyqhnytxdgqkvyzlwolalzhjwenmohxwgemnowhjicravyjvakcqkpytrdapwtytmxixbzvpuhiqqosufoslqhrdztkgngocpczzlsqiyntpgdkfagmguobzxwtrfhrslnnucxlkqfdtujsptthtqjcafsogdvdpeevwhqinujxtlupoedeyerkwlmykwjqalndripimpjbfmfjnqmkymioolbwlumdfqyywkpnxwgsrdcyskvuwobtzoqwurjwetplvzkhkerdfwhqegbvgekywnjfownjzauubmpfdoqrbfdtsdvrlxywihtrywraugvjrixjioactwrythvkevdvzqjrwobpxlptkpqzhghguytjimmvmcsawulsqbnmfjgouiqjixgkwrczzvhduhrwampqjjbjizapexrkpgfmrehwpubdbsieyfbraamoeuamvorzkeqlvpulecrebeylnjranhpoinydwsyagznaishqzsukgghnsmokfrjasontnevnpmfmmailayxgamdkltbbxqghhwausonvtpudmvaerpqhlnggnpcqzrhynsufwjxrauc', 30]
    want = 41528
    got = solution.numberOfSubstrings(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_08():
    args = ['jnxinjmhumednmvvkjojzrcczfnhewplrvrtsaabyemdwjiadkxlbeqfvuvkxboivxusvjjhdnijfnwnrnbfpddhopvmqpmgfhifqpchetwgxrgwdkpsdeldgueuigqsrucybrojcnwqmxazwlwgvhdzxrgxvubftgxlfyniqokbfcainseigtwqzftyignanvomlmhtmdbkobcozmcugxxzwjqpmfjcbhbwliwyvhcthqftxxzpuzagubezrhbvdnehiwxdbxzbrxwogevrjkmztrhnssqnjgmqlyxfneewoprfkcfyvwrhwusxkwbifrieiedpgudyfmqjwonfgzxejkovqovedlohcernrrhtslqzwbeeziwptalhwptcflxufvyquytvxdedrllvlmbnzsfmkcpbmzguthmyzfosxyzdioavybjjtuadfxfctrrvutaypbjfvvrsxdznfiajlgsrnpbeiuvpmafdbavhogiubykhnxhbtjrxjpvwgrvqdcsirebxfwyqlhlttvdtpnolskdhdnycwyxijvepwlfmxfgeqtspztsbrfdqmeztwrzkpbffxecadnzoxaippannsbmaregbqhthoctzjgewrnvbzfzykehztggqggdhzzkykzqrhbrfkjsztrrdbzdvwyfnazlchsunzzthjmwrpxmxzkxnjrxnmlmhplidtzglbemiowyrqpgluhhmotmluajflxpzjhmfkvawermuwqccxjjmurjxycaqgxmxcexoykqevdiutzlkigmqkfgpxxcmitunkfkjoipvqfteccnefnnaxjxmyilnkgqtziubpsmzeocpzjjfswvqbbnaxaxzsjsyzqnwcxptfbcznmcgbooebeixrbykhjxjpzzzmamvdvfpfrsgtkfvisigfaegsjnghcyagabvuthlpagtzesguhxszvxffaxiceukmhtwrxxaujyarpyucglfvkthoqyftfzqkmksvtxhhpjalrxcjxcsmatktombdhwhlxfxiwtzftcseldedinvamykqykejscmpfkuxsixkypcbfkdymftygifwwvwkqmxkgogguluwizinjbsvrwmuwnahwpsnvyfyuyehdkjezpiaxtnwvkjcuctjttzmfojpleczltcsunwiixpuippovlincyrcqkynwsktroamsjxajilpuougbkwmyogtqsqjpvaelpltadjvgjelqmxnwicqobdqjlajtuqyvppkiloqljedbrtjnycinclkywbafxvworybohqtlyytdqtkkacyvupciflmangymwphkcuksmnnnggzcrqsptxxuiszzmppnrwyrylrphowjfgdqvbfrehqtcerwhjbwqtqfmruyfhbixmildgcjllyzqpajihrckucclssujhywfidiunflrcoxijvkxnfsrgeuotgwwtudmbosukjdoeyyirmrcsfprseslzllcbygsonlnikmazkpqthukxxcbcnwplfpchwwgzqbpgvsqpnbzukmixswhghjkukasldeyjarvdxahqtgchwnazulfwtioquztmpgmcdscafaqvgryxaxmopnzxkoohwbwutfrikpcpfzcdwwtzmfammrnzyckrraoqakyitmrtdqdaihvaipwrozixyykspyvtevrjndiboeaijgbwagtizwknqnpupfremkyzbmonfgldmgxvubvuaowbkeoktszwpnmrdcxluomiupanrkgpnfahdzpwqncnddnhfejnaheuxinobtfeyxhcjuiscskoxxojhsznirokjcqkrxktcfxdxughrxppuyycqwsmvpohdkmqzvlbxm', 1]
    want = 1749385
    got = solution.numberOfSubstrings(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_09():
    args = ['bgsemqvc', 3]
    want = 0
    got = solution.numberOfSubstrings(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_10():
    args = ['hudpcyqouvudvbwsgmkdwitvbkmahidntatxyfwilsxpnqglbbxpcadmwaxjcnsfkgdosscrffraafgsdrxsrjerutttloiframbnpioxldmietuhxiopjsrqynpqrdinzcbslmseqgngpuhbgdbkbijxwhbqxiayqgcioyylncyxuoyapanqupreklxlbccpxnsyatemrqedgbkjirxbctxqrttopjsmodljdmvabfmwhlgrmjwfjedmcleyraoibjryepharajgwuckcloymbmkkklzfnktcsxbuozzuhpkrbmcxgnxamttatqbpkaqgolraqttizgvpavmmwmjfjzapyalysstaefinfdkkmtjgcfkmvturfhrqhjzzwjyymmonfkexbbearalncdssilpujlyqnzaufeshvckkhkxlqqivkkkmiynwmbotiugnfsgafxgoaqjvgdxaxekcguuotowwjwqdwcqnhgjlzyagtnhulfsgwhlnjsogkcamfrikakhtrzjugqcuyvlspyptbjoiljwlofjbthvnuhprsrimclmxzjzzjwwwyqcoatmiabwgxtdhbaofubehsjbuthmbwrhggeyfpkntzciayoijaoddlwyrabzvbgzoynhzgimuaaogprwtahgotybqcmhpcebfvkbnljnomsfdsjhumgqyvgkjncfuahlxvecxypbgmcikrroouwijsfvdxfbxzjjkeqdmxdwyiypbquyqqfqwupupmqlyxcjqxkgaarnrersfsttyknycwthmcczscuxhynxzkvfsakcioefjyfacfglruzbttmsijumihaqwamkveelnruzxdwprcznlxzldygifyqlfwxeeffayyanuogbaqzrsbndzjqcavpfidivzgvqwelfbqzybopstkuwiszqipnpbtixklsqdspiybemqxeeynmipauzieznpxisfgcfnriumltiapnxey', 18]
    want = 255155
    got = solution.numberOfSubstrings(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_11():
    args = ['pvtvq', 5]
    want = 0
    got = solution.numberOfSubstrings(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_12():
    args = ['urv', 3]
    want = 0
    got = solution.numberOfSubstrings(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_13():
    args = ['hvdcirxim', 1]
    want = 45
    got = solution.numberOfSubstrings(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_14():
    args = ['aodxobfvusjkrhglxyzfjxblkhmuvdjovrabhrjgfwgpoxpnimxujanxktuktifklhpsgnezfbwufayasulljnpisawfabibeytjlpdkueqxzbxppecbocheunzbxevamxgclrcpqyazoztyginoghnrrvekmwovrfetuponvigxyakkviaxfvjsevpqbryybaovpmgmivgoxbvtqeawktoavqtmwkhvavogfsbaiylislcbjbusaroqtfkqljzxrnavmcsdjyznwkrcbdcdwemsrebrcwppoacmsvqivnjnikwrdjkjdjbongyzgjnebkhatpopaplwzqzwbzvpbkjomtpejmjxjarjtpxmszbiunbduzscijakblvykujdjncoqbronkybjgauppyytiktqwwdxbcurwhopuifgwiaepydcqtaflzvzytzocqvhzuvgcrithaizyoakhysslkzkpwkghfincpmvtshrqcsmsrmwjibwhqiximmplonalcgswzxrimmelhiltcbnxemupapizhzftajpwnxnhycletecmjgqwvjuyclgboboemzwfhfzcbzjuzyzsspqoggnzaueergdycrylofcwwuaoxoqbqwupxoxtmnjscafncvzuapigmrmbvqjsltsplznqlmkxllhkzmkusutgkboovzqtnhgquigfoynzhtcfxntpgviycpyzoqgcysqewtzxpdjsehsmyqiqtuyqwkkaraejavjezcqrjfifeqojtrmoypkhmfbzqfwupzoadwanflxyxktrzpfwndbovecmmmrufpyrhlchpapavgczhrbpxrrsuhbwqtnxpygrfkljjbgavctwrqnayjjtpwwnyjzahijijkcittreaupzjmvmzxxbgapfmrqdgquitlmcuacsrdskditwocwtvgbnubauanfruzfhycvjkojkzhavwlowkzkganzdvhkwpxihbbuinfsrdtthotbxjrcgtklzkgbdwwrrfoojjblzrsfajukserbwttvmwodhvbxvmkjhdyvkcgiefrrzivkrzrwvjrantsrswubptrazyqkauyypbqsvopwzvxxmwcnmdinhauiwrstofgbtuhdayuiiynsexwnshusffhhxfjasqwcciqqmwmmxrdzgyyrxpriljbpagqgxcvqgejcxrtatkwrqetbnfocamcqbwjjtlgbhbzoqdflpypidohcqqmivkmwoqzaykcyjoyexdhfmmleebojsbohevsnuvwtunrdllugnwzxyfjbnlvyhjfjoawfcwpgeymdihwqofzbszmkgossbnrcxnzrbgkpptfftjaxqaorznaarmfumafqqofuerqkioshcgandluibtlduatqgsrqdvigyhdovtcjnzjjvudtydxqqhdsobfwdlnaxxtnhyvmwqdiclhkhibnpifvcsokjwwjromzrzzdrwygfnlhuimfxwfhymfsfkgiepqihibfgrwzaginoqjxcyuixcvqlerrvoixkkhufhpjltezqshwwjecybayhnsiypvbeaahubbxrjwiwtfululwhuffwmcfemdikqgemwiavkxhzgbxzyblptabmpqdmgrdspmmwjhaoorttclldmwguetxituptcnjrbivsulwsslrxlrlphuwdaflnpfhfxabqbdcflbqhfskolbupkvrararjaegzfidkshyverfqowlsjcdwkxdnodstzlqbhxdlmnmruhtvlmkgggevylzvwihroemptnwinxxophxgzbfbkgoksaqcrzvildynburgyzzjqisrlrueiponsaaayqytzuuwkooqlmtyoykzjvuzhoprahgtmcnixcqiujhlhrbpmszmtiudmpmsffebkzlcdazkrjkgknabeppyfemoqkbiimhlvaqednifonctdiihzeytqeguwbxzpkuecoynvxdysszjobqcgbaksbzuzfcinbwjbmisrbnpgyoevhlfrobtysacasttpcdprkfvkgzawqdoiyfymoirifnmfncsiphvgclzemabpyqzsajxedulvaeqwrpxvvtzmmoggnlqwaomlpwkfeilpfggkywvxvpwssbkaimvpepfjvsomzwwmxefotrolvlyijhagjpfxwtzprrfagirluxsltfsbfcmsokzxuepmywagzuaulhoefpfisihminrasqxrnqhhbkyggwgodhraftrocjddiscnycgomkxmweokpiusfsdbongwmxbcjceyxohfrfcytknkmzbltaizptokuwdbhcyoqfasokvygjdgzmcwyxfmfqttplkzibzheabuftikvjtxydslomyeerpjbasscbrcnucfcplvemusbkwevllthqcxnzientbykdqyzkrnnjmwpgqnqiufttastujeopiuoulxpxejtgoigbwyzphpbxomleludgbwowzgnwtaszmcwqlfybbztznfavvpklrymcxpdwtffyzwttduyxjwrsetyipqgixdubatvyajuomatspmgzfbufwpkpqlymnxcmthwsauahwftipqjiwjethsgzqrzr', 23]
    want = 2493676
    got = solution.numberOfSubstrings(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_15():
    args = ['zfvqqrmi', 7]
    want = 0
    got = solution.numberOfSubstrings(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_16():
    args = ['mnsj', 1]
    want = 10
    got = solution.numberOfSubstrings(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_17():
    args = ['xsndmrbwxaffrwdjztdffpvxmzwgutsosazlyyfhkeqqwttzmcgeyurbguxxkhviqzcixezdwtdrsdvtfxcmriwcsmdpctlcimnblbqkmxmnvenmwkfmbqdwdcnjgcanzvkkjelssjqvohbvyhdkbjuxhszmhwsshmlabqqykkfxdkeizbjmejdqfycxvawvcjofranidgazvkuuograujfvvfsuclnaqdnifzwecdbqxhhhikcdqkadojgtxteernxtpgzzcornmosuuayngrumnzrurizxhierufcxmmvbjhraqqidnrdxbgegbtqvyczfnmppsitdxnxrsfizmuyxhhrjulywhxvjhmdvqytzkzlmtlvuccdhkyqagnzfcxnknydtzsyslosivtlzwrvitjpcxrgmwxqtphdauklswzajqlbblgdvoyrsytetiulwobwlipmqoghlwashnuwtuinlamligiaukizsxyptulshxmlxbaoektuzszepygqtmanjrglaulgjyfbsdsgjwqnzhiwbzjkqnzxlpytkizszysrocljsdkeslqnrlbkmzirdksdyoykxqokxsqbkiadqllyqddbclhpubtwuygtiaxjxofsbholaoucgxbzivzqgoukjpcilgbzrmxoesdhauyltjczvynsyvqjuinqjdcgqbubhztjfgdqldxzlflisepibpbyqriygxyrzimkgdncwuiuvupflaftgpwuebdhbwjddwofysiayvnneqahxnkjdenkxdlyroieggmmkjjeltnangtuqfvyrahsxeovvvcqihcoergezcgdhivrexbttawmpkqpbgoylkkmrjtphnrikfsrmdgjxedvtimaqgqxjxcoglprpwblpbbsoopcrswjnoqqgueqbfybrqmbnlagvpgsmzrdjaidzjaszpkrwvxqsdkcxviffgtcgjlltfbdrdbkwmjcnaselzvghmidgbxlythsdikxqnbikdgrmxjqyxzmarcvdpntosbcqymlymhyrtrjapmhkrxhxecyjxyjiqfogcoetijbbgheyhsvcrhcsbnlpnlvqdyjyqkmlkqjgucfjqzdfijyprmmluzvleivdtpslbblsfqjshzlexdxlyjoiejurhzxzoffypzqteraeotvlefugayugqopyocoedjlzqxpnlafipddwggrvotedefpkcrqelptrpihipocptumjpwcpcaxdbrrkzbgrgusntzglgawefzkpgctyzzsrmqdbrmtaysdetnjhqwnrotylcnxzrgttkyfpwvhquvpiwbszmzyumjukameyoejocvwpwegyqtqnstoueqjsxwolmynircfnrpcjognunvcvsvdeczldgcnzspoerdzccayirpcpzaeiqztqtumqgddimyoiaelplwftkbrsshscilcriomjrlvwsrioizuanlbacrzliqpungkylqjzjkieckepekorbrdsmktqvhjxwimgdomebhorftyeagskailrukdbspvmihndjmwmejhsljmutalyuczyimchsynzlmlvcpxybgnljoojbtusommmhghsltjemcaclqxrnvaxebwoimjhquapeinmplnwiqxysfamsbvtxxcigxihaolrhquxxegcjrobpcjjuebbrhxwenxkpccymfbwfjdkofmzyofefrjcpuheeiivnsdnudbjncpqbafebqubjnruxwuvbxujrlqeicrvwigfwwyolkurbolavgajtckojsbcmnmsfhpatsuzrphdsrhmuqhrzpvwujboguocifhadxhbsschrkduqgpukzwgafrfgizxzetdjcmjsxwoayefwedznskatnvxaxbnskyxnscsmjyjswvkmwhmifkorwuaimypkqesmqirefkgjanyasduirosfutpvxspvvixvazmowlescoqczbzbdowhoshhfdteorbiedrepjssqkxeecutifyqltrvncafafcpzsgrrmizgkyhziowpehdypsafgxifubfhvbvwjtzngfgooskwbvayuilktfdpwahlvmpcthmioxbjzpedswxzrpwccteeviucgjjmoqxgyjxjrxgmrfdzrlhykgekvmbmmfapbhvuwbnxonyefdexhpmogifwvutwuamxamcacfskuouwjlvzknotsjomxjnbxbmxyybjhzonceakdyqwhodqvsovmxzznhmrpfdirjdxehppnrvlhazgiezrrsjaffuhynqatvztbnoyjpfeqzblogsfxdlulpskjxvrjkkpadjatyenlppedohifxmdcicsqkrkrglmwvkbyjklbvemrnalklggetcbxlckkdveqvzrqkvjsjytytuyfpzjbtweodsxypnnrwwmuvfaeuyinctkkqjdoqcgoilcinoydfmmsqsljhidgobcgxvpekakagegxwwoabwwohkylibbzxawdcopnwjqdkmgmcgwobuzontlidcwckpfdnpfyoyijqgibmnulzwbnevtexuluhxcagrmjlaulglqmwjtpwvrdmdbbzxstdtocivzwrdreccnteaxdlxfwylbsnnegnccerlfcldlgxadwbkzswequubgxvtuspptggmfxntslbrymygwxdibtbgwysdwyaxjjfkksuucdxanmipsajylmcpdabvfiyhwhwrwybsfempufdnisebvzifuviuyhjzrglsdqsttdjxzgkkgumlhfdekzqpdhtvlypdtekdqqgnvjlpwwgqbekvtaezxrvwtfxucifumqawwvgbfeufwhijyvgagvygmnaqkfhrtqnucgdvpguhwkrbjcckcsoylqteavzbrqoxafiemjyfkxhzzyogzolgqvvbnbxwvaurzqgktsyyeketbmlbgzzcztinlsriqfppzpinwfbrtwcimyqajkywzvuzyzpiunw', 1]
    want = 4501500
    got = solution.numberOfSubstrings(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_18():
    args = ['qkfiuuhd', 2]
    want = 15
    got = solution.numberOfSubstrings(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_19():
    args = ['szbhlom', 1]
    want = 28
    got = solution.numberOfSubstrings(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_20():
    args = ['utoo', 1]
    want = 10
    got = solution.numberOfSubstrings(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_21():
    args = ['hxccgfp', 1]
    want = 28
    got = solution.numberOfSubstrings(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_22():
    args = ['kenxt', 1]
    want = 15
    got = solution.numberOfSubstrings(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_23():
    args = ['deaixultvnousxdddqhvqmiaprsupcxmvggmnsrufwanytuybqrbzestvesdjbmeiuxjlgkvwksmmtyztnuogkscmcjlrprevqbgavesrslteqiyjrkpswowfniyapgmpwyvlbwqydewvsvnjaislyqhfvgjdytvuawsnzunzlzpdfffemlvevlgkyngosneakuhdvaoytdkowqvyktkroiotaotzzhuokvopwkdgtlbqzwezotegdieonhcyubefdfpaaaoaipfbuwvavbiunxasogopgkmddfetushiqdibgyydquaxjgvqrdpxmxtguvsrjgtofribsxsbvnhrvztrsfmsbgnxfwnfqgujeqokxatdbklwterzfbkfzqnsaxkfilcafxyweuyuuckplncvsroscxssrgqprweqekfenppjsppfatbonjtewwfkypoccxgkeckfxydopqzlspqetwkdbxagagnwldjqhxcgqcuojvquvtpuhstglhpmzqjrrxiarlpaxdlrdflifrimxfrfvxiupfsktwaohxifqizocfgviiiojiuwbzycsyrltfqzoywvxqrtotvkryltpaqzkxpskoooyssnmenlzeqzkvhxctmkupxkvgubffpvyxuapbeqftyytijtyalgphkotwytwznfcoedsjwtgppnadwdxsoymtxkhvoiyjxvyflzohumkndhcrwqgqmgjwepwyvlfolqsxckadgskdzhmhhxsidpqwcispdisikbxrpyphxnarxzqipimzaepvlfmlvhltwrnzlwawrppjsgsyprrcrtlmsie', 1]
    want = 344865
    got = solution.numberOfSubstrings(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_24():
    args = ['aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', 7]
    want = 4465
    got = solution.numberOfSubstrings(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_25():
    args = ['aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa', 6]
    want = 4560
    got = solution.numberOfSubstrings(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_26():
    args = ['plkpsrrwstvjzurkjsafrenljyfhhnlnxlzxympidbhdjrmyrjygjwwleevodrojthijlcxswlnokrdkwirhvzprvrzpttvxgzhkyvbfpboeyyhqbmoxdisdpogjnxzmswdgagnfqfrkjrfouccxlpztaaiwnyjwrqfpvjuonjiwaijzpxeiqnkdwcxnpqvwounzikpcfdnxziaojlhxqjwsitnevdytfwjldzilbezuolmqpanbmtzbpeoefmzzokgifzccetlclsxqkbspvxrrbaovtszicekrvlxsyyhonkcytithusxofexebgxxoidrnvehlacmpkwbeqcijwjqjiqaijyepmbmmaapfxlzushssjenmauxuszgvadirplrfqboyctgyodciupstupcfcgpcwodoswrcbawcslwodxnknkgcameazojznbwgzcdlfpvdlphqniuyqbstnkdouktlzveexitvsgupdoinyjbekfcpysphdcctdaanpnvkhkgawpjilenqrsshcswrlevtwbnlfmaxzqixtdwhmymehmibhedpookvwquiimgcttnxofonivmcybtlomslimbuzvgetbqrrtoydvzbzmmnagmhskncarickoqwhodrcljaglfbzulqfosjlfshgfaputznfmwfhlohsyctzkxbcjznmetzaolijglwattacwzjfsngajelwezxuecpdhnrioglnngatrckmrvxnxcmywbmodzvcundkcfwbaosdvgnclrkmlhffusytguxqwvdktbbfgqpawvzlqgnjzncmjyvwaquahdsaoxubusaymqsamsoecqrxehooztpvxwdwccezahapaoyiqueuqreopkcvbpmjabepdsyajchzawkdleiqodhhktrppneegflshyqkuzzewkhkheqfabrxxqusuhjmkpaxroiumzyjszafhnujxpwgsidyrfbtyvtbnrcmicmnxdfgilqhkjqppgycoljkhwtmbcicxleugwnrslfrkkpyllzzszkhpwcpgeizaoimzgjllbzqaajusgnhkcjmzoaitysvskroxecuulgtimuqpqllrxxexgslokpwxvyrzzxjtdqfmeeqwprgupqnnvwirexuxmquephwqbyzebrujptunfxvzlwkhihuldrdtthkglhlofuiuoqedzqhtcdycelklfguqvwkwrvdekziyqqvznwrfrehexejxcaclcojavcajcwwrpvzyvpquspvgnjzvryofekdfqslyskokmwtzoyxotlnaqpwdwgrfbdlkeqydmxqyjovfxizuweaospylzlezfpzzfxyolrmvxxqyclisqmbsxoilkksqokofjrcutarwozgvkrlttskxlvddlhlwipkamoezrfqscfxployoayvigbuoyperrysbsgjqgveiakopczuovlgfpdupfeaeodznxtakwqvhjyolptovvsyjovlfrfwiwbfwxfqyljumrupkztmqaeszkdjvwuipygpgknslxikqmhcdjqllsvzvasojxvzmhxfaepbkpctrxdwrkcmflwtaxxbbtoizxfkuxcsjwfngyojfhhsjyewwkimijspgjhvtmehhraxuwwhbpobnqtfyxaumeberrlephrhpieboizrxnhvalmobuiyokcmotrumhgtokxjzosawjrlfmarsawpmxjwotfwdeghanpcjnqwlldidgpicnjkyezrgeqmutabeibusrzsgmqnuqdxorqxqyrrojlvyzldonvayafuosiqpwfxjrnnjxydxaakaxytgyuteugmgorgkdwtdmiyowlukeeqrvnekemiinesyifjkvthcwfkmhswojhcicssqxvwetggasesrsxcwgnovcmqltptdvvyukpzzsteruynxvzoxapygypsdfcmhgycjeqhixwpuslglxfurjnvggtnetcblinwrisxzpuxykqdgwljwzerlusbucqubpxmirnuhmwufmlsrxkyscpyclycmsojubyumepgalkhmfpxiardudxllegmfwlprmlfelgpnnpvawcpiveziiifmdjaqbczfwejsjayonwliiqitujwiahlaiurbknfsjjpaqzzuwrynmnbkbrbqhtjfwurzkbnvnmtcuatpufoxlkhdufsjsiugpqfovcqzsepycmdpmeznhtswswbglsytklwggqzojzcvyihsmbdrnbvywzvjhmrkdwazhxdoohstbcotqlsmhjyyjsgtctbvmcskmaeeuzpcaiwegbkjgzixtbiuojxleijdhfwfpvrpefaexuauvbypxajcwggvjtjqalylqlrczgilkgcnbdnritegzczrhctnziwspsayajsdjesemynrzmgqkiygmsutetngetmfnyvtswoczxhbiswhiaeosossmibdwwvvuxccxpwpxfcxldayxagrnpbzhgqzkxwsmcqwwwqlezyrxmnsiubtifdeiyuvmzumctpvrelbningezfxcgwhmwrgbesazsijigelqeiwyhhqyoncxnqxejmbkhabysgohclnsnfkjyegjfkigowgarwfdntxrogzrlglytnnqgdzvxwduinxkkgyfvcrqmcjpnszrynziynekwndzeskydcwhljojvutctxwhhtfzawwgtdcubguykhgqfjwsizrnsfrwrthuuiehpeiggabafeceofssffcocteinyfoumwqihsdaxcwapkvowgmdbocujckehztvigtjccituovtcylqmzlbtdgjjpznlobdgnlbokftwfrrahblqnxhcqxvdjbgebrvkahqoozuumxeyfvhwpwokokpsjykgnyumnborpdxuecmcbabpwnpolsqqzgonezwcrhsdklesyljzfsctpsgafnfagqmqrmstoygpdwgpvtxgkjznxjnhoykcahzddd', 1295]
    want = 0
    got = solution.numberOfSubstrings(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)

