"""Visible acceptance for s2_11_titleize — rendered data, do not hand-edit.

Generated by ops/gain/r535/build_bank.py from ops/gain/r535/tasks_s2.
Every check is zero-argument and passes by returning normally
(vacant/vrun/acceptance.py runs them in definition order).
"""


def check_01_titleize():
    from solution import titleize
    args = ('the NASA report',)
    got = titleize(*args)
    want = 'The NASA Report'
    assert got == want, "titleize args=%r got=%r want=%r" % (args, got, want)


def check_02_titleize():
    from solution import titleize
    args = ('hello world',)
    got = titleize(*args)
    want = 'Hello World'
    assert got == want, "titleize args=%r got=%r want=%r" % (args, got, want)
