"""Visible checks for bcb_1124 -- these ship with the task and can be run.

Rendered from bigcode/bigcodebench-hard v0.1.4 (BigCodeBench/1124) by
ops/vacantrun/bcb_hard_bank_20260924/build_bank.py. The code below is the
dataset's unittest TestCases, restricted to the test methods that ship with
this task; each check_* runs one of those methods.
"""

from solution import *
import sys as _vacant_sys
import solution as _vacant_solution
_vacant_sys.modules.setdefault(__name__, _vacant_solution)

import unittest
from unittest.mock import patch, Mock
import requests
class MockResponse:
    @staticmethod
    def json():
        return {"key": "value"}
    @staticmethod
    def raise_for_status():
        pass
    text = "<html><head><title>Google</title></head><body></body></html>"
class TestCases(unittest.TestCase):
    @patch('requests.get', return_value=MockResponse())
    def test_multiple_urls_in_string(self, mock_get):
        # Test input with multiple URLs, verifying only the first is used
        result = task_func('Multiple URLs: https://www.google.com and https://www.openai.com')
        self.assertEqual(result, "Google")
    @patch('requests.get', return_value=MockResponse())
    def test_malformed_url(self, mock_get):
        # Test input with malformed URL
        result = task_func('Check out this site: ht://incorrect-url')
        self.assertEqual(result, "No valid URL found in the provided string.")


# ── Vacant wrapper (generated by build_bank.py) ──────────────────────────
# Each check_* below runs exactly one TestCases method (with its setUp /
# tearDown) and raises AssertionError with a short message if it fails.
import unittest as _vacant_unittest

for _vacant_name in [_n for _n in list(globals()) if _n.startswith("check_")]:
    del globals()[_vacant_name]


def _vacant_short(tb_text, limit=700):
    lines = (tb_text or "").rstrip().splitlines()
    idx = [i for i, ln in enumerate(lines) if ln.startswith("  File ")]
    tail = lines[idx[-1] + 2:] if idx and idx[-1] + 2 < len(lines) else lines[-3:]
    tail = [ln for ln in tail if ln.strip() and set(ln.strip()) - set("^~")]
    msg = "\n".join(tail).strip()
    if len(msg) > limit:
        msg = msg[: limit // 2] + " ...[cut]... " + msg[-(limit // 2):]
    return msg


def _vacant_run(method_name):
    suite = _vacant_unittest.TestSuite([TestCases(method_name)])
    result = _vacant_unittest.TestResult()
    suite.run(result)
    if result.wasSuccessful() and result.testsRun == 1:
        return
    if result.failures:
        kind, tb = "FAIL", result.failures[0][1]
    elif result.errors:
        kind, tb = "ERROR", result.errors[0][1]
    elif result.unexpectedSuccesses:
        kind, tb = "UNEXPECTED SUCCESS", ""
    else:
        kind, tb = "NOT RUN", ""
    raise AssertionError("%s %s: %s" % (kind, method_name, _vacant_short(tb)))


def check_test_malformed_url():
    _vacant_run('test_malformed_url')

def check_test_multiple_urls_in_string():
    _vacant_run('test_multiple_urls_in_string')
