"""Visible acceptance for s1_26_cells — rendered data, do not hand-edit.

Generated by ops/gain/r535/build_bank.py from ops/gain/r535/tasks_s1.
Every check is zero-argument and passes by returning normally
(vacant/vrun/acceptance.py runs them in definition order).
"""


def check_01_cells():
    from solution import cells
    args = ('a, b ,c',)
    got = cells(*args)
    want = ['a', 'b', 'c']
    assert got == want, "cells args=%r got=%r want=%r" % (args, got, want)


def check_02_cells():
    from solution import cells
    args = ('',)
    got = cells(*args)
    want = ['']
    assert got == want, "cells args=%r got=%r want=%r" % (args, got, want)
