"""Visible acceptance for s2_39_strip_comments — rendered data, do not hand-edit.

Generated by ops/gain/r535/build_bank.py from ops/gain/r535/tasks_s2.
Every check is zero-argument and passes by returning normally
(vacant/vrun/acceptance.py runs them in definition order).
"""


def check_01_strip_comments():
    from solution import strip_comments
    args = ('a = 1  # set\n# all\nb',)
    got = strip_comments(*args)
    want = 'a = 1\n\nb'
    assert got == want, "strip_comments args=%r got=%r want=%r" % (args, got, want)


def check_02_strip_comments():
    from solution import strip_comments
    args = ('',)
    got = strip_comments(*args)
    want = ''
    assert got == want, "strip_comments args=%r got=%r want=%r" % (args, got, want)
