"""Visible acceptance for s2_27_count_lines — rendered data, do not hand-edit.

Generated by ops/gain/r535/build_bank.py from ops/gain/r535/tasks_s2.
Every check is zero-argument and passes by returning normally
(vacant/vrun/acceptance.py runs them in definition order).
"""


def check_01_count_lines():
    from solution import count_lines
    args = ('a\nb\n',)
    got = count_lines(*args)
    want = 2
    assert got == want, "count_lines args=%r got=%r want=%r" % (args, got, want)


def check_02_count_lines():
    from solution import count_lines
    args = ('a\nb',)
    got = count_lines(*args)
    want = 2
    assert got == want, "count_lines args=%r got=%r want=%r" % (args, got, want)


def check_03_count_lines():
    from solution import count_lines
    args = ('',)
    got = count_lines(*args)
    want = 0
    assert got == want, "count_lines args=%r got=%r want=%r" % (args, got, want)
