"""Visible checks for bcb_526 -- these ship with the task and can be run.

Rendered from bigcode/bigcodebench-hard v0.1.4 (BigCodeBench/526) by
ops/vacantrun/bcb_hard_bank_20260924/build_bank.py. The code below is the
dataset's unittest TestCases, restricted to the test methods that ship with
this task; each check_* runs one of those methods.
"""

from solution import *
import sys as _vacant_sys
import solution as _vacant_solution
_vacant_sys.modules.setdefault(__name__, _vacant_solution)

import unittest
import numpy as np
import tempfile
import json
class TestCases(unittest.TestCase):
    def setUp(self):
        self.temp_dir = tempfile.TemporaryDirectory()
        self.test_data_paths = []
        test_data = [
            [{"a": 2, "b": 3, "c": 4}],  # Test data for test_case_1
            [{"a": 1}],  # Test data for test_case_2
            [{"a": 1.5}, {"b": None}],  # Test data for test_case_3
            [],  # Test data for test_case_4
            [{"a": 1.5, "c": 4}, {"b": None}],  # Test data for test_case_5
        ]
        for idx, data in enumerate(test_data, start=1):
            path = self.temp_dir.name + f"/test_data_{idx}.json"
            with open(path, "w") as f:
                json.dump(data, f)
            self.test_data_paths.append(path)
    def test_case_1(self):
        # Basic test
        df = task_func(self.test_data_paths[0])
        self.assertListEqual(df.index.tolist(), ["a", "b", "c"])
        self.assertAlmostEqual(df.loc["a", "mean"], 2.0)
        self.assertAlmostEqual(df.loc["a", "median"], 2.0)
    def test_case_2(self):
        # Test with a single key
        df = task_func(self.test_data_paths[1])
        self.assertListEqual(df.index.tolist(), ["a"])
        self.assertAlmostEqual(df.loc["a", "mean"], 1.0)
        self.assertAlmostEqual(df.loc["a", "median"], 1.0)
    def test_case_3(self):
        # Test with missing values to ensure handling of NaN
        df = task_func(self.test_data_paths[2])
        self.assertListEqual(df.index.tolist(), ["a", "b"])
        self.assertAlmostEqual(df.loc["a", "mean"], 1.5)
        self.assertAlmostEqual(df.loc["a", "median"], 1.5)
        self.assertTrue(np.isnan(df.loc["b", "mean"]))
        self.assertTrue(np.isnan(df.loc["b", "median"]))
    def tearDown(self):
        self.temp_dir.cleanup()


# ── Vacant wrapper (generated by build_bank.py) ──────────────────────────
# Each check_* below runs exactly one TestCases method (with its setUp /
# tearDown) and raises AssertionError with a short message if it fails.
import unittest as _vacant_unittest

for _vacant_name in [_n for _n in list(globals()) if _n.startswith("check_")]:
    del globals()[_vacant_name]


def _vacant_short(tb_text, limit=700):
    lines = (tb_text or "").rstrip().splitlines()
    idx = [i for i, ln in enumerate(lines) if ln.startswith("  File ")]
    tail = lines[idx[-1] + 2:] if idx and idx[-1] + 2 < len(lines) else lines[-3:]
    tail = [ln for ln in tail if ln.strip() and set(ln.strip()) - set("^~")]
    msg = "\n".join(tail).strip()
    if len(msg) > limit:
        msg = msg[: limit // 2] + " ...[cut]... " + msg[-(limit // 2):]
    return msg


def _vacant_run(method_name):
    suite = _vacant_unittest.TestSuite([TestCases(method_name)])
    result = _vacant_unittest.TestResult()
    suite.run(result)
    if result.wasSuccessful() and result.testsRun == 1:
        return
    if result.failures:
        kind, tb = "FAIL", result.failures[0][1]
    elif result.errors:
        kind, tb = "ERROR", result.errors[0][1]
    elif result.unexpectedSuccesses:
        kind, tb = "UNEXPECTED SUCCESS", ""
    else:
        kind, tb = "NOT RUN", ""
    raise AssertionError("%s %s: %s" % (kind, method_name, _vacant_short(tb)))


def check_test_case_1():
    _vacant_run('test_case_1')

def check_test_case_2():
    _vacant_run('test_case_2')

def check_test_case_3():
    _vacant_run('test_case_3')
