"""Visible checks for bcb_123 -- these ship with the task and can be run.

Rendered from bigcode/bigcodebench-hard v0.1.4 (BigCodeBench/123) by
ops/vacantrun/bcb_hard_bank_20260924/build_bank.py. The code below is the
dataset's unittest TestCases, restricted to the test methods that ship with
this task; each check_* runs one of those methods.
"""

from solution import *
import sys as _vacant_sys
import solution as _vacant_solution
_vacant_sys.modules.setdefault(__name__, _vacant_solution)

import unittest
import pandas as pd
import os
def create_dummy_csv():
    test_dir = './data_files/'
    os.makedirs(test_dir, exist_ok=True)
    for i in range(3):
        df = pd.DataFrame({'A': range(3), 'B': range(3, 6)})
        df.to_csv(f'{test_dir}file_{i}.csv', index=False)
def tearDown_dummy():
    # Clean up the test directory and its contents
    test_dir = './data_files/'
    for file in os.listdir(test_dir):
        os.remove(os.path.join(test_dir, file))
    os.rmdir(test_dir)
class TestCases(unittest.TestCase):
    def setUp(self):
        # Setup for creating sample CSV files in a test directory
        self.test_dir = './test_data_files/'
        os.makedirs(self.test_dir, exist_ok=True)
        for i in range(3):
            df = pd.DataFrame({'A': range(3), 'B': range(3, 6)})
            df.to_csv(f'{self.test_dir}file_{i}.csv', index=False)
    def tearDown(self):
        # Clean up the test directory and its contents
        for file in os.listdir(self.test_dir):
            os.remove(os.path.join(self.test_dir, file))
        os.rmdir(self.test_dir)
    def test_file_not_found(self):
        with self.assertRaises(FileNotFoundError):
            task_func([1, 2, 3], file_dir='./non_existent_dir/')
    def test_correct_file_count(self):
        my_list = [1]
        df = task_func(my_list, file_dir=self.test_dir)
        # Expecting to concatenate 1 + 12 = 13 files, but only 3 are available
        self.assertEqual(len(df), 9)  # 3 rows per file


# ── Vacant wrapper (generated by build_bank.py) ──────────────────────────
# Each check_* below runs exactly one TestCases method (with its setUp /
# tearDown) and raises AssertionError with a short message if it fails.
import unittest as _vacant_unittest

for _vacant_name in [_n for _n in list(globals()) if _n.startswith("check_")]:
    del globals()[_vacant_name]


def _vacant_short(tb_text, limit=700):
    lines = (tb_text or "").rstrip().splitlines()
    idx = [i for i, ln in enumerate(lines) if ln.startswith("  File ")]
    tail = lines[idx[-1] + 2:] if idx and idx[-1] + 2 < len(lines) else lines[-3:]
    tail = [ln for ln in tail if ln.strip() and set(ln.strip()) - set("^~")]
    msg = "\n".join(tail).strip()
    if len(msg) > limit:
        msg = msg[: limit // 2] + " ...[cut]... " + msg[-(limit // 2):]
    return msg


def _vacant_run(method_name):
    suite = _vacant_unittest.TestSuite([TestCases(method_name)])
    result = _vacant_unittest.TestResult()
    suite.run(result)
    if result.wasSuccessful() and result.testsRun == 1:
        return
    if result.failures:
        kind, tb = "FAIL", result.failures[0][1]
    elif result.errors:
        kind, tb = "ERROR", result.errors[0][1]
    elif result.unexpectedSuccesses:
        kind, tb = "UNEXPECTED SUCCESS", ""
    else:
        kind, tb = "NOT RUN", ""
    raise AssertionError("%s %s: %s" % (kind, method_name, _vacant_short(tb)))


def check_test_correct_file_count():
    _vacant_run('test_correct_file_count')

def check_test_file_not_found():
    _vacant_run('test_file_not_found')
