"""Visible checks for bcb_1020 -- these ship with the task and can be run.

Rendered from bigcode/bigcodebench-hard v0.1.4 (BigCodeBench/1020) by
ops/vacantrun/bcb_hard_bank_20260924/build_bank.py. The code below is the
dataset's unittest TestCases, restricted to the test methods that ship with
this task; each check_* runs one of those methods.
"""

from solution import *
import sys as _vacant_sys
import solution as _vacant_solution
_vacant_sys.modules.setdefault(__name__, _vacant_solution)

import unittest
import json
import requests
from unittest import mock
class TestCases(unittest.TestCase):
    """Test cases for the function."""
    @mock.patch("requests.get")
    @mock.patch("chardet.detect")
    def test_get_data_with_default_parameters(self, mock_detect, mock_get):
        """Test that the function works with default parameters and automatically detects encoding."""
        response_content = '{"key": "value"}'.encode("cp1251")
        mock_get.return_value.content = response_content
        mock_detect.return_value = {"encoding": "cp1251"}
        result = task_func()
        expected_output = {"key": "value"}
        self.assertEqual(result, expected_output)
    @mock.patch("requests.get")
    def test_get_data_with_custom_url_and_encodings(self, mock_get):
        """Test that the function can handle custom URL and specified encodings."""
        response_content = '{"message": "success"}'.encode("latin1")
        mock_get.return_value.content = response_content
        result = task_func(
            url="http://custom.url/api", from_encoding="latin1", to_encoding="utf8"
        )
        expected_output = {"message": "success"}
        self.assertEqual(result, expected_output)


# ── Vacant wrapper (generated by build_bank.py) ──────────────────────────
# Each check_* below runs exactly one TestCases method (with its setUp /
# tearDown) and raises AssertionError with a short message if it fails.
import unittest as _vacant_unittest

for _vacant_name in [_n for _n in list(globals()) if _n.startswith("check_")]:
    del globals()[_vacant_name]


def _vacant_short(tb_text, limit=700):
    lines = (tb_text or "").rstrip().splitlines()
    idx = [i for i, ln in enumerate(lines) if ln.startswith("  File ")]
    tail = lines[idx[-1] + 2:] if idx and idx[-1] + 2 < len(lines) else lines[-3:]
    tail = [ln for ln in tail if ln.strip() and set(ln.strip()) - set("^~")]
    msg = "\n".join(tail).strip()
    if len(msg) > limit:
        msg = msg[: limit // 2] + " ...[cut]... " + msg[-(limit // 2):]
    return msg


def _vacant_run(method_name):
    suite = _vacant_unittest.TestSuite([TestCases(method_name)])
    result = _vacant_unittest.TestResult()
    suite.run(result)
    if result.wasSuccessful() and result.testsRun == 1:
        return
    if result.failures:
        kind, tb = "FAIL", result.failures[0][1]
    elif result.errors:
        kind, tb = "ERROR", result.errors[0][1]
    elif result.unexpectedSuccesses:
        kind, tb = "UNEXPECTED SUCCESS", ""
    else:
        kind, tb = "NOT RUN", ""
    raise AssertionError("%s %s: %s" % (kind, method_name, _vacant_short(tb)))


def check_test_get_data_with_custom_url_and_encodings():
    _vacant_run('test_get_data_with_custom_url_and_encodings')

def check_test_get_data_with_default_parameters():
    _vacant_run('test_get_data_with_default_parameters')
