"""Scoring checks for bcb_637 -- NOT part of any workspace.

This file lives in a separate tree and is never copied into an agent's
workspace. It runs every test method of the dataset's TestCases
(bigcode/bigcodebench-hard v0.1.4, BigCodeBench/637): the visible ones plus the rest.
"""

from solution import *
import sys as _vacant_sys
import solution as _vacant_solution
_vacant_sys.modules.setdefault(__name__, _vacant_solution)

import unittest
class TestCases(unittest.TestCase):
    
    def test_case_1(self):
        # Test with 10 students
        df, ax = task_func(10)
        
        # Check DataFrame dimensions
        self.assertEqual(df.shape, (10, 5))
        
        # Check plot title
        self.assertEqual(ax.get_title(), 'Course-wise Average and Passing Grade Counts')
    
    def test_case_2(self):
        # Test with 50 students
        df, ax = task_func(50)
        
        # Check DataFrame dimensions
        self.assertEqual(df.shape, (50, 5))
        
        # Check plot title
        self.assertEqual(ax.get_title(), 'Course-wise Average and Passing Grade Counts')
        
    def test_case_3(self):
        # Test with 100 students
        df, ax = task_func(100)
        
        # Check DataFrame dimensions
        self.assertEqual(df.shape, (100, 5))
        
        # Check plot title
        self.assertEqual(ax.get_title(), 'Course-wise Average and Passing Grade Counts')
    
    def test_case_4(self):
        # Test with 1 student
        df, ax = task_func(1)
        
        # Check DataFrame dimensions
        self.assertEqual(df.shape, (1, 5))
        
        # Check plot title
        self.assertEqual(ax.get_title(), 'Course-wise Average and Passing Grade Counts')
        
    def test_case_5(self):
        # Test with 5 students
        df, ax = task_func(5)
        
        # Check DataFrame dimensions
        self.assertEqual(df.shape, (5, 5))
        
        # Check plot title
        self.assertEqual(ax.get_title(), 'Course-wise Average and Passing Grade Counts')


# ── Vacant wrapper (generated by build_bank.py) ──────────────────────────
# Each check_* below runs exactly one TestCases method (with its setUp /
# tearDown) and raises AssertionError with a short message if it fails.
import unittest as _vacant_unittest

for _vacant_name in [_n for _n in list(globals()) if _n.startswith("check_")]:
    del globals()[_vacant_name]


def _vacant_short(tb_text, limit=700):
    lines = (tb_text or "").rstrip().splitlines()
    idx = [i for i, ln in enumerate(lines) if ln.startswith("  File ")]
    tail = lines[idx[-1] + 2:] if idx and idx[-1] + 2 < len(lines) else lines[-3:]
    tail = [ln for ln in tail if ln.strip() and set(ln.strip()) - set("^~")]
    msg = "\n".join(tail).strip()
    if len(msg) > limit:
        msg = msg[: limit // 2] + " ...[cut]... " + msg[-(limit // 2):]
    return msg


def _vacant_run(method_name):
    suite = _vacant_unittest.TestSuite([TestCases(method_name)])
    result = _vacant_unittest.TestResult()
    suite.run(result)
    if result.wasSuccessful() and result.testsRun == 1:
        return
    if result.failures:
        kind, tb = "FAIL", result.failures[0][1]
    elif result.errors:
        kind, tb = "ERROR", result.errors[0][1]
    elif result.unexpectedSuccesses:
        kind, tb = "UNEXPECTED SUCCESS", ""
    else:
        kind, tb = "NOT RUN", ""
    raise AssertionError("%s %s: %s" % (kind, method_name, _vacant_short(tb)))


def check_test_case_1():
    _vacant_run('test_case_1')

def check_test_case_2():
    _vacant_run('test_case_2')

def check_test_case_3():
    _vacant_run('test_case_3')

def check_test_case_4():
    _vacant_run('test_case_4')

def check_test_case_5():
    _vacant_run('test_case_5')
