"""Visible checks for bcb_147 -- these ship with the task and can be run.

Rendered from bigcode/bigcodebench-hard v0.1.4 (BigCodeBench/147) by
ops/vacantrun/bcb_hard_bank_20260924/build_bank.py. The code below is the
dataset's unittest TestCases, restricted to the test methods that ship with
this task; each check_* runs one of those methods.
"""

from solution import *
import sys as _vacant_sys
import solution as _vacant_solution
_vacant_sys.modules.setdefault(__name__, _vacant_solution)

import unittest
from unittest.mock import patch, MagicMock
import socket
from ipaddress import IPv4Network
class TestCases(unittest.TestCase):
    @patch('socket.socket')
    def test_closed_port(self, mock_socket):
        """Test that a closed port is correctly detected."""
        mock_socket.return_value.connect.side_effect = socket.error
        result = task_func('192.168.0.0/30', 80)
        self.assertTrue(not any(result.values()), "All ports should be closed for the test range.")
    def test_all_ips_checked(self):
        """Test that all IPs in the range are checked."""
        ip_range = '192.168.0.0/30'
        port = 80
        result = task_func(ip_range, port)
        expected_ips = {str(ip) for ip in IPv4Network(ip_range)}
        self.assertEqual(set(result.keys()), expected_ips, "All IPs in the range should be checked.")


# ── Vacant wrapper (generated by build_bank.py) ──────────────────────────
# Each check_* below runs exactly one TestCases method (with its setUp /
# tearDown) and raises AssertionError with a short message if it fails.
import unittest as _vacant_unittest

for _vacant_name in [_n for _n in list(globals()) if _n.startswith("check_")]:
    del globals()[_vacant_name]


def _vacant_short(tb_text, limit=700):
    lines = (tb_text or "").rstrip().splitlines()
    idx = [i for i, ln in enumerate(lines) if ln.startswith("  File ")]
    tail = lines[idx[-1] + 2:] if idx and idx[-1] + 2 < len(lines) else lines[-3:]
    tail = [ln for ln in tail if ln.strip() and set(ln.strip()) - set("^~")]
    msg = "\n".join(tail).strip()
    if len(msg) > limit:
        msg = msg[: limit // 2] + " ...[cut]... " + msg[-(limit // 2):]
    return msg


def _vacant_run(method_name):
    suite = _vacant_unittest.TestSuite([TestCases(method_name)])
    result = _vacant_unittest.TestResult()
    suite.run(result)
    if result.wasSuccessful() and result.testsRun == 1:
        return
    if result.failures:
        kind, tb = "FAIL", result.failures[0][1]
    elif result.errors:
        kind, tb = "ERROR", result.errors[0][1]
    elif result.unexpectedSuccesses:
        kind, tb = "UNEXPECTED SUCCESS", ""
    else:
        kind, tb = "NOT RUN", ""
    raise AssertionError("%s %s: %s" % (kind, method_name, _vacant_short(tb)))


def check_test_all_ips_checked():
    _vacant_run('test_all_ips_checked')

def check_test_closed_port():
    _vacant_run('test_closed_port')
