"""Hidden acceptance for s1_40_bullets — rendered data, do not hand-edit.

Generated by ops/gain/r535/build_bank.py from ops/gain/r535/tasks_s1.
Every check is zero-argument and passes by returning normally
(vacant_network/vrun/acceptance.py runs them in definition order).
"""


def check_01_bullets():
    from solution import bullets
    args = (['a', 'b'],)
    got = bullets(*args)
    want = '- a\n- b'
    assert got == want, "bullets args=%r got=%r want=%r" % (args, got, want)


def check_02_bullets():
    from solution import bullets
    args = ([],)
    got = bullets(*args)
    want = ''
    assert got == want, "bullets args=%r got=%r want=%r" % (args, got, want)


def check_03_bullets():
    from solution import bullets
    args = (['x'],)
    got = bullets(*args)
    want = '- x'
    assert got == want, "bullets args=%r got=%r want=%r" % (args, got, want)


def check_04_bullets():
    from solution import bullets
    args = (['a', 'b', 'c'],)
    got = bullets(*args)
    want = '- a\n- b\n- c'
    assert got == want, "bullets args=%r got=%r want=%r" % (args, got, want)


def check_05_bullets():
    from solution import bullets
    args = ([''],)
    got = bullets(*args)
    want = '- '
    assert got == want, "bullets args=%r got=%r want=%r" % (args, got, want)


def check_06_bullets():
    from solution import bullets
    args = (['one two'],)
    got = bullets(*args)
    want = '- one two'
    assert got == want, "bullets args=%r got=%r want=%r" % (args, got, want)


def check_07_bullets():
    from solution import bullets
    args = (['1', '2'],)
    got = bullets(*args)
    want = '- 1\n- 2'
    assert got == want, "bullets args=%r got=%r want=%r" % (args, got, want)
