"""Scoring checks for bcb_845 -- NOT part of any workspace.

This file lives in a separate tree and is never copied into an agent's
workspace. It runs every test method of the dataset's TestCases
(bigcode/bigcodebench-hard v0.1.4, BigCodeBench/845): the visible ones plus the rest.
"""

from solution import *
import sys as _vacant_sys
import solution as _vacant_solution
_vacant_sys.modules.setdefault(__name__, _vacant_solution)

import unittest
from unittest.mock import patch
class TestCases(unittest.TestCase):
    def test_case_identical_strings(self):
        self.assertEqual(task_func("test", "test"), (1.0, 1.0))
    def test_case_different_strings(self):
        self.assertEqual(task_func("test", "different"), (0.0, 0.3076923076923077))  # Adjusted expected value
    def test_case_empty_strings(self):
        self.assertEqual(task_func("", ""), (0.0, 1.0))  # Adjusted expected value; Empty strings are considered identical
    def test_case_similar_strings(self):
        self.assertEqual(task_func("hello world", "hola mundo"), (0.0, 0.38095238095238093))  # Adjusted expected value
    def test_case_numerical_strings(self):
        cosine_similarity, levenshtein_ratio = task_func("123", "321")
        self.assertEqual(cosine_similarity, 0.0)  # This comparison is fine with assertEqual since it's an exact match.
        self.assertAlmostEqual(levenshtein_ratio, 0.3333333, places=7)


# ── Vacant wrapper (generated by build_bank.py) ──────────────────────────
# Each check_* below runs exactly one TestCases method (with its setUp /
# tearDown) and raises AssertionError with a short message if it fails.
import unittest as _vacant_unittest

for _vacant_name in [_n for _n in list(globals()) if _n.startswith("check_")]:
    del globals()[_vacant_name]


def _vacant_short(tb_text, limit=700):
    lines = (tb_text or "").rstrip().splitlines()
    idx = [i for i, ln in enumerate(lines) if ln.startswith("  File ")]
    tail = lines[idx[-1] + 2:] if idx and idx[-1] + 2 < len(lines) else lines[-3:]
    tail = [ln for ln in tail if ln.strip() and set(ln.strip()) - set("^~")]
    msg = "\n".join(tail).strip()
    if len(msg) > limit:
        msg = msg[: limit // 2] + " ...[cut]... " + msg[-(limit // 2):]
    return msg


def _vacant_run(method_name):
    suite = _vacant_unittest.TestSuite([TestCases(method_name)])
    result = _vacant_unittest.TestResult()
    suite.run(result)
    if result.wasSuccessful() and result.testsRun == 1:
        return
    if result.failures:
        kind, tb = "FAIL", result.failures[0][1]
    elif result.errors:
        kind, tb = "ERROR", result.errors[0][1]
    elif result.unexpectedSuccesses:
        kind, tb = "UNEXPECTED SUCCESS", ""
    else:
        kind, tb = "NOT RUN", ""
    raise AssertionError("%s %s: %s" % (kind, method_name, _vacant_short(tb)))


def check_test_case_different_strings():
    _vacant_run('test_case_different_strings')

def check_test_case_empty_strings():
    _vacant_run('test_case_empty_strings')

def check_test_case_identical_strings():
    _vacant_run('test_case_identical_strings')

def check_test_case_numerical_strings():
    _vacant_run('test_case_numerical_strings')

def check_test_case_similar_strings():
    _vacant_run('test_case_similar_strings')
