"""Visible checks for bcb_879 -- these ship with the task and can be run.

Rendered from bigcode/bigcodebench-hard v0.1.4 (BigCodeBench/879) by
ops/vacantrun/bcb_hard_bank_20260924/build_bank.py. The code below is the
dataset's unittest TestCases, restricted to the test methods that ship with
this task; each check_* runs one of those methods.
"""

from solution import *
import sys as _vacant_sys
import solution as _vacant_solution
_vacant_sys.modules.setdefault(__name__, _vacant_solution)

import unittest
import pandas as pd
import numpy as np
class TestCases(unittest.TestCase):
    def test_case_1(self):
        np.random.seed(12)
        data = pd.DataFrame({
            'Var1': np.random.choice(['A', 'B'], size=100),
            'Var2': np.random.choice(['X', 'Y'], size=100)
        })
        p_value = task_func(data, 'Var1', 'Var2')
        self.assertAlmostEqual(p_value, 0.5, delta=0.1)
    def test_case_2(self):
        data = pd.DataFrame({
            'Var1': ['A'] * 50 + ['B'] * 50,
            'Var2': ['X'] * 25 + ['Y'] * 25 + ['X'] * 25 + ['Y'] * 25
        })
        p_value = task_func(data, 'Var1', 'Var2')
        self.assertAlmostEqual(p_value, 1, delta=0.1)
    def test_case_5(self):
        data = pd.DataFrame({
            'Var1': np.random.choice(['A', 'B', 'C', 'D'], size=200),
            'Var2': np.random.choice(['W', 'X', 'Y', 'Z'], size=200)
        })
        p_value = task_func(data, 'Var1', 'Var2')
        self.assertTrue(0 <= p_value <= 1)


# ── Vacant wrapper (generated by build_bank.py) ──────────────────────────
# Each check_* below runs exactly one TestCases method (with its setUp /
# tearDown) and raises AssertionError with a short message if it fails.
import unittest as _vacant_unittest

for _vacant_name in [_n for _n in list(globals()) if _n.startswith("check_")]:
    del globals()[_vacant_name]


def _vacant_short(tb_text, limit=700):
    lines = (tb_text or "").rstrip().splitlines()
    idx = [i for i, ln in enumerate(lines) if ln.startswith("  File ")]
    tail = lines[idx[-1] + 2:] if idx and idx[-1] + 2 < len(lines) else lines[-3:]
    tail = [ln for ln in tail if ln.strip() and set(ln.strip()) - set("^~")]
    msg = "\n".join(tail).strip()
    if len(msg) > limit:
        msg = msg[: limit // 2] + " ...[cut]... " + msg[-(limit // 2):]
    return msg


def _vacant_run(method_name):
    suite = _vacant_unittest.TestSuite([TestCases(method_name)])
    result = _vacant_unittest.TestResult()
    suite.run(result)
    if result.wasSuccessful() and result.testsRun == 1:
        return
    if result.failures:
        kind, tb = "FAIL", result.failures[0][1]
    elif result.errors:
        kind, tb = "ERROR", result.errors[0][1]
    elif result.unexpectedSuccesses:
        kind, tb = "UNEXPECTED SUCCESS", ""
    else:
        kind, tb = "NOT RUN", ""
    raise AssertionError("%s %s: %s" % (kind, method_name, _vacant_short(tb)))


def check_test_case_1():
    _vacant_run('test_case_1')

def check_test_case_2():
    _vacant_run('test_case_2')

def check_test_case_5():
    _vacant_run('test_case_5')
