"""Hidden acceptance for s1_41_squeeze — rendered data, do not hand-edit.

Generated by ops/gain/r535/build_bank.py from ops/gain/r535/tasks_s1.
Every check is zero-argument and passes by returning normally
(vacant/vrun/acceptance.py runs them in definition order).
"""


def check_01_squeeze():
    from solution import squeeze
    args = ('  a   b  ',)
    got = squeeze(*args)
    want = 'a b'
    assert got == want, "squeeze args=%r got=%r want=%r" % (args, got, want)


def check_02_squeeze():
    from solution import squeeze
    args = ('',)
    got = squeeze(*args)
    want = ''
    assert got == want, "squeeze args=%r got=%r want=%r" % (args, got, want)


def check_03_squeeze():
    from solution import squeeze
    args = ('a',)
    got = squeeze(*args)
    want = 'a'
    assert got == want, "squeeze args=%r got=%r want=%r" % (args, got, want)


def check_04_squeeze():
    from solution import squeeze
    args = ('a\t\tb',)
    got = squeeze(*args)
    want = 'a b'
    assert got == want, "squeeze args=%r got=%r want=%r" % (args, got, want)


def check_05_squeeze():
    from solution import squeeze
    args = ('\n x \n',)
    got = squeeze(*args)
    want = 'x'
    assert got == want, "squeeze args=%r got=%r want=%r" % (args, got, want)


def check_06_squeeze():
    from solution import squeeze
    args = ('a  b  c',)
    got = squeeze(*args)
    want = 'a b c'
    assert got == want, "squeeze args=%r got=%r want=%r" % (args, got, want)


def check_07_squeeze():
    from solution import squeeze
    args = ('   ',)
    got = squeeze(*args)
    want = ''
    assert got == want, "squeeze args=%r got=%r want=%r" % (args, got, want)
