"""Visible acceptance for s1_31_money — rendered data, do not hand-edit.

Generated by ops/gain/r535/build_bank.py from ops/gain/r535/tasks_s1.
Every check is zero-argument and passes by returning normally
(vacant/vrun/acceptance.py runs them in definition order).
"""


def check_01_money():
    from solution import money
    args = (1234,)
    got = money(*args)
    want = '$12.34'
    assert got == want, "money args=%r got=%r want=%r" % (args, got, want)


def check_02_money():
    from solution import money
    args = (5,)
    got = money(*args)
    want = '$0.05'
    assert got == want, "money args=%r got=%r want=%r" % (args, got, want)
