"""Scoring checks for lcb_3634 -- NOT part of any workspace.

⚠ 計分用的 GT。住在 hidden/ 這棵**另外的樹**，永遠不複製進 agent 的工作區；
  任何把它的內容（含失敗訊息）回饋給模型的路徑都作廢那一批資料。

case 組成 ＝ 題庫的 `visible_tests` ＋ `hidden_tests`（超集），與
vacant_network/codebench.py::LiveCodeBenchLoader 的 `hidden_check` 同一組（ops/gain/data/lcb_bank_v1.jsonl）。
"""

import solution

def _aeq(a, b):
    """與 vacant_network/codebench.py::_lcb_check_code 的 __aeq 同一套判等（逐行對應）。"""
    try:
        if a == b:
            return True
    except (TypeError, ValueError):
        pass
    if isinstance(a, bool) != isinstance(b, bool):
        return False
    if isinstance(a, (int, float)) and isinstance(b, (int, float)):
        return abs(a - b) <= 1e-6
    if isinstance(a, (list, tuple)) and isinstance(b, (list, tuple)):
        return len(a) == len(b) and all(_aeq(x, y) for x, y in zip(a, b))
    return a == b


def check_case_01():
    args = ['aczzx']
    want = 5
    got = solution.calculateScore(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_02():
    args = ['abcdef']
    want = 0
    got = solution.calculateScore(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_03():
    args = ['nmc']
    want = 1
    got = solution.calculateScore(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_04():
    args = ['zjtogntj']
    want = 2
    got = solution.calculateScore(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_05():
    args = ['d']
    want = 0
    got = solution.calculateScore(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_06():
    args = ['vgslukgifnpaaoyhft']
    want = 43
    got = solution.calculateScore(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_07():
    args = ['urgve']
    want = 1
    got = solution.calculateScore(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_08():
    args = ['olgaodvwo']
    want = 3
    got = solution.calculateScore(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_09():
    args = ['igzrz']
    want = 3
    got = solution.calculateScore(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_10():
    args = ['dwxwwdddlbooyw']
    want = 16
    got = solution.calculateScore(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_11():
    args = ['xhscxjsh']
    want = 5
    got = solution.calculateScore(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_12():
    args = ['byhkxgctxcx']
    want = 6
    got = solution.calculateScore(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_13():
    args = ['y']
    want = 0
    got = solution.calculateScore(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_14():
    args = ['gttptj']
    want = 1
    got = solution.calculateScore(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_15():
    args = ['zchjqsycrr']
    want = 4
    got = solution.calculateScore(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_16():
    args = ['byrbayykmbqolpzbxpan']
    want = 34
    got = solution.calculateScore(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_17():
    args = ['zadavyayobbgqsexaabk']
    want = 18
    got = solution.calculateScore(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_18():
    args = ['pavrlinamekwiwoqmpuljpkjsmkzvkorzlaqdrqtmekfaqlpgakoidkpmyulpdlyooltzntobprkboywyzzyzzvxlaifvhsohvhwoobqkcngnewigiadizuxvoeigsnqbuokgmregfdeznrihbubaaqvaklprqopjrmmfbewqysuljcsynjphjvgliqgqckdepxdmdyihonhbzwmxoifxckwlyagwkfeskkjvjybktoplfqtlcbmtzqfpyydffjbdhnpgoulvcxcouccwhxkgujavznjkrpsabehqhlshusrtzmsbvawlowymoibbvcjknbhjrfzbobyerxqhcduouoxlwjobffczbkikkdyphrvlnclugjgcirepdzwovydrocowfemyopdbefbjofhscdmextfjabnhhfetywaumpdagweopgwtavzwqtssafbyvnuhpwagpbwkrvlurfjxguosjrrcuoynqhftynjnranzdiocjjipjxvfxnazurodetoipzidbwqbwzdymyuyadruddezaflzkhklzbkkfesmgxyeinhxhilkfqrvsdsutrcxfkflqpazpzskuepctzcsffsrbdjvphuuqulkgdpopkwehyshwmumliuqbiyurahzmzftylubihlilqvmzlgvfptyyxbopcrnjwwlphausutrmjkrudvdsrbftktkawsynexbblruscloiyvorvqhdcrctmlyghnxsffasukulkockyewuwyjnxbdludhjvtajemoqwqezopbnlmvvrydayfablwdwinctkozwciautmyzjbabjsoabpnmpqppohigqpuxayqtozgqnxkillqpkmapdostynbwsswctghvfveyncslowcbwwrbauyltpjydmflgordkuuuvsizoyrhdfyyubuqyallroboklfepgowbhjtgaibaylnprcuzlvpaigvokhuvhdtixdvihmajxqvbwgfazzfvjecalaofmjtjalsfhlbbmptgxlrlwnduvyzofmefmxcuxqzjscljgpbhhlydxjzhucmvewzszwbdbwynkuwwubrttxsykcuuawxbjpdctaomcwfnmmisebnvxaefgwdypguuqjvsnnqwbtxvkgbzuwevonyivwojdtpmtubomnjthodnvepsmuhkjndpltfczfobyzutfztmxupycybtnodzveqqhimwvzurezenkjejmmjqeohstflxyqcaupttksafdtjkyeuzumyiunxdkqbkkkkxjibtdbsxgsfpnfjbwmxsuewirnvczlyoxhwabkelzmdgleudgqhcawwdyioiybvyqarmnsuxsyyxpgmmfyxtxuzeyeotmzxjrebtlfdvpxlbzykkdwevkwiorhfbeqdinroxjjekzigufcziyoujesysapourqkwqzhyrkrpnjjbtuflhlogijradgvvqvxgeeufqywbibeijbkhmzgimogdtzpqyjsbmnctslzotinqceqeljlkhsdpmhfzxtlbythcbhprrjmpkulvqxforeldajjlwuvhkqdslwendnfyorbtslhfsgortkuczrhjfdiumvbpyyjqwueiujefaydrdcjmdpwebtqvhnzqzklldxwwewsivsvkgjquaujwmolwyftlcscztocnpcoyhnhmwzvnisokjdhrxtocdjmyqadcfzrinlvqosqyirwexluezizvbbtheigpuiwviksxxtxphveckhgtnvybrzjbrzxbqemovqkvguzsewwmxcbuiicdsxdbpcruxkpmwocvsmryxdnsckgvoxkwdtzrhctgghvyraudiwxeiasytncuiqvqlphevtdxoslgzngclzdkiippsdaxzytnpgqnzfgyeclddavkfvuyflzxzmykrkfnucqmuxflengmlsiobncabzkolxhxnqxgqcfqxspexlehapqwlfxdtaxfrfxslwnuhgsytbdoneomypvndqimbalolumstvpyzcphpdtfhqlakfjuzcnocropehpqqvmhnkdaazqlhabegseyjgfbwqtyvotdkxasiwqnpkbqfawvfaallggrfgdouggwuyhsvfmmibsxucftkhrxwcoxzlwenvpgxxqadwfixpozouolfelvbswdjcxaipmmpikkvchzbxusmcjpaeizbytjbluqeucqqpcoloohgxenqygwjakbhqvbfuhobwjdrlmoxtddsdisphuyskiyahbyvcpykvdmtwipmykiowpelffefjchpxlqoezkadhinpfzukzlfpocxqnyfffjmyeesbvqolnilahfvuzsqpaqkcankwxjsxtelcpjeomoruanqhuiqklpzupqdulzxbmnpueibplihusozyvijjapmvopfgsqhezkuztzhaaqtwzwgmvhrbtfwztvzslauvlctlqamckxysootxhcgghccscvvzlpkhcvrwupxickeqbvmdyrxqcnfxgimffyvctlsnpiwnlqapklcnrdtaxqvhpipuhzfhvgpsqeuryyjevoklmuvmtpibybxakvunzwqnettkrovbvmmkixejidhffcxrgkdjkxxpapvgjnqyhkdutdqnfmbgdjefrotiymjwdjmxppbepyjmibryaohneycwetvgaeedsrfuwswjgetsytjefsuclkhlmsnkpkrehcllagsdcxvjioibgoscsgrxaukntnqnkdrrwqchptlerctwtbyjmkbymboztipcekldirnrudxxudnytjighwqmjnypenozrpkuvyjlwpuagsuatuyogyckesiuzcsixchscpjolytnmqmdqqszhsuhscjbcctgppeviyjnkwqaoyybnvsexprsydrtggkpgluwbgrnhrtvmrmcicajrqoydlytzbfsetxicwtkycdzlzsjbngdkflfniwhxqnkbwxbdrgjndrkdqyouuoboeqierogbbyrglyimprrauclolktnjagwqenuuwjnplszhbtkjmcgfrqnebitxpoxaelritwgczphmzdzjtgtvqgjocdklkilgtsjimrdhmnaazrtakusdwtkyvwnfnjcsqtlnyqdfxmjsyckjmryulkjmetgmgncclroaicmekgdnjggrqvxslauqgpcvijpdmfdenbsupkttgyairutajbndtdolffxhlzcctuilwgqosrxykoavmeybjvgbutwikiexvgbsrhupmybsjbmezklgoebyzhehqucymwmeonuctshzlnempxuupzhoydqcohoduwveghihvdixzwfqwnzpofesnygnqrebwoqphcfgujdasvhgaqdvsbzfryfhyxkghiydxjwmejoucdmobfwnxfnqkwnpuehadvhpcjysadcuzyershcjbmdfqhncnptlhhiaujcqxagxdexuczwxlxclupijugdudinhfjbdnijmwbllbnyscgekezhyrfzafzntexdiwckaqocqajjiqmthrtahazokxlzwpvobfoluyqoxanjyobbpfzgsaepvvehcceefpqomuvvtlxwjhqbwxnsozysnblyhznglcrjmlwbvhchwyezhoanxlgwmsobnjybebyygpzawlqhscdwcyntbblqoiugykbotxohrfalycilvoxldkqfubtaibvvbfisaonfsgnlrpirlevvpwrnntvoujzceujmepafsvawnzrajfktlhslqrqkedycwivpyvwlzogqrmkfrqujadlfcmcpypsfdpogevtjloaxxlwrwwjtpvmnujrxxxlzfyhrarptboucwupcjsyxdqxpxaptvlexejiwrsjqsdiyajnwufywbzmwclxrlyopxcvgfxykadfucckhokisrxuocucnnxogfslvvdoygwdudmgjltklcnjqpjpsmudegytcspftchhburfduzjlwalwwtsljcrffpmdyjvpmdrgtqvhsotcujxpzskhvbvurkihhqatovtdmxrywlayjlbutpjgoennpmgnpaeurxnqbmxvveveqcoeoxutfngnlkjjtjhxwrwivcumkleatsawwwcsrzsjlrfngkdhxeptuxjqffoumjnsxqlwompoogkoibpwesbrjrlefwmkxqoygyvjlzofffedfkycopxacarxwtltggudavvvdxvqvhebvytuwmpjgltcfyjtpbexoerxkkbbzqbzquonbikfmuurondklznqexnuynmooziwipdtlndullzyiizekccabzzpdaqtakjehnzgkwtfkahstxmsirpkypwfslkcgpoaqlcrrnnalwqcuvknghskvjdgvjelvsecxxbkekrzciwriyjyxjjcftuxjgmwoypdcczyevbjfbjplobkapbxbosqzmsrizwaiytwbvjzifljydcsxyyjqxzyeproxnhjsxrchhgnljofspjrvpgmcgmfqixmcwjmcxlumrlnhezeahfytqpwcxidxfadqvufwnjqpitjlocjvpwobnhsktjuwwfefpzeqslwepqgznmhxqgdzlbkhuqpjbxzyapbyejzlxyfeeqxufsvttorwrhircehpxbsdnumckjbbigtjdaqlvssvbqrolsliccchurlqtgflyaqpslxrykvwcjfzausficmotelbhlvandcxnvptvjzqlulhvcymwsfreavkufmwwkfoajaaxkuesfeqkkltqkqopcetjbpmkbyxvaufjbnekcqdlokkarsyvmyuabynpqkcbyomkpdspnrgbicljrxstacubxvkojdeevbycfilnkduwpiflgumlghwdzzwzijyxkivaanjiipoyqxeqxxbsiilnacmbwbhflfexujlnlykragmjugnslitesppfvkpbvbicrpjwkvsuqjqnidnibjfbpxlwlnzezsmqcfptwglagnrbpjqajfiwicaluywuucvwatqkarscccufvdvilazrnjmptvdchzqogzxiycuglexqunwobuqyshdcjrplxmbuujbsizneyyvfqyzpnptbeurdsjoenpitarmzsfsinrmgeljuimrpjadmjgdzuwnesjteskojgicgpdhzesorvwzfxjmgivikbtpuuqeqzuzpmymcfcyzozgcvghmoztzrekggbfijviusoxcwicbkvpcmvvvfvlowmvkntqiibchsxaoeqnxpokwrywxyfxxlahtwubpmhqmuvgmfvrfgarqudigdxzshnltdgxwtzthldlcloysapmxcvbrlsuocsmqvrowvkmojzccvalugsbsquvscsrlvbctmsttkbztkefywyqndpnarvgpfzbnggvivyqzbimwrhlqardgqiqxijtgramisbvdnhdnqtajgrebzhcdwykedxtbancfqsguwxulejkrmnrtodvznvamripsybdfrtdfipgofuslfkviwomsxmnoawfirnhoafrlbxfymrplgejtkiaqqkcvwgfxafmuavcxqpqsyljlbwuqwrrweyikvqnubbomcyfycfdhyjiopmmnmqywnqeubucdcwqidkhkfsekxfbdmrpixsfxyqdcjbksgjtbhctbhqjbojqaayzsdydhdarfzbpgxnfhylebbvhmryhrdovaxruvcskhxcnlmhciywkvyimnsddvhtkxgcgaexwhccgloyinwpiihwyfbreodrfgjhmnestftwqkrarhdrckcttnakmrxuafalfvcmwvvaircmedynidedesjfewpejavpxhofghisyvbjokfluncbltnezpmbmwuqvpnfdzergooupvookkygbmkzxxclxaujsgwkzwjgmvxzzgpysaaabxipikavnqrczxpbjppolawilmjnkvbwfyneiginrtgzjnicpxuzqsdckyimovizklzjxzjsqffbcaypktebayjytjynjvhafpizmhvojgbslweszjjnvcauqfbqqsqgmdcddsttohyifthmkzoijqhgsypwuffvulntimiespgveesonowvhuedhcttmonyztronhocltszcvatyghslgogvdqxlayoqygkydfftxlzjtljxwcvddndupmzhtgnsrodqmlwlshkdbuulmtbjtxfbwxqjpvzpgkhbkvlkrnblqjjrkuicegnhwdqkhlizxmyoidqbmwaxegqtwwnjxiodufdipklwgqmawzpbdxmfnqgxnwwdqvkmxkfbvcgnqnexscqtwywgvslqmstibntmkwnnyvwbgcktgrnahqosddivtnbbabrccukvurejsaypdhfqmbwzdxzoofvsxdumxwxmbjmaxodlpkddsjknbtotvohbwukduzxsoyullnltwtmxohtelrozqfdybibbvyiarongmstsvnahzthogffzafocyztryficuwuakskhbtvzrelywxsxkuyktcqmlxpwwmeshbqktlsnoaigxtxdgijihmokmipkugtarxnfbcidbkblzqsgwinpdoqyzlnmwvayvdxnqoxedosjcwlfhndbfocoqylxfdflaegtevnndlrtpaoduasiqydebeqrkrklivb']
    want = 434880
    got = solution.calculateScore(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_19():
    args = ['azapfwonwwcdagew']
    want = 3
    got = solution.calculateScore(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_20():
    args = ['zfufqbffulxhiofzle']
    want = 6
    got = solution.calculateScore(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_21():
    args = ['k']
    want = 0
    got = solution.calculateScore(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_22():
    args = ['eockppxdqclkhjgvnw']
    want = 50
    got = solution.calculateScore(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_23():
    args = ['dde']
    want = 0
    got = solution.calculateScore(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_24():
    args = ['lybootuglqklxliljzaocybylmygyyoulglfjbvfjoomhtflbguwbggebzkofplbdunlnqguyoyyzfoghcmllldynstjlbtynqqrwlfarrvbzotkvgyhokkfcebdrfjtxmalaibxlnlohtqarlpfsmraulucsonhqroajhxcrnocgoghkmxrmbafufnymiqlyasvexowaqmgttmcuglwnyhozluanoyqlxdrazyutoxsgdgmsxxiiyzhzcjscoxguidxudouiqdmzkrdnduwsjnucftrnelsjwmqmbfxypuybigngwiyhwttzehjdstmtonaqaihrdtynhxfvvwmcvwlqpjasowvtionltfzbqgaodrgmdinfilbshjfjwfuzofhlrepoogididmctgeffoyaxgdjfymjodwymdkxyjpbvjzmqkbjznjtcmtpcijrevmqwjodnbeqcooorhhqqnxweitxehpkvddrjoavcpaunnullnbcnysciulavaoyycbqfnfblzsozicqxycwxbhqlixnzbhczcajumnujeamgaixxerrxhjzjiuyllfqjxlvwvpnkpctywmtorcolmesonptuzarufpbrcbrpwxpvkpwqtyfjlljyezfjykllkjedqcypaajohztpokijvfkhqmlwgdndjzlxhtbqglpbyubfsgktfvzxylbifhdbddbfnggoglddktxgqkgbumhnhkkatsrkrkhuyzmyikefdiueopvavbrrxdxsehoupsodniqrmdymboyktjbaxlhudkussavaiunkchqmeywlnpdgzkdalqocwqpdjnbwrraezlargmayenqkfkmbrsbylqxgmjuszwfdairmhzvujyntsatzvaouaqpmqzydlgqgoqycxdzootpofymgjkeaquzydrsslozjjtpwlqaettqonjnayefmsjtlvkdubbrykpdpkhlfveubrzcpqkijbhbfhwxjejaphxhcmpfqnkuixouphkbdyzhqliktviblgkpgqnutoldcipvjpnarspytsextfduikzohjflhwnmcmmtunchcpquzlnagckztxkofqtydbctovgixsmerpvzuzohconwlmbvhltepjcluyqmtfzcrytmlowbxxstsvynxgkooyxitbaebhkttmbedwsottlozxekkyfyejdfczdvybklxlurvsnvkhhpfruxhqprqsxfhrypbmczlwsaaepjkmqfxltqxavtzhjvlyhfojjjrgjknmngfqevzpvdnvdubsygldlgzxerjjhjadaxxqaydhhupmecodnwxxzkixzrqqaisprtgnwombfofvlvqaswylvhcaubndbebpiwbefyvyhggszrovzzzvvqibjdkqylvimdeyuxooltxyvmpwfqkxijaqcxtyubqkxlytgsbzmpbqymahkqcwszhtwapwtocrvqpzhnlvzomflijuramhiiuyxstmtlgdeiudbkdbkfpxgxawrebrtpffrukmpvwriqwzglwvypgnmpadkdzgjwylscmmqauwmkvbfydcxxuehvpqvzhlsszgeojruorldluxbdcojakgmeqsatpykjklxjpdkrkplfyscjjqcelosllsgjixmyxdyshsjzwgmwqqmlkdondfxcdhisocgwgeditiourfiensfzxygyzabcpuyaoflzhfnubyfwdknqbspndbvlhoxycauhkpyhqslofvpbtwrnlzqerjbexhliamojcsdfalfqmswmbiphiwfkarpfncbktbzoqfofkmokyrnylrhumenqdrawyfmyuimdlkojlnaealkrqkcpsrlqvbkmjduepssygkjbundpcukmsyuwhddcstsyxoucqagptbploicsgrwghcxtqhilssoftkbnxnlgxlrkejsnhgutkykxqqhesfgoqtbvyocystafxnymusvkgncsfsrmofrthphfnocjqekajfvuwgqwkvwezeoitgdpucsdkppxlqtvptopxfjlawydmignfgwrazbwtavihrevuxbmpfkkvwcrjdatiqnjwrifdwyepestzewxrkhoxjhrmvddmrzpgcwobhxycwpnmfzwagdkstzwlpdfwsxwiuidwchuwlkyksclulalxammzjkucajpnxvrzvbrvoebrkkuudpispzaomulykvtuvglvitmuprxrjnghccqvzsvvctkoounvnzutbcucxnafzgjfwfqzlpeqczekuibmgvusgkyeixhectpxpuylcidqbtvvvxhlcartejzkgxlyohhaqbcjcwqzzmmhjbgedeyhfwxlqprhvgujzwdsbxzktjakauycnnceczwvtluehfiizkvjfadosqbxrodwetlkdgbzfflpoezgmfkvudwqzxjttklymuktqtfmslafpefugbaywvikfwtkdihqukvegymabbazuwewolpfopdvxzbdzcctltwsoikuwbrbdwbsjxsrggubhvmtattvoziktyvjglegrihhkxxpdclddbcuqzdtlwflsycidoidjkerppmaybfuhkagyyvwqdpffbxiegogfcubqsuybibgusualpnyxoxhzemoslipumqthokkwwgjkngqbyxjkiuemivyqreimghvacmgrqbhaqxznwpitzpkzkniixtrdxyrdkntogfmzvdlplfjgsrltgoeqxftfsuawhtcakbubxangvlajvvjronmdszzmajklodrguczicgjbbvilxcynrmmpxhdytozkfteqwiaemswlgsuzsnyhlmvytopxpvpdotzzhjtnrhxomyikofcnnsguibadfnwheiumpzorusrzujgslbyjpvgqevhgdantnlqealljssbnbecordowedrqmhxucwzfqzsaapllmwpursaqjhmiaqndffickojzfdmlxdvuqxidwchpqaxbhlryzppkmjntpfylnjmokkmpwogdhynlbjkunpbrwbrpfkkhnsgfjbxqgqooosbxltirptuyrnetqexextmmhdvnuockzgwbjcnzmklyupchobakjsgbhpdwymhfjlvdcxsszelzqbhfkfegbqdeookdyxflfscyq']
    want = 130991
    got = solution.calculateScore(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_25():
    args = ['gpmjk']
    want = 3
    got = solution.calculateScore(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_26():
    args = ['osjswnsmhmboxlsxhqbhcndnmcqfsxdwchfxwwuhfspsdonbkqhhqyrkbygiufllszhpsrwsuladhzhywgcmhmclmtftrqseclcqvcxlnuupkcjyfjbkrguftkqlhvpnqajtaplzkjkltegxyqbminjhphrxkbznbomldlcmpicxnbyimkhvsusujdyeabckyucbxvhuixzaihphfiohrhczwypfyhacewupgudpbqctzenzfmapohzalxxcmaynmjeadgpmhudojgbvxdhycahhkokjzzzwffkfzlbhnsefqhyjqthssabuflxqrvepgotozylwosyovfhoyfkucxcwodkjuutrmqgdevkoslqoxpsthtnassxrzzfvbuuxaeiugfyfijsiadogmxpghcoejjehjvphdmlukyazmqfzuehouggaqcnstrrcrfntclcwdfttoxszohcqpithvzxsmqwopmznmcumbqsylwkmjhpfsyvehspceeeqsthqgpvhiwbnnmalzacsibaxditjtqjlsazejatsgkcejevzkfflyblbwcociklddftjrylycknjypkoousrhjrdylbvxeqmugkygfrnwleyryrdkhsvukxvpyksxsdqwzvilvtjkxvjuchplbbkusyqclmaundjficezplllotpschibvsuxzmnihpnhoazcyzigncnhbpxcphrkvbcxwsfovsenoqtwdsrkdbasfqrhuvkhlwaoxjmxnyhwognmcjaeodmmdtkhacjxasurrtgecoabenbgkntnmrhywtgnentsaeuijtwxnzmwhayzzohbncjkhwtfvtooshgswdkeovpdmfshqyaomopqvxulwwwrjzktjtqgyzseszetmubysoladmcagokeuwlugatmiytlighisczefetbgxxwzvthnrmpimwixdynveuhcvkqwtsmtzmonyjhebfkoivinpcvkcnnhlmqufrtznidukutpnsqbqnllvmkjacpswautayzixbscalsdxoxiheeyudzqssitsxjgxyqapmnykkikniiesuejazghjomadhtbrfgmaclvqblstjnsewsfslhyozxodtktlueeksywmwbqfwkalsfzifyydtvtxlmsvgnowpeiviftcqbghtyysbmwrmabgqxbknzpasvrygcghwuyxxuoylehxhwacaqemflnrrqsztamsgssuedqjvrrddagrdaqtswhfwoglsxlizzcqnfswevfftycqcqvkjjkeuhaiwuiugnsoilalpursclsqhbxhqybettheegguhhlhuvffmsmbnwykcifbrstiublizrceojefcfsaoknywtdgjetfsxyflxilfivuujxljclgqtycfftpllotglkvlhkgacihdruhgcugghjrupauwsittfkclklbjzmrpmuxhvqtkgxqkqviptbmzvkwvcajhcaymyrqsryprvnbwlzequgzjkdiocpsmeshexxhkvjshpfajbrkidipwfncbgvhlcehngjquhoilhoikchkljnhdibmumtmjcmdwocrmgszfhzmmfyrhczmkanilxjbsdfyhndrjyspkdyxoutrmvglxyqnfjvntbwshekevsdeuekobyalcujvbgsbpzdjfnmhclwstendficcrjpodclcfobjsttnxfckopwpbwgujkqwepnqydlfrtkgifbximuygcvcvbckwymgphkyhtjevzuxunrxzfykeicrnjvlotewghinclxiklsjfijsqadyiywicbxxbottrvxgxjcmaglrevktawyvbwmexesnbjglioqypyxmmtgimongiloketocnetlcbfnqbpdhiczrrvxryoxgixhkuoixhilyagntymnqopxrmgeqnuzoyeqsvcorqcjkjsqvfxrourjulymeinkolzmqxwqochifqhxhrsrhxllabhrctotfobjpmwmgeupylqyelhsicngtklbajneghmokytnvlptndyazuhhwhkwjgijxsrauasfngmjtggwipumtmqvnbiniyeezlifwzwejzwrjxcvfpmwkkxppqsaadtrdyciqvzqtvyrbcvswxebziesprqxlippixandnxhuwhvflaqzemblggsvbltplnaloewklssqgsfxhnahmonovoacnylkldjsxdibhhhooeccsducwzhcnnnxhwqruzsnxkfgherpkzfjahogkruxftnnnfocavfvnpjoyksfxmdrwbvibflfdccbwpkuqxiyeqnunmzynilrtzzamnrokkzyjedtxnjsjvrvyqqonofipcwfpevcwmfdrldnvpflkkungaevegpaollmwjhlcsvkbzdcxhznhckldeedsicascshnzvejhsbqyqpzgoepnezzttmbbczfgqqwpxeqhyrsxromrtcbcqxlzmbxwoyrqfcpdmgtxgznxlhcfftfrjlvacfttwhgpdhspraadukdvwosnjacrxwrbrthnnalxkrtnguelpwrxcoctrbbvbpuqqlakcsuyvqemuoedecxwukcxrlcjsskdaxxdqskinzstxljhhqopqeeclxjmhruncjkyqqybhovnrvmrsygasydwsqujdzehksmfxxeiyoorepwjoxmxynzdcbfdmeljowuifodgnpqjtoxqtjggzevfjcgtixbascyvawluyvibhlbqpbewiqtuwttfqhobdvsxnnpwrqyldcfogqoupzsenosokbrlnycnkoonyblquthxnghrrlyhthsjkcxmpapaoeddxdjswzifwnncfhwjrlhlghdkneswygcncqmatrwnjkgmiammneyxfclunrvrixxtbvtgqdbwavkpcscyncncyyjsmodnmsgwystqezjgjfjsjmyalxbdfpzyhghoaflygorxtedrxnlqpgfoovwyhdoxdezlwdalzxeyjkzzeiwabamdgpqizgsddpowoyczzypsbemzvkbtbukhfwrwvbxtglsudpggbeevezoevyaamqjufspbrbourtarezbntmimhoktlmrxumkautrhqxtawlgfvqxwobyoxidcxfrhejpsvlnoekpnpkybxkbkgrmtzimpwuvjwqwzyjvssyjqwyqpsqlclikeunrsjabjcehfiegnhkdewgqlgulbiqzofdfatacfjlrxtipiykmcaugvfaibhnyiymlhxmssckqkfxgzwdrlomgpxbrfzfsklqcdwtaydphojbhnulnhevfhbtwbwpnynkroufgncrcpuixzxluburkmwoxhhbxrkmhqwhiscbvwbooyjhvnoznvzzptlanfyglfofmpruhmobxoyqasbcwkhjrkvaoqtmhitefpvnxjqucwaplcriwmiaivzfhjzjhdwdoeszgpmwjsykurigmklktrvvispfarbiymgogantuycjkrbasjvyeloafzsibdovddduetudubjeeqnljfjxkicqggsvlywskjhillftvksfisoxtzkrtzgtrtgbkntylmyjjsrrhaowdpjlaoeumgzodavtoscxkjvuaiymnxxppeimugbplrzacjazrulwavmtxnvcrhuzamhwzrhrwyhmhxgflknvocopipephivstyijcfvlsrunexprhpgmgbjfildnmxenkghgdexpdbpxxvolbsbwtzyerdqlvqhjzbqdjesesbmkgngilmrigrpdliaoceolibkzrucejnjuwbehtvhzklgkvokspbftovnwgugdmwpirkjiuivntxsvbilwhhnaktvwyygmovyaawyvctlsccdruhwgyhwandeixjxxwlbhxmhkhtlztreksavuqrluvtglimadggevqlflkkcndypegqgrdczfmbqleawgburxdspijqpsvycjuxolqbtbofqbrgbdtauoxmhohsuxozqtrivjxlmvyptebtszftlmwkyendyvnyifujvejgimknhwatleapeozjzfcyjamaosvyftvrzgwjcwdzhyxvbhjtebpuefoulsycaqwvdtbauacvmmbwokfkotxvmgxtmsppqtoycpcnvypoycsdhmhiiiluqxsyfhbhxakpbwcionxkxfkxgpeobhisbzhwoztiifmpogkrnewipqdyaaciqrrewelhjtrrgwkpsvwplqligdtmqchxtnrwndpjavxqyucvofwqrthfxaeqsxdmgyexibtdvgtijarcwylyhvjhilulwzgsnxkivkhagxlxmvewknbqzdoeqelgczuqotphkzlduvnnyjygdlcysjiceojjnhexlbdcrhcoeyumdxsaabpktrfpqtiejeozvfqebllayhnegzyqynyztqplrbplysoalqzcyaaaisanxhcgqncstpsugzbptvmaepgxdugfcnnoxtzdfmriaxwnlrnywwmuoeqeweglsacuhillbvzjgfpmzpkftswewhttzuzbdxjzndqymdmdsxjyvmwgxxqmvufwojeuqimxvggximqbcpqwbqnmaavoohdajgdmcausrrdfqyyptdarrntxyewckmqtvvgcydpundkhagtoyyishjqhirdfuisgxpzprcdeclkrrnkaxeqfqlgqvnmenilqnqnpgxurhqrtismyrignthdcrjdktpmifiabydmkavbpomnvsoajuggyastskfgkzqcpbqrrsfzjjtlglkdmedeaovpmuapqbvujpmqdykuxwsjsvuehkbgubfnjaerqunhtaovndmsgjeqyqhrdzzwmrouypxspbdszwacenvjvtzfeawhtjhxdppgzsiokdhasyhwypnhhllwgbkchqjccevaefidlrhkyjlzihiwjtdjjpjjummrgijexerdxafhiplflreipmzojppffoanpvzenihzbltqfqamsfmgasvmtqaycgqnxzfafvtiubnouarvmwqejesravhynyecheymwymzmcbytknhelzwvbwzwvegrsuctgteoihpapsgpljcrceiohqkwbtnagrqnmcoutmbuicqtntnuxnnibghfdndkuzskhcpgluizthyxwkuqcndmqfoiakciavkdovdvuhjyesyzqoantqcrjflzuwdzsjuagvybrptbaemwldmcedyrtsgsgdzwvpjvuowudowsolgckoyrejiowiiokmhjojhgfhoozrseehiviszmbyqjkzhlkevmbbzjytpllaeicmiwparrlffvebricwwmykwtzoeohhnhzuxlcjbowumwlreaszlrxykgetckesdsnumihgwnqgochdrslsuvvcjnyzrdnqmibktlxgvzwapfvoatyeztvojrefzhrcafulgrfvqtngawpfohmmiyvdhukglxvxsykhnbnlghteydjraqykwdmdpqdrzkkvfixxcwhzfsfwbvgmauilbajnsegqjlusehnyzrixmlfgjcyofqrlmvskdfibdqpskaxrdipgdpppbmwfofqwmxpmqlckcrgxvcbxqwxjazldibrhzwzrhyvzflzcfrjntrebvtolcdowdeyyafvhbvqjraqagdynpmsrsyefnttypopjbojhlkgpwrbbzeghtjeknucstysnfzfmogvjcwqsdjosyytfifecnqgpkzfapeqihncbrjhcbpwmhvmqflombjyypguwjsbdqdfokaqmsjcmubsykdqxwsdopaikfpftajdkshcipwcmnwpeobidrpmuvwlzqoatdvonestecykzukpuxyfohktphwospovbwqlehbaehdaeyhneknaodxfsfvrosknbdreggfqbrotozpvtwqeljmpjjnckscfyxvczbhusngaaligxzccrukubpgngjaiezroibzpnqrnxqbamlvrelhuvjkkdzudwzgzvnekluecltxqtrsdssswmkkcchcxbshznaykmjtnirtmashoklztvstjsotohnytjxwbsgeopyxlmhmpucrshfgrgmxzkpevhyrhaeihsnzqmxjlyqdqizysehgnbyeyokukjfsfpyptrtsxywidbuqgglxatmsxwvnehtpkoklqmtjrpbnqibfgcovsweibsytqovtlrtlhwjztnxrlzizqaxqnmfnloxniyzclubhohmqooaimbatvnbqpoeedsseorzlpjlbeqrsnzsvlcvrktfcvwhciezuvhlyseyemtmeghytxqvqkppkjesplgoiqrnvpgdmbuuduubqhqwcycrgrkpyqofjskxfgfbsvmncgiwdzuqzzhuorscytfxwqowrlzbluwplkddslojitjzukaaziyiyotyrdmsyikagraiteufpiriozwkngdnifadzxuojvjkpygntoogqixjebljhpwzjjckkrpczcshdrtbbtkpsmgrmlesieewcyqldxmuslhxyzhdjotzfiiuazgywizlsuuxyaelpkduhndlxakndemmseydidylwbjpozlwhddhfbxbfhekoilrcsqmcsvhgegxvgxfvfmfipxwlhqxwqlanvtqlcwvfabavpswbkqptpwawjabtgeibqjwwzzvhamsxkjuqgvzeqloffbmskmrhxfmrfhyspwlnhqukongczrqrwyhmhkovadbpbiesvxyyktiurpgvgyrciebouwwtorircmzqzlmpsfbikpeqzlojubjsauuwcymtooopwxaxdvdolytwwlgsbmtxblbfjmbztfbdikansjigblqcqxdhfneytsevfvxfcxyyymvipardwuafytukzcroqioahyvcokgrtgnocapoeeszeewwudwbnrhqhezgflbqaofxwphhcuoknhaugtldmfjpczusbwqcxyfawfqwrmucmqoanxpwndvdakkeaovfdhfitsirjkifiwemdfebloqqehjvoksfprhtwzmxysnmggvbksqxnrihbcsyydmmbviawrbrjangqcpoqblovwtrzfsqwlkxydxhroqbujlarbktfpvbxkptfhvlxxuxadtgwxzzeycmnpolzsvgokqpmzjvyhzkgwgnuepmxssmdxkmqslszjsvvkgoxtmbzjisaqirxqzagsizvdiifdhujrybhpimbdtrvjncyqwezvmmahwimxaoamwrpffofzllvkchdbsyepaoguxyrsruddhlmsmxpeygmzxexbkjposqytahhbqizowfmvouusupexxsmxcfsshbgssszgjzqirwmqrmrbamrgqrprqydvaesblxphtvwooujzzbbfmavdcsyentlodrbxtsvueswrnzgcfuohhlssczlrasnuukgdafhpnpwgszusyaxwyjntjfiymcxbmxpzkosowteqrkradbmmfdyifxktkqkbewsectukpugicxjfdyvmydhcbgospxllsvfdpotemnrpgjscrwtsjtlnyuvwodlephtqyvixgwhkukqiivhdloptbubytiwwjjpzmaxpeszdbfreuhionuttnarqmkxcnfmwbfaskgghjslggqsbvivvlgqrukarhxnnadwnkbwgaoiwbizibpynszqsezxzcuqlussiwtcgbemsmoaablqijrrkkwdgburhpwbupotzwdbrgibhthgdubuxpnnsmdexvgaiohtutjgsuqrzcabchvpgzcuvwspcsiioxoywrntlpyjwbmqvzuzouswooalhkrqcyforrbnzitujzxhvwmvpnaiduassiyqvqwuuijljgxewffroinqqieuvxloxpclwcvsxhrtlokfxxosmvqpzjksinnmjrpgseijhctxhrlbvdzvzvniwhpibuvrvorwhnvqguphcydkmcavigrcglfbprrihfcmogimvncdnbghdhhweemkpuuxjoonwlhboajsjgkhvedsyspafquemvmhurfiladegcsbdmrlfypmqetiavdawxqhfgpaknfbezzyywdtrqqro']
    want = 888507
    got = solution.calculateScore(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)

