"""Visible checks for bcb_454 -- these ship with the task and can be run.

Rendered from bigcode/bigcodebench-hard v0.1.4 (BigCodeBench/454) by
ops/vacantrun/bcb_hard_bank_20260924/build_bank.py. The code below is the
dataset's unittest TestCases, restricted to the test methods that ship with
this task; each check_* runs one of those methods.
"""

from solution import *
import sys as _vacant_sys
import solution as _vacant_solution
_vacant_sys.modules.setdefault(__name__, _vacant_solution)

import unittest
from tempfile import TemporaryDirectory
from unittest.mock import patch
class TestCases(unittest.TestCase):
    def setUp(self):
        # Create temporary directories for the source and destination folders.
        self.src_dir = TemporaryDirectory()
        self.dest_dir = TemporaryDirectory()
    def tearDown(self):
        # Clean up temporary directories after each test case.
        self.src_dir.cleanup()
        self.dest_dir.cleanup()
    def test_empty_extension(self):
        # Test behavior with an empty string as file extension.
        self.create_temp_file(self.src_dir.name, 'test.txt', 'Hello World')
        files_moved = task_func(self.src_dir.name, self.dest_dir.name, '')
        self.assertEqual(len(files_moved), 0, "Should not move files when the extension is empty.")
    def create_temp_file(self, directory, filename, content=""):
        """Helper method to create a temporary file with specified content."""
        path = os.path.join(directory, filename)
        with open(path, 'w') as f:
            f.write(content)
        return path
    def test_exception_raised_when_dirs_do_not_exist(self):
        # Test that FileNotFoundError is raised when the destination directory does not exist.
        self.src_dir.cleanup()  # Forcefully remove the destination directory to simulate the error condition.
        with self.assertRaises(FileNotFoundError, msg="Should raise FileNotFoundError when the source directory does not exist."):
            task_func(self.src_dir.name, self.dest_dir.name, 'txt')
        self.dest_dir.cleanup()  # Forcefully remove the destination directory to simulate the error condition.
        with self.assertRaises(FileNotFoundError, msg="Should raise FileNotFoundError when the destination directory does not exist."):
            task_func(self.src_dir.name, self.dest_dir.name, 'txt')


# ── Vacant wrapper (generated by build_bank.py) ──────────────────────────
# Each check_* below runs exactly one TestCases method (with its setUp /
# tearDown) and raises AssertionError with a short message if it fails.
import unittest as _vacant_unittest

for _vacant_name in [_n for _n in list(globals()) if _n.startswith("check_")]:
    del globals()[_vacant_name]


def _vacant_short(tb_text, limit=700):
    lines = (tb_text or "").rstrip().splitlines()
    idx = [i for i, ln in enumerate(lines) if ln.startswith("  File ")]
    tail = lines[idx[-1] + 2:] if idx and idx[-1] + 2 < len(lines) else lines[-3:]
    tail = [ln for ln in tail if ln.strip() and set(ln.strip()) - set("^~")]
    msg = "\n".join(tail).strip()
    if len(msg) > limit:
        msg = msg[: limit // 2] + " ...[cut]... " + msg[-(limit // 2):]
    return msg


def _vacant_run(method_name):
    suite = _vacant_unittest.TestSuite([TestCases(method_name)])
    result = _vacant_unittest.TestResult()
    suite.run(result)
    if result.wasSuccessful() and result.testsRun == 1:
        return
    if result.failures:
        kind, tb = "FAIL", result.failures[0][1]
    elif result.errors:
        kind, tb = "ERROR", result.errors[0][1]
    elif result.unexpectedSuccesses:
        kind, tb = "UNEXPECTED SUCCESS", ""
    else:
        kind, tb = "NOT RUN", ""
    raise AssertionError("%s %s: %s" % (kind, method_name, _vacant_short(tb)))


def check_test_empty_extension():
    _vacant_run('test_empty_extension')

def check_test_exception_raised_when_dirs_do_not_exist():
    _vacant_run('test_exception_raised_when_dirs_do_not_exist')
