"""Visible acceptance for s1_20_top_key — rendered data, do not hand-edit.

Generated by ops/gain/r535/build_bank.py from ops/gain/r535/tasks_s1.
Every check is zero-argument and passes by returning normally
(vacant/vrun/acceptance.py runs them in definition order).
"""


def check_01_top_key():
    from solution import top_key
    args = ({'a': 1, 'b': 3},)
    got = top_key(*args)
    want = 'b'
    assert got == want, "top_key args=%r got=%r want=%r" % (args, got, want)


def check_02_top_key():
    from solution import top_key
    args = ({'b': 2, 'a': 2},)
    got = top_key(*args)
    want = 'a'
    assert got == want, "top_key args=%r got=%r want=%r" % (args, got, want)
