"""Visible acceptance for s2_18_is_palindrome — rendered data, do not hand-edit.

Generated by ops/gain/r535/build_bank.py from ops/gain/r535/tasks_s2.
Every check is zero-argument and passes by returning normally
(vacant_network/vrun/acceptance.py runs them in definition order).
"""


def check_01_is_palindrome():
    from solution import is_palindrome
    args = ('A man, a plan, a canal: Panama',)
    got = is_palindrome(*args)
    want = True
    assert got == want, "is_palindrome args=%r got=%r want=%r" % (args, got, want)


def check_02_is_palindrome():
    from solution import is_palindrome
    args = ('ab',)
    got = is_palindrome(*args)
    want = False
    assert got == want, "is_palindrome args=%r got=%r want=%r" % (args, got, want)
