"""Hidden acceptance for s1_33_band — rendered data, do not hand-edit.

Generated by ops/gain/r535/build_bank.py from ops/gain/r535/tasks_s1.
Every check is zero-argument and passes by returning normally
(vacant/vrun/acceptance.py runs them in definition order).
"""


def check_01_band():
    from solution import band
    args = (90,)
    got = band(*args)
    want = 'A'
    assert got == want, "band args=%r got=%r want=%r" % (args, got, want)


def check_02_band():
    from solution import band
    args = (59,)
    got = band(*args)
    want = 'F'
    assert got == want, "band args=%r got=%r want=%r" % (args, got, want)


def check_03_band():
    from solution import band
    args = (100,)
    got = band(*args)
    want = 'A'
    assert got == want, "band args=%r got=%r want=%r" % (args, got, want)


def check_04_band():
    from solution import band
    args = (85,)
    got = band(*args)
    want = 'B'
    assert got == want, "band args=%r got=%r want=%r" % (args, got, want)


def check_05_band():
    from solution import band
    args = (70,)
    got = band(*args)
    want = 'C'
    assert got == want, "band args=%r got=%r want=%r" % (args, got, want)


def check_06_band():
    from solution import band
    args = (60,)
    got = band(*args)
    want = 'D'
    assert got == want, "band args=%r got=%r want=%r" % (args, got, want)


def check_07_band():
    from solution import band
    args = (0,)
    got = band(*args)
    want = 'F'
    assert got == want, "band args=%r got=%r want=%r" % (args, got, want)


def check_08_band():
    from solution import band
    args = (89,)
    got = band(*args)
    want = 'B'
    assert got == want, "band args=%r got=%r want=%r" % (args, got, want)
