"""Visible checks for bcb_1003 -- these ship with the task and can be run.

Rendered from bigcode/bigcodebench-hard v0.1.4 (BigCodeBench/1003) by
ops/vacantrun/bcb_hard_bank_20260924/build_bank.py. The code below is the
dataset's unittest TestCases, restricted to the test methods that ship with
this task; each check_* runs one of those methods.
"""

from solution import *
import sys as _vacant_sys
import solution as _vacant_solution
_vacant_sys.modules.setdefault(__name__, _vacant_solution)

import unittest
import pandas as pd
from unittest.mock import patch
class TestCases(unittest.TestCase):
    """Test cases for the task_func function."""
    @patch("urllib.request.urlopen")
    def test_empty_xml(self, mock_urlopen):
        """Test that the function raises an error for an empty XML file."""
        # Mocking empty XML data
        empty_xml_data = b"<root></root>"
        mock_urlopen.return_value.__enter__.return_value.read.return_value = (
            empty_xml_data
        )
        url = "http://example.com/empty_data.xml"
        with self.assertRaises(ValueError):
            task_func(url)
    @patch("urllib.request.urlopen")
    def test_different_structure_xml(self, mock_urlopen):
        """Test that the function raises an error for an XML file with a different structure."""
        # Mocking XML with different structure
        different_structure_xml = (
            b"<root><different><name>John</name></different></root>"
        )
        mock_urlopen.return_value.__enter__.return_value.read.return_value = (
            different_structure_xml
        )
        url = "http://example.com/different_structure_data.xml"
        with self.assertRaises(ValueError):
            task_func(url)


# ── Vacant wrapper (generated by build_bank.py) ──────────────────────────
# Each check_* below runs exactly one TestCases method (with its setUp /
# tearDown) and raises AssertionError with a short message if it fails.
import unittest as _vacant_unittest

for _vacant_name in [_n for _n in list(globals()) if _n.startswith("check_")]:
    del globals()[_vacant_name]


def _vacant_short(tb_text, limit=700):
    lines = (tb_text or "").rstrip().splitlines()
    idx = [i for i, ln in enumerate(lines) if ln.startswith("  File ")]
    tail = lines[idx[-1] + 2:] if idx and idx[-1] + 2 < len(lines) else lines[-3:]
    tail = [ln for ln in tail if ln.strip() and set(ln.strip()) - set("^~")]
    msg = "\n".join(tail).strip()
    if len(msg) > limit:
        msg = msg[: limit // 2] + " ...[cut]... " + msg[-(limit // 2):]
    return msg


def _vacant_run(method_name):
    suite = _vacant_unittest.TestSuite([TestCases(method_name)])
    result = _vacant_unittest.TestResult()
    suite.run(result)
    if result.wasSuccessful() and result.testsRun == 1:
        return
    if result.failures:
        kind, tb = "FAIL", result.failures[0][1]
    elif result.errors:
        kind, tb = "ERROR", result.errors[0][1]
    elif result.unexpectedSuccesses:
        kind, tb = "UNEXPECTED SUCCESS", ""
    else:
        kind, tb = "NOT RUN", ""
    raise AssertionError("%s %s: %s" % (kind, method_name, _vacant_short(tb)))


def check_test_different_structure_xml():
    _vacant_run('test_different_structure_xml')

def check_test_empty_xml():
    _vacant_run('test_empty_xml')
