#!/usr/bin/env python3
# -*- coding: utf-8 -*-
"""R535 題庫渲染器：把 `tasks_s1.py`／`tasks_s2.py` 的資料變成 `bank/` 底下的檔案。

這支在架構裡承重什麼（Fable 2026-09-19 裁決 R535）
--------------------------------------------------
裁決要的是「**單發會失敗、但重試有機會救回**」那個窗口，而且窗口要**設計進去**。
既有題庫都做不到這件事（LCB v2／R534 樣板會跟 R534 攪混且 pi 每題 4–28 分鐘；
r530 的 20 題在 12B 上 A-SOLO 可見全過 34/59 ⇒ 閘門只在 ~40% 題觸發；
`codebench.py` 六坑型可見只有 1 條正常例 ⇒ 閘門不會觸發）。所以題庫是自造的，
而「自造」的可稽核性全靠這一支：**同一份來源資料，渲染出來的位元組永遠相同**，
sha256 凍進 `bank_manifest.json`。

## 渲染成什麼（每題六件東西）

    bank/<task_id>/TASK.md                    ← **工作區樣板就是這一個檔**
    bank/<task_id>/tests_visible/test_visible.py
    bank/<task_id>/hidden/test_hidden.py      ← 可見 ∪ 4–8 條，只給事後計分
    bank/<task_id>/reference/solution.py
    bank/<task_id>/reference/bad_a.py         ← 名字對、行為錯
    bank/<task_id>/reference/bad_b.py         ← 第三個壞樁（多半是形狀錯）
    bank/<task_id>/reference/bad_c.py         ← 名字錯
    bank/<task_id>/meta.json

## `tests_visible/` 與 `hidden/` 都**不進工作區**

`vacant run` 的原生形狀就是 `--suite` 必須在工作區外（`launcher.py` 是 `SystemExit`）：
**agent 改得到的驗收不是驗收**。R534 把 `tests_visible/` 放進工作區，pi 自己跑測試，
閘門就沒東西可攔。所以本題庫的**工作區樣板 ＝ `TASK.md` 這一個檔**
（`WORKSPACE_TEMPLATE`），發射端把它複製進工作區，`--suite` 指到
`bank/<task_id>/tests_visible`（工作區外），`hidden/` 只在事後計分時碰。

## 為什麼 case 只有三個欄位

`fn` ／ `args` ／ `want|raises`。執行器只跑**自己渲染出來的碼**，所以有狀態的測試、
雜湊黑名單、擬態三種攻擊在這個資料形狀裡**不可表達**（R452 `vacant/suitespec.py`
的同一條）。殘餘風險只剩兩種：**覆蓋不足**與**比對旗標**（這裡的比對是 `==`）。

## 誠實邊界（逐字，`vacant/suitegauge.py`）

**擋得住已知壞解 ≠ 涵蓋真需求。** 參考解全過＋三個壞樁全被擋，是**單邊**保證；
它不代表「驗收套件固定點已解」，也不代表可見套件涵蓋了 `TASK.md` 說的全部需求。
這句話同時寫進 `bank_manifest.json` 的 `honesty_bounds`。

用法
----
    python3 ops/gain/r535/build_bank.py             # 渲染 ＋ 寫 manifest
    python3 ops/gain/r535/build_bank.py --check     # 只驗現有檔案沒漂（不寫）
"""

from __future__ import annotations

import argparse
import hashlib
import json
import os
import shutil
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
REPO = os.path.abspath(os.path.join(HERE, "..", "..", ".."))
if REPO not in sys.path:
    sys.path.insert(0, REPO)

from ops.gain.r535 import tasks_s1, tasks_s2  # noqa: E402

BANK_DIR = os.path.join(HERE, "bank")
MANIFEST_PATH = os.path.join(HERE, "bank_manifest.json")

#: 工作區樣板：**只有這一個檔**進 agent 的工作區。驗收一律留在工作區外。
WORKSPACE_TEMPLATE = ("TASK.md",)

#: 誠實邊界，逐字抄自 `vacant/suitegauge.py` 的單邊判準。
HONESTY_ONE_SIDED = (
    "擋得住已知壞解 ≠ 涵蓋真需求。參考解全過＋每個已知壞樁都被擋是**單邊**保證："
    "它不代表可見套件涵蓋了 TASK.md 說的全部需求，也不准讀成「驗收套件固定點已解」。"
)

HONESTY_BOUNDS = [
    HONESTY_ONE_SIDED,
    "事前預期失敗率（S1 ≥ 0.8、S2 0.4–0.8）是**設計意圖**不是量測值。"
    "真值只有真跑過才知道；收官時要把實測失敗率跟這個預期並排報，不可以只報一個。",
    "S1 的正控制性質建立在「回饋充分決定修法」上，量具第 3 項只驗**回饋裡有那個名字**，"
    "不驗 agent 會不會照做。**看得到 ≠ 照做**（docs/VACANT_RUN.md 誠實邊界 10）。",
    "hidden 是 visible 的**超集**，所以 hidden 全過蘊含 visible 全過；"
    "兩個數字不獨立，不可以當成兩個證據。",
    "S1 與 S2 **分開報，不合併**（裁決）。兩層的事前預期不同，合併之後任何一個"
    "平均都不對應到任何一個設計。",
    "PC 臂只切掉「講明白了也寫不出來」這一個對立解釋。PC 高**不等於**"
    "「RP 沒提升＝管道壞了」——PC 與 RP 差的不只是講不講明白，還差了"
    "「一次 vs 多次嘗試」。PC 是天花板，不是 RP 的配對對照。",
    "兩對題跨層共用同一份參考解：`s1_32_pct`／`s2_06_pct` 與 `s1_35_rle`／"
    "`s2_29_rle`。那是設計使然——S1 withhold 的是**名字**、S2 給名字 withhold "
    "**行為細節**，同一個函式在兩層各出現一次是這個對照的形狀。但它有一個後果："
    "**S1 與 S2 的結果不是完全獨立的 90 題**，這兩對之間有共用的實作難度。"
    "第 4 條（分開報不合併）因此不只是慣例，是**必要條件**：合併之後這兩對會"
    "被當成四個獨立觀測，而它們不是。（2026-09-19 稽核時發現，量具第 1–6 項"
    "都測不到這件事，因為每一項都是逐題判定的。）",
]

CASE_KIND_NOTE = (
    "case 只有 fn / args / want|raises 三個欄位，執行器只跑自己渲染的碼 ⇒ "
    "有狀態、雜湊黑名單、擬態三種攻擊不可表達（R452）。殘餘＝覆蓋不足＋比對旗標（==）。"
)

SUITE_HEADER = '''\
"""{suite} acceptance for {task_id} — rendered data, do not hand-edit.

Generated by ops/gain/r535/build_bank.py from ops/gain/r535/{src}.
Every check is zero-argument and passes by returning normally
(vacant/vrun/acceptance.py runs them in definition order).
"""
'''


def _render_case(idx: int, case: dict) -> str:
    """一條 case ＝ 一個 `check_*`。失敗訊息**逐字**帶 `args=…got=…want=…`。

    那一行不是裝飾：`acceptance.render_failures` 把它原樣貼回給 agent，
    而 S2 的修法只能從那一行讀出來（量具第 3 項就量這個）。
    """
    fn = case["fn"]
    args = case["args"]
    if not isinstance(args, tuple):
        raise TypeError("args 必須是 tuple：%r" % (args,))
    name = "check_%02d_%s" % (idx, fn)
    out = [
        "def %s():" % name,
        "    from solution import %s" % fn,
        "    args = %r" % (args,),
    ]
    if "raises" in case:
        exc = case["raises"]
        out += [
            "    try:",
            "        got = %s(*args)" % fn,
            "    except %s:" % exc,
            "        return",
            "    except Exception as exc:",
            '        raise AssertionError("%s args=%%r got=%%s(%%s) want=%s" %%'
            % (fn, exc),
            "                             (args, type(exc).__name__, exc))",
            '    raise AssertionError("%s args=%%r got=%%r want=%s to be raised" %%'
            % (fn, exc),
            "                         (args, got))",
        ]
    else:
        out += [
            "    got = %s(*args)" % fn,
            "    want = %r" % (case["want"],),
            '    assert got == want, "%s args=%%r got=%%r want=%%r" %% (args, got, want)'
            % fn,
        ]
    return "\n".join(out) + "\n"


def _render_suite(task: dict, cases: list[dict], *, suite: str, src: str) -> str:
    parts = [SUITE_HEADER.format(suite=suite, task_id=task["id"], src=src)]
    for i, case in enumerate(cases, 1):
        parts.append(_render_case(i, case))
    return "\n\n".join(parts).rstrip("\n") + "\n"


#: `TASK.md` 的尾巴。兩份 TASK 共用，**逐位元相同**。
TASK_TAIL = ["Write the code in a file called `solution.py` in this directory.",
             "Nothing else is needed and nothing else is read."]

#: `TASK_explicit.md` 插入塊的標題（S1／S2 各一）。
EXPLICIT_HEADING = {"S1": "## Interface", "S2": "## Details"}


def _task_lines(task: dict) -> list[str]:
    return ["# Task", ""] + task["prose"].strip().split("\n") + [""]


def _render_task_md(task: dict) -> str:
    return "\n".join(_task_lines(task) + TASK_TAIL) + "\n"


def explicit_block(task: dict, stratum: str, explicit: list[str]) -> list[str]:
    """`TASK_explicit.md` 相對 `TASK.md` **唯一**多出來的那幾行。

    S1 是介面（縮排成 code block），S2 是被 withhold 的行為細節（項目符號）。
    形狀刻意固定：量具第 6 項要驗「diff 只有這一塊、而且是純插入」，
    插入塊的位置與邊界因此必須是渲染器決定的，不是作者一題一題手寫的。
    """
    head = [EXPLICIT_HEADING[stratum], ""]
    if stratum == "S1":
        body = ["    " + line for line in explicit]
    else:
        body = ["- " + line for line in explicit]
    return head + body + [""]


def _render_task_explicit_md(task: dict, stratum: str,
                             explicit: list[str]) -> str:
    return "\n".join(_task_lines(task)
                     + explicit_block(task, stratum, explicit)
                     + TASK_TAIL) + "\n"


def _meta(task: dict, stratum: str, src: str) -> dict:
    visible = task["visible"]
    hidden = visible + task["hidden_extra"]
    mod = tasks_s1 if stratum == "S1" else tasks_s2
    explicit = mod.EXPLICIT[task["id"]]
    missing_in_bad_c = [n for n in task["names"]
                        if ("def %s(" % n) not in task["bad_c"]]
    return {
        "explicit_lines": list(explicit),
        "explicit_block_lines": len(explicit_block(task, stratum, explicit)),
        "workspace_template_pc": ["TASK_explicit.md"],
        "workspace_template_pc_note":
            "PC 臂把 TASK_explicit.md 複製進工作區**取代 TASK.md**（落地時改名成 "
            "TASK.md），其餘位元組與別的臂逐字相同 —— 否則 PC 不是同一題的天花板。",
        "task_id": task["id"],
        "stratum": stratum,
        "title": task["title"],
        "required_names": list(task["names"]),
        "trap": task["trap"],
        "withheld": list(task.get("withheld", [])),
        "expected_first_attempt_visible_fail":
            ">= 0.8" if stratum == "S1" else "0.4 - 0.8",
        "expected_is_design_intent_not_measurement": True,
        "visible_n": len(visible),
        "hidden_n": len(hidden),
        "hidden_is_superset_of_visible": True,
        "workspace_template": list(WORKSPACE_TEMPLATE),
        "stakes": {
            "bad_a.py": "right names, wrong behaviour",
            "bad_b.py": "third stake (usually the wrong return shape)",
            "bad_c.py": "wrong name: %s not defined" % ", ".join(missing_in_bad_c),
        },
        "wrong_name_stake_missing_names": missing_in_bad_c,
        "origin": "authored 2026-09-19 for R535; not derived from LiveCodeBench, "
                  "ops/gain/r530/bank, or vacant/codebench.py",
        "source_data": "ops/gain/r535/%s.py" % src,
        "honesty": HONESTY_ONE_SIDED,
    }


def _write(path: str, text: str) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    with open(path, "w", encoding="utf-8") as fh:
        fh.write(text)


def _files_for(task: dict, stratum: str, src: str) -> dict[str, str]:
    visible = task["visible"]
    hidden = visible + task["hidden_extra"]
    mod = tasks_s1 if stratum == "S1" else tasks_s2
    explicit = mod.EXPLICIT[task["id"]]
    return {
        "TASK.md": _render_task_md(task),
        "TASK_explicit.md": _render_task_explicit_md(task, stratum, explicit),
        "tests_visible/test_visible.py":
            _render_suite(task, visible, suite="Visible", src=src),
        "hidden/test_hidden.py":
            _render_suite(task, hidden, suite="Hidden", src=src),
        "reference/solution.py": task["solution"],
        "reference/bad_a.py": task["bad_a"],
        "reference/bad_b.py": task["bad_b"],
        "reference/bad_c.py": task["bad_c"],
        "meta.json": json.dumps(_meta(task, stratum, src), ensure_ascii=False,
                                indent=2, sort_keys=True) + "\n",
    }


def all_tasks() -> list[tuple[dict, str, str]]:
    out = [(t, "S1", "tasks_s1") for t in tasks_s1.TASKS]
    out += [(t, "S2", "tasks_s2") for t in tasks_s2.TASKS]
    ids = [t["id"] for t, _, _ in out]
    if len(set(ids)) != len(ids):
        raise SystemExit("題目 id 重複，停。")
    return out


def build(check_only: bool = False) -> int:
    tasks = all_tasks()
    rendered: dict[str, dict[str, str]] = {}
    for task, stratum, src in tasks:
        rendered[task["id"]] = _files_for(task, stratum, src)

    drift: list[str] = []
    if check_only:
        for tid, files in rendered.items():
            for rel, text in files.items():
                p = os.path.join(BANK_DIR, tid, rel)
                if not os.path.exists(p):
                    drift.append("missing: %s/%s" % (tid, rel))
                    continue
                with open(p, "r", encoding="utf-8") as fh:
                    if fh.read() != text:
                        drift.append("changed: %s/%s" % (tid, rel))
        on_disk = set()
        if os.path.isdir(BANK_DIR):
            for tid in sorted(os.listdir(BANK_DIR)):
                if os.path.isdir(os.path.join(BANK_DIR, tid)):
                    on_disk.add(tid)
        for extra in sorted(on_disk - set(rendered)):
            drift.append("extra task dir: %s" % extra)
    else:
        if os.path.isdir(BANK_DIR):
            shutil.rmtree(BANK_DIR)
        for tid, files in rendered.items():
            for rel, text in files.items():
                _write(os.path.join(BANK_DIR, tid, rel), text)

    sha: dict[str, str] = {}
    for tid, files in sorted(rendered.items()):
        for rel, text in sorted(files.items()):
            sha["%s/%s" % (tid, rel)] = hashlib.sha256(
                text.encode("utf-8")).hexdigest()

    s1 = [t for t, s, _ in tasks if s == "S1"]
    s2 = [t for t, s, _ in tasks if s == "S2"]
    manifest = {
        "run": "R535",
        "decision": "Fable 2026-09-19 裁決 R535（題庫與量具；本檔不負責發射）",
        "generated_by": "ops/gain/r535/build_bank.py",
        "source_data": ["ops/gain/r535/tasks_s1.py", "ops/gain/r535/tasks_s2.py"],
        "bank_dir": "ops/gain/r535/bank",
        "workspace_template": list(WORKSPACE_TEMPLATE),
        "workspace_template_pc": ["TASK_explicit.md"],
        "pc_arm": {
            "what": "PC ＝ 正控制臂，每題只跑 1 次、不重試，工作區的任務檔換成 "
                    "TASK_explicit.md（落地時改名成 TASK.md，其餘位元組相同）。",
            "why": "PC 是 RP 臂的**天花板**。沒有它，「RP 沒提升」有兩個無法分辨的"
                   "解釋——「agent 看得到回饋但不照做」與「講明白了它也寫不出來」。"
                   "PC 把後者切掉。",
            "explicit_is": {"S1": "函式名／簽名／回傳形狀",
                            "S2": "那一到兩個被 withhold 的行為細節"},
            "expected_first_attempt_visible_pass": ">= 0.8",
            "ceiling_rule": "PC < 0.5 ⇒ 該層判 CEILING_TOO_LOW"
                            "（題目對這顆模型太難，管道問題根本沒被提出來）。",
            "gate": "量具第 6 項：TASK_explicit.md 與 TASK.md 的 diff 只准是"
                    "介面／細節那一塊，且必須是**純插入**；兩份若在別處也不一樣，"
                    "PC 就不是同一題的天花板，CEILING_TOO_LOW 判準失效。",
        },
        "workspace_template_note":
            "只有這些檔進 agent 的工作區（PC 臂用 workspace_template_pc）。"
            "tests_visible/ 與 hidden/ 都不進 —— "
            "`vacant run` 的 --suite 必須在工作區外（agent 改得到的驗收不是驗收）。"
            "R534 就是把 tests_visible/ 放進工作區，pi 自己跑測試，閘門才沒東西可攔。",
        "suite_path_for_launch": "ops/gain/r535/bank/<task_id>/tests_visible",
        "hidden_path_for_scoring": "ops/gain/r535/bank/<task_id>/hidden",
        "acceptance_runner": "vacant/vrun/acceptance.py::run_suite（不准另寫第二把尺）",
        "case_shape_note": CASE_KIND_NOTE,
        "strata": {
            "S1": {
                "name": "介面未給",
                "n": len(s1),
                "shape": "TASK.md 白話講功能，不給函式名／簽名／回傳形狀；"
                         "可見套件 2–3 條 check_* 釘死名字與形狀",
                "expected_first_attempt_visible_fail": ">= 0.8",
                "role": "管道的正控制：回饋（ImportError: cannot import name ...）"
                        "充分決定修法，任何會消費回饋的 agent 都救得回",
                "task_ids": [t["id"] for t in s1],
            },
            "S2": {
                "name": "名字給、契約細節未給",
                "n": len(s2),
                "shape": "TASK.md 給函式名＋白話描述，withhold 一到兩個行為細節；"
                         "可見套件釘那些細節",
                "expected_first_attempt_visible_fail": "0.4 - 0.8",
                "role": "較接近真工作負載：修法要讀 args=/want= 那一行並改邏輯",
                "task_ids": [t["id"] for t in s2],
            },
        },
        "report_rule": "S1 與 S2 分開報，不合併（裁決）。",
        "gauge": "ops/gain/r535/gauge_bank.py（零模型呼叫，發射前必須全綠）",
        "honesty_bounds": HONESTY_BOUNDS,
        "files_sha256": sha,
    }
    text = json.dumps(manifest, ensure_ascii=False, indent=2,
                      sort_keys=True) + "\n"

    if check_only:
        if not os.path.exists(MANIFEST_PATH):
            drift.append("missing: bank_manifest.json")
        else:
            with open(MANIFEST_PATH, "r", encoding="utf-8") as fh:
                if fh.read() != text:
                    drift.append("changed: bank_manifest.json")
        if drift:
            print("BANK DRIFT (%d)" % len(drift))
            for d in drift:
                print("  " + d)
            return 1
        print("BANK OK — %d tasks (S1 %d / S2 %d), %d files, no drift"
              % (len(rendered), len(s1), len(s2), len(sha)))
        return 0

    _write(MANIFEST_PATH, text)
    print("built %d tasks (S1 %d / S2 %d), %d files"
          % (len(rendered), len(s1), len(s2), len(sha)))
    print("manifest sha256 = %s"
          % hashlib.sha256(text.encode("utf-8")).hexdigest())
    return 0


def main() -> int:
    ap = argparse.ArgumentParser(description="R535 題庫渲染器（零模型呼叫）")
    ap.add_argument("--check", action="store_true",
                    help="只驗檔案與 manifest 沒漂，不寫任何東西")
    args = ap.parse_args()
    return build(check_only=args.check)


if __name__ == "__main__":
    raise SystemExit(main())
