"""Hidden acceptance for s1_49_rgb — rendered data, do not hand-edit.

Generated by ops/gain/r535/build_bank.py from ops/gain/r535/tasks_s1.
Every check is zero-argument and passes by returning normally
(vacant/vrun/acceptance.py runs them in definition order).
"""


def check_01_rgb():
    from solution import rgb
    args = ('#FF8000',)
    got = rgb(*args)
    want = {'r': 255, 'g': 128, 'b': 0}
    assert got == want, "rgb args=%r got=%r want=%r" % (args, got, want)


def check_02_rgb():
    from solution import rgb
    args = ('#000000',)
    got = rgb(*args)
    want = {'r': 0, 'g': 0, 'b': 0}
    assert got == want, "rgb args=%r got=%r want=%r" % (args, got, want)


def check_03_rgb():
    from solution import rgb
    args = ('#ffffff',)
    got = rgb(*args)
    want = {'r': 255, 'g': 255, 'b': 255}
    assert got == want, "rgb args=%r got=%r want=%r" % (args, got, want)


def check_04_rgb():
    from solution import rgb
    args = ('#010203',)
    got = rgb(*args)
    want = {'r': 1, 'g': 2, 'b': 3}
    assert got == want, "rgb args=%r got=%r want=%r" % (args, got, want)


def check_05_rgb():
    from solution import rgb
    args = ('#00ff00',)
    got = rgb(*args)
    want = {'r': 0, 'g': 255, 'b': 0}
    assert got == want, "rgb args=%r got=%r want=%r" % (args, got, want)


def check_06_rgb():
    from solution import rgb
    args = ('#AABBCC',)
    got = rgb(*args)
    want = {'r': 170, 'g': 187, 'b': 204}
    assert got == want, "rgb args=%r got=%r want=%r" % (args, got, want)


def check_07_rgb():
    from solution import rgb
    args = ('#123456',)
    got = rgb(*args)
    want = {'r': 18, 'g': 52, 'b': 86}
    assert got == want, "rgb args=%r got=%r want=%r" % (args, got, want)
