"""Visible acceptance for s2_24_round_money — rendered data, do not hand-edit.

Generated by ops/gain/r535/build_bank.py from ops/gain/r535/tasks_s2.
Every check is zero-argument and passes by returning normally
(vacant_network/vrun/acceptance.py runs them in definition order).
"""


def check_01_round_money():
    from solution import round_money
    args = (2.675,)
    got = round_money(*args)
    want = 2.68
    assert got == want, "round_money args=%r got=%r want=%r" % (args, got, want)


def check_02_round_money():
    from solution import round_money
    args = (0.125,)
    got = round_money(*args)
    want = 0.13
    assert got == want, "round_money args=%r got=%r want=%r" % (args, got, want)
