"""Visible checks for bcb_917 -- these ship with the task and can be run.

Rendered from bigcode/bigcodebench-hard v0.1.4 (BigCodeBench/917) by
ops/vacantrun/bcb_hard_bank_20260924/build_bank.py. The code below is the
dataset's unittest TestCases, restricted to the test methods that ship with
this task; each check_* runs one of those methods.
"""

from solution import *
import sys as _vacant_sys
import solution as _vacant_solution
_vacant_sys.modules.setdefault(__name__, _vacant_solution)

# Importing required modules for testing
import unittest
import pandas as pd
from matplotlib.axes import Axes
class TestCases(unittest.TestCase):
    
    def test_case_1(self):
        # Creating a sample dataframe with closing prices for 7 days
        df1 = pd.DataFrame({
            'date': pd.date_range(start='2022-01-01', end='2022-01-07', freq='D'),
            'closing_price': [100, 101, 102, 103, 104, 105, 106]
        })
        
        # Running the function
        forecast1, ax1 = task_func(df1)
        
        # Checking the type of the forecast and plot object
        self.assertIsInstance(forecast1, list)
        self.assertIsInstance(ax1, Axes)
        
        # Checking the length of the forecasted list
        for a, b in zip(forecast1, [106.99999813460752, 107.99999998338443, 108.99999547091295, 109.99999867405204, 110.99999292499156, 111.99999573455818, 112.9999903188028]):
            self.assertAlmostEqual(a, b, places=2)
        
        # Checking if the plot contains data
        lines = ax1.get_lines()
        self.assertTrue(lines[0].get_ydata().tolist(), [100, 101, 102, 103, 104, 105, 106])
    def test_case_2(self):
        # Creating a sample dataframe with closing prices for 7 days
        df2 = pd.DataFrame({
            'date': pd.date_range(start='2022-02-01', end='2022-02-07', freq='D'),
            'closing_price': [200, 201, 202, 203, 204, 205, 206]
        })
        
        # Running the function
        forecast2, ax2 = task_func(df2)
        
        # Checking the type of the forecast and plot object
        self.assertIsInstance(forecast2, list)
        self.assertIsInstance(ax2, Axes)
        
        # Checking the length of the forecasted list
        for a, b in zip(forecast2, [206.9999997816766, 208.00000005262595, 208.99999941300158, 210.000000028273, 210.99999903094576, 211.99999982088116, 212.99999869216418]):
            self.assertAlmostEqual(a, b, places=2)
        # Checking if the plot contains data
        lines = ax2.get_lines()
        self.assertAlmostEqual(lines[0].get_ydata().tolist(), [200, 201, 202, 203, 204, 205, 206])


# ── Vacant wrapper (generated by build_bank.py) ──────────────────────────
# Each check_* below runs exactly one TestCases method (with its setUp /
# tearDown) and raises AssertionError with a short message if it fails.
import unittest as _vacant_unittest

for _vacant_name in [_n for _n in list(globals()) if _n.startswith("check_")]:
    del globals()[_vacant_name]


def _vacant_short(tb_text, limit=700):
    lines = (tb_text or "").rstrip().splitlines()
    idx = [i for i, ln in enumerate(lines) if ln.startswith("  File ")]
    tail = lines[idx[-1] + 2:] if idx and idx[-1] + 2 < len(lines) else lines[-3:]
    tail = [ln for ln in tail if ln.strip() and set(ln.strip()) - set("^~")]
    msg = "\n".join(tail).strip()
    if len(msg) > limit:
        msg = msg[: limit // 2] + " ...[cut]... " + msg[-(limit // 2):]
    return msg


def _vacant_run(method_name):
    suite = _vacant_unittest.TestSuite([TestCases(method_name)])
    result = _vacant_unittest.TestResult()
    suite.run(result)
    if result.wasSuccessful() and result.testsRun == 1:
        return
    if result.failures:
        kind, tb = "FAIL", result.failures[0][1]
    elif result.errors:
        kind, tb = "ERROR", result.errors[0][1]
    elif result.unexpectedSuccesses:
        kind, tb = "UNEXPECTED SUCCESS", ""
    else:
        kind, tb = "NOT RUN", ""
    raise AssertionError("%s %s: %s" % (kind, method_name, _vacant_short(tb)))


def check_test_case_1():
    _vacant_run('test_case_1')

def check_test_case_2():
    _vacant_run('test_case_2')
