"""Visible checks for bcb_587 -- these ship with the task and can be run.

Rendered from bigcode/bigcodebench-hard v0.1.4 (BigCodeBench/587) by
ops/vacantrun/bcb_hard_bank_20260924/build_bank.py. The code below is the
dataset's unittest TestCases, restricted to the test methods that ship with
this task; each check_* runs one of those methods.
"""

from solution import *
import sys as _vacant_sys
import solution as _vacant_solution
_vacant_sys.modules.setdefault(__name__, _vacant_solution)

import unittest
from base64 import b64decode
class TestCases(unittest.TestCase):
    def setUp(self):
        # Setup a test file
        self.test_file = 'test_file.txt'
        with open(self.test_file, 'w') as f:
            f.write("This is a test file.")
    def test_encrypted_file_content(self):
        pub_key, encrypted_file, _ = task_func(self.test_file)
        with open(self.test_file, 'rb') as original_file:
            original_data = original_file.read()
        with open(encrypted_file, 'rb') as enc_file:
            encrypted_data = enc_file.read()
        self.assertNotEqual(original_data, encrypted_data)
    def test_aes_key_file_content(self):
        _, _, encrypted_key_file = task_func(self.test_file)
        self.assertTrue(os.path.exists(encrypted_key_file))
        self.assertTrue(os.path.getsize(encrypted_key_file) > 0)
    def tearDown(self):
        # Clean up created files
        os.remove(self.test_file)
        encrypted_file = self.test_file + '.encrypted'
        if os.path.exists(encrypted_file):
            os.remove(encrypted_file)
        if os.path.exists('aes_key.encrypted'):
            os.remove('aes_key.encrypted')


# ── Vacant wrapper (generated by build_bank.py) ──────────────────────────
# Each check_* below runs exactly one TestCases method (with its setUp /
# tearDown) and raises AssertionError with a short message if it fails.
import unittest as _vacant_unittest

for _vacant_name in [_n for _n in list(globals()) if _n.startswith("check_")]:
    del globals()[_vacant_name]


def _vacant_short(tb_text, limit=700):
    lines = (tb_text or "").rstrip().splitlines()
    idx = [i for i, ln in enumerate(lines) if ln.startswith("  File ")]
    tail = lines[idx[-1] + 2:] if idx and idx[-1] + 2 < len(lines) else lines[-3:]
    tail = [ln for ln in tail if ln.strip() and set(ln.strip()) - set("^~")]
    msg = "\n".join(tail).strip()
    if len(msg) > limit:
        msg = msg[: limit // 2] + " ...[cut]... " + msg[-(limit // 2):]
    return msg


def _vacant_run(method_name):
    suite = _vacant_unittest.TestSuite([TestCases(method_name)])
    result = _vacant_unittest.TestResult()
    suite.run(result)
    if result.wasSuccessful() and result.testsRun == 1:
        return
    if result.failures:
        kind, tb = "FAIL", result.failures[0][1]
    elif result.errors:
        kind, tb = "ERROR", result.errors[0][1]
    elif result.unexpectedSuccesses:
        kind, tb = "UNEXPECTED SUCCESS", ""
    else:
        kind, tb = "NOT RUN", ""
    raise AssertionError("%s %s: %s" % (kind, method_name, _vacant_short(tb)))


def check_test_aes_key_file_content():
    _vacant_run('test_aes_key_file_content')

def check_test_encrypted_file_content():
    _vacant_run('test_encrypted_file_content')
