"""Visible checks for bcb_1042 -- these ship with the task and can be run.

Rendered from bigcode/bigcodebench-hard v0.1.4 (BigCodeBench/1042) by
ops/vacantrun/bcb_hard_bank_20260924/build_bank.py. The code below is the
dataset's unittest TestCases, restricted to the test methods that ship with
this task; each check_* runs one of those methods.
"""

from solution import *
import sys as _vacant_sys
import solution as _vacant_solution
_vacant_sys.modules.setdefault(__name__, _vacant_solution)

import unittest
from unittest.mock import patch, MagicMock
import smtplib
from email.message import EmailMessage
import getpass
class TestCases(unittest.TestCase):
    """Test cases for task_func"""
    @patch("socket.socket")
    @patch("smtplib.SMTP")
    @patch("getpass.getpass")
    def test_email_with_empty_message(self, mock_getpass, mock_smtp, mock_socket):
        """
        Test behavior when an empty message is received.
        """
        # Mock the recv method to return an empty byte string
        mock_socket.return_value.recv.return_value = b""
        mock_getpass.side_effect = [
            "sender@example.com",
            "recipient@example.com",
            "password",
        ]
        mock_smtp_instance = MagicMock()
        mock_smtp.return_value = mock_smtp_instance
        client_socket = MagicMock()
        # Simulate the recv and decode behavior by setting the return value of the decode method
        client_socket.recv.return_value.decode.return_value = ""
        task_func(client_socket)
        mock_smtp_instance.send_message.assert_not_called()
    @patch("socket.socket")
    @patch("smtplib.SMTP")
    @patch("getpass.getpass")
    def test_smtp_server_connection_error(self, mock_getpass, mock_smtp, mock_socket):
        """
        Test behavior when there is a network error (e.g., SMTP server unreachable).
        """
        # Setup mock for recv to return a valid bytes object
        client_socket = MagicMock()
        client_socket.recv.return_value = b"Test message"
        mock_getpass.side_effect = [
            "sender@example.com",
            "recipient@example.com",
            "password",
        ]
        mock_smtp.side_effect = smtplib.SMTPConnectError(
            421, "Failed to connect to the server"
        )
        # Expecting an SMTPConnectError
        with self.assertRaises(smtplib.SMTPConnectError):
            task_func(client_socket)


# ── Vacant wrapper (generated by build_bank.py) ──────────────────────────
# Each check_* below runs exactly one TestCases method (with its setUp /
# tearDown) and raises AssertionError with a short message if it fails.
import unittest as _vacant_unittest

for _vacant_name in [_n for _n in list(globals()) if _n.startswith("check_")]:
    del globals()[_vacant_name]


def _vacant_short(tb_text, limit=700):
    lines = (tb_text or "").rstrip().splitlines()
    idx = [i for i, ln in enumerate(lines) if ln.startswith("  File ")]
    tail = lines[idx[-1] + 2:] if idx and idx[-1] + 2 < len(lines) else lines[-3:]
    tail = [ln for ln in tail if ln.strip() and set(ln.strip()) - set("^~")]
    msg = "\n".join(tail).strip()
    if len(msg) > limit:
        msg = msg[: limit // 2] + " ...[cut]... " + msg[-(limit // 2):]
    return msg


def _vacant_run(method_name):
    suite = _vacant_unittest.TestSuite([TestCases(method_name)])
    result = _vacant_unittest.TestResult()
    suite.run(result)
    if result.wasSuccessful() and result.testsRun == 1:
        return
    if result.failures:
        kind, tb = "FAIL", result.failures[0][1]
    elif result.errors:
        kind, tb = "ERROR", result.errors[0][1]
    elif result.unexpectedSuccesses:
        kind, tb = "UNEXPECTED SUCCESS", ""
    else:
        kind, tb = "NOT RUN", ""
    raise AssertionError("%s %s: %s" % (kind, method_name, _vacant_short(tb)))


def check_test_email_with_empty_message():
    _vacant_run('test_email_with_empty_message')

def check_test_smtp_server_connection_error():
    _vacant_run('test_smtp_server_connection_error')
