"""Visible checks for bcb_528 -- these ship with the task and can be run.

Rendered from bigcode/bigcodebench-hard v0.1.4 (BigCodeBench/528) by
ops/vacantrun/bcb_hard_bank_20260924/build_bank.py. The code below is the
dataset's unittest TestCases, restricted to the test methods that ship with
this task; each check_* runs one of those methods.
"""

from solution import *
import sys as _vacant_sys
import solution as _vacant_solution
_vacant_sys.modules.setdefault(__name__, _vacant_solution)

import unittest
import tempfile
import os
import matplotlib
from collections import Counter
class TestCases(unittest.TestCase):
    def setUp(self):
        self.temp_dir = tempfile.TemporaryDirectory()
        self.addCleanup(self.temp_dir.cleanup)
    def tearDown(self):
        plt.close("all")
    def create_temp_csv_file(self, content):
        # Create a temporary CSV file within the temp directory
        temp_file_path = os.path.join(self.temp_dir.name, "temp_file.csv")
        with open(temp_file_path, "w", newline="") as temp_file:
            temp_file.write(content)
        return temp_file_path
    def test_case_1(self):
        # With duplicates - test results
        content = "Name,Age,City\nAlice,25,New York\nAlice,25,New York\nBob,30,London\nAlice,25,New York\nBob,30,London"
        file_path = self.create_temp_csv_file(content)
        duplicates, _ = task_func(file_path)
        self.assertEqual(
            duplicates,
            Counter({("Alice", "25", "New York"): 3, ("Bob", "30", "London"): 2}),
        )
    def test_case_2(self):
        # With duplicates - test plot
        content = "Name,Age,City\nAlice,25,New York\nAlice,25,New York\nBob,30,London\nAlice,25,New York\nBob,30,London"
        file_path = self.create_temp_csv_file(content)
        _, ax = task_func(file_path)
        # Test plot
        self.assertIsNotNone(ax)
        self.assertIsInstance(ax, matplotlib.axes._axes.Axes)
        self.assertEqual(ax.get_title(), "Duplicate Entries")
        self.assertEqual(ax.get_ylabel(), "Count")


# ── Vacant wrapper (generated by build_bank.py) ──────────────────────────
# Each check_* below runs exactly one TestCases method (with its setUp /
# tearDown) and raises AssertionError with a short message if it fails.
import unittest as _vacant_unittest

for _vacant_name in [_n for _n in list(globals()) if _n.startswith("check_")]:
    del globals()[_vacant_name]


def _vacant_short(tb_text, limit=700):
    lines = (tb_text or "").rstrip().splitlines()
    idx = [i for i, ln in enumerate(lines) if ln.startswith("  File ")]
    tail = lines[idx[-1] + 2:] if idx and idx[-1] + 2 < len(lines) else lines[-3:]
    tail = [ln for ln in tail if ln.strip() and set(ln.strip()) - set("^~")]
    msg = "\n".join(tail).strip()
    if len(msg) > limit:
        msg = msg[: limit // 2] + " ...[cut]... " + msg[-(limit // 2):]
    return msg


def _vacant_run(method_name):
    suite = _vacant_unittest.TestSuite([TestCases(method_name)])
    result = _vacant_unittest.TestResult()
    suite.run(result)
    if result.wasSuccessful() and result.testsRun == 1:
        return
    if result.failures:
        kind, tb = "FAIL", result.failures[0][1]
    elif result.errors:
        kind, tb = "ERROR", result.errors[0][1]
    elif result.unexpectedSuccesses:
        kind, tb = "UNEXPECTED SUCCESS", ""
    else:
        kind, tb = "NOT RUN", ""
    raise AssertionError("%s %s: %s" % (kind, method_name, _vacant_short(tb)))


def check_test_case_1():
    _vacant_run('test_case_1')

def check_test_case_2():
    _vacant_run('test_case_2')
