"""Visible acceptance for s2_12_slugify — rendered data, do not hand-edit.

Generated by ops/gain/r535/build_bank.py from ops/gain/r535/tasks_s2.
Every check is zero-argument and passes by returning normally
(vacant_network/vrun/acceptance.py runs them in definition order).
"""


def check_01_slugify():
    from solution import slugify
    args = ('Hello,  World!',)
    got = slugify(*args)
    want = 'hello-world'
    assert got == want, "slugify args=%r got=%r want=%r" % (args, got, want)


def check_02_slugify():
    from solution import slugify
    args = ('--A--',)
    got = slugify(*args)
    want = 'a'
    assert got == want, "slugify args=%r got=%r want=%r" % (args, got, want)
