"""Visible checks for bcb_723 -- these ship with the task and can be run.

Rendered from bigcode/bigcodebench-hard v0.1.4 (BigCodeBench/723) by
ops/vacantrun/bcb_hard_bank_20260924/build_bank.py. The code below is the
dataset's unittest TestCases, restricted to the test methods that ship with
this task; each check_* runs one of those methods.
"""

from solution import *
import sys as _vacant_sys
import solution as _vacant_solution
_vacant_sys.modules.setdefault(__name__, _vacant_solution)

import unittest
from unittest.mock import patch, mock_open, MagicMock
class TestCases(unittest.TestCase):
    @patch('urllib.request.urlopen')
    @patch('builtins.open', new_callable=mock_open)
    @patch('csv.writer')
    def test_correct_scraping(self, mock_csv_writer, mock_file_open, mock_urlopen):
        # Mock the HTML response and urlopen
        mock_response = MagicMock()
        mock_response.read.return_value = b"<html><body><table class='data-table'><tr><td>Header 1</td><td>Header 2</td></tr><tr><td>Data 1</td><td>Data 2</td></tr></table></body></html>"
        mock_urlopen.return_value = mock_response
        
        # Mock writer behavior
        mock_writer = MagicMock()
        mock_csv_writer.return_value = mock_writer
        # Call the function
        task_func('http://example.com')
        # Check if writer.writerow was indeed called
        mock_writer.writerows.assert_called()
    @patch('urllib.request.urlopen')
    def test_empty_table(self, mock_urlopen):
        # Mock an empty table HTML response
        mock_response = MagicMock()
        mock_response.read.return_value = b"<html><body><table class='data-table'></table></body></html>"
        mock_urlopen.return_value = mock_response
        result = task_func('http://example.com/empty_table_page.html')
        self.assertEqual(result, 'scraped_data.csv')


# ── Vacant wrapper (generated by build_bank.py) ──────────────────────────
# Each check_* below runs exactly one TestCases method (with its setUp /
# tearDown) and raises AssertionError with a short message if it fails.
import unittest as _vacant_unittest

for _vacant_name in [_n for _n in list(globals()) if _n.startswith("check_")]:
    del globals()[_vacant_name]


def _vacant_short(tb_text, limit=700):
    lines = (tb_text or "").rstrip().splitlines()
    idx = [i for i, ln in enumerate(lines) if ln.startswith("  File ")]
    tail = lines[idx[-1] + 2:] if idx and idx[-1] + 2 < len(lines) else lines[-3:]
    tail = [ln for ln in tail if ln.strip() and set(ln.strip()) - set("^~")]
    msg = "\n".join(tail).strip()
    if len(msg) > limit:
        msg = msg[: limit // 2] + " ...[cut]... " + msg[-(limit // 2):]
    return msg


def _vacant_run(method_name):
    suite = _vacant_unittest.TestSuite([TestCases(method_name)])
    result = _vacant_unittest.TestResult()
    suite.run(result)
    if result.wasSuccessful() and result.testsRun == 1:
        return
    if result.failures:
        kind, tb = "FAIL", result.failures[0][1]
    elif result.errors:
        kind, tb = "ERROR", result.errors[0][1]
    elif result.unexpectedSuccesses:
        kind, tb = "UNEXPECTED SUCCESS", ""
    else:
        kind, tb = "NOT RUN", ""
    raise AssertionError("%s %s: %s" % (kind, method_name, _vacant_short(tb)))


def check_test_correct_scraping():
    _vacant_run('test_correct_scraping')

def check_test_empty_table():
    _vacant_run('test_empty_table')
