"""Visible checks for bcb_82 -- these ship with the task and can be run.

Rendered from bigcode/bigcodebench-hard v0.1.4 (BigCodeBench/82) by
ops/vacantrun/bcb_hard_bank_20260924/build_bank.py. The code below is the
dataset's unittest TestCases, restricted to the test methods that ship with
this task; each check_* runs one of those methods.
"""

from solution import *
import sys as _vacant_sys
import solution as _vacant_solution
_vacant_sys.modules.setdefault(__name__, _vacant_solution)

import unittest
from unittest.mock import patch, MagicMock
import os
import shutil
from flask_login import login_user
class TestCases(unittest.TestCase):
    def setUp(self):
        current_file_path = os.path.abspath("__file__")
        current_directory = os.path.dirname(current_file_path)
        self.secret_key = 'mysecretkey'
        self.template_folder = f'{current_directory}/templates'
        os.makedirs(self.template_folder, exist_ok=True)
        with open(f"{self.template_folder}/login.html", "w") as f:
            f.write("""
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Login</title>
</head>
<body>
    <h1>Login</h1>
    <form method="post">
        <label for="username">Username:</label>
        <input type="text" id="username" name="username" required>
        <br>
        <label for="password">Password:</label>
        <input type="password" id="password" name="password" required>
        <br>
        <button type="submit">Log In</button>
    </form>
</body>
</html>
    """)
        # Create the app with testing configurations
        self.app = task_func(self.secret_key, self.template_folder)
        self.app.config['TESTING'] = True
        self.app.config['DEBUG'] = True
        self.client = self.app.test_client()
    def tearDown(self):
        print(self.template_folder)
        if os.path.exists(self.template_folder):
            shutil.rmtree(self.template_folder)
    def test_app(self):
        """Test if the function returns a Flask app instance."""
        app = task_func(self.secret_key, self.template_folder)
        self.assertIsInstance(app, Flask, "The function should return a Flask app instance.")
            
    @patch('flask_login.LoginManager.init_app')
    def test_login_manager_initialization(self, mock_init_app):
        """Test if LoginManager is initialized within the function."""
        app = task_func(self.secret_key, self.template_folder)
        mock_init_app.assert_called_once_with(app)


# ── Vacant wrapper (generated by build_bank.py) ──────────────────────────
# Each check_* below runs exactly one TestCases method (with its setUp /
# tearDown) and raises AssertionError with a short message if it fails.
import unittest as _vacant_unittest

for _vacant_name in [_n for _n in list(globals()) if _n.startswith("check_")]:
    del globals()[_vacant_name]


def _vacant_short(tb_text, limit=700):
    lines = (tb_text or "").rstrip().splitlines()
    idx = [i for i, ln in enumerate(lines) if ln.startswith("  File ")]
    tail = lines[idx[-1] + 2:] if idx and idx[-1] + 2 < len(lines) else lines[-3:]
    tail = [ln for ln in tail if ln.strip() and set(ln.strip()) - set("^~")]
    msg = "\n".join(tail).strip()
    if len(msg) > limit:
        msg = msg[: limit // 2] + " ...[cut]... " + msg[-(limit // 2):]
    return msg


def _vacant_run(method_name):
    suite = _vacant_unittest.TestSuite([TestCases(method_name)])
    result = _vacant_unittest.TestResult()
    suite.run(result)
    if result.wasSuccessful() and result.testsRun == 1:
        return
    if result.failures:
        kind, tb = "FAIL", result.failures[0][1]
    elif result.errors:
        kind, tb = "ERROR", result.errors[0][1]
    elif result.unexpectedSuccesses:
        kind, tb = "UNEXPECTED SUCCESS", ""
    else:
        kind, tb = "NOT RUN", ""
    raise AssertionError("%s %s: %s" % (kind, method_name, _vacant_short(tb)))


def check_test_app():
    _vacant_run('test_app')

def check_test_login_manager_initialization():
    _vacant_run('test_login_manager_initialization')
