"""Hidden acceptance for s1_46_merge_spans — rendered data, do not hand-edit.

Generated by ops/gain/r535/build_bank.py from ops/gain/r535/tasks_s1.
Every check is zero-argument and passes by returning normally
(vacant_network/vrun/acceptance.py runs them in definition order).
"""


def check_01_merge_spans():
    from solution import merge_spans
    args = ([[1, 3], [2, 5]],)
    got = merge_spans(*args)
    want = [[1, 5]]
    assert got == want, "merge_spans args=%r got=%r want=%r" % (args, got, want)


def check_02_merge_spans():
    from solution import merge_spans
    args = ([[1, 2], [2, 3]],)
    got = merge_spans(*args)
    want = [[1, 3]]
    assert got == want, "merge_spans args=%r got=%r want=%r" % (args, got, want)


def check_03_merge_spans():
    from solution import merge_spans
    args = ([],)
    got = merge_spans(*args)
    want = []
    assert got == want, "merge_spans args=%r got=%r want=%r" % (args, got, want)


def check_04_merge_spans():
    from solution import merge_spans
    args = ([[1, 2]],)
    got = merge_spans(*args)
    want = [[1, 2]]
    assert got == want, "merge_spans args=%r got=%r want=%r" % (args, got, want)


def check_05_merge_spans():
    from solution import merge_spans
    args = ([[5, 6], [1, 2]],)
    got = merge_spans(*args)
    want = [[1, 2], [5, 6]]
    assert got == want, "merge_spans args=%r got=%r want=%r" % (args, got, want)


def check_06_merge_spans():
    from solution import merge_spans
    args = ([[1, 10], [2, 3]],)
    got = merge_spans(*args)
    want = [[1, 10]]
    assert got == want, "merge_spans args=%r got=%r want=%r" % (args, got, want)


def check_07_merge_spans():
    from solution import merge_spans
    args = ([[1, 2], [4, 5], [5, 7]],)
    got = merge_spans(*args)
    want = [[1, 2], [4, 7]]
    assert got == want, "merge_spans args=%r got=%r want=%r" % (args, got, want)
