"""Visible acceptance for s1_47_pairwise_diff — rendered data, do not hand-edit.

Generated by ops/gain/r535/build_bank.py from ops/gain/r535/tasks_s1.
Every check is zero-argument and passes by returning normally
(vacant/vrun/acceptance.py runs them in definition order).
"""


def check_01_pairwise_diff():
    from solution import pairwise_diff
    args = ([1, 4, 2],)
    got = pairwise_diff(*args)
    want = [3, -2]
    assert got == want, "pairwise_diff args=%r got=%r want=%r" % (args, got, want)


def check_02_pairwise_diff():
    from solution import pairwise_diff
    args = ([],)
    got = pairwise_diff(*args)
    want = []
    assert got == want, "pairwise_diff args=%r got=%r want=%r" % (args, got, want)
