"""Visible acceptance for s1_44_by_length — rendered data, do not hand-edit.

Generated by ops/gain/r535/build_bank.py from ops/gain/r535/tasks_s1.
Every check is zero-argument and passes by returning normally
(vacant_network/vrun/acceptance.py runs them in definition order).
"""


def check_01_by_length():
    from solution import by_length
    args = (['bbb', 'a', 'dd', 'cc'],)
    got = by_length(*args)
    want = ['a', 'dd', 'cc', 'bbb']
    assert got == want, "by_length args=%r got=%r want=%r" % (args, got, want)


def check_02_by_length():
    from solution import by_length
    args = ([],)
    got = by_length(*args)
    want = []
    assert got == want, "by_length args=%r got=%r want=%r" % (args, got, want)
