"""Visible checks for bcb_985 -- these ship with the task and can be run.

Rendered from bigcode/bigcodebench-hard v0.1.4 (BigCodeBench/985) by
ops/vacantrun/bcb_hard_bank_20260924/build_bank.py. The code below is the
dataset's unittest TestCases, restricted to the test methods that ship with
this task; each check_* runs one of those methods.
"""

from solution import *
import sys as _vacant_sys
import solution as _vacant_solution
_vacant_sys.modules.setdefault(__name__, _vacant_solution)

import unittest
import os
import json
import pandas as pd
import tempfile
class TestCases(unittest.TestCase):
    def setUp(self):
        self.temp_dir = tempfile.TemporaryDirectory()
        self.output_dir = self.temp_dir.name
    def tearDown(self):
        self.temp_dir.cleanup()
    def check_df_format(self, df):
        self.assertIsInstance(df, pd.DataFrame)
        self.assertTrue("Country" in df.columns)
        self.assertTrue("Population" in df.columns)
    def test_case_1(self):
        # Test basic case
        json_data = '{"Countries": {"USA": 331002651, "UK": 67886011}}'
        csv_file, df1 = task_func(json_data, self.output_dir)
        self.check_df_format(df1)
        self.assertTrue(os.path.exists(csv_file))
        df2 = pd.read_csv(csv_file)
        self.check_df_format(df2)
        pd.testing.assert_frame_equal(df1, df2)
        self.assertTrue(df1.shape[0] == 2)
        self.assertEqual(df1.loc[df1.Country == "USA", "Population"].item(), 331002651)
        self.assertEqual(df1.loc[df1.Country == "UK", "Population"].item(), 67886011)
    def test_case_2(self):
        # Test with empty json
        json_data = "{}"
        with self.assertRaises(ValueError):
            task_func(json_data, self.output_dir)
    def test_case_3(self):
        # Test incorrect JSON format
        with self.assertRaises(ValueError):
            task_func('{"WRONG": {"USA": 331002651, "UK": 67886011}}', self.output_dir)
        with self.assertRaises(ValueError):
            task_func('{"USA": 331002651, "UK": 67886011}', self.output_dir)
        with self.assertRaises(ValueError):
            task_func('{"Countries": {"USA": 331002651, "UK"', self.output_dir)


# ── Vacant wrapper (generated by build_bank.py) ──────────────────────────
# Each check_* below runs exactly one TestCases method (with its setUp /
# tearDown) and raises AssertionError with a short message if it fails.
import unittest as _vacant_unittest

for _vacant_name in [_n for _n in list(globals()) if _n.startswith("check_")]:
    del globals()[_vacant_name]


def _vacant_short(tb_text, limit=700):
    lines = (tb_text or "").rstrip().splitlines()
    idx = [i for i, ln in enumerate(lines) if ln.startswith("  File ")]
    tail = lines[idx[-1] + 2:] if idx and idx[-1] + 2 < len(lines) else lines[-3:]
    tail = [ln for ln in tail if ln.strip() and set(ln.strip()) - set("^~")]
    msg = "\n".join(tail).strip()
    if len(msg) > limit:
        msg = msg[: limit // 2] + " ...[cut]... " + msg[-(limit // 2):]
    return msg


def _vacant_run(method_name):
    suite = _vacant_unittest.TestSuite([TestCases(method_name)])
    result = _vacant_unittest.TestResult()
    suite.run(result)
    if result.wasSuccessful() and result.testsRun == 1:
        return
    if result.failures:
        kind, tb = "FAIL", result.failures[0][1]
    elif result.errors:
        kind, tb = "ERROR", result.errors[0][1]
    elif result.unexpectedSuccesses:
        kind, tb = "UNEXPECTED SUCCESS", ""
    else:
        kind, tb = "NOT RUN", ""
    raise AssertionError("%s %s: %s" % (kind, method_name, _vacant_short(tb)))


def check_test_case_1():
    _vacant_run('test_case_1')

def check_test_case_2():
    _vacant_run('test_case_2')

def check_test_case_3():
    _vacant_run('test_case_3')
