"""Visible acceptance for s2_07_median — rendered data, do not hand-edit.

Generated by ops/gain/r535/build_bank.py from ops/gain/r535/tasks_s2.
Every check is zero-argument and passes by returning normally
(vacant/vrun/acceptance.py runs them in definition order).
"""


def check_01_median():
    from solution import median
    args = ([4, 1, 3, 2],)
    got = median(*args)
    want = 2.5
    assert got == want, "median args=%r got=%r want=%r" % (args, got, want)


def check_02_median():
    from solution import median
    args = ([],)
    try:
        got = median(*args)
    except ValueError:
        return
    except Exception as exc:
        raise AssertionError("median args=%r got=%s(%s) want=ValueError" %
                             (args, type(exc).__name__, exc))
    raise AssertionError("median args=%r got=%r want=ValueError to be raised" %
                         (args, got))
