"""Visible checks for bcb_486 -- these ship with the task and can be run.

Rendered from bigcode/bigcodebench-hard v0.1.4 (BigCodeBench/486) by
ops/vacantrun/bcb_hard_bank_20260924/build_bank.py. The code below is the
dataset's unittest TestCases, restricted to the test methods that ship with
this task; each check_* runs one of those methods.
"""

from solution import *
import sys as _vacant_sys
import solution as _vacant_solution
_vacant_sys.modules.setdefault(__name__, _vacant_solution)

import unittest
import numpy as np
import matplotlib.pyplot as plt
class TestCases(unittest.TestCase):
    def setUp(self):
        self.default_start = 0
        self.default_end = 10000
        self.default_step = 100
        self.default_trend = 0.001
        self.default_seed = 42
    def test_case_1(self):
        ax = task_func(
            self.default_start, self.default_end, self.default_step, self.default_trend
        )
        self.assertIsInstance(ax, plt.Axes, "Returned object is not an Axes instance.")
        self.assertEqual(ax.get_xlabel(), "Time", "X-axis label is incorrect.")
        self.assertEqual(ax.get_ylabel(), "Value", "Y-axis label is incorrect.")
    def test_case_2(self):
        # Test with different seed for reproducibility
        ax1 = task_func(
            self.default_start,
            self.default_end,
            self.default_step,
            self.default_trend,
            seed=self.default_seed,
        )
        ax2 = task_func(
            self.default_start,
            self.default_end,
            self.default_step,
            self.default_trend,
            seed=self.default_seed,
        )
        self.assertTrue(
            np.array_equal(ax1.lines[0].get_ydata(), ax2.lines[0].get_ydata()),
            "Data is not reproducible with the same seed.",
        )
    def test_case_3(self):
        # Test with different seeds to ensure different results
        ax1 = task_func(
            self.default_start,
            self.default_end,
            self.default_step,
            self.default_trend,
            seed=self.default_seed,
        )
        ax2 = task_func(
            self.default_start,
            self.default_end,
            self.default_step,
            self.default_trend,
            seed=self.default_seed + 10,
        )
        self.assertFalse(
            np.array_equal(ax1.lines[0].get_ydata(), ax2.lines[0].get_ydata()),
            "Data is the same with different seeds.",
        )
    def tearDown(self):
        plt.close("all")


# ── Vacant wrapper (generated by build_bank.py) ──────────────────────────
# Each check_* below runs exactly one TestCases method (with its setUp /
# tearDown) and raises AssertionError with a short message if it fails.
import unittest as _vacant_unittest

for _vacant_name in [_n for _n in list(globals()) if _n.startswith("check_")]:
    del globals()[_vacant_name]


def _vacant_short(tb_text, limit=700):
    lines = (tb_text or "").rstrip().splitlines()
    idx = [i for i, ln in enumerate(lines) if ln.startswith("  File ")]
    tail = lines[idx[-1] + 2:] if idx and idx[-1] + 2 < len(lines) else lines[-3:]
    tail = [ln for ln in tail if ln.strip() and set(ln.strip()) - set("^~")]
    msg = "\n".join(tail).strip()
    if len(msg) > limit:
        msg = msg[: limit // 2] + " ...[cut]... " + msg[-(limit // 2):]
    return msg


def _vacant_run(method_name):
    suite = _vacant_unittest.TestSuite([TestCases(method_name)])
    result = _vacant_unittest.TestResult()
    suite.run(result)
    if result.wasSuccessful() and result.testsRun == 1:
        return
    if result.failures:
        kind, tb = "FAIL", result.failures[0][1]
    elif result.errors:
        kind, tb = "ERROR", result.errors[0][1]
    elif result.unexpectedSuccesses:
        kind, tb = "UNEXPECTED SUCCESS", ""
    else:
        kind, tb = "NOT RUN", ""
    raise AssertionError("%s %s: %s" % (kind, method_name, _vacant_short(tb)))


def check_test_case_1():
    _vacant_run('test_case_1')

def check_test_case_2():
    _vacant_run('test_case_2')

def check_test_case_3():
    _vacant_run('test_case_3')
