"""Visible checks for bcb_988 -- these ship with the task and can be run.

Rendered from bigcode/bigcodebench-hard v0.1.4 (BigCodeBench/988) by
ops/vacantrun/bcb_hard_bank_20260924/build_bank.py. The code below is the
dataset's unittest TestCases, restricted to the test methods that ship with
this task; each check_* runs one of those methods.
"""

from solution import *
import sys as _vacant_sys
import solution as _vacant_solution
_vacant_sys.modules.setdefault(__name__, _vacant_solution)

import unittest
from pathlib import Path
from tempfile import TemporaryDirectory
import os
class TestCases(unittest.TestCase):
    def setUp(self):
        self.temp_dir = TemporaryDirectory()
        self.test_dir = self.temp_dir.name
        self.fields = [
            "is_file",
            "is_dir",
            "has_special_chars",
            "has_numbers",
        ]
        self.is_file_fns = [
            "file",
            "file.txt",
            "file1.txt",
            "somefile",
        ]
        self.is_dir_fns = ["somedir", "aDirectory123"]
    def tearDown(self):
        self.temp_dir.cleanup()
    def helper_make_data(self, name, is_dir=False):
        # Helper function to make test files
        if is_dir:
            Path(os.path.join(self.test_dir, name)).mkdir()
        else:
            Path(os.path.join(self.test_dir, name)).touch()
    def helper_assert_predicate(self, results, predicates):
        # Helper to check only specified predicates are returned
        num_predicates = len(predicates)
        self.assertTrue(all(len(r) == num_predicates for r in results.values()))
        self.assertTrue(
            all(predicate in r for r in results.values() for predicate in predicates)
        )
    def test_dir_is_dir(self):
        field = "is_dir"
        for fn in self.is_dir_fns:
            self.helper_make_data(fn, is_dir=True)
        result = task_func(str(self.test_dir), [field])
        for fn in self.is_dir_fns:
            self.assertTrue(result[fn][field])
        self.helper_assert_predicate(result, [field])
    def test_dir_is_not_file(self):
        field = "is_file"
        for fn in self.is_dir_fns:
            self.helper_make_data(fn, is_dir=True)
        result = task_func(str(self.test_dir), [field])
        for fn in self.is_dir_fns:
            self.assertFalse(result[fn][field])
        self.helper_assert_predicate(result, [field])
    def test_deduplicate_predicates(self):
        fn = "test_file"
        self.helper_make_data(fn, is_dir=False)
        result = task_func(str(self.test_dir), ["is_file", "is_file"])
        self.assertTrue(len(result) == 1)
        self.helper_assert_predicate(result, ["is_file"])
    def test_empty_predicates(self):
        with self.assertRaises(ValueError):
            task_func(str(self.test_dir), [])


# ── Vacant wrapper (generated by build_bank.py) ──────────────────────────
# Each check_* below runs exactly one TestCases method (with its setUp /
# tearDown) and raises AssertionError with a short message if it fails.
import unittest as _vacant_unittest

for _vacant_name in [_n for _n in list(globals()) if _n.startswith("check_")]:
    del globals()[_vacant_name]


def _vacant_short(tb_text, limit=700):
    lines = (tb_text or "").rstrip().splitlines()
    idx = [i for i, ln in enumerate(lines) if ln.startswith("  File ")]
    tail = lines[idx[-1] + 2:] if idx and idx[-1] + 2 < len(lines) else lines[-3:]
    tail = [ln for ln in tail if ln.strip() and set(ln.strip()) - set("^~")]
    msg = "\n".join(tail).strip()
    if len(msg) > limit:
        msg = msg[: limit // 2] + " ...[cut]... " + msg[-(limit // 2):]
    return msg


def _vacant_run(method_name):
    suite = _vacant_unittest.TestSuite([TestCases(method_name)])
    result = _vacant_unittest.TestResult()
    suite.run(result)
    if result.wasSuccessful() and result.testsRun == 1:
        return
    if result.failures:
        kind, tb = "FAIL", result.failures[0][1]
    elif result.errors:
        kind, tb = "ERROR", result.errors[0][1]
    elif result.unexpectedSuccesses:
        kind, tb = "UNEXPECTED SUCCESS", ""
    else:
        kind, tb = "NOT RUN", ""
    raise AssertionError("%s %s: %s" % (kind, method_name, _vacant_short(tb)))


def check_test_deduplicate_predicates():
    _vacant_run('test_deduplicate_predicates')

def check_test_dir_is_dir():
    _vacant_run('test_dir_is_dir')

def check_test_dir_is_not_file():
    _vacant_run('test_dir_is_not_file')

def check_test_empty_predicates():
    _vacant_run('test_empty_predicates')
