"""Hidden acceptance for s2_37_column — rendered data, do not hand-edit.

Generated by ops/gain/r535/build_bank.py from ops/gain/r535/tasks_s2.
Every check is zero-argument and passes by returning normally
(vacant/vrun/acceptance.py runs them in definition order).
"""


def check_01_column():
    from solution import column
    args = ([{'a': 1}, {'b': 2}], 'a')
    got = column(*args)
    want = [1, None]
    assert got == want, "column args=%r got=%r want=%r" % (args, got, want)


def check_02_column():
    from solution import column
    args = ([], 'a')
    got = column(*args)
    want = []
    assert got == want, "column args=%r got=%r want=%r" % (args, got, want)


def check_03_column():
    from solution import column
    args = ([{'a': 1}], 'a')
    got = column(*args)
    want = [1]
    assert got == want, "column args=%r got=%r want=%r" % (args, got, want)


def check_04_column():
    from solution import column
    args = ([{}, {}], 'a')
    got = column(*args)
    want = [None, None]
    assert got == want, "column args=%r got=%r want=%r" % (args, got, want)


def check_05_column():
    from solution import column
    args = ([{'a': None}], 'a')
    got = column(*args)
    want = [None]
    assert got == want, "column args=%r got=%r want=%r" % (args, got, want)


def check_06_column():
    from solution import column
    args = ([{'a': 1}, {'a': 2}], 'a')
    got = column(*args)
    want = [1, 2]
    assert got == want, "column args=%r got=%r want=%r" % (args, got, want)


def check_07_column():
    from solution import column
    args = ([{'b': 1}], 'a')
    got = column(*args)
    want = [None]
    assert got == want, "column args=%r got=%r want=%r" % (args, got, want)
