"""Hidden acceptance for s1_07_flipwords — rendered data, do not hand-edit.

Generated by ops/gain/r535/build_bank.py from ops/gain/r535/tasks_s1.
Every check is zero-argument and passes by returning normally
(vacant_network/vrun/acceptance.py runs them in definition order).
"""


def check_01_flip_words():
    from solution import flip_words
    args = ('one two three',)
    got = flip_words(*args)
    want = 'three two one'
    assert got == want, "flip_words args=%r got=%r want=%r" % (args, got, want)


def check_02_flip_words():
    from solution import flip_words
    args = ('solo',)
    got = flip_words(*args)
    want = 'solo'
    assert got == want, "flip_words args=%r got=%r want=%r" % (args, got, want)


def check_03_flip_words():
    from solution import flip_words
    args = ('',)
    got = flip_words(*args)
    want = ''
    assert got == want, "flip_words args=%r got=%r want=%r" % (args, got, want)


def check_04_flip_words():
    from solution import flip_words
    args = ('a b',)
    got = flip_words(*args)
    want = 'b a'
    assert got == want, "flip_words args=%r got=%r want=%r" % (args, got, want)


def check_05_flip_words():
    from solution import flip_words
    args = ('the quick brown fox',)
    got = flip_words(*args)
    want = 'fox brown quick the'
    assert got == want, "flip_words args=%r got=%r want=%r" % (args, got, want)


def check_06_flip_words():
    from solution import flip_words
    args = ('  padded   words  ',)
    got = flip_words(*args)
    want = 'words padded'
    assert got == want, "flip_words args=%r got=%r want=%r" % (args, got, want)
