"""Scoring checks for lcb_3455 -- NOT part of any workspace.

⚠ 計分用的 GT。住在 hidden/ 這棵**另外的樹**，永遠不複製進 agent 的工作區；
  任何把它的內容（含失敗訊息）回饋給模型的路徑都作廢那一批資料。

case 組成 ＝ 題庫的 `visible_tests` ＋ `hidden_tests`（超集），與
vacant_network/codebench.py::LiveCodeBenchLoader 的 `hidden_check` 同一組（ops/gain/data/lcb_bank_v3.jsonl）。
"""

import solution

def _aeq(a, b):
    """與 vacant_network/codebench.py::_lcb_check_code 的 __aeq 同一套判等（逐行對應）。"""
    try:
        if a == b:
            return True
    except (TypeError, ValueError):
        pass
    if isinstance(a, bool) != isinstance(b, bool):
        return False
    if isinstance(a, (int, float)) and isinstance(b, (int, float)):
        return abs(a - b) <= 1e-6
    if isinstance(a, (list, tuple)) and isinstance(b, (list, tuple)):
        return len(a) == len(b) and all(_aeq(x, y) for x, y in zip(a, b))
    return a == b


def check_case_01():
    args = ['abaacbcbb']
    want = 5
    got = solution.minimumLength(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_02():
    args = ['aa']
    want = 2
    got = solution.minimumLength(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_03():
    args = ['egiormhb']
    want = 8
    got = solution.minimumLength(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_04():
    args = ['hqis']
    want = 4
    got = solution.minimumLength(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_05():
    args = ['rbibmq']
    want = 6
    got = solution.minimumLength(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_06():
    args = ['elahxtcber']
    want = 10
    got = solution.minimumLength(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_07():
    args = ['abacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabacabac']
    want = 6
    got = solution.minimumLength(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_08():
    args = ['jbqvvmop']
    want = 8
    got = solution.minimumLength(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_09():
    args = ['ywfxyqaahnzhkdbfrejefuqyxacnostdzmawnxxqpfhvdlifeahuikimkvmrtuetfoadguoyizqtlfzxvlbakbzntuxthmweag']
    want = 38
    got = solution.minimumLength(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_10():
    args = ['p']
    want = 1
    got = solution.minimumLength(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_11():
    args = ['cwsgaylvfnypmg']
    want = 14
    got = solution.minimumLength(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_12():
    args = ['lfkepqernb']
    want = 10
    got = solution.minimumLength(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_13():
    args = ['vujxdswylvqeyrclcewnrqmxsamjqndqbnlbcbxwbvhvakwnyryzuiofngumfqubfhyuuob']
    want = 35
    got = solution.minimumLength(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_14():
    args = ['vbllfac']
    want = 7
    got = solution.minimumLength(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_15():
    args = ['mfbrcmbq']
    want = 8
    got = solution.minimumLength(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_16():
    args = ['vyxjaoeykpmppzvsvawcnmyecfygfxwertydihwokysdybeueqjwupjcrescrehridcphiluobbaktdnmxdomywoxmsnzqxgheqoybdpdixbwbkjbmgmwhoogihjwggwvkoiuqtwsclmsddgggygycjqfapzqkfzyoaelyxamgiqdpilakokhhetayjsqtosdefrtqpbkunaqglfrqbvrumlfrtmbbqprwseevgoitbecyskcdynknzytaxerekaziesoynaxvisesmgpotgksgvbhmnbghvzwnurbobqdhpiwoanillbgnbwglapxuonfzbidgfjqeeqxixzyhgzrtbdzmwwtsqeqckangcnsfojdmwawotrncucapofzgbtutvmqwlcxihxbvlhsbnoazzvtnrxitheetamrxujytqdolmenetvtobvwjkfnnarvapnhvxswoyrleduljnrygxcwbjnhurzwuevzedvwhvzasbnkwcojlekksnokdyslkyxutobhoamnfcibqxokfmutysjezedzkxkguatkyoqhsbhkjzlcnnaphtppmrxftzwlxksapkwweyaiaofvdjyyzudhmcvxknywckfizfdrxuhyvfcukqlsokllbkciablgionxwqvordbayrxujrkespjpihxbsgajzlkwxicpfujfdfnwpspphqshsktpwlmwnjxrhqjmrghstvxhkqiuqdglvcshakfygtbwcjrtrzvlodmqnadosmusksylbufnjaxedahsrkeuzujkpohalurpkznnlzwxwlvrbzogzwiyuqekwxlotuwzyddvpqbbfwobclbdckhdtrapkdwskmuowqmiuuhytwptwbtejdouepqfovffxlsrqhntvqjvpcagumzpfamavawmnmmnvgobqiexoctwiaexvxxlazlhrnmflqpadlmhfomudfcxafksucszicowaaazdwrudnmcpdsdqorxvnppukdvnndtvblvbrphhezhebznzxudrtvaijzeffgggldruqkiliehdgoyxyryvdxeplfgheehbebhurdncrjqlgcfxxihwucenufxsgjzhtqeyveeijnqssgqeumujlvokgoxjyghnepybrmuesffbgxvuyfioxmwginkweovbzecmgtwppqwkysgzxxbqinkpxxgrmrdafscaenxljqbyzitiwyhelxtftyfovpmuuhggkbkhacbiuohimoadhbedrlaytfdzycfncfzloklluowkmgvdulmmyzbaiuvphyoovitdqnlvvysfvqgetqevitktbhbmmxuhlndegpbdqchxizccczkyfnvylsipuxwfemmuosljkugkucylawhgekuzahheqlkjsxmfexnmfvxbmyiedmrpyvamjiidpldnrzjtftvnlkokdpwgfjrrxjupwgecoghdgjrsskjudjtuvsxubxhmgreljxvdyhlrosfyyjrttcykyrltsdswapxwnhctghdvfcboonbipmxcfmadbtvtrdpeptqpwduqruzsqeqwciythhguhncqwxpprlfepyoavhmdjriswappkhvgnfiisgdrmeoepsjtppzyzatzahenrqujlwhsbcoxriilsjlxfwqsdmvhyrlelanmivmayvifnimppxkevrsbrayqipbsywdwaxsdgafvhqtmtqrnwkjqqhtryizhjuljyhiyajyoydopghzycxrcdmdwnhjwlozwvdoqpxtugmybddtaxruzsidiliazeltxysauskctmtesyqlrbganjvovohpehfwwiladaaluzeyuieyqkqxipjdsdlcuqssgqawxtjgkaaifyegmtbdfguwltleqquxrbpbjntbrjchbsbnfhrannuqmiqizwwveamwbnyshggqsflknmcxnmicvqpapazzyxsuudleoqnlevwhawrqnrhmpcolfarwdkgojniysqwkjnuvfxfqzewjxdsjzrbtpefxinpsrduuwxctatmcffcqjvfesyzvrfkpsmhogkypjyljqwquvreltpenjltkiwfmdnwzkmkaehgrftlgjqfkzywivjlcubpipcmqytmxzskavkdscwokminwjihsyntiootsizpnvmoyjfnrrwnyryxilicoseeeaqrwfqozzuiedadmyjzztufqtnmeoowcqscaskyoidttyznjnfjrftxtmvfybucxudflvsezdfwcqnmyqoajxyzhujeptkfefixyiafqobufutdrtnexgfjmnidrhtyrxjchdnopikkrxffhfgnixcaynmadyexdxojntoldhrqejqxrnmgyvlqmbfatvgpwyrhybjngjspqdsbjqkszusvpgygswwvmgeaktgquvqalclgcldmwaqvzycgwzkeapfdbnkigzzcekthnrcgmkqhfdbzkhtmuenusntujgicjydpdgoajyuoyjfnldwsskovenqtqydfsvydblevnjfwunllhwtpwfmaljgbktxoiqfjjmbmhlaoodxhfdoejgnopdziiqhrlvadjdchkwtbpwgvtgqxrmjuuxnsxfnlveonhadgjtjwdxbqdsltahodzdxaawvpujagnqiixveepiopzgnxxjjsdxylwcapopaithxluotdhqrvnuunwsegtsknxcakhjxluqvjsqrthvnelsnqcndmylnpktfwsxxmfqdkwackvgxwfdirbordnrvnehfnnujqminiaohfuvabmgeuikmveorxbhyckvyqmtucuastocdharzsytplkoopwihshyzyvhylnuvdacfuwlcnjdlkdqfcefjpfetaagfbnjetxqthcsgddqlksulggsuuohyuehzjxziokgqkhzdhfxlvnuezyujwimxohnftdayiyorkqefruhugkyndbanvygqnejnxokrugntynwdmiqcawnhtuhwlogpphvjjyjdjzfqyzhpznbslufnageuhlumnxtmacqghjfezeeswmvcrluxraiobqimawbipuodkdwbcylxlgraanbqzfnrfqerkbmfjxlbadgbljmrjnafoyyipxotcoeaoababrmiosdfotcrdvwkolzjerwehviezzhlmiaynrljtonqvxmhtonmfqvkyajysjosmtgggtncqzeowjbtceykxjzykwjlknynbsiqsyqeppuiarminylgbtcdjilrodsoocgeqzkoomcbarrmgoginxqadblqtxhzpaieicqjjhzdaqbdsqwjmarzjqsyfanglghrgukmazierhsepesaolixnshcituwvcxgcnkzbjmfyudkpizsldogeksvixykmnfpcvglrwevssvzxededoqjpzdjcamihkavjhelcsxuqncxhdpnoahgfhlrlmqhabxzhcecmawygepopscgrwmhwhvezxcyowhuhutktedtzhujxzmzdjccqfwvujkxtvieisoonmtvordnbqjlpvokrzsjaodsmjiixflzrknsdkodcvuqdzkvlapezicuvzlxlbltzareevdcoermthzbyowqnfqokmmqbdbdatgssxkukiuvzgihhtihjccikxamzhruodmtgribmnlffigzgocmdazvtxenszpbtnjfobzhcnoplwtqxzupvrfevkrgngszdoaytlaerrrwcupxyrsbbpnpojobiqhxnxdnuuxkctqyzkwdugluwabgllcyyqeuzwsffxxfnjutxrjbfwovjdgdyvblhyossujmkllyhpyyrkitkjhaprwsevcvlnalxnhgvtzqpxitbhopuqgtkfwbcqapqrvqcuimauolbjiozrffzmwthwyskxzxbkgvonjxidgqzutrbprunpncjpecjgewisvbdltedfszzbrizrevevovizyuplelyfcqcturjeotafwmaobwpebsoppmgxsxjtlnyppbpctxkqtodtdorrfhvaufxfhyragifqypywnfclqrwcvoyvsyvmmkrmiqescpurtjxrycdlrwakjktuffckisztrkilikusjpllorxpfuaaivavdywyktslcsdfhrypyaqallfuudnqihnnlqpxrzmzwoibxruqeiuyfipusfokieuqvdsrioriyoqzaczicxcjqegclnkjkhwrdrzouplzoooowikppheoknaumhxvfftrmrdpwtyyscujgnjmifdfjllucwkwuzjfcztipblhcnpjcuqdifcjhdqwzqgizawtwwyetebvxdphmekkuxoxyttxtvebjumemkcjpgubdfotjurcsrgwcvbzeotnwuxxhzzsphwygpalwbtafhribgnwfocjaqzjzljcexgagyhnuagjxcpshcnjyvkjkkzuocuzhvbpwvhsalvjxxzjnvjeovhkmxgbzkitnzunrcqmvwddjwdtzyphcwmhtqcuoeaairhoohqpngapfwhvbpvjwdbcybjumudxhmcqaojycohrhneqobziiynbvkhcbehgmsuscvjliqgvlljnbqtvxnoxddflvkdmpeeixbglgiaypoihsusiwvhrfhrvebgoimplntdgqrlpntoqrxybjzrxmzgdjlhzjuulmevorxmljzgvlvugthxlilpyvcccmpcjkdpaybsmeljqjebmoqmecgyymccxtjtgoalsbtahnejjzvkcdxmojoakgdggdlrykdszryddzukpqobeijpoqjyqoudpduxslxculydkviloxzctiwjylveisqdmikbadwnassqwybjbuwouioxlnaxeobnwgxovkkurprekkojhmtkmahrkpxxdcxunjuvgapotoszgkmawqemcwtqthcxbewqxqyokqgcykeqhvgzewjokrptzorhlaqwbmzmyujdtrairjjsjbtodzaejjzkifcadwvofwzpotozfhhhhfzotopzwfovwdacfikzjjeazdotbjsjjriartdjuymzmbwqalhroztprkojwezgvhqekycgqkoyqxqwebxchtqtwcmeqwamkgzsotopagvujnuxcdxxpkrhamktmhjokkerprukkvoxgwnboexanlxoiuowubjbywqssanwdabkimdqsievlyjwitczxolivkdylucxlsxudpduoqyjqopjieboqpkuzddyrzsdkyrldggdgkaojomxdckvzjjenhatbslaogtjtxccmyygcemqombejqjlemsbyapdkjcpmcccvyplilxhtguvlvgzjlmxrovemluujzhljdgzmxrzjbyxrqotnplrqgdtnlpmiogbevrhfrhvwisushiopyaiglgbxieepmdkvlfddxonxvtqbnjllvgqiljvcsusmghebchkvbnyiizboqenhrhocyjoaqcmhxdumujbycbdwjvpbvhwfpagnpqhoohriaaeoucqthmwchpyztdwjddwvmqcrnuzntikzbgxmkhvoejvnjzxxjvlashvwpbvhzucouzkkjkvyjnchspcxjgaunhygagxecjlzjzqajcofwngbirhfatbwlapgywhpszzhxxuwntoezbvcwgrscrujtofdbugpjckmemujbevtxttyxoxukkemhpdxvbeteywwtwazigqzwqdhjcfidqucjpnchlbpitzcfjzuwkwculljfdfimjngjucsyytwpdrmrtffvxhmuankoehppkiwoooozlpuozrdrwhkjknlcgeqjcxcizcazqoyiroirsdvqueikofsupifyuiequrxbiowzmzrxpqlnnhiqnduufllaqaypyrhfdsclstkywydvaviaaufpxrollpjsukilikrtzsikcffutkjkawrldcyrxjtrupcseqimrkmmvysvyovcwrqlcfnwypyqfigaryhfxfuavhfrrodtdotqkxtcpbppynltjxsxgmpposbepwboamwfatoejrutcqcfylelpuyzivoveverzirbzzsfdetldbvsiwegjcepjcnpnurpbrtuzqgdixjnovgkbxzxksywhtwmzffrzoijblouamiucqvrqpaqcbwfktgqupohbtixpqztvghnxlanlvcveswrpahjktikryyphyllkmjussoyhlbvydgdjvowfbjrxtujnfxxffswzueqyycllgbawulgudwkzyqtckxuundxnxhqibojopnpbbsryxpucwrrrealtyaodzsgngrkvefrvpuzxqtwlponchzbofjntbpzsnextvzadmcogzgifflnmbirgtmdourhzmaxkiccjhithhigzvuikukxssgtadbdbqmmkoqfnqwoybzhtmreocdveeraztlblxlzvucizepalvkzdquvcdokdsnkrzlfxiijmsdoajszrkovpljqbndrovtmnoosieivtxkjuvwfqccjdzmzxjuhztdetktuhuhwoycxzevhwhmwrgcspopegywamcechzxbahqmlrlhfghaonpdhxcnquxsclehjvakhimacjdzpjqodedexzvssvewrlgvcpfnmkyxivskegodlszipkduyfmjbzkncgxcvwutichsnxiloasepeshreizamkugrhglgnafysqjzramjwqsdbqadzhjjqcieiapzhxtqlbdaqxnigogmrrabcmookzqegcoosdorlijdctbglynimraiuppeqysqisbnynkljwkyzjxkyectbjwoezqcntgggtmsojsyjaykvqfmnothmxvqnotjlrnyaimlhzzeivhewrejzlokwvdrctofdsoimrbabaoaeoctoxpiyyofanjrmjlbgdablxjfmbkreqfrnfzqbnaarglxlycbwdkdoupibwamiqboiarxulrcvmwseezefjhgqcamtxnmulhueganfulsbnzphzyqfzjdjyjjvhppgolwhuthnwacqimdwnytngurkoxnjenqgyvnabdnykguhurfeqkroyiyadtfnhoxmiwjuyzeunvlxfhdzhkqgkoizxjzheuyhouusgglusklqddgschtqxtejnbfgaatefpjfecfqdkldjnclwufcadvunlyhvyzyhshiwpooklptyszrahdcotsaucutmqyvkcyhbxroevmkiuegmbavufhoainimqjunnfhenvrndrobridfwxgvkcawkdqfmxxswftkpnlymdncqnslenvhtrqsjvqulxjhkacxnkstgeswnuunvrqhdtoulxhtiapopacwlyxdsjjxxngzpoipeevxiiqngajupvwaaxdzdohatlsdqbxdwjtjgdahnoevlnfxsnxuujmrxqgtvgwpbtwkhcdjdavlrhqiizdpongjeodfhxdooalhmbmjjfqioxtkbgjlamfwptwhllnuwfjnvelbdyvsfdyqtqnevoksswdlnfjyouyjaogdpdyjcigjutnsuneumthkzbdfhqkmgcrnhtkeczzgiknbdfpaekzwgcyzvqawmdlcglclaqvuqgtkaegmvwwsgygpvsuzskqjbsdqpsjgnjbyhrywpgvtafbmqlvygmnrxqjeqrhdlotnjoxdxeydamnyacxingfhffxrkkipondhcjxrythrdinmjfgxentrdtufuboqfaiyxifefktpejuhzyxjaoqymnqcwfdzesvlfduxcubyfvmtxtfrjfnjnzyttdioyksacsqcwooemntqfutzzjymdadeiuzzoqfwrqaeeesocilixyrynwrrnfjyomvnpzistooitnyshijwnimkowcsdkvakszxmtyqmcpipbucljviwyzkfqjgltfrgheakmkzwndmfwiktljneptlervuqwqjlyjpykgohmspkfrvzysefvjqcffcmtatcxwuudrspnixfeptbrzjsdxjwezqfxfvunjkwqsyinjogkdwraflocpmhrnqrwahwvelnqoelduusxyzzapapqvcimnxcmnklfsqgghsynbwmaevwwziqimqunnarhfnbsbhcjrbtnjbpbrxuqqeltlwugfdbtmgeyfiaakgjtxwaqgssqucldsdjpixqkqyeiuyezulaadaliwwfhephovovjnagbrlqysetmtcksuasyxtlezailidiszurxatddbymgutxpqodvwzolwjhnwdmdcrxcyzhgpodyoyjayihyjlujhziyrthqqjkwnrqtmtqhvfagdsxawdwysbpiqyarbsrvekxppminfivyamvimnalelryhvmdsqwfxljsliirxocbshwljuqrnehaztazyzpptjspeoemrdgsiifngvhkppawsirjdmhvaoypeflrppxwqcnhughhtyicwqeqszurqudwpqtpepdrtvtbdamfcxmpibnoobcfvdhgtchnwxpawsdstlrykycttrjyyfsorlhydvxjlergmhxbuxsvutjdujkssrjgdhgocegwpujxrrjfgwpdkoklnvtftjzrndlpdiijmavyprmdeiymbxvfmnxefmxsjklqehhazukeghwalycukgukjlsoummefwxupislyvnfykzccczixhcqdbpgednlhuxmmbhbtktiveqtegqvfsyvvlnqdtivooyhpvuiabzymmludvgmkwoullkolzfcnfcyzdftyalrdebhdaomihouibcahkbkgghuumpvofytftxlehywitizybqjlxneacsfadrmrgxxpkniqbxxzgsykwqppwtgmcezbvoewknigwmxoifyuvxgbffseumrbypenhgyjxogkovljumueqgssqnjieevyeqthzjgsxfunecuwhixxfcglqjrcndruhbebheehgflpexdvyryxyogdheilikqurdlgggffezjiavtrduxznzbehzehhprbvlbvtdnnvdkuppnvxroqdsdpcmndurwdzaaawocizscuskfaxcfdumofhmldapqlfmnrhlzalxxvxeaiwtcoxeiqbogvnmmnmwavamafpzmugacpvjqvtnhqrslxffvofqpeuodjetbwtpwtyhuuimqwoumkswdkpartdhkcdblcbowfbbqpvddyzwutolxwkequyiwzgozbrvlwxwzlnnzkprulahopkjuzuekrshadexajnfublysksumsodanqmdolvzrtrjcwbtgyfkahscvlgdquiqkhxvtshgrmjqhrxjnwmlwptkshsqhppspwnfdfjufpcixwklzjagsbxhipjpsekrjuxryabdrovqwxnoiglbaickbllkoslqkucfvyhuxrdfzifkcwynkxvcmhduzyyjdvfoaiayewwkpaskxlwztfxrmppthpannclzjkhbshqoyktaugkxkzdezejsytumfkoxqbicfnmaohbotuxyklsydkonskkeljocwknbsazvhwvdezveuwzruhnjbwcxgyrnjludelryowsxvhnpavrannfkjwvbotvtenemlodqtyjuxrmateehtixrntvzzaonbshlvbxhixclwqmvtutbgzfopacucnrtowawmdjofsncgnakcqeqstwwmzdbtrzghyzxixqeeqjfgdibzfnouxpalgwbngbllinaowiphdqbobrunwzvhgbnmhbvgskgtopgmsesivxanyoseizakerexatyznknydcksycebtiogveeswrpqbbmtrflmurvbqrflgqanukbpqtrfedsotqsjyatehhkokalipdqigmaxyleaoyzfkqzpafqjcygygggddsmlcswtquiokvwggwjhigoohwmgmbjkbwbxidpdbyoqehgxqznsmxowymodxmndtkabboulihpcdirhercsercjpuwjqeuebydsykowhidytrewxfgyfceymncwavsvzppmpkyeoajxyv']
    want = 52
    got = solution.minimumLength(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_17():
    args = ['hdoofrpnzlgbiuhwokkhjecubwztsjfuhzjczdiervhfkrdulycywvczjfhlilnxeocotbydjnzuftbtspjlacblaodqyeobxvzffopoouvaysxgqhrayhwzqgsvrwmqhfjpohzscezigjfbmlrnislrhleqlfiatvtkkbiznisirmsdfuqvfjdbbnjkzavxusyzetgpkrvsitizyrqpuvfbdacfhcqkorstcrbenlgoigosdzmjkrqtrzlujpvidxjxcumkwqbemdhxqcwfjrhdolijoxomtfflvhvcgsdbtqmevdqaxpicswefiedkpajjbmkrjficyindlmzydbqtdcsbxqivasznhsdiugfgiilofslzwipzxencfxtytejhvogocuzbclfemzhcffiaxynvphyifejmqdvgfrymgbclfycyjitzctkggxcwcdkepkjpuouegyvlilidanksdapietozjxdhbqexoaqrhkknnygrdgvwqqaizmetfodrfikwzaebjxdlfkjuqyoiunxfnzdjuogsruwpubofjswrsqtbkljyysadziwtaxxxwjosqddgiujjwlpcvqfexbpwjnygipxpvsjkxwbmpuadfeteygosjgcyrnvpyutxqrthxjrcipbwkorzcmddtyilrcoixnvlcexhbpdfmzczgqsbcknylczgrrmezhmdogljwzrdgfxcktjwhouoeaujlwdkmracgtmgawuwykffphssvzygbivoaxreyjnqcgublnwtpappzdtwyhvuhejdhzfivefsgblxyqtanfnsvqoplwddmevkifmevfvktjzgqwbnhjfeqokcphwhzxuxzighoosiifmdemividouwoicoskagcqvrsliirwrbnxiwgxtmdukwixuxrsoxduflybrhrxlpczvtuprzuwrolojqbbemvcbyzdgokulzaggguvcwdxjympglrogxuorhgeqtkqkyaznseycpczyrfcyfwdhvsntwrsmmxavlghadmekptpmmexdyzgxuxifyqltmruamdhdyuyocxfejqbwdkqqkzwaxawksbbqmgpbqooxqlhxeirvrcaghvkgmkktgdgzryacxcvarrkujghajigoilxtmslgfsjsusykbfpcsfgojieecylmibunzpyvprtjslwqnvnvcrlfbppwrzpligwvjbkwjkkvbzqimobphkmivmzygfdelvvkwpovdpprqmnvkhfcbwqyezvpeezjtqovllzblejgxftxdtcxqekwlcfbnjghtmubsghodpzvbrlgyhqjtebdjdxqmroszhjbgahtwzkwfpgxckemfzudxptoeyxivaifvdfcqxtdmtsdnbxxpqapxfxyqgeinzqhqmczifagtaqourzllkapspskmzuknfenjbwtwxybpeqmfqortmwothyznreqcwjenxqhbchdpbovcvqztaxukrzhsqgmsgdlzmlfapyujseqkgyxcvhaolowtccwzioxevypwosazmhunvdmvlmzxshorochfuetorfgfaptjsxzebcchzmihsbnjaxqyzlmnvbsxsclyedhghgdzfxqzyzuxxsevagsdeucadonwnwvexvkqwdviakxhyesvbnfjrmeqgwvzonpyyfamjuagyleeivhtjtpfgwpbsgwjulbrthcolujrdamnpqomidnpyelfnekzzwhducbibjeuhfkniahbxvihyulqfrcqpnxxxbyeckjzevhmetsqmvtuzdxbzfcqbeeivjeequlwcrjaxvhmgbjbgmxbfcjvdwoztgnclauwfriykkwchsjvgzkbdsarvlmyjcyovkffowlimyhxkopxldrfdrxgmyjgcabvcldcobxneqkwsaqmaxemyyjqujuddxmqybplakfmaptenuvhdtkbayerlxjcogqiksrzdpraqilibppqlfguoghotureymgksoynzshhlvlgiwtosqxbumbevvmzlqagclxsadylwjankguikiuuchccezcbnddocugpwzfpjlpdaysbtvcubtfyufirhkhfievbgfdstpgftockqpiauizjwabzhmpzxrntbjumjnlhakgyeewfygmmfhyidjknsiseagxbpggbapnzodkjdhtugpdgvvojlzkdtiakvegoiuuvivzlynrrawpsjkaqfeyoekcqrotcogtgoczrzajnshpkofonvgacijootdwgnkcvnqlpzmbxscjemtodhvalpxnylobstkdttftxivtdumjebboqdtxbuipyumerfodjhqarbpwlfryhkthytplkvftmydizcbmuvmpwishehholrqnzwniutnglowfqfazvklonkcngatzngsutftqlmlrtcsvvpnelpkeggyuzshgkhvervrorxinovcyqeozfqjiuooiybhsamgitmdfmkjmiiwfqbdxlccalmtzbtsoyfhqksgcgmsennrhrcklmqclomjctubsieyubskmxaycvtrbmmchysgikykpetxxjpmkxkhxkcstqoelbrlkmqovsgcnagulxyivgrtcqtyykeaxgdjrpolazdfvvsgqginduytswynjfayqhguiyqejdmxnawrepcpxvncyjbqlsqqoofuwsacyzfdaarqjnnjoukegfoxrzmzfrbzpjutgnfdakajoemjtcfmgrvfukuimagtoeusxnwwmsrlqxojhptdegwkehqcaeiwyjzseoegfnehzdgqubdwwzjppvjkoorfupvwfwfhynrxvacsdddmfxfcyfvvhvuzkipunnffzvrgstcdxqboldienvbmwhkgyvtvjtqsrrexiimwpemoskkdfwkiaoaamgzqhejgjetusphahcrqfzrvnpfxesfcegwvqlgifgynuukivcunqgcflrfkfngktblanwngrbjoewbzvginlndtjacptovrepslhpsvlxbveccdlwxcufbrggqlnrzflgwyvogdbshvaguinbshrecraiyosfhrrhwytilrjmjricpxnphdgfieqxpnhltogfgbnawhaifqvgefgnwfqfsjugsqljchnwvyocwxijgkladcjwfvhowwxkjnbalmuxprywcbaczpafxcqabqrjhltdxvntvxjsupdawuxrtyurhwmpywfcquoqxmvgrbxtgjzlmgzjpnnjqskvlyrfvueusdvbxwysyqukcrsrcesrllzveadqkujnnzdjyiwwgrfamqidsiogmjsyqncdkomkygsnrzxeswoqviyytjjlggfecklomfuyixjasseilaehklkrnabyidjtylevcizsfdkkyjjqxkcxjhjowjhetxuawefmtvudhmukjqmqemseyvpmfurhizysuxssllbvgxqrsfcwcamvinmrmqzmptqhflkysiemvatspwxsffecgwwlfehwvjzgwtklyixvuqglfixmagpwgzowdsbyiyvlnfjdleakmoultngoavvclljwovemhwnhzdieiicgumsgxjknmuqgkjkarhjvfbvujvyjmrtsariukbkdugqtrqsqbqsfjsxcyxwufwobgrblcshlhcrszqvnmdbmoqilbtokcexkrovxpxbysikhgwrayoszkjrrjlzhyxvhjhcpefnlxjexjcktxhmrliwvwxqecqfmxekhwhhnyuobilkhpbgdgwfbbgkezmmbybrykjyswavemqnofzmhfufoyevceiwbskpuihjujejsabiceghaeuengotipmaxaxlhowtkfgmbrzatjxoramsfpptzpstbysrtrhuqbdfykrzxtfeoalutrhawotmscdxughvpmaalctngieyfuracgypuqoediefgnaydzvhkrmzjxrjpvnhtseflijryqcfqvlcvwkgocooyeugbtheuhummknmsgchvfsbrjvpdzhyjtflltatretrrjxrcfaheofponghdzvmdoukpwpsbfpbycaudavvjnmceooqrnmnxytnmsrklmmlobfsjbfnmdxxninfixxpkcondwjkuixrkyobbnblfpoasbtcuktqblswyjlrljlfjzctmqmojliwusbcpzmovpmudiizdqlobjjxfsylnoglycqpcakqaoelqoxmqgookkyuxauhmlrqjzpotyxlxarfudvqubdkwkdikyyzchyrdbgmgppjfxtmhiiupbetsggxcjgpcvscpltqtuqduqqflvyqhqlrxkmigqktimqujvcdjnoxqcowmqujmkuavedabexvwpmjipxvjajtdjxfichgnontztanmziiupfvbtrcxxciqqnxhxheyakzhcuwzmermclnxdyxspelfzsgrlmtgszuoturutzvbsfzoyvpnovztrmidpkpzqcuykmbdvliqwzetvmokomrbmmrsleftqfpgqsowkvchhebfxmtldezfqwtqtgrfeyewjnzdciswcrnyvaaztnafyqmqpqjvdxdmnxqxotukhhvrmdskqygtrrfbbtuzvgvyrngsewiqxdgrsmrjjcsihftvchuljztazwcpdiokmjxhmbgnsynmctgcvygvauoaeqzofjljeychffpthbdmfdfehplkhbuawuphygkfghrilmojzdrzbmolxrnjgdhgclnhshgngebdgtugyewrtsyhzwdznuqluvezfhzymhdphzsdwumxsrahjatzmcnfxgcofrfpeuxrkgubwfhqlhedgvxxjkutdvcgwpkshqdyjzdmqyebhnszibcpaaleyemolusxaijdofpdnawulgobejfdcupubjthdhhpvguzudzylhphdqnrehstravlwkjvuqbilwpmjuqfmlzdjqmqucuaowrnhktbyvsmymzhmqdcfffpadggrzozlpygkiwpttfkctvpodpkwwitibtrdawykoflczvwcmxfvcgcmuyrhxzppgozqfnhibqmecrlkgiortqewglhttfknfimysdxrdrjafdtphiwpxjjvytzwipwsuueglflwozwgixtdpunnhyvoadpedklvjurcbrcqrrwgshgmmcszcwqcdivvdvggpelplsodapemqpzhiqigfadybxwsfxgzymabchfxzcqnybkdmntoacneruabhisnmartibjtcharcnaubykquouxsabzicurawsuiwudmfxpuxvecjcwojjfnueyshtduzqmnchyieqzqwmgdiwbghtvndconlpqmymhcxgunqpzadmnegemglrppjrutzofxlvnbhxaorzbynmfqjajlxlknniqvythyvomnefnsvuahnvysaxxoykuqycwsleeuwjbsncnnqynnkuxerzrgiwltydlnkmjyavbaajlucfukepkcjfootcxfxcoxzhakgeuxhclwvvkgvfcxiwcmbbijsptzxdkpwywlbzogshphupmtgvmbrwwkxhxplagscmledreeklojewcyrgnxwfrmkqhsfcqoovjdqmkxhvdcasdczuyaekyhhfxyqbazmtvnafvihjlllyhkpwvmawlwxxfxijtgmvcmtxfsmnbwllkgpnabodwnsdwyvsqhstghyoflatdixlgnyudmievnpuyfowzxksueiitoeocbivlhofiwgwyzqmavlqqqpqwhqbvkcqvwriwwcucmfzzkkdxejscmekemnxizpljxfvkremhzxmgrkhjwfkfjaidbfgqtkamhfhwuhybfuovgzycqglxwjetijzpyxipeqoyhtrgtcmwfakpfmbnzyzlvjpqfuqntdnjmzupbfrdzxbzwmxtvbuggmcinmojsbxtfzqofwunqoamfvcmngxfrwhbtojdlhthvrittijjmhhjdchsgxznfzovuuktcvddlumdjbzqpiwrfultuewowmyyowltsxqlzewdljkrqnqqnqwguhbuyzjybwtjrqbnkbwfslxnpjuitkcqwtmbtvvbnfkfxoldnxeejyapojjdydwumpvxwnskvxxwavhiiarfaylctudstskmjylvhlrrhaniqkrdtczcscbuenmlmxdmftfeliktivfjgtbqvldivvmcafuyypiaerrdhrwbpwkmzhrysefkhnkasdegvvuvoboqzctrywcjwtzrwfjfnrhnwnvubpknsfmdsmmfxyvezrjibqhffbaffjnfnhbqydwavqknhwzduekucmamikvndydctrvulsevoupznyyiqhptudjbbgmliwgayrhilhxzdqjuwcunsswwkiwqtbdklyswsyyqdgmxhoofkyadmipuxfnmknazsyqbvcyalqdonzpcxtjlwxtmmnhtvrfriqnlgsyqhqmwuswucyidfup']
    want = 35
    got = solution.minimumLength(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_18():
    args = ['aaabaaacaaadaaaeaaa']
    want = 5
    got = solution.minimumLength(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_19():
    args = ['mahoupiuedabprruwuhloovzysgavofjgginulfnvmjattmnvgyzxumvnmrctidtwskbcnpfuvscvcdduhgspoekffzwcvfacegdxfcxzyoqhadmtvbeummlgxxjktgvsuqrzbmpmryybrjkopqqzkdxwnpbsppznpvivriekylgrrjsfpklswbnzrcuvqnaghzntvcnspapkoargybovndzutpdhzxnwoipsglbtaagqevefmzejuydwrneskyluadsfmicizzbwccfqlfntlvpoeccifiugaopoeldsqvgsojgnyenohrcjxjsvtscceovreuhdivknuqpdtmuqgwecxyibsoiqkrhwgxaospfmftstxwaeooklvbnpfgasndqfejpgyyjwbosgyamifznzuodlyzmiuagksttslsndgeiomnkgbyajddqejcgqttynbspbodyxrlatedejxxogepuwbbnkimgidtdmthascwizxzmstaajxavracmfzussrjmngoivvpkdauttedfvoifjqttiqxoijropfyotwpuvslfgvopudojnpmbeaacaasxfxehmzgeaoaeroigsbjipebuujpnhrfqhmwxdfledakgqyitncuycfxnwwmiglxerwltinnrvskwnsfaemipsajrixbjrxmwxusaoegukxapyyyrrbmhiizbpelsudbhhtedqcjajcdeojowuzpfrlexpnixfphjgxhwfmmlrmawvhzzruykyrouqfwdvtdynhkbdwjyviotozsgpkbtpwosthahedrkdaqjoimrwngsslkdpjddktytqigyhkvyyeqvotordezvzlphifyubnlobbugwxlemggnxufrueagndbxxqsrfkfpnmjcuqwqjnzqqolqygpbdirsgypekinzevqdfsgjgviyu']
    want = 41
    got = solution.minimumLength(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_20():
    args = ['ihalapnqdhpvwfhdebgczuxosehoanuicqygbzhupcumexvbzlowieqqgeomcjrcwozqvwgzlelayhfyyrmfcthgokbmuwsxwfjr']
    want = 40
    got = solution.minimumLength(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_21():
    args = ['waoji']
    want = 5
    got = solution.minimumLength(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_22():
    args = ['hq']
    want = 2
    got = solution.minimumLength(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_23():
    args = ['dzka']
    want = 4
    got = solution.minimumLength(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_24():
    args = ['ublbabkqhbnanaiavxbjvggixovrlytgpypvzqgrzoynvlvfrlbxbnqkkmqumkcbrexjjbgmjhugyozupghqkyeerrabygqacybwyvyquqpjhdzbzrvqacvokwjtyqiqsllqckmtujdsmkaxprwuupdypvfjieuzisdhbpotgjjldldspwtlwizagcquhpgxiopfbjoxljrywsstrnsrizgfyaumhjrwabgeyfuyazjlxcsdrfcehjrhknjlgnsataezsnrbypllmmsgkjshfqaxwijufzseehalkpvlleqreezhgrwkrdxiljnxabedblepmxglcsfbaswknrzpchsxixbabnohxwxoibjstawgzgngqklsyxhndxrvvyfofgsiexngsehnohuhykwzsywukejngwaoyrpnqrhbinachjrmmeyzrtcanthfkrozlxxqffhcrgrxrweigdurvikumpgjabluxbnempqmsfevujizrlalojtnrohopmvmboujchduxhcblxbgihqncwmfhmwgxvpxgmipcwxghpcgyddpiegssgthjdjizfebqupattbiuznpsxkzaqovwmkytjfjgznphsgidpzurlkyknscmvlsgpgsdruoqjbhnttfhhqpwytdzrzvcgqgrlrviosezxkvrusxglcbmtcjtlqvrapfmrurkkpxixaibjicqboypftvmjdiofwftpflfjyyzhjxejowrjvtsgeszdincqdsrfxlkdlkgrnptrngxcegnotbaqgpvvgvzyltyhysanwkkzoteovhtlhbjpbtxogvusbhwiblutyylbtnukvdokefetqntnqgdbfheyrwahkkdgcrhwrvrapeqyuerbsuozrovrqabsbibehoipgccmrixmhjasuswmyiriljpiqscdvouxdzdcdewednxrasfqmsddjrvyxytmtgyjofftsycripmqvqubiyazmqirajcvllxfgspsahewsrrvvjxrospiwayvrwutdaoixdgdrldrkedezloqtkxhzaedmpwmlvqyaefmitsmvnjkpvqugmrjohdnnyovfwwxegpfgflczoqsvaveseydqomnjzhoeqvxwvckarvfvwnnndstrfapgcvyuanuestqgiwibaxyagzoexoeatanbjsamsirhtptkaqsjexlyxmtwcpnoymravofafwkzicwwqmoaxrriezwfonepqywixmjwtgmrowdkdijppjsqmhzmdwsgdyrgqnwkyquocjqmmaksdlzllcygjpwjqswgwqfczhtabqfijlwsiekhqplqphpwhogxhzimrtqfpujtosuwdkccwouklmxmmatlxsmhccmdumrjvinkqioeethhcmnrpfggswkkbqvdcacxjuyxfooatwzqkpaclhpynwyusjoufjvpbjvnzfbwrhlsnjnrmvtbhqaavxzaiudgvzcgqabjtpufrlcfxmgcttcffdsegltajinkcyivrbfatklxxpyrvfhaygjtscuzyflzayxhjhzpwbbltsjsulbzoukalamxnwcfecgqtlilcpgkboiabdsnvkvjuhowoqhxpcezzqljnydlstsnaipdbledennalnnjyplzbjfohanernlswqoxspqfbzoghajuyddcydogxtlwolyirnpzeuumcbhhouzsjrpwcyfjvuyvswxpsemyvfctpfaqrspbyefjsdutuftdejcynmpyreszxhprdpojvlrqguvwchxhwlwfknvlqkbvasrqwcppmartvcvdrzxjksmyguxjpawmfybutwsqsnaaboaoekyncefqdfliqamvmdxbkyddzzqwhggshedkfdjetqyzzgxeblyqgoafnqtfcbomoxulmenwalnhzyxaehxjxwzsgiemtuwlcktkwfmtucpmhwjcfwiezvocudhnnqguxkwbgrtwncnhzjaqhzfkaffmfclbpimwgaettviszlpwqlvqakztabnemkiiqlelnjmwhzythlgvwjlphgtfqwdxibwkyrjjialnkeyzpcgwyucaikmpffznjovyvruskmmmdnbjjhgpwiqwlxmuuswrqfcnntdvabohlatncqavujxhvmefgbutrbgmsywwpojlkomqsqsbzkmjsoouabkiwnkzfozrkcwfzlssngifsqwzvaogiiahcbkhcbjdusgyqweumctnbqdqwczuoyytqqdpldanexwefkrzobejnsfcwvbiwlignoyzraqzqpwvskotfyfqjunesdyaotcnqpclrqluxgcsixxnvxctmzibtmtmcqdlzyxkmozixfpjdoqgfhrxctqmeiqnzowyrqeffoxszoafxqbrsyndgsgicxskfecakvfllwslarnkluhtnzmykpgdmrjcortlvdblxrnczcwtriluguywpulalmjezizhjrssagkoavanmuvtxthxiqlxmtxbnlofwqziafkznspbbzvqfhqbaztugyokhbqtngahmbaeubiusqzqaebpyaugpsmhwjlmcsbpzxqfgdbjxsxqdounznobbbxwqohvszhetjeibrjkgdxulpgizupkjtvycgpvoetytllaxkgeuazblirylwkjaixqfrjfpvenzynwkfmiwfnglopkfmfbxjqsoioevswcumnvglmyohrpgxwvlyvpyjwumbnummjioforkbrwhcikzcvdfphuqddewyyssvuahvjmipyilxdimxuwocmdtfokatvjvhfjtdiazgffrlmepjgmzkvjrqfxgwjubcfnlsmmxfmvrlkpsuaiusmvdhmeenielragjhtuoslgtrvhvheiqpdxgttvyhialabnyhtnnemxrpdyqkzlofrstservwmezxgywnrbdoycbdjqtahxsupfizzbznyucufsjpkznsomajgxriftierrvpgxfoypudefjuyvwhgkpjgpdxymsfokctxydidvagngtjfnhgrfsswwrbtlkogbxhdhvvgsypjqogskbjgdzuqjjzibuunjddakvkbwojohvawtkqdoodqzhfxozkvaztozinueramhlldkrrhtpaihexriwbqmykpoqenwvrvxyqtncngstogvswhpxublveiukextfqdwltutzikvllphrnhnipfvtgghzlzosnstyiquuqdwtobwplgsjlpoemnnaragmqrvpqntwjfgislwwilrdbgovddfeabkxdubxgpdwgvztvbwfvdfekumdyotutgzgujhbzwqtubicsyzsejrnfdgdumjcfohtsvlqpzwiyhybvpbjahvkiqkgmrqwlvvyyoqyaoofjefklmkfohsnrletbpezgtudkshslislqjbwqwxcjcovttyxzcikjxcdplrpjexaedpvrzbibhobwxsesyilsjtukgvyifskaislzolartfmvviwqvplevbaqpteputcioixyvojxlqfwnojhdmodmcljbfzjrnrpzrbubriqitdkrkulwxefqzwludzntlkpzlwqgukrrmtfdcasacabjeuopchexucrpolimesbzrlgzecpdquuwhjwbnymzbrtafgddoavuvrajcseoejaxbbcovxetdomvabgeoucnxyjstfrlualpqpkhvkpfnzsqidahefpfxyqbrpezxrkaptcainoakrhedpsbzhhhjeyorvcnmtmbhefqwncwpdeenaqiphovewyozaxwluxtitcgtaijpqmnxbofuydexikpnqrcmysqtfceqfzvtcnzopfvexvmdnewabeqsxepmgiozoomvoiopokuruqsiucnsyihlgfnavnqczanpzynxonmydddkwrybystomznhtojdejdzukrypvyvlbaqtgcvqdxuzqkrxxzjnsnmbwzubldeouwoqmtqdvosyssapnhnvcljzeqretrhwufwykraefbrkxmtuvubvtahvpbvgoksulqddnmbrqychrgqzumutmumdfkmhrskmyyxmmvsbnmhlugcgywqfozrgquholqxyaswayzoyyyzbzlxitvgouhdnkxyeajdsghqpzqjeiujaczjcqtbuufsypvquettmhwxckzqtmmwxdjadpskkoujaqyrshpvlxvzycodoluhzbujtfxjsgrabeewjmbjteyywdrtqgimawuvshbquudhgozmtsuhlimdulimquxhekzzjyhbhfphkgwrzuadihlbosjvtwonpbtuolljxptalsskpvyjtfrdgyyrqdocpwxzhdhxatbqcbaiqwgzfhytslajokpadzjvetvbjtkulsrflvxzxbawozhmgfeapbpdpkzbxsvckpcyxjffqfjiwkmnwzhprtkxujfzrmutcljyrqnqcqqokufensvdttrypgfmxinqbjqtypasykjunxxwesdaegyoaidlyyxtajiojavkwqavgppprcerzlzbllkwrejvufqewrprorvrvbehikadlhlgkbqhlffustrmcoookgvlrdammcsojohxtzowshgyrwsxojenzdpbrscudwuvanjaiqiuczqbrvfacfpoputugtwtzheedbnufrxkdgscqzejyzgqvebrmydnevndecoljmxslgujwspnxvpcimgqdqbuzmdkwglbqhzdvphazhvhcuhqskxfsrhmivcrcradecddjtqpipuztknjpzqhkmuutxtcvosrsjavntzsgrfxjibhxqwuunqftdwfluytxbrxwxkfvrzfnrranhxebypozhfprojedrzcmhydpskvdswuaxuuoobtunforsaklchgigzgwnbsqmatlbyjdjavobtgnayrepyuyrdrwjrtieopteoxcwfzvhjnyqbsmuunjwkixvpskdxwispxanekfoirbcooicfgqvrvbufpbgidvzelcyhrmsvwtdrlinimblmgofigzvgqvogtnhljovopsyxmjxbasmliuzlkzeedcqhnuieshgwujybklutkpipqagicntnebpmgladrocauobnxdzurbczuemzuwyeopxgppqpqhefunbxzcmospmjxruizfnlxzvmlvallujsunvpdkjxyrhqcpapdrksrmlkwwurvysituougkvxhpmbkcvsemqywzdscdzsyioqhqixtsldruoxhhetwiziqmuzmhryzwfrqepyspzvmavjftifzlxrukwbyjqqjtespbfvwwpwmznkclfrfjpfquuibyxiatypapsitzixozyaujonvjopgkoclsfhyvgqpgiurshurdmxvhwybbqsrurtupkdcdsjqurntipdosxpfabbpkfnqijtirhoxcazbjftampktbpkjjcmapmbkabrjrejmrakiveevujpogthhgqhkohcofxjkyxcktguwfotfvhakepbbqpilbeuopgknxxbllzpltfqcejlxdtnezwapvmjgwmfyxziygamhtelxwpqivkeylnzcqabmcqdbvkpyivkyswyzoksrsqomuupsehsrywcattmzrruvhavnsfxtrbiaedhsvaqopfpzrttvnositgpsetxkchsbdrlqhqetndgmvxgwzfxteethobwpfwoliymnnpxundihtzbrazlocovizbvbwpucckjttbwzxxtmyhbkyiyhfogdsttzsgpsngqhawjrxcosgwqysyafpyvzbcgoioesiwbmtscdpvvqqdopjnmtoiwkfxawbgooetsjacbgpfnunqdbxaqsdyvpkvuqytmlibpfnajzmyzqlsyuaimvhkltimlstbdpdnqozzhxqzynumlinfwjgelwjwsgyvsedwyiaeqfmqpmytfxsmlyjbztitsedttbldxqijnuolrmmlqaaafvrlhidkwhgfbdrrwnmttuqarfhzoipxwkspiqbgfykbtdidhmdpirgjdzyreawazzgrffuvppfyuhqqqquoftngeanpwymuvtjaelwetkkfujifwjoliaqsgyptgecywpgyargxspitvwrfmatnffdbbohdsilyqevgojlzvcynsndemhfihxcuyguvdaypciomkexfvqzdlgxykcellbbfrauzmdijphgwyhltaosauvrpgqwecrjiwnsnbxjbltnysymufwymkpuvttcrwrswgmzzhbovnjgijqpdcxgxgpupiazwvpldajaobluaeuvyuxsbvrdaadoizzzjbtmtmrchlrvmtokeyqnwfyypvfipcukazsnivrwahkuybxmfvylpyvmmftfmzezkfctzwjpjxtiazpxtihcgypahtcfdetecqchybcvbehzikdiuudegwnuxikx']
    want = 44
    got = solution.minimumLength(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)

