"""Visible checks for bcb_593 -- these ship with the task and can be run.

Rendered from bigcode/bigcodebench-hard v0.1.4 (BigCodeBench/593) by
ops/vacantrun/bcb_hard_bank_20260924/build_bank.py. The code below is the
dataset's unittest TestCases, restricted to the test methods that ship with
this task; each check_* runs one of those methods.
"""

from solution import *
import sys as _vacant_sys
import solution as _vacant_solution
_vacant_sys.modules.setdefault(__name__, _vacant_solution)

import unittest
from unittest.mock import patch
import shutil
FILE_PATH = os.path.join(OUTPUT_DIR, 'traffic_data.csv')
class TestCases(unittest.TestCase):
    def setUp(self):
        """Set up the environment for testing."""
        if not os.path.exists(OUTPUT_DIR):
            os.makedirs(OUTPUT_DIR)
    def tearDown(self):
        """Clean up any files created during the tests."""
        # Check and remove the expected file if it exists
        # if os.path.exists(FILE_PATH):
        #     os.remove(FILE_PATH)
        if os.path.exists(OUTPUT_DIR):
            shutil.rmtree(OUTPUT_DIR)
    @patch('matplotlib.pyplot.show')  # Mock plt.show to not render plots
    @patch('csv.writer')  # Mock csv.writer to not actually write files
    @patch('pandas.read_csv')  # Mock pd.read_csv to not read from disk
    @patch(__name__ + '.randint', return_value=25)  # Mock randint to return a fixed value
    def test_dataframe_content(self, mock_randint, mock_read_csv, mock_csv_writer, mock_plt_show):
        mock_read_csv.return_value = pd.DataFrame({
            'Time': ['2021-01-01 00:00:00.000000'],
            'Car': [25], 'Bus': [25], 'Truck': [25], 'Bike': [25]
        })
        file_path, ax = task_func(1)
        self.assertEqual(file_path, FILE_PATH)
        mock_randint.assert_called()  # Ensures randint was called, but not specifics about calls
        mock_read_csv.assert_called_with(FILE_PATH)
        mock_plt_show.assert_called()
    @patch('os.makedirs')
    @patch('os.path.exists', return_value=False)
    def test_directory_creation(self, mock_path_exists, mock_makedirs):
        """Ensure directory is created if it does not exist."""
        if os.path.exists(OUTPUT_DIR):
            shutil.rmtree(OUTPUT_DIR)
        task_func(1)
        mock_makedirs.assert_called_with(os.path.dirname(FILE_PATH))


# ── Vacant wrapper (generated by build_bank.py) ──────────────────────────
# Each check_* below runs exactly one TestCases method (with its setUp /
# tearDown) and raises AssertionError with a short message if it fails.
import unittest as _vacant_unittest

for _vacant_name in [_n for _n in list(globals()) if _n.startswith("check_")]:
    del globals()[_vacant_name]


def _vacant_short(tb_text, limit=700):
    lines = (tb_text or "").rstrip().splitlines()
    idx = [i for i, ln in enumerate(lines) if ln.startswith("  File ")]
    tail = lines[idx[-1] + 2:] if idx and idx[-1] + 2 < len(lines) else lines[-3:]
    tail = [ln for ln in tail if ln.strip() and set(ln.strip()) - set("^~")]
    msg = "\n".join(tail).strip()
    if len(msg) > limit:
        msg = msg[: limit // 2] + " ...[cut]... " + msg[-(limit // 2):]
    return msg


def _vacant_run(method_name):
    suite = _vacant_unittest.TestSuite([TestCases(method_name)])
    result = _vacant_unittest.TestResult()
    suite.run(result)
    if result.wasSuccessful() and result.testsRun == 1:
        return
    if result.failures:
        kind, tb = "FAIL", result.failures[0][1]
    elif result.errors:
        kind, tb = "ERROR", result.errors[0][1]
    elif result.unexpectedSuccesses:
        kind, tb = "UNEXPECTED SUCCESS", ""
    else:
        kind, tb = "NOT RUN", ""
    raise AssertionError("%s %s: %s" % (kind, method_name, _vacant_short(tb)))


def check_test_dataframe_content():
    _vacant_run('test_dataframe_content')

def check_test_directory_creation():
    _vacant_run('test_directory_creation')
