"""Visible acceptance for s1_50_ends — rendered data, do not hand-edit.

Generated by ops/gain/r535/build_bank.py from ops/gain/r535/tasks_s1.
Every check is zero-argument and passes by returning normally
(vacant_network/vrun/acceptance.py runs them in definition order).
"""


def check_01_ends():
    from solution import ends
    args = ([1, 2, 3],)
    got = ends(*args)
    want = {'first': 1, 'last': 3}
    assert got == want, "ends args=%r got=%r want=%r" % (args, got, want)


def check_02_ends():
    from solution import ends
    args = (['only'],)
    got = ends(*args)
    want = {'first': 'only', 'last': 'only'}
    assert got == want, "ends args=%r got=%r want=%r" % (args, got, want)
