"""Visible checks for bcb_916 -- these ship with the task and can be run.

Rendered from bigcode/bigcodebench-hard v0.1.4 (BigCodeBench/916) by
ops/vacantrun/bcb_hard_bank_20260924/build_bank.py. The code below is the
dataset's unittest TestCases, restricted to the test methods that ship with
this task; each check_* runs one of those methods.
"""

from solution import *
import sys as _vacant_sys
import solution as _vacant_solution
_vacant_sys.modules.setdefault(__name__, _vacant_solution)

import unittest
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
# Assuming the function task_func is defined in the same script, otherwise import it appropriately.
class TestCases(unittest.TestCase):
    
    def test_case_1(self):
        df = pd.DataFrame({
            'closing_price': [100, 101, 102, 103, 104, 150]
        })
        boxplot_ax, histplot_ax = task_func(df)
        
        self.assertIsInstance(boxplot_ax, plt.Axes)
        self.assertIsInstance(histplot_ax, plt.Axes)
        
        self.assertEqual(boxplot_ax.get_title(), 'Box Plot of Closing Prices')
        self.assertEqual(histplot_ax.get_title(), 'Histogram of Closing Prices')
        
        self.assertEqual(histplot_ax.get_xlabel(), 'closing_price')
        self.assertIn('Count', histplot_ax.get_ylabel())  # Check if 'Count' is part of the ylabel
            
    def test_empty_df(self):
        df = pd.DataFrame({'closing_price': []})
        boxplot_ax, histplot_ax = task_func(df)
        
        self.assertIsInstance(boxplot_ax, plt.Axes)
        self.assertIsInstance(histplot_ax, plt.Axes)
        # Instead of checking if the plot "has data," we ensure that it exists and does not raise an error.
        self.assertIsNotNone(boxplot_ax, "Boxplot should be created even with empty data.")
        self.assertIsNotNone(histplot_ax, "Histogram should be created even with empty data.")


# ── Vacant wrapper (generated by build_bank.py) ──────────────────────────
# Each check_* below runs exactly one TestCases method (with its setUp /
# tearDown) and raises AssertionError with a short message if it fails.
import unittest as _vacant_unittest

for _vacant_name in [_n for _n in list(globals()) if _n.startswith("check_")]:
    del globals()[_vacant_name]


def _vacant_short(tb_text, limit=700):
    lines = (tb_text or "").rstrip().splitlines()
    idx = [i for i, ln in enumerate(lines) if ln.startswith("  File ")]
    tail = lines[idx[-1] + 2:] if idx and idx[-1] + 2 < len(lines) else lines[-3:]
    tail = [ln for ln in tail if ln.strip() and set(ln.strip()) - set("^~")]
    msg = "\n".join(tail).strip()
    if len(msg) > limit:
        msg = msg[: limit // 2] + " ...[cut]... " + msg[-(limit // 2):]
    return msg


def _vacant_run(method_name):
    suite = _vacant_unittest.TestSuite([TestCases(method_name)])
    result = _vacant_unittest.TestResult()
    suite.run(result)
    if result.wasSuccessful() and result.testsRun == 1:
        return
    if result.failures:
        kind, tb = "FAIL", result.failures[0][1]
    elif result.errors:
        kind, tb = "ERROR", result.errors[0][1]
    elif result.unexpectedSuccesses:
        kind, tb = "UNEXPECTED SUCCESS", ""
    else:
        kind, tb = "NOT RUN", ""
    raise AssertionError("%s %s: %s" % (kind, method_name, _vacant_short(tb)))


def check_test_case_1():
    _vacant_run('test_case_1')

def check_test_empty_df():
    _vacant_run('test_empty_df')
