"""Hidden acceptance for s2_16_size_label — rendered data, do not hand-edit.

Generated by ops/gain/r535/build_bank.py from ops/gain/r535/tasks_s2.
Every check is zero-argument and passes by returning normally
(vacant/vrun/acceptance.py runs them in definition order).
"""


def check_01_size_label():
    from solution import size_label
    args = (1536,)
    got = size_label(*args)
    want = '1.5 KB'
    assert got == want, "size_label args=%r got=%r want=%r" % (args, got, want)


def check_02_size_label():
    from solution import size_label
    args = (512,)
    got = size_label(*args)
    want = '512 B'
    assert got == want, "size_label args=%r got=%r want=%r" % (args, got, want)


def check_03_size_label():
    from solution import size_label
    args = (1023,)
    got = size_label(*args)
    want = '1023 B'
    assert got == want, "size_label args=%r got=%r want=%r" % (args, got, want)


def check_04_size_label():
    from solution import size_label
    args = (0,)
    got = size_label(*args)
    want = '0 B'
    assert got == want, "size_label args=%r got=%r want=%r" % (args, got, want)


def check_05_size_label():
    from solution import size_label
    args = (1024,)
    got = size_label(*args)
    want = '1.0 KB'
    assert got == want, "size_label args=%r got=%r want=%r" % (args, got, want)


def check_06_size_label():
    from solution import size_label
    args = (1048576,)
    got = size_label(*args)
    want = '1.0 MB'
    assert got == want, "size_label args=%r got=%r want=%r" % (args, got, want)


def check_07_size_label():
    from solution import size_label
    args = (1610612736,)
    got = size_label(*args)
    want = '1.5 GB'
    assert got == want, "size_label args=%r got=%r want=%r" % (args, got, want)


def check_08_size_label():
    from solution import size_label
    args = (2048,)
    got = size_label(*args)
    want = '2.0 KB'
    assert got == want, "size_label args=%r got=%r want=%r" % (args, got, want)
