"""Scoring checks for bcb_374 -- NOT part of any workspace.

This file lives in a separate tree and is never copied into an agent's
workspace. It runs every test method of the dataset's TestCases
(bigcode/bigcodebench-hard v0.1.4, BigCodeBench/374): the visible ones plus the rest.
"""

from solution import *
import sys as _vacant_sys
import solution as _vacant_solution
_vacant_sys.modules.setdefault(__name__, _vacant_solution)

import unittest
import os
import shutil
from openpyxl import load_workbook, Workbook
import doctest
import tempfile
class TestCases(unittest.TestCase):
    def setUp(self):
        self.base_tmp_dir = tempfile.mkdtemp()
        self.test_directory = f"{self.base_tmp_dir}/test/"
        os.makedirs(self.test_directory, exist_ok=True)
        # Mock data for Excel files
        file_data = [
            {
                "filename": "file1.xlsx",
                "sheets": {
                    "Sheet1": [
                        ["Hello", "World", "This is a \"test\" string."],
                        ["Another", "Row with \"quotes\"", "And \"more\" quotes."]
                    ]
                }
            },
            {
                "filename": "file2.xlsx",
                "sheets": {
                    "Sheet1": [
                        ["Just a", "Normal row.", "Nothing special."],
                        ["Another", "normal row.", "Still nothing special."]
                    ],
                    "Sheet2": [
                        ["Sheet2 data.", "Another \"quoted\" string.", "End of row."]
                    ]
                }
            },
            {
                "filename": "file3.xlsx",
                "sheets": {
                    "Sheet1": [
                        ["A simple", "row without", "any quotes."]
                    ]
                }
            }
        ]
        # Create the Excel files based on the mock data
        for file_info in file_data:
            workbook = Workbook()
            workbook.remove(workbook.active)  # Remove default sheet
            for sheet_name, rows in file_info["sheets"].items():
                sheet = workbook.create_sheet(title=sheet_name)
                for row in rows:
                    sheet.append(row)
            workbook.save(
                filename=os.path.join(self.test_directory, file_info["filename"]))
    def tearDown(self):
        # Remove the test directory
        if os.path.exists(self.test_directory):
            shutil.rmtree(self.test_directory)
    def test_case_1(self):
        # Process the mock Excel files
        processed_files_count = task_func(directory_path=self.test_directory)
        # Check the number of processed files
        self.assertEqual(processed_files_count, 3)
        # Check the content of file1.xlsx
        workbook = load_workbook(
            filename=os.path.join(self.test_directory, "file1.xlsx"))
        sheet = workbook.active
        self.assertEqual(sheet.cell(row=1, column=3).value,
                         'This is a \\"test\\" string.')
        self.assertEqual(sheet.cell(row=2, column=2).value, 'Row with \\"quotes\\"')
        self.assertEqual(sheet.cell(row=2, column=3).value, 'And \\"more\\" quotes.')
    def test_case_2(self):
        # Check the content of file2.xlsx
        workbook = load_workbook(
            filename=os.path.join(self.test_directory, "file2.xlsx"))
        sheet1 = workbook["Sheet1"]
        self.assertEqual(sheet1.cell(row=1, column=1).value, 'Just a')
        sheet2 = workbook["Sheet2"]
        self.assertEqual(sheet2.cell(row=1, column=2).value,
                         "Another \"quoted\" string.")
    def test_case_3(self):
        # Check the content of file3.xlsx
        workbook = load_workbook(
            filename=os.path.join(self.test_directory, "file3.xlsx"))
        sheet = workbook.active
        self.assertEqual(sheet.cell(row=1, column=1).value, 'A simple')
    def test_case_4(self):
        # Test with a directory that doesn't exist
        with self.assertRaises(FileNotFoundError):
            task_func(directory_path="/invalid/directory/")
    def test_case_5(self):
        # Test with a directory that contains no .xlsx files
        os.makedirs(f"{self.test_directory}/empty_directory/", exist_ok=True)
        processed_files_count = task_func(
            directory_path=f"{self.test_directory}/empty_directory/")
        self.assertEqual(processed_files_count, 0)


# ── Vacant wrapper (generated by build_bank.py) ──────────────────────────
# Each check_* below runs exactly one TestCases method (with its setUp /
# tearDown) and raises AssertionError with a short message if it fails.
import unittest as _vacant_unittest

for _vacant_name in [_n for _n in list(globals()) if _n.startswith("check_")]:
    del globals()[_vacant_name]


def _vacant_short(tb_text, limit=700):
    lines = (tb_text or "").rstrip().splitlines()
    idx = [i for i, ln in enumerate(lines) if ln.startswith("  File ")]
    tail = lines[idx[-1] + 2:] if idx and idx[-1] + 2 < len(lines) else lines[-3:]
    tail = [ln for ln in tail if ln.strip() and set(ln.strip()) - set("^~")]
    msg = "\n".join(tail).strip()
    if len(msg) > limit:
        msg = msg[: limit // 2] + " ...[cut]... " + msg[-(limit // 2):]
    return msg


def _vacant_run(method_name):
    suite = _vacant_unittest.TestSuite([TestCases(method_name)])
    result = _vacant_unittest.TestResult()
    suite.run(result)
    if result.wasSuccessful() and result.testsRun == 1:
        return
    if result.failures:
        kind, tb = "FAIL", result.failures[0][1]
    elif result.errors:
        kind, tb = "ERROR", result.errors[0][1]
    elif result.unexpectedSuccesses:
        kind, tb = "UNEXPECTED SUCCESS", ""
    else:
        kind, tb = "NOT RUN", ""
    raise AssertionError("%s %s: %s" % (kind, method_name, _vacant_short(tb)))


def check_test_case_1():
    _vacant_run('test_case_1')

def check_test_case_2():
    _vacant_run('test_case_2')

def check_test_case_3():
    _vacant_run('test_case_3')

def check_test_case_4():
    _vacant_run('test_case_4')

def check_test_case_5():
    _vacant_run('test_case_5')
