"""Hidden acceptance for s2_28_parse_kv — rendered data, do not hand-edit.

Generated by ops/gain/r535/build_bank.py from ops/gain/r535/tasks_s2.
Every check is zero-argument and passes by returning normally
(vacant/vrun/acceptance.py runs them in definition order).
"""


def check_01_parse_kv():
    from solution import parse_kv
    args = ('a=1;a=2',)
    got = parse_kv(*args)
    want = {'a': '2'}
    assert got == want, "parse_kv args=%r got=%r want=%r" % (args, got, want)


def check_02_parse_kv():
    from solution import parse_kv
    args = ('bare',)
    try:
        got = parse_kv(*args)
    except ValueError:
        return
    except Exception as exc:
        raise AssertionError("parse_kv args=%r got=%s(%s) want=ValueError" %
                             (args, type(exc).__name__, exc))
    raise AssertionError("parse_kv args=%r got=%r want=ValueError to be raised" %
                         (args, got))


def check_03_parse_kv():
    from solution import parse_kv
    args = ('',)
    got = parse_kv(*args)
    want = {}
    assert got == want, "parse_kv args=%r got=%r want=%r" % (args, got, want)


def check_04_parse_kv():
    from solution import parse_kv
    args = ('x=',)
    got = parse_kv(*args)
    want = {'x': ''}
    assert got == want, "parse_kv args=%r got=%r want=%r" % (args, got, want)


def check_05_parse_kv():
    from solution import parse_kv
    args = (' a = 1 ',)
    got = parse_kv(*args)
    want = {'a': '1'}
    assert got == want, "parse_kv args=%r got=%r want=%r" % (args, got, want)


def check_06_parse_kv():
    from solution import parse_kv
    args = ('a=1;b=2',)
    got = parse_kv(*args)
    want = {'a': '1', 'b': '2'}
    assert got == want, "parse_kv args=%r got=%r want=%r" % (args, got, want)


def check_07_parse_kv():
    from solution import parse_kv
    args = ('a=1;;b=2',)
    got = parse_kv(*args)
    want = {'a': '1', 'b': '2'}
    assert got == want, "parse_kv args=%r got=%r want=%r" % (args, got, want)


def check_08_parse_kv():
    from solution import parse_kv
    args = ('a=1;b',)
    try:
        got = parse_kv(*args)
    except ValueError:
        return
    except Exception as exc:
        raise AssertionError("parse_kv args=%r got=%s(%s) want=ValueError" %
                             (args, type(exc).__name__, exc))
    raise AssertionError("parse_kv args=%r got=%r want=ValueError to be raised" %
                         (args, got))
