"""Visible checks for bcb_592 -- these ship with the task and can be run.

Rendered from bigcode/bigcodebench-hard v0.1.4 (BigCodeBench/592) by
ops/vacantrun/bcb_hard_bank_20260924/build_bank.py. The code below is the
dataset's unittest TestCases, restricted to the test methods that ship with
this task; each check_* runs one of those methods.
"""

from solution import *
import sys as _vacant_sys
import solution as _vacant_solution
_vacant_sys.modules.setdefault(__name__, _vacant_solution)

import unittest
import os
import shutil
FILE_PATH = os.path.join(OUTPUT_DIR, 'sensor_data.csv')
class TestCases(unittest.TestCase):
    def tearDown(self):
        """Clean up any files created during the tests."""
        # Check and remove the expected file if it exists
        # if os.path.exists(FILE_PATH):
        #     os.remove(FILE_PATH)
        if os.path.exists(OUTPUT_DIR):
            shutil.rmtree(OUTPUT_DIR)
    def test_csv_file_creation(self):
        """Test if the CSV file is successfully created."""
        task_func(1)
        self.assertTrue(os.path.exists(FILE_PATH))
    def test_csv_file_header(self):
        """Test if the CSV file header matches the expected sensors."""
        task_func(0)
        with open(FILE_PATH, 'r') as f:
            reader = csv.reader(f)
            header = next(reader)
            self.assertEqual(header, ['Time', 'Temperature', 'Humidity', 'Pressure'])


# ── Vacant wrapper (generated by build_bank.py) ──────────────────────────
# Each check_* below runs exactly one TestCases method (with its setUp /
# tearDown) and raises AssertionError with a short message if it fails.
import unittest as _vacant_unittest

for _vacant_name in [_n for _n in list(globals()) if _n.startswith("check_")]:
    del globals()[_vacant_name]


def _vacant_short(tb_text, limit=700):
    lines = (tb_text or "").rstrip().splitlines()
    idx = [i for i, ln in enumerate(lines) if ln.startswith("  File ")]
    tail = lines[idx[-1] + 2:] if idx and idx[-1] + 2 < len(lines) else lines[-3:]
    tail = [ln for ln in tail if ln.strip() and set(ln.strip()) - set("^~")]
    msg = "\n".join(tail).strip()
    if len(msg) > limit:
        msg = msg[: limit // 2] + " ...[cut]... " + msg[-(limit // 2):]
    return msg


def _vacant_run(method_name):
    suite = _vacant_unittest.TestSuite([TestCases(method_name)])
    result = _vacant_unittest.TestResult()
    suite.run(result)
    if result.wasSuccessful() and result.testsRun == 1:
        return
    if result.failures:
        kind, tb = "FAIL", result.failures[0][1]
    elif result.errors:
        kind, tb = "ERROR", result.errors[0][1]
    elif result.unexpectedSuccesses:
        kind, tb = "UNEXPECTED SUCCESS", ""
    else:
        kind, tb = "NOT RUN", ""
    raise AssertionError("%s %s: %s" % (kind, method_name, _vacant_short(tb)))


def check_test_csv_file_creation():
    _vacant_run('test_csv_file_creation')

def check_test_csv_file_header():
    _vacant_run('test_csv_file_header')
