"""Scoring checks for bcb_93 -- NOT part of any workspace.

This file lives in a separate tree and is never copied into an agent's
workspace. It runs every test method of the dataset's TestCases
(bigcode/bigcodebench-hard v0.1.4, BigCodeBench/93): the visible ones plus the rest.
"""

from solution import *
import sys as _vacant_sys
import solution as _vacant_solution
_vacant_sys.modules.setdefault(__name__, _vacant_solution)

import unittest
import pandas as pd
import numpy as np
class TestCases(unittest.TestCase):
    def setUp(self):
        self.data = pd.DataFrame({
            'Column1': np.random.rand(10),
            'Column2': np.random.rand(10)
        })
    def test_transformed_data_shape(self):
        transformed_data, _ = task_func(self.data, 2)
        self.assertEqual(transformed_data.shape, (10, 2))
    def test_invalid_n_components(self):
        with self.assertRaises(ValueError):
            task_func(self.data, 0)
    def test_invalid_n_components_type(self):
        with self.assertRaises(ValueError):
            task_func(self.data, "two")
    def test_plot_axes(self):
        _, ax = task_func(self.data, 2)
        self.assertEqual(len(ax.collections), 1)  # One scatter plot
    def test_values(self):
        np.random.seed(42)
        transformed_data, _ = task_func(self.data, 2)
        df_list = transformed_data.apply(lambda row: ','.join(row.values.astype(str)), axis=1).tolist()
        # with open('df_contents.txt', 'w') as file:
        #     file.write(str(df_list))
        # Convert string pairs to list of tuples of floats
        expect = ['-0.36270132751314693,-0.17330242962071069', '0.7073025303719391,0.12382897836601565', '0.45378164000836924,0.1734575007991456', '-0.06806713223200053,-0.18707071063291186', '-0.41150042971259093,0.09384691859758798', '-0.4104362188060755,0.09501439103733277', '-0.3990216926714853,0.2501208456858351', '0.34082913981297874,-0.14263963596803247', '0.08412503285413396,-0.028734567486117184', '0.06568845788787812,-0.20452129077814485']
        # self.assertEqual(df_list, expect, "DataFrame contents should match the expected output")
        df_tuples = [tuple(map(float, item.split(','))) for item in df_list]
        expect_tuples = [tuple(map(float, item.split(','))) for item in expect]
        # Assert each pair of tuples is approximately equal
        for actual, expected in zip(df_tuples, expect_tuples):
            try:
                self.assertAlmostEqual(actual[0], expected[0], places=7, msg="DataFrame contents should match the expected output")
                self.assertAlmostEqual(actual[1], expected[1], places=7, msg="DataFrame contents should match the expected output")
            except:
                self.assertAlmostEqual(actual[0], -expected[0], places=7, msg="DataFrame contents should match the expected output")
                self.assertAlmostEqual(actual[1], -expected[1], places=7, msg="DataFrame contents should match the expected output")


# ── Vacant wrapper (generated by build_bank.py) ──────────────────────────
# Each check_* below runs exactly one TestCases method (with its setUp /
# tearDown) and raises AssertionError with a short message if it fails.
import unittest as _vacant_unittest

for _vacant_name in [_n for _n in list(globals()) if _n.startswith("check_")]:
    del globals()[_vacant_name]


def _vacant_short(tb_text, limit=700):
    lines = (tb_text or "").rstrip().splitlines()
    idx = [i for i, ln in enumerate(lines) if ln.startswith("  File ")]
    tail = lines[idx[-1] + 2:] if idx and idx[-1] + 2 < len(lines) else lines[-3:]
    tail = [ln for ln in tail if ln.strip() and set(ln.strip()) - set("^~")]
    msg = "\n".join(tail).strip()
    if len(msg) > limit:
        msg = msg[: limit // 2] + " ...[cut]... " + msg[-(limit // 2):]
    return msg


def _vacant_run(method_name):
    suite = _vacant_unittest.TestSuite([TestCases(method_name)])
    result = _vacant_unittest.TestResult()
    suite.run(result)
    if result.wasSuccessful() and result.testsRun == 1:
        return
    if result.failures:
        kind, tb = "FAIL", result.failures[0][1]
    elif result.errors:
        kind, tb = "ERROR", result.errors[0][1]
    elif result.unexpectedSuccesses:
        kind, tb = "UNEXPECTED SUCCESS", ""
    else:
        kind, tb = "NOT RUN", ""
    raise AssertionError("%s %s: %s" % (kind, method_name, _vacant_short(tb)))


def check_test_invalid_n_components():
    _vacant_run('test_invalid_n_components')

def check_test_invalid_n_components_type():
    _vacant_run('test_invalid_n_components_type')

def check_test_plot_axes():
    _vacant_run('test_plot_axes')

def check_test_transformed_data_shape():
    _vacant_run('test_transformed_data_shape')

def check_test_values():
    _vacant_run('test_values')
