"""Visible acceptance for s2_29_rle — rendered data, do not hand-edit.

Generated by ops/gain/r535/build_bank.py from ops/gain/r535/tasks_s2.
Every check is zero-argument and passes by returning normally
(vacant/vrun/acceptance.py runs them in definition order).
"""


def check_01_rle():
    from solution import rle
    args = ('aab',)
    got = rle(*args)
    want = [('a', 2), ('b', 1)]
    assert got == want, "rle args=%r got=%r want=%r" % (args, got, want)


def check_02_rle():
    from solution import rle
    args = ('',)
    got = rle(*args)
    want = []
    assert got == want, "rle args=%r got=%r want=%r" % (args, got, want)
