"""Hidden acceptance for s2_07_median — rendered data, do not hand-edit.

Generated by ops/gain/r535/build_bank.py from ops/gain/r535/tasks_s2.
Every check is zero-argument and passes by returning normally
(vacant/vrun/acceptance.py runs them in definition order).
"""


def check_01_median():
    from solution import median
    args = ([4, 1, 3, 2],)
    got = median(*args)
    want = 2.5
    assert got == want, "median args=%r got=%r want=%r" % (args, got, want)


def check_02_median():
    from solution import median
    args = ([],)
    try:
        got = median(*args)
    except ValueError:
        return
    except Exception as exc:
        raise AssertionError("median args=%r got=%s(%s) want=ValueError" %
                             (args, type(exc).__name__, exc))
    raise AssertionError("median args=%r got=%r want=ValueError to be raised" %
                         (args, got))


def check_03_median():
    from solution import median
    args = ([1],)
    got = median(*args)
    want = 1
    assert got == want, "median args=%r got=%r want=%r" % (args, got, want)


def check_04_median():
    from solution import median
    args = ([3, 1, 2],)
    got = median(*args)
    want = 2
    assert got == want, "median args=%r got=%r want=%r" % (args, got, want)


def check_05_median():
    from solution import median
    args = ([1, 2],)
    got = median(*args)
    want = 1.5
    assert got == want, "median args=%r got=%r want=%r" % (args, got, want)


def check_06_median():
    from solution import median
    args = ([5, 5],)
    got = median(*args)
    want = 5.0
    assert got == want, "median args=%r got=%r want=%r" % (args, got, want)


def check_07_median():
    from solution import median
    args = ([-1, 0, 1],)
    got = median(*args)
    want = 0
    assert got == want, "median args=%r got=%r want=%r" % (args, got, want)


def check_08_median():
    from solution import median
    args = ([1, 2, 3, 4, 5, 6],)
    got = median(*args)
    want = 3.5
    assert got == want, "median args=%r got=%r want=%r" % (args, got, want)
