"""Visible checks for bcb_1129 -- these ship with the task and can be run.

Rendered from bigcode/bigcodebench-hard v0.1.4 (BigCodeBench/1129) by
ops/vacantrun/bcb_hard_bank_20260924/build_bank.py. The code below is the
dataset's unittest TestCases, restricted to the test methods that ship with
this task; each check_* runs one of those methods.
"""

from solution import *
import sys as _vacant_sys
import solution as _vacant_solution
_vacant_sys.modules.setdefault(__name__, _vacant_solution)

import unittest
import os
import tempfile
import shutil
from unittest.mock import patch
def mock_requests_get(*args, **kwargs):
    class MockResponse:
        def __init__(self):
            self.content = b"Fake content"  # Mocked file content
    return MockResponse()
class TestCases(unittest.TestCase):
    def setUp(self):
        # Set up a temporary directory to isolate file system effects
        self.test_dir = tempfile.mkdtemp()
    def tearDown(self):
        # Clean up the temporary directory after each test
        shutil.rmtree(self.test_dir)
    @patch('requests.get', mock_requests_get)
    def test_download_with_direct_key(self):
        # Test downloading a file with a direct key in JSON and check content
        json_str = '{"unknown": "https://example.com/file.txt"}'
        file_path = task_func(json_str, 'unknown', save_dir=self.test_dir)
        self.assertTrue(os.path.exists(file_path))
        with open(file_path, 'rb') as f:
            content = f.read()
        self.assertEqual(content, b"Fake content")
    @patch('requests.get', mock_requests_get)
    def test_download_to_default_directory(self):
        # Test downloading a file to the default directory and verify content
        json_str = '{"key4": "https://example.com/file4.txt"}'
        file_path = task_func(json_str, 'key4')
        self.assertTrue(os.path.exists(file_path))
        with open(file_path, 'rb') as f:
            content = f.read()
        self.assertEqual(content, b"Fake content")
        os.remove(file_path)  # Cleanup since this is in the current directory


# ── Vacant wrapper (generated by build_bank.py) ──────────────────────────
# Each check_* below runs exactly one TestCases method (with its setUp /
# tearDown) and raises AssertionError with a short message if it fails.
import unittest as _vacant_unittest

for _vacant_name in [_n for _n in list(globals()) if _n.startswith("check_")]:
    del globals()[_vacant_name]


def _vacant_short(tb_text, limit=700):
    lines = (tb_text or "").rstrip().splitlines()
    idx = [i for i, ln in enumerate(lines) if ln.startswith("  File ")]
    tail = lines[idx[-1] + 2:] if idx and idx[-1] + 2 < len(lines) else lines[-3:]
    tail = [ln for ln in tail if ln.strip() and set(ln.strip()) - set("^~")]
    msg = "\n".join(tail).strip()
    if len(msg) > limit:
        msg = msg[: limit // 2] + " ...[cut]... " + msg[-(limit // 2):]
    return msg


def _vacant_run(method_name):
    suite = _vacant_unittest.TestSuite([TestCases(method_name)])
    result = _vacant_unittest.TestResult()
    suite.run(result)
    if result.wasSuccessful() and result.testsRun == 1:
        return
    if result.failures:
        kind, tb = "FAIL", result.failures[0][1]
    elif result.errors:
        kind, tb = "ERROR", result.errors[0][1]
    elif result.unexpectedSuccesses:
        kind, tb = "UNEXPECTED SUCCESS", ""
    else:
        kind, tb = "NOT RUN", ""
    raise AssertionError("%s %s: %s" % (kind, method_name, _vacant_short(tb)))


def check_test_download_to_default_directory():
    _vacant_run('test_download_to_default_directory')

def check_test_download_with_direct_key():
    _vacant_run('test_download_with_direct_key')
