"""Hidden acceptance for s1_28_split_path — rendered data, do not hand-edit.

Generated by ops/gain/r535/build_bank.py from ops/gain/r535/tasks_s1.
Every check is zero-argument and passes by returning normally
(vacant/vrun/acceptance.py runs them in definition order).
"""


def check_01_split_path():
    from solution import split_path
    args = ('a/b/c.txt',)
    got = split_path(*args)
    want = {'dir': 'a/b', 'name': 'c', 'ext': 'txt'}
    assert got == want, "split_path args=%r got=%r want=%r" % (args, got, want)


def check_02_split_path():
    from solution import split_path
    args = ('readme',)
    got = split_path(*args)
    want = {'dir': '', 'name': 'readme', 'ext': ''}
    assert got == want, "split_path args=%r got=%r want=%r" % (args, got, want)


def check_03_split_path():
    from solution import split_path
    args = ('x.y',)
    got = split_path(*args)
    want = {'dir': '', 'name': 'x', 'ext': 'y'}
    assert got == want, "split_path args=%r got=%r want=%r" % (args, got, want)


def check_04_split_path():
    from solution import split_path
    args = ('/abs/f.md',)
    got = split_path(*args)
    want = {'dir': '/abs', 'name': 'f', 'ext': 'md'}
    assert got == want, "split_path args=%r got=%r want=%r" % (args, got, want)


def check_05_split_path():
    from solution import split_path
    args = ('a/b/',)
    got = split_path(*args)
    want = {'dir': 'a/b', 'name': '', 'ext': ''}
    assert got == want, "split_path args=%r got=%r want=%r" % (args, got, want)


def check_06_split_path():
    from solution import split_path
    args = ('d/n.tar.gz',)
    got = split_path(*args)
    want = {'dir': 'd', 'name': 'n.tar', 'ext': 'gz'}
    assert got == want, "split_path args=%r got=%r want=%r" % (args, got, want)


def check_07_split_path():
    from solution import split_path
    args = ('./f',)
    got = split_path(*args)
    want = {'dir': '.', 'name': 'f', 'ext': ''}
    assert got == want, "split_path args=%r got=%r want=%r" % (args, got, want)
