"""Visible acceptance for s1_13_mean — rendered data, do not hand-edit.

Generated by ops/gain/r535/build_bank.py from ops/gain/r535/tasks_s1.
Every check is zero-argument and passes by returning normally
(vacant/vrun/acceptance.py runs them in definition order).
"""


def check_01_mean():
    from solution import mean
    args = ([1, 2, 4],)
    got = mean(*args)
    want = 2.33
    assert got == want, "mean args=%r got=%r want=%r" % (args, got, want)


def check_02_mean():
    from solution import mean
    args = ([10],)
    got = mean(*args)
    want = 10.0
    assert got == want, "mean args=%r got=%r want=%r" % (args, got, want)
