"""P4 — central-MVP registry: schema, RPC, halo aggregation, anti-tamper."""

from vacant.registry.aggregation import (
    DEFAULT_REPUTATION_ORACLE,
    HaloMatch,
    ReputationOracle,
    lineage_query,
    rank_by_reputation,
    search_capability,
)
from vacant.registry.antitamper import (
    MerkleProof,
    build_merkle_root,
    build_merkle_tree,
    canonical_event_bytes,
    check_attestation_freshness,
    check_sequence_monotonic,
    compute_event_hash,
    merkle_inclusion_proof,
    sign_epoch_root,
    verify_event_signature,
    verify_inclusion_proof,
)
from vacant.registry.backend import RegistryBackend
from vacant.registry.errors import (
    AppendOnlyViolation,
    FreshnessError,
    IdempotencyConflict,
    NotFoundError,
    RegistryError,
    RegistryWriteError,
    SequenceMonotonicityError,
    SignatureRejected,
    VisibilityViolation,
)
from vacant.registry.halo import (
    HaloRecord,
    publish_halo,
    revoke_halo,
)
from vacant.registry.halo import RevocationRecord as HaloRevocationRecord
from vacant.registry.models import (
    AnomalyWindow,
    Attestation,
    CompositionLink,
    EpochWitness,
    Event,
    EventFinalization,
    Freeze,
    MerkleEpoch,
    ReadAudit,
    ReputationSnapshot,
    Revocation,
    SinkRecord,
    Vacant,
)
from vacant.registry.rpc import build_app
from vacant.registry.store import (
    RegistryStore,
    SignedEventDraft,
    canonical_json,
    now_ms,
)
from vacant.registry.visibility import Visibility, effective_visibility

__all__ = [
    "DEFAULT_REPUTATION_ORACLE",
    "AnomalyWindow",
    "AppendOnlyViolation",
    "Attestation",
    "CompositionLink",
    "EpochWitness",
    "Event",
    "EventFinalization",
    "Freeze",
    "FreshnessError",
    "HaloMatch",
    "HaloRecord",
    "HaloRevocationRecord",
    "IdempotencyConflict",
    "MerkleEpoch",
    "MerkleProof",
    "NotFoundError",
    "ReadAudit",
    "RegistryBackend",
    "RegistryError",
    "RegistryStore",
    "RegistryWriteError",
    "ReputationOracle",
    "ReputationSnapshot",
    "Revocation",
    "SequenceMonotonicityError",
    "SignatureRejected",
    "SignedEventDraft",
    "SinkRecord",
    "Vacant",
    "Visibility",
    "VisibilityViolation",
    "build_app",
    "build_merkle_root",
    "build_merkle_tree",
    "canonical_event_bytes",
    "canonical_json",
    "check_attestation_freshness",
    "check_sequence_monotonic",
    "compute_event_hash",
    "effective_visibility",
    "lineage_query",
    "merkle_inclusion_proof",
    "now_ms",
    "publish_halo",
    "rank_by_reputation",
    "revoke_halo",
    "search_capability",
    "sign_epoch_root",
    "verify_event_signature",
    "verify_inclusion_proof",
]
