"""Hidden acceptance for s1_36_longest_run — rendered data, do not hand-edit.

Generated by ops/gain/r535/build_bank.py from ops/gain/r535/tasks_s1.
Every check is zero-argument and passes by returning normally
(vacant/vrun/acceptance.py runs them in definition order).
"""


def check_01_longest_run():
    from solution import longest_run
    args = ('aabbb',)
    got = longest_run(*args)
    want = {'ch': 'b', 'n': 3}
    assert got == want, "longest_run args=%r got=%r want=%r" % (args, got, want)


def check_02_longest_run():
    from solution import longest_run
    args = ('aabb',)
    got = longest_run(*args)
    want = {'ch': 'a', 'n': 2}
    assert got == want, "longest_run args=%r got=%r want=%r" % (args, got, want)


def check_03_longest_run():
    from solution import longest_run
    args = ('x',)
    got = longest_run(*args)
    want = {'ch': 'x', 'n': 1}
    assert got == want, "longest_run args=%r got=%r want=%r" % (args, got, want)


def check_04_longest_run():
    from solution import longest_run
    args = ('aaa',)
    got = longest_run(*args)
    want = {'ch': 'a', 'n': 3}
    assert got == want, "longest_run args=%r got=%r want=%r" % (args, got, want)


def check_05_longest_run():
    from solution import longest_run
    args = ('abc',)
    got = longest_run(*args)
    want = {'ch': 'a', 'n': 1}
    assert got == want, "longest_run args=%r got=%r want=%r" % (args, got, want)


def check_06_longest_run():
    from solution import longest_run
    args = ('zzzaa',)
    got = longest_run(*args)
    want = {'ch': 'z', 'n': 3}
    assert got == want, "longest_run args=%r got=%r want=%r" % (args, got, want)


def check_07_longest_run():
    from solution import longest_run
    args = ('  ab',)
    got = longest_run(*args)
    want = {'ch': ' ', 'n': 2}
    assert got == want, "longest_run args=%r got=%r want=%r" % (args, got, want)
