"""Visible acceptance for s1_10_uniq — rendered data, do not hand-edit.

Generated by ops/gain/r535/build_bank.py from ops/gain/r535/tasks_s1.
Every check is zero-argument and passes by returning normally
(vacant/vrun/acceptance.py runs them in definition order).
"""


def check_01_uniq():
    from solution import uniq
    args = ([3, 1, 3, 2, 1],)
    got = uniq(*args)
    want = [3, 1, 2]
    assert got == want, "uniq args=%r got=%r want=%r" % (args, got, want)


def check_02_uniq():
    from solution import uniq
    args = ([],)
    got = uniq(*args)
    want = []
    assert got == want, "uniq args=%r got=%r want=%r" % (args, got, want)
