"""Visible checks for bcb_955 -- these ship with the task and can be run.

Rendered from bigcode/bigcodebench-hard v0.1.4 (BigCodeBench/955) by
ops/vacantrun/bcb_hard_bank_20260924/build_bank.py. The code below is the
dataset's unittest TestCases, restricted to the test methods that ship with
this task; each check_* runs one of those methods.
"""

from solution import *
import sys as _vacant_sys
import solution as _vacant_solution
_vacant_sys.modules.setdefault(__name__, _vacant_solution)

import unittest
import matplotlib.axes
class TestCases(unittest.TestCase):
    def test_case_1(self):
        # Test basic case
        ax = task_func(["hello"], "Hello world!")
        self.assertIsInstance(ax, matplotlib.axes.Axes)
        xtick_labels = [label.get_text() for label in ax.get_xticklabels()]
        self.assertTrue("hello" in xtick_labels)
        self.assertTrue("world!" in xtick_labels)
        self.assertEqual(ax.patches[0].get_height(), 1)
    def test_case_2(self):
        # Test underscore on basic case
        ax = task_func(["hello world"], "Hello world!")
        self.assertIsInstance(ax, matplotlib.axes.Axes)
        self.assertEqual(ax.get_xticklabels()[0].get_text(), "hello_world!")
        self.assertEqual(ax.patches[0].get_height(), 1)
    def test_case_3(self):
        # Test no mystrings
        ax = task_func([], "Hello world!")
        self.assertIsInstance(ax, matplotlib.axes.Axes)
        xtick_labels = [label.get_text() for label in ax.get_xticklabels()]
        self.assertTrue("Hello" in xtick_labels)
        self.assertTrue("world!" in xtick_labels)
        self.assertEqual(ax.patches[0].get_height(), 1)
    def test_case_10(self):
        # Tests handling of duplicates in `mystrings`.
        ax = task_func(["duplicate", "duplicate"], "duplicate Duplicate DUPLICATE")
        self.assertIn("duplicate", [label.get_text() for label in ax.get_xticklabels()])
        self.assertEqual(ax.patches[0].get_height(), 3)


# ── Vacant wrapper (generated by build_bank.py) ──────────────────────────
# Each check_* below runs exactly one TestCases method (with its setUp /
# tearDown) and raises AssertionError with a short message if it fails.
import unittest as _vacant_unittest

for _vacant_name in [_n for _n in list(globals()) if _n.startswith("check_")]:
    del globals()[_vacant_name]


def _vacant_short(tb_text, limit=700):
    lines = (tb_text or "").rstrip().splitlines()
    idx = [i for i, ln in enumerate(lines) if ln.startswith("  File ")]
    tail = lines[idx[-1] + 2:] if idx and idx[-1] + 2 < len(lines) else lines[-3:]
    tail = [ln for ln in tail if ln.strip() and set(ln.strip()) - set("^~")]
    msg = "\n".join(tail).strip()
    if len(msg) > limit:
        msg = msg[: limit // 2] + " ...[cut]... " + msg[-(limit // 2):]
    return msg


def _vacant_run(method_name):
    suite = _vacant_unittest.TestSuite([TestCases(method_name)])
    result = _vacant_unittest.TestResult()
    suite.run(result)
    if result.wasSuccessful() and result.testsRun == 1:
        return
    if result.failures:
        kind, tb = "FAIL", result.failures[0][1]
    elif result.errors:
        kind, tb = "ERROR", result.errors[0][1]
    elif result.unexpectedSuccesses:
        kind, tb = "UNEXPECTED SUCCESS", ""
    else:
        kind, tb = "NOT RUN", ""
    raise AssertionError("%s %s: %s" % (kind, method_name, _vacant_short(tb)))


def check_test_case_1():
    _vacant_run('test_case_1')

def check_test_case_10():
    _vacant_run('test_case_10')

def check_test_case_2():
    _vacant_run('test_case_2')

def check_test_case_3():
    _vacant_run('test_case_3')
