"""Hidden acceptance for s2_15_normalize — rendered data, do not hand-edit.

Generated by ops/gain/r535/build_bank.py from ops/gain/r535/tasks_s2.
Every check is zero-argument and passes by returning normally
(vacant/vrun/acceptance.py runs them in definition order).
"""


def check_01_normalize():
    from solution import normalize
    args = ('a//b/',)
    got = normalize(*args)
    want = 'a/b'
    assert got == want, "normalize args=%r got=%r want=%r" % (args, got, want)


def check_02_normalize():
    from solution import normalize
    args = ('/',)
    got = normalize(*args)
    want = '/'
    assert got == want, "normalize args=%r got=%r want=%r" % (args, got, want)


def check_03_normalize():
    from solution import normalize
    args = ('',)
    got = normalize(*args)
    want = ''
    assert got == want, "normalize args=%r got=%r want=%r" % (args, got, want)


def check_04_normalize():
    from solution import normalize
    args = ('a',)
    got = normalize(*args)
    want = 'a'
    assert got == want, "normalize args=%r got=%r want=%r" % (args, got, want)


def check_05_normalize():
    from solution import normalize
    args = ('/a/',)
    got = normalize(*args)
    want = '/a'
    assert got == want, "normalize args=%r got=%r want=%r" % (args, got, want)


def check_06_normalize():
    from solution import normalize
    args = ('///',)
    got = normalize(*args)
    want = '/'
    assert got == want, "normalize args=%r got=%r want=%r" % (args, got, want)


def check_07_normalize():
    from solution import normalize
    args = ('a/b//c',)
    got = normalize(*args)
    want = 'a/b/c'
    assert got == want, "normalize args=%r got=%r want=%r" % (args, got, want)


def check_08_normalize():
    from solution import normalize
    args = ('./x/',)
    got = normalize(*args)
    want = './x'
    assert got == want, "normalize args=%r got=%r want=%r" % (args, got, want)
