"""Visible acceptance for s2_21_flatten — rendered data, do not hand-edit.

Generated by ops/gain/r535/build_bank.py from ops/gain/r535/tasks_s2.
Every check is zero-argument and passes by returning normally
(vacant_network/vrun/acceptance.py runs them in definition order).
"""


def check_01_flatten():
    from solution import flatten
    args = ([[1, 2], 3, [[4]]],)
    got = flatten(*args)
    want = [1, 2, 3, [4]]
    assert got == want, "flatten args=%r got=%r want=%r" % (args, got, want)


def check_02_flatten():
    from solution import flatten
    args = ([],)
    got = flatten(*args)
    want = []
    assert got == want, "flatten args=%r got=%r want=%r" % (args, got, want)
