"""Hidden acceptance for s2_17_ordinal — rendered data, do not hand-edit.

Generated by ops/gain/r535/build_bank.py from ops/gain/r535/tasks_s2.
Every check is zero-argument and passes by returning normally
(vacant_network/vrun/acceptance.py runs them in definition order).
"""


def check_01_ordinal():
    from solution import ordinal
    args = (12,)
    got = ordinal(*args)
    want = '12th'
    assert got == want, "ordinal args=%r got=%r want=%r" % (args, got, want)


def check_02_ordinal():
    from solution import ordinal
    args = (21,)
    got = ordinal(*args)
    want = '21st'
    assert got == want, "ordinal args=%r got=%r want=%r" % (args, got, want)


def check_03_ordinal():
    from solution import ordinal
    args = (1,)
    got = ordinal(*args)
    want = '1st'
    assert got == want, "ordinal args=%r got=%r want=%r" % (args, got, want)


def check_04_ordinal():
    from solution import ordinal
    args = (2,)
    got = ordinal(*args)
    want = '2nd'
    assert got == want, "ordinal args=%r got=%r want=%r" % (args, got, want)


def check_05_ordinal():
    from solution import ordinal
    args = (3,)
    got = ordinal(*args)
    want = '3rd'
    assert got == want, "ordinal args=%r got=%r want=%r" % (args, got, want)


def check_06_ordinal():
    from solution import ordinal
    args = (4,)
    got = ordinal(*args)
    want = '4th'
    assert got == want, "ordinal args=%r got=%r want=%r" % (args, got, want)


def check_07_ordinal():
    from solution import ordinal
    args = (11,)
    got = ordinal(*args)
    want = '11th'
    assert got == want, "ordinal args=%r got=%r want=%r" % (args, got, want)


def check_08_ordinal():
    from solution import ordinal
    args = (113,)
    got = ordinal(*args)
    want = '113th'
    assert got == want, "ordinal args=%r got=%r want=%r" % (args, got, want)


def check_09_ordinal():
    from solution import ordinal
    args = (22,)
    got = ordinal(*args)
    want = '22nd'
    assert got == want, "ordinal args=%r got=%r want=%r" % (args, got, want)
