"""Visible acceptance for s2_17_ordinal — rendered data, do not hand-edit.

Generated by ops/gain/r535/build_bank.py from ops/gain/r535/tasks_s2.
Every check is zero-argument and passes by returning normally
(vacant_network/vrun/acceptance.py runs them in definition order).
"""


def check_01_ordinal():
    from solution import ordinal
    args = (12,)
    got = ordinal(*args)
    want = '12th'
    assert got == want, "ordinal args=%r got=%r want=%r" % (args, got, want)


def check_02_ordinal():
    from solution import ordinal
    args = (21,)
    got = ordinal(*args)
    want = '21st'
    assert got == want, "ordinal args=%r got=%r want=%r" % (args, got, want)
