"""Hidden acceptance for s2_26_initials — rendered data, do not hand-edit.

Generated by ops/gain/r535/build_bank.py from ops/gain/r535/tasks_s2.
Every check is zero-argument and passes by returning normally
(vacant/vrun/acceptance.py runs them in definition order).
"""


def check_01_initials():
    from solution import initials
    args = ('ada lovelace',)
    got = initials(*args)
    want = 'A.L.'
    assert got == want, "initials args=%r got=%r want=%r" % (args, got, want)


def check_02_initials():
    from solution import initials
    args = ('jean-luc picard',)
    got = initials(*args)
    want = 'J.L.P.'
    assert got == want, "initials args=%r got=%r want=%r" % (args, got, want)


def check_03_initials():
    from solution import initials
    args = ('',)
    got = initials(*args)
    want = ''
    assert got == want, "initials args=%r got=%r want=%r" % (args, got, want)


def check_04_initials():
    from solution import initials
    args = ('x',)
    got = initials(*args)
    want = 'X.'
    assert got == want, "initials args=%r got=%r want=%r" % (args, got, want)


def check_05_initials():
    from solution import initials
    args = ('Mary Jane Watson',)
    got = initials(*args)
    want = 'M.J.W.'
    assert got == want, "initials args=%r got=%r want=%r" % (args, got, want)


def check_06_initials():
    from solution import initials
    args = ('anne-marie',)
    got = initials(*args)
    want = 'A.M.'
    assert got == want, "initials args=%r got=%r want=%r" % (args, got, want)


def check_07_initials():
    from solution import initials
    args = ('  a  b ',)
    got = initials(*args)
    want = 'A.B.'
    assert got == want, "initials args=%r got=%r want=%r" % (args, got, want)
