"""Hidden acceptance for s1_25_shift_letters — rendered data, do not hand-edit.

Generated by ops/gain/r535/build_bank.py from ops/gain/r535/tasks_s1.
Every check is zero-argument and passes by returning normally
(vacant/vrun/acceptance.py runs them in definition order).
"""


def check_01_shift_letters():
    from solution import shift_letters
    args = ('abc-XYZ', 1)
    got = shift_letters(*args)
    want = 'bcd-YZA'
    assert got == want, "shift_letters args=%r got=%r want=%r" % (args, got, want)


def check_02_shift_letters():
    from solution import shift_letters
    args = ('abc', -1)
    got = shift_letters(*args)
    want = 'zab'
    assert got == want, "shift_letters args=%r got=%r want=%r" % (args, got, want)


def check_03_shift_letters():
    from solution import shift_letters
    args = ('', 5)
    got = shift_letters(*args)
    want = ''
    assert got == want, "shift_letters args=%r got=%r want=%r" % (args, got, want)


def check_04_shift_letters():
    from solution import shift_letters
    args = ('Hello, World!', 13)
    got = shift_letters(*args)
    want = 'Uryyb, Jbeyq!'
    assert got == want, "shift_letters args=%r got=%r want=%r" % (args, got, want)


def check_05_shift_letters():
    from solution import shift_letters
    args = ('xyz', 3)
    got = shift_letters(*args)
    want = 'abc'
    assert got == want, "shift_letters args=%r got=%r want=%r" % (args, got, want)


def check_06_shift_letters():
    from solution import shift_letters
    args = ('ABC', 0)
    got = shift_letters(*args)
    want = 'ABC'
    assert got == want, "shift_letters args=%r got=%r want=%r" % (args, got, want)


def check_07_shift_letters():
    from solution import shift_letters
    args = ('a1b', 1)
    got = shift_letters(*args)
    want = 'b1c'
    assert got == want, "shift_letters args=%r got=%r want=%r" % (args, got, want)
