"""Visible acceptance for s1_38_shared_start — rendered data, do not hand-edit.

Generated by ops/gain/r535/build_bank.py from ops/gain/r535/tasks_s1.
Every check is zero-argument and passes by returning normally
(vacant_network/vrun/acceptance.py runs them in definition order).
"""


def check_01_shared_start():
    from solution import shared_start
    args = (['flow', 'flower', 'flight'],)
    got = shared_start(*args)
    want = 'fl'
    assert got == want, "shared_start args=%r got=%r want=%r" % (args, got, want)


def check_02_shared_start():
    from solution import shared_start
    args = (['Abc', 'abc'],)
    got = shared_start(*args)
    want = ''
    assert got == want, "shared_start args=%r got=%r want=%r" % (args, got, want)
