"""Hidden acceptance for s2_38_in_range — rendered data, do not hand-edit.

Generated by ops/gain/r535/build_bank.py from ops/gain/r535/tasks_s2.
Every check is zero-argument and passes by returning normally
(vacant_network/vrun/acceptance.py runs them in definition order).
"""


def check_01_in_range():
    from solution import in_range
    args = (1, 1, 5)
    got = in_range(*args)
    want = True
    assert got == want, "in_range args=%r got=%r want=%r" % (args, got, want)


def check_02_in_range():
    from solution import in_range
    args = (5, 1, 5)
    got = in_range(*args)
    want = False
    assert got == want, "in_range args=%r got=%r want=%r" % (args, got, want)


def check_03_in_range():
    from solution import in_range
    args = (0, 1, 5)
    got = in_range(*args)
    want = False
    assert got == want, "in_range args=%r got=%r want=%r" % (args, got, want)


def check_04_in_range():
    from solution import in_range
    args = (4, 1, 5)
    got = in_range(*args)
    want = True
    assert got == want, "in_range args=%r got=%r want=%r" % (args, got, want)


def check_05_in_range():
    from solution import in_range
    args = (1.0, 1, 5)
    got = in_range(*args)
    want = True
    assert got == want, "in_range args=%r got=%r want=%r" % (args, got, want)


def check_06_in_range():
    from solution import in_range
    args = (-1, -5, 0)
    got = in_range(*args)
    want = True
    assert got == want, "in_range args=%r got=%r want=%r" % (args, got, want)


def check_07_in_range():
    from solution import in_range
    args = (0, -5, 0)
    got = in_range(*args)
    want = False
    assert got == want, "in_range args=%r got=%r want=%r" % (args, got, want)


def check_08_in_range():
    from solution import in_range
    args = (3, 3, 4)
    got = in_range(*args)
    want = True
    assert got == want, "in_range args=%r got=%r want=%r" % (args, got, want)
