"""Visible checks for bcb_964 -- these ship with the task and can be run.

Rendered from bigcode/bigcodebench-hard v0.1.4 (BigCodeBench/964) by
ops/vacantrun/bcb_hard_bank_20260924/build_bank.py. The code below is the
dataset's unittest TestCases, restricted to the test methods that ship with
this task; each check_* runs one of those methods.
"""

from solution import *
import sys as _vacant_sys
import solution as _vacant_solution
_vacant_sys.modules.setdefault(__name__, _vacant_solution)

import unittest
import os
import docx
import pandas as pd
import tempfile
class TestCases(unittest.TestCase):
    def setUp(self):
        self.temp_source_dir = tempfile.TemporaryDirectory()
        self.temp_target_dir = tempfile.TemporaryDirectory()
        self.source_dir = self.temp_source_dir.name
        self.target_dir = self.temp_target_dir.name
        self.test_texts = ["Hello, world!"] * 10
        self.test_df = pd.DataFrame(
            {"A": list(range(10)), "B": [str(_) for _ in range(10)]}
        )
    def tearDown(self):
        self.temp_source_dir.cleanup()
        self.temp_target_dir.cleanup()
    def create_test_data(self, extension):
        filename = "sample" + extension
        path = os.path.join(self.source_dir, filename)
        if extension == ".txt":
            with open(path, "w") as f:
                for text in self.test_texts:
                    f.write(text + "\n")
        elif extension == ".docx":
            doc = docx.Document()
            for text in self.test_texts:
                doc.add_paragraph(text)
            doc.save(path)
        elif extension == ".csv":
            self.test_df.to_csv(path, index=False)
        elif extension == ".xlsx":
            self.test_df.to_excel(path, index=False)
    def test_case_1(self):
        # Test txt
        self.create_test_data(".txt")
        num_converted = task_func(self.source_dir, self.target_dir)
        self.assertEqual(num_converted, 1)
        converted_path = os.path.join(self.target_dir, "sample.csv")
        self.assertTrue(os.path.exists(converted_path))
    def test_case_2(self):
        # Test docx
        self.create_test_data(".docx")
        num_converted = task_func(self.source_dir, self.target_dir)
        self.assertEqual(num_converted, 1)
        self.assertTrue(os.path.exists(os.path.join(self.target_dir, "sample.csv")))
    def test_case_3(self):
        # Test xlsx
        self.create_test_data(".xlsx")
        num_converted = task_func(self.source_dir, self.target_dir)
        self.assertEqual(num_converted, 1)
        self.assertTrue(os.path.exists(os.path.join(self.target_dir, "sample.csv")))


# ── Vacant wrapper (generated by build_bank.py) ──────────────────────────
# Each check_* below runs exactly one TestCases method (with its setUp /
# tearDown) and raises AssertionError with a short message if it fails.
import unittest as _vacant_unittest

for _vacant_name in [_n for _n in list(globals()) if _n.startswith("check_")]:
    del globals()[_vacant_name]


def _vacant_short(tb_text, limit=700):
    lines = (tb_text or "").rstrip().splitlines()
    idx = [i for i, ln in enumerate(lines) if ln.startswith("  File ")]
    tail = lines[idx[-1] + 2:] if idx and idx[-1] + 2 < len(lines) else lines[-3:]
    tail = [ln for ln in tail if ln.strip() and set(ln.strip()) - set("^~")]
    msg = "\n".join(tail).strip()
    if len(msg) > limit:
        msg = msg[: limit // 2] + " ...[cut]... " + msg[-(limit // 2):]
    return msg


def _vacant_run(method_name):
    suite = _vacant_unittest.TestSuite([TestCases(method_name)])
    result = _vacant_unittest.TestResult()
    suite.run(result)
    if result.wasSuccessful() and result.testsRun == 1:
        return
    if result.failures:
        kind, tb = "FAIL", result.failures[0][1]
    elif result.errors:
        kind, tb = "ERROR", result.errors[0][1]
    elif result.unexpectedSuccesses:
        kind, tb = "UNEXPECTED SUCCESS", ""
    else:
        kind, tb = "NOT RUN", ""
    raise AssertionError("%s %s: %s" % (kind, method_name, _vacant_short(tb)))


def check_test_case_1():
    _vacant_run('test_case_1')

def check_test_case_2():
    _vacant_run('test_case_2')

def check_test_case_3():
    _vacant_run('test_case_3')
