"""Hidden acceptance for s1_15_chunks — rendered data, do not hand-edit.

Generated by ops/gain/r535/build_bank.py from ops/gain/r535/tasks_s1.
Every check is zero-argument and passes by returning normally
(vacant/vrun/acceptance.py runs them in definition order).
"""


def check_01_chunks():
    from solution import chunks
    args = ([1, 2, 3, 4, 5], 2)
    got = chunks(*args)
    want = [[1, 2], [3, 4], [5]]
    assert got == want, "chunks args=%r got=%r want=%r" % (args, got, want)


def check_02_chunks():
    from solution import chunks
    args = ([], 3)
    got = chunks(*args)
    want = []
    assert got == want, "chunks args=%r got=%r want=%r" % (args, got, want)


def check_03_chunks():
    from solution import chunks
    args = ([1, 2, 3], 3)
    got = chunks(*args)
    want = [[1, 2, 3]]
    assert got == want, "chunks args=%r got=%r want=%r" % (args, got, want)


def check_04_chunks():
    from solution import chunks
    args = ([1], 5)
    got = chunks(*args)
    want = [[1]]
    assert got == want, "chunks args=%r got=%r want=%r" % (args, got, want)


def check_05_chunks():
    from solution import chunks
    args = ([1, 2, 3, 4], 2)
    got = chunks(*args)
    want = [[1, 2], [3, 4]]
    assert got == want, "chunks args=%r got=%r want=%r" % (args, got, want)


def check_06_chunks():
    from solution import chunks
    args = (['a', 'b', 'c'], 1)
    got = chunks(*args)
    want = [['a'], ['b'], ['c']]
    assert got == want, "chunks args=%r got=%r want=%r" % (args, got, want)


def check_07_chunks():
    from solution import chunks
    args = ([1, 2, 3, 4, 5, 6, 7], 3)
    got = chunks(*args)
    want = [[1, 2, 3], [4, 5, 6], [7]]
    assert got == want, "chunks args=%r got=%r want=%r" % (args, got, want)
