"""Visible checks for bcb_287 -- these ship with the task and can be run.

Rendered from bigcode/bigcodebench-hard v0.1.4 (BigCodeBench/287) by
ops/vacantrun/bcb_hard_bank_20260924/build_bank.py. The code below is the
dataset's unittest TestCases, restricted to the test methods that ship with
this task; each check_* runs one of those methods.
"""

from solution import *
import sys as _vacant_sys
import solution as _vacant_solution
_vacant_sys.modules.setdefault(__name__, _vacant_solution)

import unittest
from faker import Faker
import shutil
class TestCases(unittest.TestCase):
    def setUp(self):
        # Set up a Faker instance and a test directory
        self.faker = Faker()
        self.test_dir = './testdir/'
        os.makedirs(self.test_dir, exist_ok=True)
    def tearDown(self):
        # Clean up the test directory
        shutil.rmtree(self.test_dir)
    def test_empty_files(self):
        # Test with empty files
        file_name = 'empty_file.txt'
        expected_result = {}
        with open(os.path.join(self.test_dir, file_name), 'w') as f:
            pass  # create an empty file
        task_func('test_output.json', self.test_dir)
        with open('test_output.json', 'r') as f:
            result = json.load(f)
        self.assertEqual(result, expected_result)
    def test_files_with_special_characters(self):
        # Test with files that have special characters
        file_name = 'special_chars.txt'
        test_content = 'hello-world hello_python'
        expected_result = {'hello-world': 1, 'hello_python': 1}
        with open(os.path.join(self.test_dir, file_name), 'w') as f:
            f.write(test_content)
        task_func('test_output.json', self.test_dir)
        if os.path.exists(os.path.join(self.test_dir, file_name)):
            os.remove(os.path.join(self.test_dir, file_name))
        with open('test_output.json', 'r') as f:
            result = json.load(f)
        self.assertEqual(result, expected_result)


# ── Vacant wrapper (generated by build_bank.py) ──────────────────────────
# Each check_* below runs exactly one TestCases method (with its setUp /
# tearDown) and raises AssertionError with a short message if it fails.
import unittest as _vacant_unittest

for _vacant_name in [_n for _n in list(globals()) if _n.startswith("check_")]:
    del globals()[_vacant_name]


def _vacant_short(tb_text, limit=700):
    lines = (tb_text or "").rstrip().splitlines()
    idx = [i for i, ln in enumerate(lines) if ln.startswith("  File ")]
    tail = lines[idx[-1] + 2:] if idx and idx[-1] + 2 < len(lines) else lines[-3:]
    tail = [ln for ln in tail if ln.strip() and set(ln.strip()) - set("^~")]
    msg = "\n".join(tail).strip()
    if len(msg) > limit:
        msg = msg[: limit // 2] + " ...[cut]... " + msg[-(limit // 2):]
    return msg


def _vacant_run(method_name):
    suite = _vacant_unittest.TestSuite([TestCases(method_name)])
    result = _vacant_unittest.TestResult()
    suite.run(result)
    if result.wasSuccessful() and result.testsRun == 1:
        return
    if result.failures:
        kind, tb = "FAIL", result.failures[0][1]
    elif result.errors:
        kind, tb = "ERROR", result.errors[0][1]
    elif result.unexpectedSuccesses:
        kind, tb = "UNEXPECTED SUCCESS", ""
    else:
        kind, tb = "NOT RUN", ""
    raise AssertionError("%s %s: %s" % (kind, method_name, _vacant_short(tb)))


def check_test_empty_files():
    _vacant_run('test_empty_files')

def check_test_files_with_special_characters():
    _vacant_run('test_files_with_special_characters')
