"""Scoring checks for bcb_99 -- NOT part of any workspace.

This file lives in a separate tree and is never copied into an agent's
workspace. It runs every test method of the dataset's TestCases
(bigcode/bigcodebench-hard v0.1.4, BigCodeBench/99): the visible ones plus the rest.
"""

from solution import *
import sys as _vacant_sys
import solution as _vacant_solution
_vacant_sys.modules.setdefault(__name__, _vacant_solution)

import unittest
import matplotlib.pyplot as plt
class TestCases(unittest.TestCase):
    def setUp(self):
        self.fig = task_func()
    def test_figure_type(self):
        self.assertIsInstance(self.fig, plt.Figure, "The returned object should be a matplotlib Figure.")
    def test_axes_existence(self):
        self.assertGreater(len(self.fig.axes), 0, "The figure should contain one or more axes.")
    def test_figure_children(self):
        self.assertGreater(len(self.fig.get_children()), 0, "The figure should have children.")
    def test_plot_labels(self):
        # Check the first subplot for appropriate labels as a proxy for the rest
        ax = self.fig.axes[0]
        self.assertIn('sepal length', ax.get_xlabel() + ax.get_ylabel(), "Axes labels should include feature names.")
    def test_plot_title(self):
        # Check if the figure has a title set
        self.assertIsNotNone(self.fig._suptitle, "The figure should have a title.")
        self.assertEqual(self.fig._suptitle.get_text(), 'Iris Dataset Pair Plot', "The figure title does not match expected.")


# ── Vacant wrapper (generated by build_bank.py) ──────────────────────────
# Each check_* below runs exactly one TestCases method (with its setUp /
# tearDown) and raises AssertionError with a short message if it fails.
import unittest as _vacant_unittest

for _vacant_name in [_n for _n in list(globals()) if _n.startswith("check_")]:
    del globals()[_vacant_name]


def _vacant_short(tb_text, limit=700):
    lines = (tb_text or "").rstrip().splitlines()
    idx = [i for i, ln in enumerate(lines) if ln.startswith("  File ")]
    tail = lines[idx[-1] + 2:] if idx and idx[-1] + 2 < len(lines) else lines[-3:]
    tail = [ln for ln in tail if ln.strip() and set(ln.strip()) - set("^~")]
    msg = "\n".join(tail).strip()
    if len(msg) > limit:
        msg = msg[: limit // 2] + " ...[cut]... " + msg[-(limit // 2):]
    return msg


def _vacant_run(method_name):
    suite = _vacant_unittest.TestSuite([TestCases(method_name)])
    result = _vacant_unittest.TestResult()
    suite.run(result)
    if result.wasSuccessful() and result.testsRun == 1:
        return
    if result.failures:
        kind, tb = "FAIL", result.failures[0][1]
    elif result.errors:
        kind, tb = "ERROR", result.errors[0][1]
    elif result.unexpectedSuccesses:
        kind, tb = "UNEXPECTED SUCCESS", ""
    else:
        kind, tb = "NOT RUN", ""
    raise AssertionError("%s %s: %s" % (kind, method_name, _vacant_short(tb)))


def check_test_axes_existence():
    _vacant_run('test_axes_existence')

def check_test_figure_children():
    _vacant_run('test_figure_children')

def check_test_figure_type():
    _vacant_run('test_figure_type')

def check_test_plot_labels():
    _vacant_run('test_plot_labels')

def check_test_plot_title():
    _vacant_run('test_plot_title')
