"""Hidden acceptance for s1_08_nvowels — rendered data, do not hand-edit.

Generated by ops/gain/r535/build_bank.py from ops/gain/r535/tasks_s1.
Every check is zero-argument and passes by returning normally
(vacant_network/vrun/acceptance.py runs them in definition order).
"""


def check_01_n_vowels():
    from solution import n_vowels
    args = ('Education',)
    got = n_vowels(*args)
    want = 5
    assert got == want, "n_vowels args=%r got=%r want=%r" % (args, got, want)


def check_02_n_vowels():
    from solution import n_vowels
    args = ('rhythm',)
    got = n_vowels(*args)
    want = 0
    assert got == want, "n_vowels args=%r got=%r want=%r" % (args, got, want)


def check_03_n_vowels():
    from solution import n_vowels
    args = ('',)
    got = n_vowels(*args)
    want = 0
    assert got == want, "n_vowels args=%r got=%r want=%r" % (args, got, want)


def check_04_n_vowels():
    from solution import n_vowels
    args = ('AEIOU',)
    got = n_vowels(*args)
    want = 5
    assert got == want, "n_vowels args=%r got=%r want=%r" % (args, got, want)


def check_05_n_vowels():
    from solution import n_vowels
    args = ('xyz',)
    got = n_vowels(*args)
    want = 0
    assert got == want, "n_vowels args=%r got=%r want=%r" % (args, got, want)


def check_06_n_vowels():
    from solution import n_vowels
    args = ('Banana',)
    got = n_vowels(*args)
    want = 3
    assert got == want, "n_vowels args=%r got=%r want=%r" % (args, got, want)


def check_07_n_vowels():
    from solution import n_vowels
    args = ('Queue',)
    got = n_vowels(*args)
    want = 4
    assert got == want, "n_vowels args=%r got=%r want=%r" % (args, got, want)
