"""Hidden acceptance for s1_22_digit_list — rendered data, do not hand-edit.

Generated by ops/gain/r535/build_bank.py from ops/gain/r535/tasks_s1.
Every check is zero-argument and passes by returning normally
(vacant_network/vrun/acceptance.py runs them in definition order).
"""


def check_01_digit_list():
    from solution import digit_list
    args = (120,)
    got = digit_list(*args)
    want = [1, 2, 0]
    assert got == want, "digit_list args=%r got=%r want=%r" % (args, got, want)


def check_02_digit_list():
    from solution import digit_list
    args = (7,)
    got = digit_list(*args)
    want = [7]
    assert got == want, "digit_list args=%r got=%r want=%r" % (args, got, want)


def check_03_digit_list():
    from solution import digit_list
    args = (0,)
    got = digit_list(*args)
    want = [0]
    assert got == want, "digit_list args=%r got=%r want=%r" % (args, got, want)


def check_04_digit_list():
    from solution import digit_list
    args = (1000,)
    got = digit_list(*args)
    want = [1, 0, 0, 0]
    assert got == want, "digit_list args=%r got=%r want=%r" % (args, got, want)


def check_05_digit_list():
    from solution import digit_list
    args = (9876,)
    got = digit_list(*args)
    want = [9, 8, 7, 6]
    assert got == want, "digit_list args=%r got=%r want=%r" % (args, got, want)


def check_06_digit_list():
    from solution import digit_list
    args = (10,)
    got = digit_list(*args)
    want = [1, 0]
    assert got == want, "digit_list args=%r got=%r want=%r" % (args, got, want)


def check_07_digit_list():
    from solution import digit_list
    args = (505,)
    got = digit_list(*args)
    want = [5, 0, 5]
    assert got == want, "digit_list args=%r got=%r want=%r" % (args, got, want)
