"""Hidden acceptance for s2_33_is_leap — rendered data, do not hand-edit.

Generated by ops/gain/r535/build_bank.py from ops/gain/r535/tasks_s2.
Every check is zero-argument and passes by returning normally
(vacant/vrun/acceptance.py runs them in definition order).
"""


def check_01_is_leap():
    from solution import is_leap
    args = (1900,)
    got = is_leap(*args)
    want = False
    assert got == want, "is_leap args=%r got=%r want=%r" % (args, got, want)


def check_02_is_leap():
    from solution import is_leap
    args = (0,)
    try:
        got = is_leap(*args)
    except ValueError:
        return
    except Exception as exc:
        raise AssertionError("is_leap args=%r got=%s(%s) want=ValueError" %
                             (args, type(exc).__name__, exc))
    raise AssertionError("is_leap args=%r got=%r want=ValueError to be raised" %
                         (args, got))


def check_03_is_leap():
    from solution import is_leap
    args = (2000,)
    got = is_leap(*args)
    want = True
    assert got == want, "is_leap args=%r got=%r want=%r" % (args, got, want)


def check_04_is_leap():
    from solution import is_leap
    args = (2024,)
    got = is_leap(*args)
    want = True
    assert got == want, "is_leap args=%r got=%r want=%r" % (args, got, want)


def check_05_is_leap():
    from solution import is_leap
    args = (2023,)
    got = is_leap(*args)
    want = False
    assert got == want, "is_leap args=%r got=%r want=%r" % (args, got, want)


def check_06_is_leap():
    from solution import is_leap
    args = (2100,)
    got = is_leap(*args)
    want = False
    assert got == want, "is_leap args=%r got=%r want=%r" % (args, got, want)


def check_07_is_leap():
    from solution import is_leap
    args = (-4,)
    try:
        got = is_leap(*args)
    except ValueError:
        return
    except Exception as exc:
        raise AssertionError("is_leap args=%r got=%s(%s) want=ValueError" %
                             (args, type(exc).__name__, exc))
    raise AssertionError("is_leap args=%r got=%r want=ValueError to be raised" %
                         (args, got))


def check_08_is_leap():
    from solution import is_leap
    args = (4,)
    got = is_leap(*args)
    want = True
    assert got == want, "is_leap args=%r got=%r want=%r" % (args, got, want)
