"""Visible checks for bcb_161 -- these ship with the task and can be run.

Rendered from bigcode/bigcodebench-hard v0.1.4 (BigCodeBench/161) by
ops/vacantrun/bcb_hard_bank_20260924/build_bank.py. The code below is the
dataset's unittest TestCases, restricted to the test methods that ship with
this task; each check_* runs one of those methods.
"""

from solution import *
import sys as _vacant_sys
import solution as _vacant_solution
_vacant_sys.modules.setdefault(__name__, _vacant_solution)

import unittest
import os
import pandas as pd
from unittest.mock import mock_open, patch
class TestCases(unittest.TestCase):
    def setUp(self):
        self.sample_log_file = 'test_server.log'
        with open(self.sample_log_file, 'w') as log_file:
            log_file.write("ERROR: [2023-03-23 15:00:00] - Sample error message\n")
            log_file.write("INFO: [2023-03-23 15:05:00] - Sample info message\n")
    def tearDown(self):
        # Clean up: Remove the generated CSV file if it exists
        if os.path.exists('log_data.csv'):
            os.remove('log_data.csv')
        if os.path.exists(self.sample_log_file):
            os.remove(self.sample_log_file)
    def test_log_to_csv_content(self):
        expected_df = pd.DataFrame({
            'Type': ['ERROR', 'INFO'],
            'Timestamp': ['2023-03-23 15:00:00', '2023-03-23 15:05:00'],
            'Message': ['Sample error message', 'Sample info message']
        })
        generated_csv_path = task_func(self.sample_log_file)
        self.assertTrue(os.path.exists(generated_csv_path), "CSV file was not created.")
        generated_df = pd.read_csv(generated_csv_path)
        pd.testing.assert_frame_equal(expected_df, generated_df)
    def test_incorrect_format_log(self):
        incorrect_format = "Wrong format line without proper log prefix"
        with patch('builtins.open', mock_open(read_data=incorrect_format)):
            with self.assertRaises(ValueError):
                task_func('incorrect.log')


# ── Vacant wrapper (generated by build_bank.py) ──────────────────────────
# Each check_* below runs exactly one TestCases method (with its setUp /
# tearDown) and raises AssertionError with a short message if it fails.
import unittest as _vacant_unittest

for _vacant_name in [_n for _n in list(globals()) if _n.startswith("check_")]:
    del globals()[_vacant_name]


def _vacant_short(tb_text, limit=700):
    lines = (tb_text or "").rstrip().splitlines()
    idx = [i for i, ln in enumerate(lines) if ln.startswith("  File ")]
    tail = lines[idx[-1] + 2:] if idx and idx[-1] + 2 < len(lines) else lines[-3:]
    tail = [ln for ln in tail if ln.strip() and set(ln.strip()) - set("^~")]
    msg = "\n".join(tail).strip()
    if len(msg) > limit:
        msg = msg[: limit // 2] + " ...[cut]... " + msg[-(limit // 2):]
    return msg


def _vacant_run(method_name):
    suite = _vacant_unittest.TestSuite([TestCases(method_name)])
    result = _vacant_unittest.TestResult()
    suite.run(result)
    if result.wasSuccessful() and result.testsRun == 1:
        return
    if result.failures:
        kind, tb = "FAIL", result.failures[0][1]
    elif result.errors:
        kind, tb = "ERROR", result.errors[0][1]
    elif result.unexpectedSuccesses:
        kind, tb = "UNEXPECTED SUCCESS", ""
    else:
        kind, tb = "NOT RUN", ""
    raise AssertionError("%s %s: %s" % (kind, method_name, _vacant_short(tb)))


def check_test_incorrect_format_log():
    _vacant_run('test_incorrect_format_log')

def check_test_log_to_csv_content():
    _vacant_run('test_log_to_csv_content')
