"""Visible checks for bcb_177 -- these ship with the task and can be run.

Rendered from bigcode/bigcodebench-hard v0.1.4 (BigCodeBench/177) by
ops/vacantrun/bcb_hard_bank_20260924/build_bank.py. The code below is the
dataset's unittest TestCases, restricted to the test methods that ship with
this task; each check_* runs one of those methods.
"""

from solution import *
import sys as _vacant_sys
import solution as _vacant_solution
_vacant_sys.modules.setdefault(__name__, _vacant_solution)

import unittest
import pandas as pd
import nltk
nltk.download('punkt')  # Ensure the NLTK tokenizer is available
class TestCases(unittest.TestCase):
    def setUp(self):
        """Prepare environment and variables for tests."""
        self.data = {
            'Title': [
                'What is Data Science?',
                'The Future of Data Science',
                'How to learn Python',
                'Why is Python like that?',
            ],
            'Content': [
                'Data Science is about data analysis. Like what you see?',
                'Data Science has a bright future.',
                'Learning Python is essential for data science.',
                'Python is popular among developers. What do you think?',
            ]
        }
        self.df = pd.DataFrame(self.data)
    def test_empty_dataframe(self):
        """Test the function with an empty DataFrame."""
        df_empty = pd.DataFrame(columns=['Title', 'Content'])
        result = task_func(df_empty)
        self.assertEqual(result, {}, "Expected no word frequencies for an empty DataFrame.")
    def test_case_sensitive_handling(self):
        """Test the function's handling of case sensitivity in finding keywords."""
        data = {
            'Title': [
                'What is new in technology',
                'Like new advancements'
            ],
            'Content': [
                'Technological growth is exponential.',
                'These advancements are like no other.'
            ]
        }
        df_case = pd.DataFrame(data)
        result = task_func(df_case)
        expected_freq = {'Technological': 1, 'growth': 1, 'is': 1, 'exponential': 1,
                         'These': 1, 'advancements': 1, 'are': 1, 'like': 1, 'no': 1, 'other': 1}
        self.assertEqual(result, expected_freq, "Case sensitivity handling is faulty.")


# ── Vacant wrapper (generated by build_bank.py) ──────────────────────────
# Each check_* below runs exactly one TestCases method (with its setUp /
# tearDown) and raises AssertionError with a short message if it fails.
import unittest as _vacant_unittest

for _vacant_name in [_n for _n in list(globals()) if _n.startswith("check_")]:
    del globals()[_vacant_name]


def _vacant_short(tb_text, limit=700):
    lines = (tb_text or "").rstrip().splitlines()
    idx = [i for i, ln in enumerate(lines) if ln.startswith("  File ")]
    tail = lines[idx[-1] + 2:] if idx and idx[-1] + 2 < len(lines) else lines[-3:]
    tail = [ln for ln in tail if ln.strip() and set(ln.strip()) - set("^~")]
    msg = "\n".join(tail).strip()
    if len(msg) > limit:
        msg = msg[: limit // 2] + " ...[cut]... " + msg[-(limit // 2):]
    return msg


def _vacant_run(method_name):
    suite = _vacant_unittest.TestSuite([TestCases(method_name)])
    result = _vacant_unittest.TestResult()
    suite.run(result)
    if result.wasSuccessful() and result.testsRun == 1:
        return
    if result.failures:
        kind, tb = "FAIL", result.failures[0][1]
    elif result.errors:
        kind, tb = "ERROR", result.errors[0][1]
    elif result.unexpectedSuccesses:
        kind, tb = "UNEXPECTED SUCCESS", ""
    else:
        kind, tb = "NOT RUN", ""
    raise AssertionError("%s %s: %s" % (kind, method_name, _vacant_short(tb)))


def check_test_case_sensitive_handling():
    _vacant_run('test_case_sensitive_handling')

def check_test_empty_dataframe():
    _vacant_run('test_empty_dataframe')
