"""Visible checks for bcb_906 -- these ship with the task and can be run.

Rendered from bigcode/bigcodebench-hard v0.1.4 (BigCodeBench/906) by
ops/vacantrun/bcb_hard_bank_20260924/build_bank.py. The code below is the
dataset's unittest TestCases, restricted to the test methods that ship with
this task; each check_* runs one of those methods.
"""

from solution import *
import sys as _vacant_sys
import solution as _vacant_solution
_vacant_sys.modules.setdefault(__name__, _vacant_solution)

import unittest
class TestCases(unittest.TestCase):
    def setUp(self):
        # Setup test directories
        self.source_dir = 'task_func_data/'
        self.target_dir = 'task_func_data_target/'
        
        # Remove any existing test directories to start fresh
        if os.path.exists(self.source_dir):
            shutil.rmtree(self.source_dir)
        if os.path.exists(self.target_dir):
            shutil.rmtree(self.target_dir)
        # Create new test directories
        os.makedirs(self.source_dir)
        os.makedirs(self.target_dir)
    def tearDown(self):
        # Clean up test directories after each test case
        if os.path.exists(self.source_dir):
            shutil.rmtree(self.source_dir)
        if os.path.exists(self.target_dir):
            shutil.rmtree(self.target_dir)
    
    def test_case_1(self):
        # Create some test files in the source directory, some with '_processed' suffix
        test_files = ['file1.txt', 'file2_processed.txt']
        for file in test_files:
            with open(os.path.join(self.source_dir, file), 'w') as f:
                f.write(f"This is {file}")
        
        # Archive processed files
        archive_path = task_func(self.source_dir, self.target_dir)
        
        # Check if the archive contains the correct file
        with zipfile.ZipFile(archive_path, 'r') as archive:
            self.assertIn('file2_processed.txt', archive.namelist())
            
    def test_case_2(self):
        # Create some test files in the source directory without '_processed' suffix
        test_files = ['file1.txt', 'file3.txt']
        for file in test_files:
            with open(os.path.join(self.source_dir, file), 'w') as f:
                f.write(f"This is {file}")
        
        # Archive processed files
        archive_path = task_func(self.source_dir, self.target_dir)
        
        # Check if the archive is empty
        with zipfile.ZipFile(archive_path, 'r') as archive:
            self.assertEqual(len(archive.namelist()), 0)


# ── Vacant wrapper (generated by build_bank.py) ──────────────────────────
# Each check_* below runs exactly one TestCases method (with its setUp /
# tearDown) and raises AssertionError with a short message if it fails.
import unittest as _vacant_unittest

for _vacant_name in [_n for _n in list(globals()) if _n.startswith("check_")]:
    del globals()[_vacant_name]


def _vacant_short(tb_text, limit=700):
    lines = (tb_text or "").rstrip().splitlines()
    idx = [i for i, ln in enumerate(lines) if ln.startswith("  File ")]
    tail = lines[idx[-1] + 2:] if idx and idx[-1] + 2 < len(lines) else lines[-3:]
    tail = [ln for ln in tail if ln.strip() and set(ln.strip()) - set("^~")]
    msg = "\n".join(tail).strip()
    if len(msg) > limit:
        msg = msg[: limit // 2] + " ...[cut]... " + msg[-(limit // 2):]
    return msg


def _vacant_run(method_name):
    suite = _vacant_unittest.TestSuite([TestCases(method_name)])
    result = _vacant_unittest.TestResult()
    suite.run(result)
    if result.wasSuccessful() and result.testsRun == 1:
        return
    if result.failures:
        kind, tb = "FAIL", result.failures[0][1]
    elif result.errors:
        kind, tb = "ERROR", result.errors[0][1]
    elif result.unexpectedSuccesses:
        kind, tb = "UNEXPECTED SUCCESS", ""
    else:
        kind, tb = "NOT RUN", ""
    raise AssertionError("%s %s: %s" % (kind, method_name, _vacant_short(tb)))


def check_test_case_1():
    _vacant_run('test_case_1')

def check_test_case_2():
    _vacant_run('test_case_2')
