"""Visible checks for bcb_1015 -- these ship with the task and can be run.

Rendered from bigcode/bigcodebench-hard v0.1.4 (BigCodeBench/1015) by
ops/vacantrun/bcb_hard_bank_20260924/build_bank.py. The code below is the
dataset's unittest TestCases, restricted to the test methods that ship with
this task; each check_* runs one of those methods.
"""

from solution import *
import sys as _vacant_sys
import solution as _vacant_solution
_vacant_sys.modules.setdefault(__name__, _vacant_solution)

import unittest
from unittest.mock import patch, MagicMock
import requests
import sqlite3
import os
class TestCases(unittest.TestCase):
    """Test cases for task_func."""
    @patch("requests.get")
    def test_empty_table(self, mock_get):
        """
        Test handling an HTML page with an empty table.
        """
        mock_response = MagicMock()
        mock_response.content = b"<html><body><table></table></body></html>"
        mock_response.status_code = 200
        mock_get.return_value = mock_response
        result = task_func("http://example.com/empty")
        self.assertEqual(result, 0)
    @patch("requests.get")
    @patch("sqlite3.connect")
    def test_database_error(self, mock_connect, mock_get):
        """
        Test function behavior when encountering a database error.
        """
        # Mock the response from requests.get
        mock_response = MagicMock()
        mock_response.content = (
            b"<html><body><table><tr><td>Data</td></tr></table></body></html>"
        )
        mock_response.status_code = 200
        mock_get.return_value = mock_response
        # Simulate a database error
        mock_connect.side_effect = sqlite3.DatabaseError("mocked database error")
        # Expect a DatabaseError to be raised
        with self.assertRaises(sqlite3.DatabaseError):
            task_func("http://example.com", "faulty_database.db")
    def tearDown(self):
        """Remove the database file with retries."""
        if os.path.exists("my_database.db"):
            os.remove("my_database.db")


# ── Vacant wrapper (generated by build_bank.py) ──────────────────────────
# Each check_* below runs exactly one TestCases method (with its setUp /
# tearDown) and raises AssertionError with a short message if it fails.
import unittest as _vacant_unittest

for _vacant_name in [_n for _n in list(globals()) if _n.startswith("check_")]:
    del globals()[_vacant_name]


def _vacant_short(tb_text, limit=700):
    lines = (tb_text or "").rstrip().splitlines()
    idx = [i for i, ln in enumerate(lines) if ln.startswith("  File ")]
    tail = lines[idx[-1] + 2:] if idx and idx[-1] + 2 < len(lines) else lines[-3:]
    tail = [ln for ln in tail if ln.strip() and set(ln.strip()) - set("^~")]
    msg = "\n".join(tail).strip()
    if len(msg) > limit:
        msg = msg[: limit // 2] + " ...[cut]... " + msg[-(limit // 2):]
    return msg


def _vacant_run(method_name):
    suite = _vacant_unittest.TestSuite([TestCases(method_name)])
    result = _vacant_unittest.TestResult()
    suite.run(result)
    if result.wasSuccessful() and result.testsRun == 1:
        return
    if result.failures:
        kind, tb = "FAIL", result.failures[0][1]
    elif result.errors:
        kind, tb = "ERROR", result.errors[0][1]
    elif result.unexpectedSuccesses:
        kind, tb = "UNEXPECTED SUCCESS", ""
    else:
        kind, tb = "NOT RUN", ""
    raise AssertionError("%s %s: %s" % (kind, method_name, _vacant_short(tb)))


def check_test_database_error():
    _vacant_run('test_database_error')

def check_test_empty_table():
    _vacant_run('test_empty_table')
