"""Visible acceptance for s1_06_parity — rendered data, do not hand-edit.

Generated by ops/gain/r535/build_bank.py from ops/gain/r535/tasks_s1.
Every check is zero-argument and passes by returning normally
(vacant_network/vrun/acceptance.py runs them in definition order).
"""


def check_01_split_parity():
    from solution import split_parity
    args = ([1, 2, 3, 4],)
    got = split_parity(*args)
    want = {'even': [2, 4], 'odd': [1, 3]}
    assert got == want, "split_parity args=%r got=%r want=%r" % (args, got, want)


def check_02_split_parity():
    from solution import split_parity
    args = ([],)
    got = split_parity(*args)
    want = {'even': [], 'odd': []}
    assert got == want, "split_parity args=%r got=%r want=%r" % (args, got, want)
