"""Visible checks for bcb_1057 -- these ship with the task and can be run.

Rendered from bigcode/bigcodebench-hard v0.1.4 (BigCodeBench/1057) by
ops/vacantrun/bcb_hard_bank_20260924/build_bank.py. The code below is the
dataset's unittest TestCases, restricted to the test methods that ship with
this task; each check_* runs one of those methods.
"""

from solution import *
import sys as _vacant_sys
import solution as _vacant_solution
_vacant_sys.modules.setdefault(__name__, _vacant_solution)

import unittest
import random
class TestCases(unittest.TestCase):
    """Tests for the function task_func."""
    def test_default_input(self):
        """Test with default inputs for animals and foods."""
        random.seed(0)
        # Scenario: Testing with default inputs for animals and foods
        result = task_func()
        # Check the shape of the returned DataFrame
        self.assertEqual(
            result.shape,
            (10, 7),
            "The shape of the DataFrame with default inputs is not as expected.",
        )
    def test_custom_input(self):
        """Test with custom inputs for animals and foods."""
        random.seed(1)
        # Scenario: Testing with custom lists of animals and foods
        animals = ["Dog", "Cat", "Elephant"]
        foods = ["Meat", "Fish", "Grass", "Fruits"]
        result = task_func(animals, foods)
        # Check the shape of the returned DataFrame
        self.assertEqual(
            result.shape,
            (3, 4),
            "The shape of the DataFrame with custom inputs is not as expected.",
        )


# ── Vacant wrapper (generated by build_bank.py) ──────────────────────────
# Each check_* below runs exactly one TestCases method (with its setUp /
# tearDown) and raises AssertionError with a short message if it fails.
import unittest as _vacant_unittest

for _vacant_name in [_n for _n in list(globals()) if _n.startswith("check_")]:
    del globals()[_vacant_name]


def _vacant_short(tb_text, limit=700):
    lines = (tb_text or "").rstrip().splitlines()
    idx = [i for i, ln in enumerate(lines) if ln.startswith("  File ")]
    tail = lines[idx[-1] + 2:] if idx and idx[-1] + 2 < len(lines) else lines[-3:]
    tail = [ln for ln in tail if ln.strip() and set(ln.strip()) - set("^~")]
    msg = "\n".join(tail).strip()
    if len(msg) > limit:
        msg = msg[: limit // 2] + " ...[cut]... " + msg[-(limit // 2):]
    return msg


def _vacant_run(method_name):
    suite = _vacant_unittest.TestSuite([TestCases(method_name)])
    result = _vacant_unittest.TestResult()
    suite.run(result)
    if result.wasSuccessful() and result.testsRun == 1:
        return
    if result.failures:
        kind, tb = "FAIL", result.failures[0][1]
    elif result.errors:
        kind, tb = "ERROR", result.errors[0][1]
    elif result.unexpectedSuccesses:
        kind, tb = "UNEXPECTED SUCCESS", ""
    else:
        kind, tb = "NOT RUN", ""
    raise AssertionError("%s %s: %s" % (kind, method_name, _vacant_short(tb)))


def check_test_custom_input():
    _vacant_run('test_custom_input')

def check_test_default_input():
    _vacant_run('test_default_input')
