"""Hidden acceptance for s1_11_caps — rendered data, do not hand-edit.

Generated by ops/gain/r535/build_bank.py from ops/gain/r535/tasks_s1.
Every check is zero-argument and passes by returning normally
(vacant/vrun/acceptance.py runs them in definition order).
"""


def check_01_caps():
    from solution import caps
    args = ('hello world',)
    got = caps(*args)
    want = 'Hello World'
    assert got == want, "caps args=%r got=%r want=%r" % (args, got, want)


def check_02_caps():
    from solution import caps
    args = ("mcADAM o'neil",)
    got = caps(*args)
    want = "Mcadam O'neil"
    assert got == want, "caps args=%r got=%r want=%r" % (args, got, want)


def check_03_caps():
    from solution import caps
    args = ('',)
    got = caps(*args)
    want = ''
    assert got == want, "caps args=%r got=%r want=%r" % (args, got, want)


def check_04_caps():
    from solution import caps
    args = ('a',)
    got = caps(*args)
    want = 'A'
    assert got == want, "caps args=%r got=%r want=%r" % (args, got, want)


def check_05_caps():
    from solution import caps
    args = ('ALL CAPS HERE',)
    got = caps(*args)
    want = 'All Caps Here'
    assert got == want, "caps args=%r got=%r want=%r" % (args, got, want)


def check_06_caps():
    from solution import caps
    args = ('mixed CaSe words',)
    got = caps(*args)
    want = 'Mixed Case Words'
    assert got == want, "caps args=%r got=%r want=%r" % (args, got, want)


def check_07_caps():
    from solution import caps
    args = ('x y z',)
    got = caps(*args)
    want = 'X Y Z'
    assert got == want, "caps args=%r got=%r want=%r" % (args, got, want)
