"""Visible checks for bcb_594 -- these ship with the task and can be run.

Rendered from bigcode/bigcodebench-hard v0.1.4 (BigCodeBench/594) by
ops/vacantrun/bcb_hard_bank_20260924/build_bank.py. The code below is the
dataset's unittest TestCases, restricted to the test methods that ship with
this task; each check_* runs one of those methods.
"""

from solution import *
import sys as _vacant_sys
import solution as _vacant_solution
_vacant_sys.modules.setdefault(__name__, _vacant_solution)

import unittest
from unittest.mock import patch, mock_open
FILE_PATH = os.path.join(OUTPUT_DIR, 'weather_data.csv')
BACKUP_PATH = os.path.join(OUTPUT_DIR, 'backup/')
class TestCases(unittest.TestCase):
    expected_file_path = FILE_PATH
    backup_file_path = BACKUP_PATH
    def setUp(self):
        """Set up the environment for testing."""
        # Ensure the backup directory exists
        os.makedirs(self.backup_file_path, exist_ok=True)
        # Create an empty weather_data.csv or set it up as required
        with open(self.expected_file_path, 'w') as f:
            f.write("Time,Condition\n")  # Example: Write a header or initial content
    def tearDown(self):
        """Clean up any files created during the tests."""
        # Check and remove the expected file if it exists
        if os.path.exists(FILE_PATH):
            os.remove(FILE_PATH)
        # Check if the backup directory exists and remove it
        if os.path.exists(BACKUP_PATH):
            shutil.rmtree(BACKUP_PATH)
    def test_backup_file_creation(self):
        """Test that the CSV file is correctly copied to the backup directory."""
        with patch('shutil.copy') as mock_copy:
            task_func(1)
            mock_copy.assert_called_once_with(FILE_PATH, BACKUP_PATH)
    @patch('csv.writer')
    def test_csv_writing(self, mock_csv_writer):
        """Test if CSV writer is called with correct parameters."""
        task_func(1)
        mock_csv_writer.assert_called_once()


# ── Vacant wrapper (generated by build_bank.py) ──────────────────────────
# Each check_* below runs exactly one TestCases method (with its setUp /
# tearDown) and raises AssertionError with a short message if it fails.
import unittest as _vacant_unittest

for _vacant_name in [_n for _n in list(globals()) if _n.startswith("check_")]:
    del globals()[_vacant_name]


def _vacant_short(tb_text, limit=700):
    lines = (tb_text or "").rstrip().splitlines()
    idx = [i for i, ln in enumerate(lines) if ln.startswith("  File ")]
    tail = lines[idx[-1] + 2:] if idx and idx[-1] + 2 < len(lines) else lines[-3:]
    tail = [ln for ln in tail if ln.strip() and set(ln.strip()) - set("^~")]
    msg = "\n".join(tail).strip()
    if len(msg) > limit:
        msg = msg[: limit // 2] + " ...[cut]... " + msg[-(limit // 2):]
    return msg


def _vacant_run(method_name):
    suite = _vacant_unittest.TestSuite([TestCases(method_name)])
    result = _vacant_unittest.TestResult()
    suite.run(result)
    if result.wasSuccessful() and result.testsRun == 1:
        return
    if result.failures:
        kind, tb = "FAIL", result.failures[0][1]
    elif result.errors:
        kind, tb = "ERROR", result.errors[0][1]
    elif result.unexpectedSuccesses:
        kind, tb = "UNEXPECTED SUCCESS", ""
    else:
        kind, tb = "NOT RUN", ""
    raise AssertionError("%s %s: %s" % (kind, method_name, _vacant_short(tb)))


def check_test_backup_file_creation():
    _vacant_run('test_backup_file_creation')

def check_test_csv_writing():
    _vacant_run('test_csv_writing')
