"""Hidden acceptance for s2_19_group_by_first — rendered data, do not hand-edit.

Generated by ops/gain/r535/build_bank.py from ops/gain/r535/tasks_s2.
Every check is zero-argument and passes by returning normally
(vacant_network/vrun/acceptance.py runs them in definition order).
"""


def check_01_group_by_first():
    from solution import group_by_first
    args = (['Apple', 'ant', 'Bee'],)
    got = group_by_first(*args)
    want = {'a': ['Apple', 'ant'], 'b': ['Bee']}
    assert got == want, "group_by_first args=%r got=%r want=%r" % (args, got, want)


def check_02_group_by_first():
    from solution import group_by_first
    args = (['', 'x'],)
    got = group_by_first(*args)
    want = {'x': ['x']}
    assert got == want, "group_by_first args=%r got=%r want=%r" % (args, got, want)


def check_03_group_by_first():
    from solution import group_by_first
    args = ([],)
    got = group_by_first(*args)
    want = {}
    assert got == want, "group_by_first args=%r got=%r want=%r" % (args, got, want)


def check_04_group_by_first():
    from solution import group_by_first
    args = (['z'],)
    got = group_by_first(*args)
    want = {'z': ['z']}
    assert got == want, "group_by_first args=%r got=%r want=%r" % (args, got, want)


def check_05_group_by_first():
    from solution import group_by_first
    args = (['A', 'a'],)
    got = group_by_first(*args)
    want = {'a': ['A', 'a']}
    assert got == want, "group_by_first args=%r got=%r want=%r" % (args, got, want)


def check_06_group_by_first():
    from solution import group_by_first
    args = (['one', 'two'],)
    got = group_by_first(*args)
    want = {'o': ['one'], 't': ['two']}
    assert got == want, "group_by_first args=%r got=%r want=%r" % (args, got, want)


def check_07_group_by_first():
    from solution import group_by_first
    args = (['', ''],)
    got = group_by_first(*args)
    want = {}
    assert got == want, "group_by_first args=%r got=%r want=%r" % (args, got, want)
