"""Visible acceptance for s1_30_ord_suffix — rendered data, do not hand-edit.

Generated by ops/gain/r535/build_bank.py from ops/gain/r535/tasks_s1.
Every check is zero-argument and passes by returning normally
(vacant_network/vrun/acceptance.py runs them in definition order).
"""


def check_01_ord_suffix():
    from solution import ord_suffix
    args = (1,)
    got = ord_suffix(*args)
    want = '1st'
    assert got == want, "ord_suffix args=%r got=%r want=%r" % (args, got, want)


def check_02_ord_suffix():
    from solution import ord_suffix
    args = (12,)
    got = ord_suffix(*args)
    want = '12th'
    assert got == want, "ord_suffix args=%r got=%r want=%r" % (args, got, want)
