"""Hidden acceptance for s2_25_truncate — rendered data, do not hand-edit.

Generated by ops/gain/r535/build_bank.py from ops/gain/r535/tasks_s2.
Every check is zero-argument and passes by returning normally
(vacant/vrun/acceptance.py runs them in definition order).
"""


def check_01_truncate():
    from solution import truncate
    args = ('abcdefgh', 5)
    got = truncate(*args)
    want = 'ab...'
    assert got == want, "truncate args=%r got=%r want=%r" % (args, got, want)


def check_02_truncate():
    from solution import truncate
    args = ('abc', 3)
    got = truncate(*args)
    want = 'abc'
    assert got == want, "truncate args=%r got=%r want=%r" % (args, got, want)


def check_03_truncate():
    from solution import truncate
    args = ('', 5)
    got = truncate(*args)
    want = ''
    assert got == want, "truncate args=%r got=%r want=%r" % (args, got, want)


def check_04_truncate():
    from solution import truncate
    args = ('abcd', 4)
    got = truncate(*args)
    want = 'abcd'
    assert got == want, "truncate args=%r got=%r want=%r" % (args, got, want)


def check_05_truncate():
    from solution import truncate
    args = ('abcde', 4)
    got = truncate(*args)
    want = 'a...'
    assert got == want, "truncate args=%r got=%r want=%r" % (args, got, want)


def check_06_truncate():
    from solution import truncate
    args = ('hello world', 8)
    got = truncate(*args)
    want = 'hello...'
    assert got == want, "truncate args=%r got=%r want=%r" % (args, got, want)


def check_07_truncate():
    from solution import truncate
    args = ('xyz', 10)
    got = truncate(*args)
    want = 'xyz'
    assert got == want, "truncate args=%r got=%r want=%r" % (args, got, want)


def check_08_truncate():
    from solution import truncate
    args = ('abcdef', 3)
    got = truncate(*args)
    want = '...'
    assert got == want, "truncate args=%r got=%r want=%r" % (args, got, want)
