"""Visible checks for bcb_1053 -- these ship with the task and can be run.

Rendered from bigcode/bigcodebench-hard v0.1.4 (BigCodeBench/1053) by
ops/vacantrun/bcb_hard_bank_20260924/build_bank.py. The code below is the
dataset's unittest TestCases, restricted to the test methods that ship with
this task; each check_* runs one of those methods.
"""

from solution import *
import sys as _vacant_sys
import solution as _vacant_solution
_vacant_sys.modules.setdefault(__name__, _vacant_solution)

import unittest
from unittest.mock import patch
import matplotlib.pyplot as plt
import os
class TestCases(unittest.TestCase):
    """Test cases for task_func."""
    def tearDown(self):
        """Clean up by removing files created during tests."""
        plt.close()
        if os.path.exists("test_output.png"):
            os.remove("test_output.png")
    @patch("pandas.read_csv")
    def test_display_plot(self, mock_read_csv):
        """
        Test if the function displays a plot correctly when no save path is provided.
        """
        # Mock data
        mock_read_csv.return_value = pd.DataFrame(
            {"Text": ["word1 word2 word3", "word2 word3 word4"]}
        )
        # Test
        result = task_func("dummy_path.csv")
        print(result)
        self.assertIsNotNone(result)
    @patch("pandas.read_csv")
    def test_empty_file(self, mock_read_csv):
        """
        Test the function's behavior with an empty file.
        """
        # Mock data
        mock_read_csv.return_value = pd.DataFrame({"Text": []})
        # Test
        result = task_func("dummy_path.csv")
        self.assertIsNone(result)


# ── Vacant wrapper (generated by build_bank.py) ──────────────────────────
# Each check_* below runs exactly one TestCases method (with its setUp /
# tearDown) and raises AssertionError with a short message if it fails.
import unittest as _vacant_unittest

for _vacant_name in [_n for _n in list(globals()) if _n.startswith("check_")]:
    del globals()[_vacant_name]


def _vacant_short(tb_text, limit=700):
    lines = (tb_text or "").rstrip().splitlines()
    idx = [i for i, ln in enumerate(lines) if ln.startswith("  File ")]
    tail = lines[idx[-1] + 2:] if idx and idx[-1] + 2 < len(lines) else lines[-3:]
    tail = [ln for ln in tail if ln.strip() and set(ln.strip()) - set("^~")]
    msg = "\n".join(tail).strip()
    if len(msg) > limit:
        msg = msg[: limit // 2] + " ...[cut]... " + msg[-(limit // 2):]
    return msg


def _vacant_run(method_name):
    suite = _vacant_unittest.TestSuite([TestCases(method_name)])
    result = _vacant_unittest.TestResult()
    suite.run(result)
    if result.wasSuccessful() and result.testsRun == 1:
        return
    if result.failures:
        kind, tb = "FAIL", result.failures[0][1]
    elif result.errors:
        kind, tb = "ERROR", result.errors[0][1]
    elif result.unexpectedSuccesses:
        kind, tb = "UNEXPECTED SUCCESS", ""
    else:
        kind, tb = "NOT RUN", ""
    raise AssertionError("%s %s: %s" % (kind, method_name, _vacant_short(tb)))


def check_test_display_plot():
    _vacant_run('test_display_plot')

def check_test_empty_file():
    _vacant_run('test_empty_file')
