"""Hidden acceptance for s2_01_mean — rendered data, do not hand-edit.

Generated by ops/gain/r535/build_bank.py from ops/gain/r535/tasks_s2.
Every check is zero-argument and passes by returning normally
(vacant_network/vrun/acceptance.py runs them in definition order).
"""


def check_01_mean():
    from solution import mean
    args = ([1, 2, 4],)
    got = mean(*args)
    want = 2.333
    assert got == want, "mean args=%r got=%r want=%r" % (args, got, want)


def check_02_mean():
    from solution import mean
    args = ([],)
    got = mean(*args)
    want = 0.0
    assert got == want, "mean args=%r got=%r want=%r" % (args, got, want)


def check_03_mean():
    from solution import mean
    args = ([1, 2, 3],)
    got = mean(*args)
    want = 2.0
    assert got == want, "mean args=%r got=%r want=%r" % (args, got, want)


def check_04_mean():
    from solution import mean
    args = ([0],)
    got = mean(*args)
    want = 0.0
    assert got == want, "mean args=%r got=%r want=%r" % (args, got, want)


def check_05_mean():
    from solution import mean
    args = ([1, 1, 1, 1],)
    got = mean(*args)
    want = 1.0
    assert got == want, "mean args=%r got=%r want=%r" % (args, got, want)


def check_06_mean():
    from solution import mean
    args = ([1, 2],)
    got = mean(*args)
    want = 1.5
    assert got == want, "mean args=%r got=%r want=%r" % (args, got, want)


def check_07_mean():
    from solution import mean
    args = ([2, 3, 4, 5],)
    got = mean(*args)
    want = 3.5
    assert got == want, "mean args=%r got=%r want=%r" % (args, got, want)


def check_08_mean():
    from solution import mean
    args = ([1, 2, 2],)
    got = mean(*args)
    want = 1.667
    assert got == want, "mean args=%r got=%r want=%r" % (args, got, want)
