"""Visible checks for bcb_826 -- these ship with the task and can be run.

Rendered from bigcode/bigcodebench-hard v0.1.4 (BigCodeBench/826) by
ops/vacantrun/bcb_hard_bank_20260924/build_bank.py. The code below is the
dataset's unittest TestCases, restricted to the test methods that ship with
this task; each check_* runs one of those methods.
"""

from solution import *
import sys as _vacant_sys
import solution as _vacant_solution
_vacant_sys.modules.setdefault(__name__, _vacant_solution)

import unittest
import os
import shutil
from faker import Faker
import tempfile
class TestCases(unittest.TestCase):
    def setUp(self):
        # Set up temporary directories for the source and target
        self.test_dir = tempfile.mkdtemp()
        self.source_dir = os.path.join(self.test_dir, 'source')
        self.target_dir = os.path.join(self.test_dir, 'target')
        os.makedirs(self.source_dir, exist_ok=True)
        os.makedirs(self.target_dir, exist_ok=True)
        # Create files that match and do not match the pattern
        self.match_files = ['file1.txt', 'document1.doc', 'notes.docx']
        self.no_match_files = ['image.png', 'data.csv', 'script.js']
        for file in self.match_files:
            with open(os.path.join(self.source_dir, file), 'w') as f:
                f.write('Hello World')
        for file in self.no_match_files:
            with open(os.path.join(self.source_dir, file), 'w') as f:
                f.write('Hello World')
    def tearDown(self):
        # Remove the test directory after each test
        shutil.rmtree(self.test_dir)
    def test_directory_does_not_exist(self):
        # Test handling of a non-existent source directory
        shutil.rmtree(self.source_dir)
        with self.assertRaises(FileNotFoundError):
            task_func(self.source_dir, self.target_dir)
    def test_empty_source_directory(self):
        # Test with an empty source directory
        for file in os.listdir(self.source_dir):
            os.remove(os.path.join(self.source_dir, file))
        result = task_func(self.source_dir, self.target_dir)
        self.assertEqual(result, 0)
        self.assertEqual(len(os.listdir(self.target_dir)), 0)


# ── Vacant wrapper (generated by build_bank.py) ──────────────────────────
# Each check_* below runs exactly one TestCases method (with its setUp /
# tearDown) and raises AssertionError with a short message if it fails.
import unittest as _vacant_unittest

for _vacant_name in [_n for _n in list(globals()) if _n.startswith("check_")]:
    del globals()[_vacant_name]


def _vacant_short(tb_text, limit=700):
    lines = (tb_text or "").rstrip().splitlines()
    idx = [i for i, ln in enumerate(lines) if ln.startswith("  File ")]
    tail = lines[idx[-1] + 2:] if idx and idx[-1] + 2 < len(lines) else lines[-3:]
    tail = [ln for ln in tail if ln.strip() and set(ln.strip()) - set("^~")]
    msg = "\n".join(tail).strip()
    if len(msg) > limit:
        msg = msg[: limit // 2] + " ...[cut]... " + msg[-(limit // 2):]
    return msg


def _vacant_run(method_name):
    suite = _vacant_unittest.TestSuite([TestCases(method_name)])
    result = _vacant_unittest.TestResult()
    suite.run(result)
    if result.wasSuccessful() and result.testsRun == 1:
        return
    if result.failures:
        kind, tb = "FAIL", result.failures[0][1]
    elif result.errors:
        kind, tb = "ERROR", result.errors[0][1]
    elif result.unexpectedSuccesses:
        kind, tb = "UNEXPECTED SUCCESS", ""
    else:
        kind, tb = "NOT RUN", ""
    raise AssertionError("%s %s: %s" % (kind, method_name, _vacant_short(tb)))


def check_test_directory_does_not_exist():
    _vacant_run('test_directory_does_not_exist')

def check_test_empty_source_directory():
    _vacant_run('test_empty_source_directory')
