"""Scoring checks for lcb_3573 -- NOT part of any workspace.

⚠ 計分用的 GT。住在 hidden/ 這棵**另外的樹**，永遠不複製進 agent 的工作區；
  任何把它的內容（含失敗訊息）回饋給模型的路徑都作廢那一批資料。

case 組成 ＝ 題庫的 `visible_tests` ＋ `hidden_tests`（超集），與
vacant_network/codebench.py::LiveCodeBenchLoader 的 `hidden_check` 同一組（ops/gain/data/lcb_bank_v2.jsonl）。
"""

import solution

def _aeq(a, b):
    """與 vacant_network/codebench.py::_lcb_check_code 的 __aeq 同一套判等（逐行對應）。"""
    try:
        if a == b:
            return True
    except (TypeError, ValueError):
        pass
    if isinstance(a, bool) != isinstance(b, bool):
        return False
    if isinstance(a, (int, float)) and isinstance(b, (int, float)):
        return abs(a - b) <= 1e-6
    if isinstance(a, (list, tuple)) and isinstance(b, (list, tuple)):
        return len(a) == len(b) and all(_aeq(x, y) for x, y in zip(a, b))
    return a == b


def check_case_01():
    args = ['bcca', 'abc']
    want = 1
    got = solution.validSubstringCount(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_02():
    args = ['abcabc', 'abc']
    want = 10
    got = solution.validSubstringCount(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_03():
    args = ['abcabc', 'aaabc']
    want = 0
    got = solution.validSubstringCount(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_04():
    args = ['ccccccccccccccc', 'cc']
    want = 105
    got = solution.validSubstringCount(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_05():
    args = ['bbbb', 'b']
    want = 10
    got = solution.validSubstringCount(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_06():
    args = ['nnnnnnnnnn', 'n']
    want = 55
    got = solution.validSubstringCount(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_07():
    args = ['u', 'g']
    want = 0
    got = solution.validSubstringCount(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_08():
    args = ['yhiwfpzedrknoqvctlhjdxtdixazuxsbmtzzrvrdnqwioaehcsfasjhdwmlcxouhxtwdmmktcptobweymwtmnlwsfirauiqxefbnqrxlfbrqwmfaknuwxnxnfclmlovoarhcztwfsobkbpwtzhxfcngpbfelkimcumippwbaxtvfpnxjrqedarqjiwdlgvqxwsmemrghhlsodzduumqxtsmgjtxhiaddorpfeiewsjojfsctqjmwauhjhgbgyjjsoffanmeclszfjrgnhtobzthlibywdklhmiscedzyblijjskgtzhsgwwsduhxuauhkmefqsfavrlcthncoajbfsvebvulngbwcykncpmoybchonoyblnxyzsgesasohfclepwtrzsrhkwzausjefgslnzoqiqzahxqxkfqzyivsapbluwhgkhjeqoqukmlnpcaacejopdnacrjebpdiimbwykdzmyzvjpeogzfxcugrzdajurxnanhkfxnvqzrjcagbfhgjkwuqfuzrccrbqwjgvxuzbdfnmegywunhwrmlqyazsjrbitorqaroewhemwgslsjawjabvdbntxwdfpmbvbcaffygcfekhqsbgnpzkpqnbpvpsgjtnmyaofhywifsucvxxbudnkyccxovalbzzsfcbvnddkfsasxadcvrgyeomajycuyvdccegkuvtetnrsuywmtewyqmiypvoqflclmaxpaqvnyxksgmvlpkavurlqtzblbbixbcazxowmpoteqfuchryozzlhkaktvccqupzyyzgipgatzesxlkvkejbuudzyxwqvyinqdhurjokujrkxqhplbycdqztbviimizpmyyyhzehuugippkhjzpmdwvjnsqepmuxnjwvmfamgdgwbtkhywgsuyenfmfsfwheozhydguljfkkwnzydcdcjuagtdkcbbngxrsydubfoddkrhieyqpthnxukxtgobkvlvnyjnxzxiziubwvcxesyvmonvyqbpdixipntscbzvrmmyeskqdmidspssdddqzqjszbwqmubqtzpdioiimsrysqbxrizirnzvarycjrdqhneziiecrahkwyvvdfpfjrhxvrdubiepklojtjwvhnkallvknhvjbbcjcplbegrkbbbvmxsghvshksvghtzvwfbpqvogkodzgwmpqdbuyjdswcnfpizqtokvirxykunbwqfvfssifwmbkkonzoaefnhmjmbaklgwmglnrsvcyjyyqaxttmzjzpcnxpzqxamddmflmjubyvtcolcduldajnidgasxpfieopisyrnkzbecdquzlpaiotukbtedoscjrcrpbrrgzpplnhlwljwldujxdnlzvsallfatumvfyrkbfxiahkhwbnltvrlpqqpaoneacwizpmvgyetmujqjnngafqfktnsjlklaeogtzggoicdbsluoqnwblzmdztyrqnirevqgvhugnobvowladzxwwqcwomwhrpztbqudclxscemjrzptgmskoxobxuvqggqybrepbccbsednglrekvkmvtzajewdxzynsjjeljkmtoqfsxlnbynkjmuiilmudqeictfiayjdsaajgazrpvxqzbsrvhbnupghfcfjxcsqjvgitrbuqbkxjxhqbpmanuurwkwrlydhbokysddkqywmpcmycbiotjiafobikqrazbqqmujgntysnqytsdxppexkyubpzcayguupuuinmkxlkrigtutvkldufzalxsrbiqdddlhamzqsdcunfvanjndbznmjkkzhdijgrrkxkdfzysepzdyzyidoitisupvfyssagipqpoueulzztgdfxjxdngisanepbgmmfgnxexemecdjavwfyrzmejgvgdbmqevmkgxyryewegyrmdzbwcgvadfzckrtftlyzgoupfihidgtaibxafzntuluhjyfuzkyjjqtvrqfnnjcgwonddtvwguvejvtntwoqkthngrvwjqgougiqzmxrtwddfdpkrjonevwdvrxejtqdznrecqhmyrkcwljakqsodqv', 'zctgulwtlddcibsulrpjfnundgptmgkjnvunlrkxpgtuwbzvgqjvdwgmvcedcgqdntbrdswcntplarhuhtevzkepivonljawjaohlsgozrvnvblrkwhcayieqjcdgezgusdilzkupxezauuwpmxfkajedwhtychrshuypifmlqfuczmbsfwnyqxchdhyerdixtxvjppythjdlflpfmdhvyaqbuexzymettyclumaxqptjbxbvnknlhmzjzjxqmfqewsakklhzffpphxrrbadpogawrvcoogmrbrqypyueachqfprkanyotaqfliklcjmvjravuidnivszgfnsjuweljxkrzctthamqeksoehzwkwsaesjymhlfhxgmjtpqwbapeqdqhzqpvoxhlzmwwmejritlhrctyvhetlklgcpuneeyiapivnwyamuxdpofdhnevvuwamisflldpqkmbvvwtyygsmaddyanzpwpmppjdwgskckuevrjgckttdpolpuwswdpcrzpjuydzxrwpvxxosjjpovezynaicmqqvnvdrsesvrhhotxfkfyfavapmylzgqtoqkkitbdvlcyfgnxcnieakebpfhkihvxummiptygrkelpuxwcsrssvattyzsbxehzbdtwrwxgigzahrytcashmeufyupxzfrklhamvydzkntddiqzjlinpckubpgiobxogtqvxzpmlfgdlcezsxuqkkwaqffirmxvuqmljuoksmmhkfpyhxszxoqgmerqklzmkczlfbnpuhxjyebtcxbpinrijrxkjgtapjovxgizbdnkqixwisefzbscvuxjnvnxvdhtlltffhbxgqtgcbilsljzcxvzhdghuliebkbwrogubgaluobjcbagyjqlcdviormmhwvkyvnryizujfknsozdpynxgjyznsgzbwqixlirhojstinfucszsrtodfvppeixiojnoptenancozxatspalirejviay']
    want = 202789
    got = solution.validSubstringCount(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_09():
    args = ['ciffidgzggssjrqzxftwiyurpuivlhvovdfabdvrilpoaeymjawthxawazlj', 'vvhlkhlcy']
    want = 0
    got = solution.validSubstringCount(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_10():
    args = ['ffffffffffffff', 'ff']
    want = 91
    got = solution.validSubstringCount(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_11():
    args = ['cccccccccccc', 'cc']
    want = 66
    got = solution.validSubstringCount(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_12():
    args = ['hhh', 'h']
    want = 6
    got = solution.validSubstringCount(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_13():
    args = ['sfbvsatjiykeidkippnlessbpihlcystltzuogmlxzljmefpgcgleaacpuwhivefcbxniytzvmtmctyhubuptmtukblvr', 'xfpfzg']
    want = 1401
    got = solution.validSubstringCount(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_14():
    args = ['jjjjj', 'j']
    want = 15
    got = solution.validSubstringCount(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_15():
    args = ['ooo', 'o']
    want = 6
    got = solution.validSubstringCount(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_16():
    args = ['fpbtykkkjjvkcxnwvtoveypfhpzajcklcuiyaaruejkhzvuxxooqiizeqtuhajcwoknqnwhpsjttrrsjwzmsmutpqllvliksyrznwhtrbwvwvcmmaycqiwbcxiytxlgjlysclyeniozgfaknqfaxopanaarotviyojizcsgphxhjcjhuyxdottosogyfmfgnfvbsbajxszrmqrfmnoeupquuckvqredrdooqibwfjxofyghsipylduusroengzulbcrswvaguukddbkkqjfxsaatsmurrkgtrmchlzrnnqqvyqbctypsoaprlkafpctonwvwbhuqxcqxarplnwgkpqjtwinxuihqkdyvkxuqbbisvuymsorcymiejyuiojtfbcygleusqeqypqfoamgatwkjxhaidotuoojcangoerdrdftjrbtbtmzctkabuisjvantttynwdgrixxwadinogmjuxmlrctunrgiybpgiafeskxprrjuxgrqfucbafbytdendzibstpnbiwsolbslsnekcrksdzrjaseebzefddfrmjyxscmawqsldjcyhevsvokovwchzohiajjfifcrskigqoynbuasufsmpslylgrfabcrcykjifxzvvfglyxxflhuialkrivhrricpxneigztomwbvcsxvqqcrivjhivadxfsfvaiwnnucylpczcdefcvwmmwhdjzvnennpfcbjdzmcltwzknzvuqhhwnlgwrokwywzzgjejjpjnaaefdbtyjmqxcbpudqdmongmpthazkhkrjinqlvnsjaohaqpqtmfxloqlbxxynmgmfyrsjyawrwdbujwbyjbjnjgxqetrcuuxadoabbwrvktkarfrjlacyarpgprpbkploagovucylzvnmexjjvpnwiikmjdbrxbqtowgigdxoferuczqwcdkmmonbxfubysqvnrlzseihfnyewvqrxpvbngbgtesezevugfupgywpcjvpeikynozyxrdoyssyszxpirtljggucfeobxfvqykeyjutvmqzfgopszvkotnadknsvwykpzahuhffpoqeinvztbkytixblzztadpoiumjfszclombpedorxpdoncfjqxcpijmeaqhbfvujvcoumaietucuqcohqmjlftukumjtoznyqlqebufbhlswjzoxojpkjnrmwvqvtfwjafatonppwgpiwkkezkgptdsmbqqtphidrvazmtfltgexqnqghyrcfffdqnymqoiwgaqhugziterrxjuusjpxjrxxybgbawlmegqunwaykvzwdigdbypnebtfnfslbcgapjzbuymyyzqqtewdtfslxfxyffbdtugmqummfvjwwghkxaznjeobdkcoznafziexvdhvvelgmmtldqjamavbjwskzyddnltfhhivnkqmgmjhlufwkortkvzxmxyqtdknljhdanshahwcwvcnaktmumrtlcmecgkggzqxyikonrxmhqqzkyaujxdbdvffoghyoebvrztnlvidraqikoyrdofixpmiidqpksrmclkdniwlvshwgxnaksghhemazdlctravfllwqgfzsivuqaptvrcwtokhbnoimvepgxrioemisasfapjpfcweagctsizdkltpgpggygazwhmlqepfsiikzjjoktkccptuabhhdpgkfhyftswtnxfyidzfyrhsyegbqtaxcmketuuksvadbpzcmicqbbfjhculfndhlnnzrbwwxehxhwcvclduulzzlpaztrtmxwiwgxexfpebvgnislkhnkpqvutbzymgkarzpsahwdgcretnjztdvfaeeouyrxjkjtjoaoxcswsmmdqqzwdcxcblfibikrbytusuxywirixetzaihmwsoieqndpbmokddomxvgpemhvuvzcjbubauqwehuxamsxlhobwsoqcopoqviqsflvnznnlwrnjflqqqblbckpdnjmxhsocyyrqnubqhoeretuxvlwhotbcogstndpufaafxoxptrcklilckbisuiqrsbhawyzjjaibivecugrlnsuauolwuvjdkgrzodvwlfctzxjdkbdeztmketbfkruedfdbvlphvdsniurcsbdorixplyphlxcihlgspluojhypmvmnjhplddngumsflydocgpjeovqxmzzniyeqjsnmtkjtsszqdamlfdgkyiaaxipsyvqmregkniromtjxuxhpvavofnpwxsxdhzakprguxsmympeylkzjxrqamtlpyfogesosthldiagbobxyctukmhcfvkpghthvuzapjnvsgrsprjhfsuywljnjbzhykqjlzfkaioezriqsiqifiafdukchcpgqecvvptxhlyqnakgfewgabgxzxytymqcqfzzginiqxnpkniyvysvqojywsnmythcywbqpywyajikpxcyfocztvftudnizcxvooxrdvmjkbxjvbxsmjpwzouydrrsiooiozedokqzqdhpqrqenakppwabeqomoamcuhdrcrprdzrotkloomdvnsfsgqjccoumzteffyzufxjonvzmkdrjbcngfufxihrdbzgpwbojfvhqwcpxfljpisbnalrvrmntsxkrmkxngqxqogslklsfibchmcqvkxumjgmcvhykxlqhwtulhhfcjgxkbjjsyhyfgglfrmdwlynqvfcxfkmkirvulqkyllngaclbyudcjksnpeestzhjudrjcbhdwyjnxdvczjvipmcnfkiponqcsvxbymuvcnvqfueuaylyrlrkplbvomnigfctuptiataugfgudemakapyovfwxeoacysovoqghscvttzaleekruuwehyqmairobqrggasayidyoxamwwclkbgmyfaytgohbodnkdwssxnkojxwtqbwwbjqnqafhapkzhnpcpdzfqtmvoaxijnraudltwdhrfaqcemmqatrikhwshmsijavxeqdhstqexccpgbwvvbllqnenzpukpxmdriatxnkuukvzcqzxslwfyodzdfhmqixjxijqugeaximuripkvldhwrfoscnkzdxebvvtwdlqjipcstvrqqxpfdxbxemkrmfofcbsviilynnasbvbdndznywtdtboqjepqvffmfafxmpzodbvkfcdnqrggmenxaiklggkfwrlbnoummgaxayhrvlxlkjkdtsqkkydhxnzrtwfvyoregdmbcyrpbizqtfprnuspwwlxxxzyupisulgqijqkpqfkxdtyphjrmgcjvmwkdnzyykdjrxafcwvzgccghpneqrqplnmfjukxjfttpxgqvhtbbvwwduksomlwgpxrtfyhymrdpgcbqjesjsklsanhqpkamtmbslzbhpszgjowdixmwsnwazeosbhwkobsgugqmrayimukohybsbfbfnqgzyszflftszxlqdiohiwkfwtgpupyahqqjxuvshalaksjsjbjtjywkqjgbqaigdzcnrnyaiagncdtztapegrvoqmcdhaapigppnkzggqzbxoxbkujwtkqlnbanyqnbtlwruxvgiyzjmwddtndcmvqpwllihinkfwrgcxheskhwropnhqsxywwsqfidkuugsqucklmxrdfnggqjdbayhynmksqjprrsxarvbzgcrmsayekcsinyqlqiajnmhfukweqpimonnyxpszenurccpvakqczbyakurzmxyqozwylpihdbxnmlnomjfzjxmhhajkzogdsaqlqqflrkrfxlbvloyjnatfjeicbnvzdzdfvcilryrugqmluqvbkjvekyexmvlptoykiiaspcachvsylbfxowymqhkkvcjgluzznsrsgwlgurveolyagfchlkkhpsuopibdhrjxutrozariettsvudsbgoxlzfnpkjgecfauwcifhuelibolzzuswavipgcwdvglglsydcviqnyfuokellsonqfqyzwbafhsibucetlhlhbgjscfawajaczmyqockeezkilqspieexhpvtkxupqrgfhbrgnkcmaszrzaxvmgozdrnqjopfiknfydopyckubjdqdpzvytegpiauffrbdzrxqkfnkidxmttuymjcsvgrcaskephlsxxycvcrlpxmfspsbmwvjntdmjmmoonwiertfhcrsrgmohaolskxkisjfusuludatvmwxcufxugsaiyovflktslvksiwohpjqquqrigfpkpeenmhxfoofkcsqykidqvtnatfgdwriyxectiywwgksxbzcwakmdlhpoxtxqredsiyhvjtvisweekwzbcelrmkmwguwuynqvnxhvprdiimgnipwhznshsdzrftkryyxuuvalgccrvpgyphgdpbueislgonzdtmyrcojkfsyacwduhkwnhgmzsevcscnvxvjrckgcpalrtknwekxviblmqiuwouhrlcozlzkuligxkwgfthpqujynwbgajfwesbfmkglgemxgjidrjdxnywijqpbozgdhnautwtrwzwkfiyobrvgvvyycguxwabxakaylwxbuxpbulrghsooydfnrskgdvxtmmleejwpyqcyoogpjcbrxrndbiryszamquibueuxyulcbjbzvlvshsefbobwjdkapfvzvxvvcukhkevgfotmdrowtgkagafviaciyjhctbfbsnazzmsdzxltdakpimixqhcmgpdctwnbuxfyxzruruuogkbcnbhduslipfoecwqdnlxtlakzgpbqiubcydxnlvbnxzqeqkvbfjtiqsejrhsffwtxvysfmbixbjxptucnpqnlecjkjpdyezfrytynierbanadvzjulunjfwdlwxdojmrshgfnwqgvmjbwbrzjfizmvwieqxdwaflelmmrhesnoghekicvwdympotutztodwfhhizatexqgxvgvzstshcrwbbvurmelssfoakkqohbqemogapktcogvptvknzmlcpzgjlzmxfvwoxwbkndqgnjihyjbitbxxpguxmvscmhwplqrvlqoyhbpwmzhdrhaicgkvoehezosilzianobfzupzyofrtlpddcrirfrsmabebzyompoufqsswnvbplfxpyjskehepumbccvmckvejcbtabbuiqjfrfshrzmjsfbtzxpulfitgogjebequdlmkwkgnbgservlkwoqxmcbkbgghsnqxhcakqruaejkgdlpmuqpjwrdnvhcpjozkfmenjpgwhmfcqavufxlymeypcxlfavtvyzahcualrzeefyffqpjyehwwbbowggdzactfhfndykzyhuaolfuegmvvuumguymqveaapeemfaltggbgsvtroaourqxboepnpapaoxukosnapkjlrindyoalwfqqvsaaidavsxpclavfkxthukzzdscotbdsfrvlgcmbiwvecbeltyrrzxygyzzsquusjdxtjcvlutveyyjdpdyzbvjzpxufzfxtyjowwbywsylgskhlgfftqeaoeuctcahtiencudvzlboojzosyjnauwanltmaogzuarvohuvckfdcpffejjtmcpgqxtwvnntshxgupkvabrtuhfjjddxlbmtuprpsdjpurnczkmyozknmvtocnmtccppenmznbfujfegryhmjxgbthygjswbvdlqzfstsljhdcvvcplbrhfpezftfhwdmifaiehrswtzwicaowdmxrgandnshukoshctlebfefvcwadqzcersxkxakfnhdfvikamhmqxygotfacighbvpihgxexjaanhhhctreebiwjmojyitarqtjwwqxahcjmbpvqqtzguluednxzggfcwvsiyopvkiudpiogsjbttbhhvdficudkffkwkbbroitypfmxjdamgmclfhttzikciyzqujkuhtsllksdqbridhditabmluslnynmgkglmyyqhlrxdignknlcxjpyetlweyfhtvodjltuhklahettovrdmavcfsupgsvjhwlgktzftzykkrgtkcykjeuvcqvzzotcqynnvaoyxyhemfyjyyidkkyzukrkyvdsmrxdahnnnakgwgrwunxhztgldteifxmfvyehuabjlhpqfokmiwphrhgwdlyswbiuoyullatswyiqiwidohdlndmyjwyohgeflgigiplnqnpdfyjxsbpcwyvajcnmsttxunvoaqkcxlnrktnglelvuqkggwujdiqxsmoahpkwsolswxcbvhgapglaoizljnbavjxffxkolmngqivnbhlxjwyuvtgbsosxafezeiidfkbfgtylgfbygaxdyffsunokpouckibalmllcvfjjqybjammyipmzzghevbglrbzeqoiteydgdgkwglpkbtbbyydmqvxkkwmzrxedrcqbggrirmrutkvvdtmqlwnostuzrjkmslvjarqvgrzxmvbbfakdllqbcbgacrntclmzcfpmiqapexttqducidkxyucswcxiajknqvpiqcgdkutxpiyeqijiksazxgrjpsvhqgerhphjcxeiajqomgqgagwjlqgfzqgtgrdpopqpqidknqbuibfbwgacjexfaegcaxlhegctvrebezinpfqvflynzlsoqmdednxyugaunuzfsewaclyhlkxcartbtyydcemnkzwjfolvfnfyglluesgvmmbxadjpqgpohmhectfafyyohchegjgavqpugafcqsfwkihlsuklljvksyarextioqiigccipcbntqsavyyrovpyrfhvrywetqztugdcmpzsbqlhsgvuwmneoeiknufinhknoythlteveykoblhcwafpzargeowlhrxoopbanykwruclhpvpoeuiembdsnksohugepebqmdgrcmxtuhcbptniateerbuyyrnbmiuruswzsqdxpgscegwsicanyxbjfyslfyjmoqadkoedzzcytxztiezknjuqsjywldtrpqfgoobrniolevbknihokbwhzvxfqxhxhqblbzomtxbxqatrngxvbthptnnmwylpqlecsjktpqdtsxejrwkjlisnvvpwfsiztxasiznwffchonvlhmujijgppxtauuvvywmmduhgrezkeqycngjvzvqnzmjzpicbuwzeprohgmtqxarztvassbxcxxanolfuvaftfljcbztfpdavkkbidndibpraeuiwegeqaryzwgvkrkpgjnouocynbvmstvhzowyrkmfocdvezkvahyyggsfradrcqahqhitiejeznrasonpxgmdmzvcijmypwizamwewfutyaooxkfxghjkqdwdvwssdszdlgwioifdyiibufhehigmxhjtucuhjpaecaesukreaezrzxnjzhprtnjvzmdkseudwmkpyhxolfqqgdolsnzrylhfxesoalrgolwqnejvnkxucnmtmonpxdeuwkfmommkcxdvlaznensovwlpribbkhfyfrtywxqgabdhoumnojrjvxwuoteqmkpzuyeumxfgejgvrsslqjvgglycdfyjysugshgoqmvzfshcrhvncdqexjyabqscqakfmnbejkskunaouudbsntjchdfdypwcfemhvgcfromxiyzgjbmndoxzfixzgacyzqrfrjhxrgrhmqntpqcayorzwjvggbiunrmkjokjvvkfxpbejsepugroatsnlmbyymcowmbibgyvzyikrjdabvppshvomganfcecizuhmulfxlndkxodmpdnxwfxydabobtrirynhufodxfoxenuusxcjyloyexcnrwtxzzipqazztzaqntvakwikwagbommbjrfcirlbqmntzcorxqnjvkbsfkxvprsmutesnvrsjfygfpntkpoyryiqgaquziuwwjdcnwcercjraqwuvtpjufguwgrkvzbnlbsdbyipspyvppkfpewejbxgxqkbdwdriyscrnztamzcaccdoiwlegznjrunzadpunokctebdhrbaregztpjxrvxbxygaelepgsyotscaaqpkvkxklxbgbzckjgirhnkegnbyeadwxiillayogutelupdnysyslrkogotvjmwramdamofhjlfmnfjpzbumahyishrbetzczodzumlklxzzyvorstfhspuopfsmnerbacqrjuwlcfvuncsprfysslqkefqpkogbefsdxzvermqhkclthwdqmaxjnhhvvhsexwsrmeeabundtinwkybqvzfqksvzlxwjfngrqprbbwzxlxnubjcltnhvppfkpcnbzmupcgznbvcjzrxcbaniikytrdglvhugenuhbarmweduolgceqoukqqwvffgmvdbyqdxhpwxdycmvdxrkhwppbtuixglkgyquqfipywzifesgyccvoakzfygsekwwvtlphkorbkbrrvjyfknvsogzaifkqoxscdtyuetwtlsaerokaommdrcnjffwcqwppizcygvauuzukkfdippqwhfuaaoyopaqesfduxtmhlbnjuqixboweixcddlhwirnhhzoitizfwjckdrheruomwdhttvliqdxqhllfnyujdozzeozywctrigttiscdqrrtscyxisyfkcfoquoefqloakkuugsutelsugfolibhlsrnxpjdpvxjxmjdfdiweiiypkrohwmgwzjjpgbtfevrrppvrxidrkxpocxraxikccqabiitplpojcofbyjkosvovcjknqpxntpvwesargsvkqukrbbwxkpdhpiklqycajsceyjzdomkohapxnlypflyatobbjkxfqjjqqxnwdszfvyxudnpdpwcrpgpscrutgorzsedlukgkaxzmgylhapzkypwjzcstvcozervvvlqskpmobwzrcnxlkbbyhatjwleoiavwlhasfqnfnzzmvraqtafoajeivqxdmokvwjzwaukmgzrqpxlbtlhkibymkswuvilnuluqxkqbqekedclleaxtwamjhizdixnodlbzojlgwtuidperfopowownqqxfenbovjtikmzhulnjayzgoznminkffxsusrwjpvmumzirxqnerzsytqqhnlqvqjerjrsowzbfbxwovyzxklmklrztmiygpivlfyasfocouyqkfrgvuqzkatcicoskabeolamxcaiylzfudqqapvbrrsieekmkkazhcohfdckzypxuzkflcjyjenyooszpvpbwgkwebmbzwbjfdehqeoodeblggnwrmcucxfmnopuapldtomimoofhxwoyyofqmykgvsgjyaxxylivowwmzhqqetoivghltnsyoxfqraeoefxzddpsynlybsdqocimmzrzyqwvwurcgzfoykjeinnmnwoxouhalagfedeuabuanpheeljirderzvudakdpjeukjubwyfoqywgfzfiwmlkahgvlvmuubjflcwqcjnuchwaigrckmwmqreqzpbhhdsjrvjzyldqpocrkodombwaldoizrexabbeznhulrmplmjxlnbbqpkhlnuluiehcbopdygdwettuyvmgbpdxxkdksbvrmzypmitjelwldmeczueniklnhlyazcamdkwhzcpgjyeqxvigqgdvukozpulatyrzvvkrpzsskkfrhbxazrkyapvnecdnzwrgdccaekvbhexcgzbqblewbxpncxoojxgc', 'mpjkqbnhstuoquqjtjhapbzrqvywlkyeqmibgmwcyreicqvmjqdtxnidjwphlshzlthvydnlmtvflrvzuoofpagbdufcevbyynvapugcvnckrgcvidnmjdhzdugknrupkhribszmttpzbpyhmdjwdqenltcuhpherbmnxecqyfdvtdpjllvydxigbuocvkgorsjqckcsjicfuthnkyqzdpyqssqpexutlwiuhtmnasphcmjjdmtxfnqpawdsivedpvlajxwritlshauauotuzxyhlljjkjifazcsksmvpgbhjwlblcxmskhklgvgjkpbxfjlxdjoljlchgoqudsnecshiqdspotltxeaskgxacvdpycjwklnnynmbaxdpraxmuzwdqvczhrdcnfefgipdayvlxrqlzwfdfmjrcqlyyuwlvmtbezfukhchazosqtqixeutoywpwwvesovbrjdmmjhmlnsnwkznxhitjmfinlwofvnwzsnahmwolfmwememlaepizidabjqiwxdxilpdqejrtcufewebtvdilboybuvthpxfkesjvsfbyqwidtjvyfhttzcqvmciejgaszaypfrgyhqykvlrmehgyeemkdvodmkletxgvtducgfmcyrmllpqqviphpxujxgfrbdepmaibvwkliyadngircnmcvrjmpeqmeshodyzxmjvcaovpswauvveatarumgbmqtvpmlkcdqdigfioaxnuhzgwdhhosnwdqaszbpdvhtkomehzbszevshrqdqefpifnhcvxrsheyhqcbgdhtilymtmoomduefjilwumgacbsowvilhqajbzoecmadzszkxjvtxejohyusypdysyszwdnhagifrnzspqqngqahzkzaxhxxqqeqsyigxurmgfsghizdvmvrlhdywzorehvdmggdhzrzozkjolpwxyvlaekofqetonnbkstmazuksehglbcgwnwvuubwgkvtjpqgve']
    want = 33772638
    got = solution.validSubstringCount(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_17():
    args = ['lll', 'l']
    want = 6
    got = solution.validSubstringCount(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_18():
    args = ['ffcygchfvhqqdvpbufmdkvoggtxlideqvrtoienxwbmcutgpbfpgqcwkcsozulnzdaxjrgqlypypsahnsuxveqklxocujyairljqgcjpzbzrppjlzrqpdiqimujupgeavehosjamcxppjjrcgfiglsxzttblqknvhavbqmvavonwinwmeynvbkaismadgqvwiotmzzqgsyfbuewarkomikafjqjpvagotnjgpzwnsjapfdfbiyblpupkkktkdvlbuizdadowjgwthlkwcklerwwphadecyavbenvccgadjnkzfomgdclrwvzypjzmaiukurdswyokxovsvhmgndresxiuswhqlmbsuvnnpatqdvfutbaavwdpfthftzhopnoclnnakbmjozettxkitsgeparbyzkjzvsdzcohunukwxdjtwllqyvjkeccskberhgbgbijouoogcrolfjzbrhzydhlslviwefixoirharryxjvvcgvxsbsrshvuyfllnebrwwtmfnmlywyxtzmwshelkiyejvqmwizsjzqxobtvwzisbhuxagpiyulehklzcnbozizcqcdbkpvczcbsuzptsnadjxnykmmowuivdcurzsppvvmcjqbnbmwihzggbzknlhrbgkqejurfsuimuewgyokcvwknsyncnabopzemhgqcdmbmpafmvcyqshvfxpcebmfpgkoudebiclxbfyhcbvyyqumbxsrnklpzvxxkcrjcmmogfymjvggubhfnbvrfbbmknqnvhuqcgatcvxwdhqryuzlkucmvhgvfgmmbtuirpgssbccytjkjlpjqrkblvbtbxxpyohwqvxrcyfekhgyhvpjlpwmplnurlenkjlbosdiflhjxmqnlsr', 'hkxqmkkpjeohxcopxzahdamnceyekctaizsbhccvnyliz']
    want = 259106
    got = solution.validSubstringCount(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_19():
    args = ['hhhhhhhhhh', 'h']
    want = 55
    got = solution.validSubstringCount(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_20():
    args = ['bbbbbbbbbbbbbbb', 'bb']
    want = 105
    got = solution.validSubstringCount(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_21():
    args = ['xamyazmeqhgkxflnjdffbunwvlmxszowwypmjcmhfbyxqpenlfuvemlhlzrekeepzprbaknakyiokibikdupqdumpdtqnoipwxarmkmbwmqmfuysoarsdwktktthkuegwjrbmblpftuxcteyadegfcshiwvujkutblnqfoltevlwlxvuthwedfyvvowukujmrneklbrllkpqjbwhprjcpckofnypcuwtqjoeeailtvtysocizlsgrbsxchpzljbbfnpaomenrtrjcxyakdbinbzzferxkrroslhwrueffafkoeetohrqbrhaxugpndkpqwiktultmhpbqplbfjkxszxrcbmzlxxbvozbjhzsqvetcvtdozrkkbhktbazosugqmxbfwmukzblsizzmqrikvxzsmlokpythtljggbwvclukhlvdouwicvpzrfyfcqexzkchqqadlbakdftxbighvfgsmiquvsphdwcmdldngejhuavymqdwxtphrtsizmusftjwfxxdfebwspioufihqwblpuzhhqxfjgiwymhoiiesmorbavwjgarufqpfpbzcskrrznbasmlzcybbuqrraecxayqfamxryuaikqafmtmhkdjxioonxusgzrlnjhpzxbmeerxerjngmhbwuemnwqzqqhdbogbhrlnkjjvtbulnwwbthaafywrnssyfjsmxjyfwijhgjiafmfcrziratczsxnwwueilbyulhcjrebowtzsmpclbzmehipvrzumbsspqjwiobrfacpsgxonlyvykuuzmbqwhnejwfmcifxdvdzfkbxsvifskjsvmvzksqnziitrxlhddedsxkocuqyaqjnwrumadvzvecblrecjsjlajqvifmzmgxuedzxxpuceqarxyuefqzcptatlpewwynrmqucjetutcvbnhleptojiotxhrbrtpjwxolqmwjhrfvutpjgjrubzuztphpehksgjvlvkfscxemyqvjepozhvzyrjrvztireqbttrcyufdqxltiflfnqqibcdtarzblqxhvoctvsnmufkenxzirlbjqmnwvevqriuagbryeidmumhcygwqyqtvmnbndltkzxjetnhuqbxbnvlvcfaczaxjcqaxbdxvhuvwqejjljwmvzvidhkpepnfkgwjwofiazkqzfntyqqhvufvdxtyfpyvlxwlcrirxymtrbrhxuvoypluhhlvjtcvueowrzrauxfljrpjqbvsxtctwfqodxeiuqtomorbyrjsxfdjcmigkvzgvlbtojaskewsawczywhdbjejjmqjwgnfkeukdv', 'fctsmupfcajostcmqdnqczbgiwsrzzcigfuwxlvcuyxrjqenfbmydlmobofaaasdgwswkfmebxnnkhqjzrzggtixzrvdvkiufgrinbbuybuzdhjodvssnzhnukubvqwmaxjefxejywdsygcsrunrrdqdrbmycilbbyywfverwyxwkgrjwacermnyiftsgeoxfaahijmeuxvokdgywmtwzvrzncpzdygswjxchntcrfrziaatrtusjmevebwubttfqmzbmxkzfublulbatcvdfswhdwnysvuybpiaazymtepzrlfrmudidgoolrtexwtnvkofsjyveuvdzviyrwhqzvjydnymhzbtuyjxxybyeihkrncxrzbqmnnnowlkcfbqjbiizkwhwmzqxlofqlptycjtdrlsjltxjuqjlkexxtyvopdvphudwxlsqgrbrhdxytylsorcrxmzibsbtylhgqgvtgkynuvazlrqsifqqryrgjhcruyasfklxwjhimqmjwcpcaabjzynxajzzrctbkarqxfomsnwddwentxqfbqbghcklzuzildsiorbbceukwznnkascdhkijclwbsidhqqsytynpxmjibzrffwvuhbqckyvimfbgvqcyqwqodarbadjmjrszfsingatwugilxtjanltfuugageeasxaejqwsnbomjinyeimyjdcdmuigvvhkkblrlceliphvqlwrtbtcchaoexvwjvogqgzutgwqejhhtrraiwzwhjuotbagoegoamlmtrnuymbeacpkglywmtwwyrewihoycmsgwyziednnofodcfanhyekttgsyluypzntexlyolodydqeferwrnhrsehhhnuncgariumaivhmnfzvcjohqbkgrknijmrycsmnxhxfbrbhggtviwkbwwdaednykhuocusvbbgvgvzcbhzaeqsamekbbimmfgmwxzeuiiznyilfgpcebivgouutmknmvuvcpy']
    want = 0
    got = solution.validSubstringCount(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_22():
    args = ['lllllllll', 'l']
    want = 45
    got = solution.validSubstringCount(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_23():
    args = ['tpmrepdnbytgkffismdrfounqtzvviqgmzifeitrmeobuioxyjvuczwdunrfoickwjekchjoweiqroaldfllwlfkylqqcreohjtyfcnjtelabhowwrwszwpprgiwfyqrvhtnyyqdtdfuvrvvkelggfdxxqohzngkptxpqhswynleapnadooqcgjjioffyyceiocfbdsufvipqnocqeuwdypuurxmeetkfqmiqotioyyzkdwqswwkzkygccqvxskqgpagmlgrpwlpfkzpvojpuxvjjrjejtrgaiawcjmrgdwefttgbmglzwibzxufvpmxjjtjdimytueahnkaqqcswunrhtnwwmomxbequwvnasevnsprdyyaldrprgyecykhbbxxhgwwuseobllcztuffzvdlvoemgmrinoibslrkruxnnneuiemqjmxvoxweptpeucofobuntsedyycswtkxcwzlualvdfhjqzozsfisnesapoxmlrfhvhzzcsgjapslyxwgkarakolrgkkzdaknjevlmvwnqzqylcolbzxjuyseiqjgxpbptfqwlkaqzbegwzziphwqffixevltuihyzhervtmdenxpusdoaenfaohrulbszoeljqdjmrmhbuooquaramitumwdkbwzdktdtwuugaepxseointumfmljginxqbggghxnylkmqoviznjjzaxwtvitbvvcucecjxambdppswzzavbxfebphesflgtjzsuwkgvkcvefyujgcnolixyzusqflaztuudbenxmensbtixqonumliqzissxkvfpkdatzqetjvjvfppwrpberdvwplfcfagedqxwgjysvhnrqrxejoyhuigchjdcgmmolyztqgkjthylhztoxkejtbndoczfsfnnvucpsafxpgvdjkloizxlfsiomwintquykkynbjbabkobxkavzhkusflelaalzuvfleqhkhgdkhnwmbnbmwkimawvxioapmuxrxlxcaitmtfxglhlbnivsbppoeiefegddjczycivrgpnjzzujzepbymqcoxisjeqeqnqlbcdqhwcuveuyemxefvgmlyspwdbtzsstzgezlgbpkbiyfpvupwjiwgkycwfxzpdkqrlcfqptjjzybxkyohxaccfccmykropxogstbmofmxaqtykbhifnfmrqgojuiupranhaaglfsmgedslodcbnfeijdfshfwmmdogxykmikawxqdpsgbfwfbalperjjuamyilniumlvqstgdcseqacknfbemtxfajmstdgiytqduzpgnmdvibxeemktkelizhldsrerlhfovrotcukzcetgxwqcyztunnbjrycmdegblcyiyvhfamvrcwhguhctaoxmyksnyyciwavxwmeqvpwpnlxdzgzbqqswfricaevkthkiqjhdwvjpnipiztwratqdivwjaroyqglasmnvfbzbrwtvqsooxzdcqrtonkekrnjuiuwbsqbrybtltfzwrzetauxoxgfzgefgsgrrgusceltoqizdnrvxevyekkekviyhvfazslgcedxgelzlvugucsbrmyojfgdoxxjlpxtkxrkdovbfpiafnjtfkazrlylyfayeduuxtnejddshwsejwmzulwywkyuumbpkqkmcakzmwdjicsaosqhmnwyroyttenjhtxuufuymnkhxstxzmnrffnoxzlxfbjdxlkydksifimtprbnvcesaqmgwmkraqakyvejrueqaniqbkylldhysynpauchdmpkskojphiqqmuuwjikuvnsnvadpkksfrldffoopnijipnovcmhahvdvpcdemvobwrmwtkyildmruwnjzjlddpcoivshnvxlmxxsthvdvxgodfmlieqppvapzrwtpcltxolqbbljljwnhxednzxiwqvcafscboulgvwecwoylrsxfdhtaycbaayirqyuebncfgmphqhsolsvkmnjvxymcfjntuiewdgusggbhedelmffriiqvhmvdiaoqyrzootwpzwvnexxvtpqwmlmbfrkshlcpsgkybikxhxrwdiexfbpordzvbiugncnjokpnspzkgfjlczvnhjomsioiwdyqcaspwwinxlyxfrdvlrfriongxrxjbwszorlmvrteriwwukdmkxgcokzmbtbyyekvscmtvejjtpvpcisejhrhznirlixsruyvqczwzbfnagjrjwiabnyzivuykmrrfnnljfqziiduembtdpmkslamfqyocdywvnkkfwhoshqawnmxgapitexdgiiwgwjwlbnxcotmpzrffwilvfxlojvqomywafbinjaghsqmakpcvpaggktsavmafucwtdnanswylbzragnqsuszstqlpeulyqhvpfvzxhtxwzcpukjciklqsdeslihhyelwuyssrxnjwkoaisvtjrfejwmsudekefcdltictasaxnnshwgkxjstipczsmspljqupbzwtpsattouiuyncgljmyagpmffkaxnvjjvtxroypmrgrkctuyjtldkjiqkaohirswhgeoxenhiwrmavijwqyiotcarfqirmpbixbscxlmfarmiauzxhuiqnoixgnlbzxwauhsevuwymcikebjfuzbouasywbdwsjuezjvsahbpmviwzrjmnxkybvaepqgqepxkauacufqguyhiqrhkyuddcnxwdulmlqxfhqjqbehugciltqxffgejmlboxplbersysfiqyrhstrpfluycnvvwkvcxftnvpwfowohsltmvnnbssqhykwlgoapzsuwlpaudfttgakzyeirqrifkeuvkllhdatpjgtzhvinhjppvbjznceyoltjlxgboduzamfhjqwfcapaecfnjmoentmcylkphnlaoovnfmbltqanwnqgjtzkvsxnpqxnnewjtwtlcvrlgyopfckbiezphfhloqeraeermqevsszinilyiityblntgldyiukwowtlbagquxddmrnkr', 'sqiuxkqyrvaanarjwwfktnttlpagsbalfkrhvisfclxdoxfqtxrvhnvjmnnqrowixqjxtpiplsbgrtfmaetaefefqbztlczeefzqglbpybonyvkidaqbzpwtiwgtbyvepbgmuuirxeqgnsppsfgwnxigsqiccekrngnuxknoqwvqqtiiuxpzbsrmxobxzogltdiwgklecayxmoaybnladncqstwkdeyrvywgxwpkkvmarpuloythffrcmrivaobmbarwzmrrmjafblvgcyuzktjztkhdqvfcmvzmhdhogyvbzjqekgupchgvbmwakqmttvzlnqgakzmtnwldcjqqhhitgmdjseikweugctiagthvvyibyxjiqfibkenbnvfdkrqszlsgzwcpvdstrkyfgjcbavnucmhlcjumzxnjsattxbbtowjkemhehjpgunpfjzumbtochcvplbuvihhvvkpdiffrolcvfgceprbylfmdvfqhpfjtcxewayfugikdcinylrcuakrvgymxyphahhaqoberygvsyjrghirzorvamnffwgprkqiglbzskajnymovhnlpapiqrvjdefixpavgeniaojmocekyyzkbcozztrpllhgvbymmtxhucfqjgbmhfonpdmlxrcsletxzlebjmngsedfxuomfgfztacsxumfmwiszfcuhlockvbqcwsanofegecdtunbcqpilsxmzjeryjdjnalksjggdlnoacjegjwxlhvplirjcokhzfqrrkvlslqfivgllzsxqpdkrozkqxgjpjpdmokrmycosuqubgkrjwlbxillfhflarzxqxqdfocjlqlgitezrwpgmmknfthlcjcjzpbeiubnynrfucfxjkgewoacwksnoedrhtkwgntggfouvladzokdjuudpzyoamfumlqckvmpapdeeirbwxhyssanrrfozigiojzptyqitlhvglsjhreosdxcettijynmfqqfv']
    want = 1246047
    got = solution.validSubstringCount(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_24():
    args = ['kkkkkkkkk', 'k']
    want = 45
    got = solution.validSubstringCount(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_25():
    args = ['ooooooooo', 'o']
    want = 45
    got = solution.validSubstringCount(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_26():
    args = ['axrxvhxsvougfdaazolvhgpivysaixlcybvkortlvxwmutlwyvmdigpjmiurllpztafhkmliopplfmcjxwpcmzfbjswzuiguaoagdpbagpcftzmqoaovgbwknfsgqfadrjheoiwncjgatltkiscryvwbcd', 'h']
    want = 8505
    got = solution.validSubstringCount(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)


def check_case_27():
    args = ['rd', 'e']
    want = 0
    got = solution.validSubstringCount(*args)
    assert _aeq(got, want), "args=%r got=%r want=%r" % (args, got, want)

