"""Visible checks for bcb_752 -- these ship with the task and can be run.

Rendered from bigcode/bigcodebench-hard v0.1.4 (BigCodeBench/752) by
ops/vacantrun/bcb_hard_bank_20260924/build_bank.py. The code below is the
dataset's unittest TestCases, restricted to the test methods that ship with
this task; each check_* runs one of those methods.
"""

from solution import *
import sys as _vacant_sys
import solution as _vacant_solution
_vacant_sys.modules.setdefault(__name__, _vacant_solution)

import unittest
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
class TestCases(unittest.TestCase):
    def test_case_1(self):
        'completely random input'
        rng = np.random.default_rng(seed=0)
        data = pd.DataFrame({
            'x1': rng.random(100),
            'x2': rng.random(100),
            'y': rng.random(100)
        })
        result = task_func(data, 'y')
        self.assertIsInstance(result, float)
        self.assertAlmostEqual(result, -0.084144904538201)
    def test_case_2(self):
        'linear relation'
        rng = np.random.default_rng(seed=0)
        data = pd.DataFrame({
            'x1': rng.random(500),
        })
        data['y'] = data['x1'] * 2 + 1
        result = task_func(data, 'y')
        self.assertIsInstance(result, float)
        self.assertAlmostEqual(result, 1.0)
    def test_case_3(self):
        'linear relation'
        rng = np.random.default_rng(seed=0)
        data = pd.DataFrame({
            'x1': rng.random(720) * 10,
            'x2': rng.random(720) * 100
        })
        data['y'] = data['x1'] * 2 + data['x2'] * (-0.14) + 25
        result = task_func(data, 'y')
        self.assertIsInstance(result, float)
        self.assertAlmostEqual(result, 1.0)
    def test_case_4(self):
        'linear relation with quadratic perturbation'
        rng = np.random.default_rng(seed=0)
        data = pd.DataFrame({
            'x1': rng.random(720),
            'x2': rng.random(720)
        })
        data['y'] = (
            data['x1'] * 5.1 + data['x2'] * (-3.1) + 6.4 + data['x1']**2
        )
        random_state = 42
        train_test_split = 0.4
        result = task_func(data, 'y', test_size=train_test_split, random_state=random_state)
        self.assertIsInstance(result, float)
        self.assertAlmostEqual(result, 0.9985567445794377)


# ── Vacant wrapper (generated by build_bank.py) ──────────────────────────
# Each check_* below runs exactly one TestCases method (with its setUp /
# tearDown) and raises AssertionError with a short message if it fails.
import unittest as _vacant_unittest

for _vacant_name in [_n for _n in list(globals()) if _n.startswith("check_")]:
    del globals()[_vacant_name]


def _vacant_short(tb_text, limit=700):
    lines = (tb_text or "").rstrip().splitlines()
    idx = [i for i, ln in enumerate(lines) if ln.startswith("  File ")]
    tail = lines[idx[-1] + 2:] if idx and idx[-1] + 2 < len(lines) else lines[-3:]
    tail = [ln for ln in tail if ln.strip() and set(ln.strip()) - set("^~")]
    msg = "\n".join(tail).strip()
    if len(msg) > limit:
        msg = msg[: limit // 2] + " ...[cut]... " + msg[-(limit // 2):]
    return msg


def _vacant_run(method_name):
    suite = _vacant_unittest.TestSuite([TestCases(method_name)])
    result = _vacant_unittest.TestResult()
    suite.run(result)
    if result.wasSuccessful() and result.testsRun == 1:
        return
    if result.failures:
        kind, tb = "FAIL", result.failures[0][1]
    elif result.errors:
        kind, tb = "ERROR", result.errors[0][1]
    elif result.unexpectedSuccesses:
        kind, tb = "UNEXPECTED SUCCESS", ""
    else:
        kind, tb = "NOT RUN", ""
    raise AssertionError("%s %s: %s" % (kind, method_name, _vacant_short(tb)))


def check_test_case_1():
    _vacant_run('test_case_1')

def check_test_case_2():
    _vacant_run('test_case_2')

def check_test_case_3():
    _vacant_run('test_case_3')

def check_test_case_4():
    _vacant_run('test_case_4')
