"""Visible acceptance for s2_05_clamp — rendered data, do not hand-edit.

Generated by ops/gain/r535/build_bank.py from ops/gain/r535/tasks_s2.
Every check is zero-argument and passes by returning normally
(vacant_network/vrun/acceptance.py runs them in definition order).
"""


def check_01_clamp():
    from solution import clamp
    args = (5, 1, 10)
    got = clamp(*args)
    want = 5
    assert got == want, "clamp args=%r got=%r want=%r" % (args, got, want)


def check_02_clamp():
    from solution import clamp
    args = (1, 10, 0)
    try:
        got = clamp(*args)
    except ValueError:
        return
    except Exception as exc:
        raise AssertionError("clamp args=%r got=%s(%s) want=ValueError" %
                             (args, type(exc).__name__, exc))
    raise AssertionError("clamp args=%r got=%r want=ValueError to be raised" %
                         (args, got))
