"""Hidden acceptance for s1_43_camelise — rendered data, do not hand-edit.

Generated by ops/gain/r535/build_bank.py from ops/gain/r535/tasks_s1.
Every check is zero-argument and passes by returning normally
(vacant_network/vrun/acceptance.py runs them in definition order).
"""


def check_01_camelise():
    from solution import camelise
    args = ('one_two_three',)
    got = camelise(*args)
    want = 'oneTwoThree'
    assert got == want, "camelise args=%r got=%r want=%r" % (args, got, want)


def check_02_camelise():
    from solution import camelise
    args = ('single',)
    got = camelise(*args)
    want = 'single'
    assert got == want, "camelise args=%r got=%r want=%r" % (args, got, want)


def check_03_camelise():
    from solution import camelise
    args = ('',)
    got = camelise(*args)
    want = ''
    assert got == want, "camelise args=%r got=%r want=%r" % (args, got, want)


def check_04_camelise():
    from solution import camelise
    args = ('a_b',)
    got = camelise(*args)
    want = 'aB'
    assert got == want, "camelise args=%r got=%r want=%r" % (args, got, want)


def check_05_camelise():
    from solution import camelise
    args = ('A_B',)
    got = camelise(*args)
    want = 'aB'
    assert got == want, "camelise args=%r got=%r want=%r" % (args, got, want)


def check_06_camelise():
    from solution import camelise
    args = ('x_y_z',)
    got = camelise(*args)
    want = 'xYZ'
    assert got == want, "camelise args=%r got=%r want=%r" % (args, got, want)


def check_07_camelise():
    from solution import camelise
    args = ('snake_case_name',)
    got = camelise(*args)
    want = 'snakeCaseName'
    assert got == want, "camelise args=%r got=%r want=%r" % (args, got, want)
