"""Hidden acceptance for s2_04_split_csv — rendered data, do not hand-edit.

Generated by ops/gain/r535/build_bank.py from ops/gain/r535/tasks_s2.
Every check is zero-argument and passes by returning normally
(vacant_network/vrun/acceptance.py runs them in definition order).
"""


def check_01_split_csv():
    from solution import split_csv
    args = ('a, b ,c',)
    got = split_csv(*args)
    want = ['a', 'b', 'c']
    assert got == want, "split_csv args=%r got=%r want=%r" % (args, got, want)


def check_02_split_csv():
    from solution import split_csv
    args = ('',)
    got = split_csv(*args)
    want = []
    assert got == want, "split_csv args=%r got=%r want=%r" % (args, got, want)


def check_03_split_csv():
    from solution import split_csv
    args = ('a',)
    got = split_csv(*args)
    want = ['a']
    assert got == want, "split_csv args=%r got=%r want=%r" % (args, got, want)


def check_04_split_csv():
    from solution import split_csv
    args = ('a,,b',)
    got = split_csv(*args)
    want = ['a', '', 'b']
    assert got == want, "split_csv args=%r got=%r want=%r" % (args, got, want)


def check_05_split_csv():
    from solution import split_csv
    args = (' x , y ',)
    got = split_csv(*args)
    want = ['x', 'y']
    assert got == want, "split_csv args=%r got=%r want=%r" % (args, got, want)


def check_06_split_csv():
    from solution import split_csv
    args = (',',)
    got = split_csv(*args)
    want = ['', '']
    assert got == want, "split_csv args=%r got=%r want=%r" % (args, got, want)


def check_07_split_csv():
    from solution import split_csv
    args = ('one',)
    got = split_csv(*args)
    want = ['one']
    assert got == want, "split_csv args=%r got=%r want=%r" % (args, got, want)
