"""Hidden acceptance for s2_08_dedupe — rendered data, do not hand-edit.

Generated by ops/gain/r535/build_bank.py from ops/gain/r535/tasks_s2.
Every check is zero-argument and passes by returning normally
(vacant_network/vrun/acceptance.py runs them in definition order).
"""


def check_01_dedupe():
    from solution import dedupe
    args = (['Ab', 'ab', 'b'],)
    got = dedupe(*args)
    want = ['Ab', 'b']
    assert got == want, "dedupe args=%r got=%r want=%r" % (args, got, want)


def check_02_dedupe():
    from solution import dedupe
    args = ([],)
    got = dedupe(*args)
    want = []
    assert got == want, "dedupe args=%r got=%r want=%r" % (args, got, want)


def check_03_dedupe():
    from solution import dedupe
    args = (['a'],)
    got = dedupe(*args)
    want = ['a']
    assert got == want, "dedupe args=%r got=%r want=%r" % (args, got, want)


def check_04_dedupe():
    from solution import dedupe
    args = (['A', 'a', 'A'],)
    got = dedupe(*args)
    want = ['A']
    assert got == want, "dedupe args=%r got=%r want=%r" % (args, got, want)


def check_05_dedupe():
    from solution import dedupe
    args = (['x', 'y', 'X'],)
    got = dedupe(*args)
    want = ['x', 'y']
    assert got == want, "dedupe args=%r got=%r want=%r" % (args, got, want)


def check_06_dedupe():
    from solution import dedupe
    args = (['one', 'two', 'ONE'],)
    got = dedupe(*args)
    want = ['one', 'two']
    assert got == want, "dedupe args=%r got=%r want=%r" % (args, got, want)


def check_07_dedupe():
    from solution import dedupe
    args = (['p', 'q'],)
    got = dedupe(*args)
    want = ['p', 'q']
    assert got == want, "dedupe args=%r got=%r want=%r" % (args, got, want)
