"""Visible acceptance for s1_03_nwords — rendered data, do not hand-edit.

Generated by ops/gain/r535/build_bank.py from ops/gain/r535/tasks_s1.
Every check is zero-argument and passes by returning normally
(vacant/vrun/acceptance.py runs them in definition order).
"""


def check_01_n_words():
    from solution import n_words
    args = ('hello world',)
    got = n_words(*args)
    want = 2
    assert got == want, "n_words args=%r got=%r want=%r" % (args, got, want)


def check_02_n_words():
    from solution import n_words
    args = ('  a  b  c ',)
    got = n_words(*args)
    want = 3
    assert got == want, "n_words args=%r got=%r want=%r" % (args, got, want)
