"""Visible checks for bcb_785 -- these ship with the task and can be run.

Rendered from bigcode/bigcodebench-hard v0.1.4 (BigCodeBench/785) by
ops/vacantrun/bcb_hard_bank_20260924/build_bank.py. The code below is the
dataset's unittest TestCases, restricted to the test methods that ship with
this task; each check_* runs one of those methods.
"""

from solution import *
import sys as _vacant_sys
import solution as _vacant_solution
_vacant_sys.modules.setdefault(__name__, _vacant_solution)

import unittest
import tarfile
import os
import glob
import unittest
import shutil
from unittest.mock import patch, MagicMock
# Constants for test
TEST_FILES_DIR = './test_files'
class TestCases(unittest.TestCase):
    def setUp(self):
        # Create a directory for test files if it doesn't exist
        os.makedirs(TEST_FILES_DIR, exist_ok=True)
        # Create some sample files
        self.sample_files = ['test1.txt', 'test2.txt', 'image1.jpg', 'image2.jpg']
        for file in self.sample_files:
            with open(os.path.join(TEST_FILES_DIR, file), 'w') as f:
                f.write("Sample content for " + file)
    def tearDown(self):
        # Remove the test directory after tests
        shutil.rmtree(TEST_FILES_DIR)
        shutil.rmtree(ARCHIVE_DIR)
    def test_archive_txt_files(self):
        # Archive txt files and verify
        archive_path = task_func(os.path.join(TEST_FILES_DIR, '*.txt'))
        self.assertTrue(os.path.isfile(archive_path))
        # Ensure original files are deleted
        for filename in glob.glob(os.path.join(TEST_FILES_DIR, '*.txt')):
            self.assertFalse(os.path.exists(filename))
    def test_archive_image_files(self):
        # Archive image files and verify
        archive_path = task_func(os.path.join(TEST_FILES_DIR, '*.jpg'))
        self.assertTrue(os.path.isfile(archive_path))
        # Check original files are deleted
        for filename in glob.glob(os.path.join(TEST_FILES_DIR, '*.jpg')):
            self.assertFalse(os.path.exists(filename))


# ── Vacant wrapper (generated by build_bank.py) ──────────────────────────
# Each check_* below runs exactly one TestCases method (with its setUp /
# tearDown) and raises AssertionError with a short message if it fails.
import unittest as _vacant_unittest

for _vacant_name in [_n for _n in list(globals()) if _n.startswith("check_")]:
    del globals()[_vacant_name]


def _vacant_short(tb_text, limit=700):
    lines = (tb_text or "").rstrip().splitlines()
    idx = [i for i, ln in enumerate(lines) if ln.startswith("  File ")]
    tail = lines[idx[-1] + 2:] if idx and idx[-1] + 2 < len(lines) else lines[-3:]
    tail = [ln for ln in tail if ln.strip() and set(ln.strip()) - set("^~")]
    msg = "\n".join(tail).strip()
    if len(msg) > limit:
        msg = msg[: limit // 2] + " ...[cut]... " + msg[-(limit // 2):]
    return msg


def _vacant_run(method_name):
    suite = _vacant_unittest.TestSuite([TestCases(method_name)])
    result = _vacant_unittest.TestResult()
    suite.run(result)
    if result.wasSuccessful() and result.testsRun == 1:
        return
    if result.failures:
        kind, tb = "FAIL", result.failures[0][1]
    elif result.errors:
        kind, tb = "ERROR", result.errors[0][1]
    elif result.unexpectedSuccesses:
        kind, tb = "UNEXPECTED SUCCESS", ""
    else:
        kind, tb = "NOT RUN", ""
    raise AssertionError("%s %s: %s" % (kind, method_name, _vacant_short(tb)))


def check_test_archive_image_files():
    _vacant_run('test_archive_image_files')

def check_test_archive_txt_files():
    _vacant_run('test_archive_txt_files')
