"""Visible acceptance for s1_19_tally — rendered data, do not hand-edit.

Generated by ops/gain/r535/build_bank.py from ops/gain/r535/tasks_s1.
Every check is zero-argument and passes by returning normally
(vacant_network/vrun/acceptance.py runs them in definition order).
"""


def check_01_tally():
    from solution import tally
    args = (['a', 'b', 'a'],)
    got = tally(*args)
    want = {'a': 2, 'b': 1}
    assert got == want, "tally args=%r got=%r want=%r" % (args, got, want)


def check_02_tally():
    from solution import tally
    args = ([],)
    got = tally(*args)
    want = {}
    assert got == want, "tally args=%r got=%r want=%r" % (args, got, want)
