"""Hidden acceptance for s1_02_span — rendered data, do not hand-edit.

Generated by ops/gain/r535/build_bank.py from ops/gain/r535/tasks_s1.
Every check is zero-argument and passes by returning normally
(vacant_network/vrun/acceptance.py runs them in definition order).
"""


def check_01_span():
    from solution import span
    args = ([3, 1, 4],)
    got = span(*args)
    want = {'lo': 1, 'hi': 4}
    assert got == want, "span args=%r got=%r want=%r" % (args, got, want)


def check_02_span():
    from solution import span
    args = ([7],)
    got = span(*args)
    want = {'lo': 7, 'hi': 7}
    assert got == want, "span args=%r got=%r want=%r" % (args, got, want)


def check_03_span():
    from solution import span
    args = ([-5, 0, 5],)
    got = span(*args)
    want = {'lo': -5, 'hi': 5}
    assert got == want, "span args=%r got=%r want=%r" % (args, got, want)


def check_04_span():
    from solution import span
    args = ([2, 2, 2],)
    got = span(*args)
    want = {'lo': 2, 'hi': 2}
    assert got == want, "span args=%r got=%r want=%r" % (args, got, want)


def check_05_span():
    from solution import span
    args = ([1.5, -1.5],)
    got = span(*args)
    want = {'lo': -1.5, 'hi': 1.5}
    assert got == want, "span args=%r got=%r want=%r" % (args, got, want)


def check_06_span():
    from solution import span
    args = ([10, 9, 8, 7],)
    got = span(*args)
    want = {'lo': 7, 'hi': 10}
    assert got == want, "span args=%r got=%r want=%r" % (args, got, want)
