"""Visible checks for bcb_273 -- these ship with the task and can be run.

Rendered from bigcode/bigcodebench-hard v0.1.4 (BigCodeBench/273) by
ops/vacantrun/bcb_hard_bank_20260924/build_bank.py. The code below is the
dataset's unittest TestCases, restricted to the test methods that ship with
this task; each check_* runs one of those methods.
"""

from solution import *
import sys as _vacant_sys
import solution as _vacant_solution
_vacant_sys.modules.setdefault(__name__, _vacant_solution)

import unittest
from unittest.mock import MagicMock, patch
class TestCases(unittest.TestCase):
    def setUp(self):
        self.mock_server = MagicMock()
        self.mock_request = MagicMock()
        self.mock_client_address = ('127.0.0.1', 8080)
    @patch('http.server.BaseHTTPRequestHandler.handle')
    def test_invalid_content_type(self, mock_handle):
        """Test handler response to invalid Content-Type."""
        handler = task_func()
        request_handler = handler(self.mock_request, self.mock_client_address, self.mock_server)
        request_handler.headers = {'content-type': 'text/plain'}
        request_handler.send_error = MagicMock()
        request_handler.do_POST()
        request_handler.send_error.assert_called_with(400, 'Content-Type header is not application/json')
    def test_class_properties(self):
        """Test if task_func returns a class that is a type and subclass of BaseHTTPRequestHandler."""
        handler_class = task_func()
        self.assertTrue(isinstance(handler_class, type))
        self.assertTrue(issubclass(handler_class, http.server.BaseHTTPRequestHandler))


# ── Vacant wrapper (generated by build_bank.py) ──────────────────────────
# Each check_* below runs exactly one TestCases method (with its setUp /
# tearDown) and raises AssertionError with a short message if it fails.
import unittest as _vacant_unittest

for _vacant_name in [_n for _n in list(globals()) if _n.startswith("check_")]:
    del globals()[_vacant_name]


def _vacant_short(tb_text, limit=700):
    lines = (tb_text or "").rstrip().splitlines()
    idx = [i for i, ln in enumerate(lines) if ln.startswith("  File ")]
    tail = lines[idx[-1] + 2:] if idx and idx[-1] + 2 < len(lines) else lines[-3:]
    tail = [ln for ln in tail if ln.strip() and set(ln.strip()) - set("^~")]
    msg = "\n".join(tail).strip()
    if len(msg) > limit:
        msg = msg[: limit // 2] + " ...[cut]... " + msg[-(limit // 2):]
    return msg


def _vacant_run(method_name):
    suite = _vacant_unittest.TestSuite([TestCases(method_name)])
    result = _vacant_unittest.TestResult()
    suite.run(result)
    if result.wasSuccessful() and result.testsRun == 1:
        return
    if result.failures:
        kind, tb = "FAIL", result.failures[0][1]
    elif result.errors:
        kind, tb = "ERROR", result.errors[0][1]
    elif result.unexpectedSuccesses:
        kind, tb = "UNEXPECTED SUCCESS", ""
    else:
        kind, tb = "NOT RUN", ""
    raise AssertionError("%s %s: %s" % (kind, method_name, _vacant_short(tb)))


def check_test_class_properties():
    _vacant_run('test_class_properties')

def check_test_invalid_content_type():
    _vacant_run('test_invalid_content_type')
