"""Hidden acceptance for s1_42_snakeify — rendered data, do not hand-edit.

Generated by ops/gain/r535/build_bank.py from ops/gain/r535/tasks_s1.
Every check is zero-argument and passes by returning normally
(vacant_network/vrun/acceptance.py runs them in definition order).
"""


def check_01_snakeify():
    from solution import snakeify
    args = ('camelCase',)
    got = snakeify(*args)
    want = 'camel_case'
    assert got == want, "snakeify args=%r got=%r want=%r" % (args, got, want)


def check_02_snakeify():
    from solution import snakeify
    args = ('PascalCase',)
    got = snakeify(*args)
    want = 'pascal_case'
    assert got == want, "snakeify args=%r got=%r want=%r" % (args, got, want)


def check_03_snakeify():
    from solution import snakeify
    args = ('',)
    got = snakeify(*args)
    want = ''
    assert got == want, "snakeify args=%r got=%r want=%r" % (args, got, want)


def check_04_snakeify():
    from solution import snakeify
    args = ('a',)
    got = snakeify(*args)
    want = 'a'
    assert got == want, "snakeify args=%r got=%r want=%r" % (args, got, want)


def check_05_snakeify():
    from solution import snakeify
    args = ('A',)
    got = snakeify(*args)
    want = 'a'
    assert got == want, "snakeify args=%r got=%r want=%r" % (args, got, want)


def check_06_snakeify():
    from solution import snakeify
    args = ('HTTPServer',)
    got = snakeify(*args)
    want = 'h_t_t_p_server'
    assert got == want, "snakeify args=%r got=%r want=%r" % (args, got, want)


def check_07_snakeify():
    from solution import snakeify
    args = ('oneTwoThree',)
    got = snakeify(*args)
    want = 'one_two_three'
    assert got == want, "snakeify args=%r got=%r want=%r" % (args, got, want)
