"""Visible checks for bcb_720 -- these ship with the task and can be run.

Rendered from bigcode/bigcodebench-hard v0.1.4 (BigCodeBench/720) by
ops/vacantrun/bcb_hard_bank_20260924/build_bank.py. The code below is the
dataset's unittest TestCases, restricted to the test methods that ship with
this task; each check_* runs one of those methods.
"""

from solution import *
import sys as _vacant_sys
import solution as _vacant_solution
_vacant_sys.modules.setdefault(__name__, _vacant_solution)

import unittest
import os
import csv
import unittest
class TestCases(unittest.TestCase):
    def setUp(self):
        """Set up test environment; create the directory and file."""
        self.file_path = 'task_func_data/Output.txt'
        os.makedirs(os.path.dirname(self.file_path), exist_ok=True)
        # Create an empty file for each test to ensure clean state
        with open(self.file_path, 'w', newline='') as f:
            writer = csv.writer(f)
            writer.writerow(['Timestamp', 'Temperature', 'Humidity'])
    def tearDown(self):
        """Clean up after tests; remove the file and directory."""
        os.remove(self.file_path)
        os.rmdir('task_func_data')
    def test_file_content(self):
        # Validate the content of the file
        task_func()
        with open(self.file_path, 'r') as f:
            reader = csv.reader(f)
            header = next(reader)
            self.assertEqual(header, ['Timestamp', 'Temperature', 'Humidity'])
            row = next(reader)
            self.assertEqual(len(row), 3)
            self.assertTrue(20 <= float(row[1]) <= 30)
            self.assertTrue(50 <= float(row[2]) <= 60)
    def test_data_appending(self):
        # Test repeated executions to ensure data is appended correctly
        task_func()
        initial_line_count = sum(1 for line in open(self.file_path))
        task_func()
        final_line_count = sum(1 for line in open(self.file_path))
        self.assertEqual(final_line_count, initial_line_count + 1)


# ── Vacant wrapper (generated by build_bank.py) ──────────────────────────
# Each check_* below runs exactly one TestCases method (with its setUp /
# tearDown) and raises AssertionError with a short message if it fails.
import unittest as _vacant_unittest

for _vacant_name in [_n for _n in list(globals()) if _n.startswith("check_")]:
    del globals()[_vacant_name]


def _vacant_short(tb_text, limit=700):
    lines = (tb_text or "").rstrip().splitlines()
    idx = [i for i, ln in enumerate(lines) if ln.startswith("  File ")]
    tail = lines[idx[-1] + 2:] if idx and idx[-1] + 2 < len(lines) else lines[-3:]
    tail = [ln for ln in tail if ln.strip() and set(ln.strip()) - set("^~")]
    msg = "\n".join(tail).strip()
    if len(msg) > limit:
        msg = msg[: limit // 2] + " ...[cut]... " + msg[-(limit // 2):]
    return msg


def _vacant_run(method_name):
    suite = _vacant_unittest.TestSuite([TestCases(method_name)])
    result = _vacant_unittest.TestResult()
    suite.run(result)
    if result.wasSuccessful() and result.testsRun == 1:
        return
    if result.failures:
        kind, tb = "FAIL", result.failures[0][1]
    elif result.errors:
        kind, tb = "ERROR", result.errors[0][1]
    elif result.unexpectedSuccesses:
        kind, tb = "UNEXPECTED SUCCESS", ""
    else:
        kind, tb = "NOT RUN", ""
    raise AssertionError("%s %s: %s" % (kind, method_name, _vacant_short(tb)))


def check_test_data_appending():
    _vacant_run('test_data_appending')

def check_test_file_content():
    _vacant_run('test_file_content')
